from .log_levels import LogLevel as LogLevel
from .structured_logger import StructuredLogger as StructuredLogger
from _typeshed import Incomplete
from functools import partial as partial

default_logger: Incomplete

def log_debug(message: str, **kwargs) -> None: ...
def log_info(message: str, lang: str = 'en', **kwargs) -> None: ...
def log_warning(message: str, lang: str = 'en', **kwargs) -> None: ...
def log_error(message: str, lang: str = 'en', **kwargs) -> None: ...
def log_critical(message: str, lang: str = 'en', **kwargs) -> None: ...
log_info_structured = log_info

def get_logger(name: str = 'wl') -> StructuredLogger: ...
