from .file_operations import get_file_operations as get_file_operations
from .uv_tool import get_direct_command as get_direct_command, get_uv_tool_env as get_uv_tool_env, is_running_in_uv_tool as is_running_in_uv_tool, should_use_direct_execution as should_use_direct_execution
from _typeshed import Incomplete
from pathlib import Path

class SubprocessResult:
    returncode: Incomplete
    stdout: Incomplete
    stderr: Incomplete
    def __init__(self, returncode: int, stdout: str, stderr: str) -> None: ...
    @property
    def success(self) -> bool: ...

class SubprocessExecutor:
    def __init__(self) -> None: ...
    def run(self, command: list[str], env: dict[str, str] | None = None, cwd: Path | None = None, cache_result: bool = False, quiet: bool = False) -> SubprocessResult: ...
    def clear_cache(self) -> None: ...
    def get_cached_commands(self) -> list[str]: ...
