import datetime as dt

from collections.abc import Generator
from typing import Any, TypeAlias

import msgspec

from _typeshed import Incomplete

from .enumerations import MeasurementType as MeasurementType

log: Incomplete

class Quantile(msgspec.Struct, frozen=True):
    """One quantile point."""

    p: float
    value: float | None

class Freq(msgspec.Struct, frozen=True):
    """One row of a frequency table; order matters (usually sorted by freq desc)."""

    level: Any
    count: float
    prop: float

class DescribeBase(msgspec.Struct, frozen=True):
    name: str
    mtype: MeasurementType
    n: int
    n_missing: int
    weighted: bool
    drop_nulls: bool

class DescribeContinuous(DescribeBase, frozen=True):
    mean: float | None = ...
    std: float | None = ...
    var: float | None = ...
    min: float | None = ...
    p25: float | None = ...
    p50: float | None = ...
    p75: float | None = ...
    max: float | None = ...
    sum: float | None = ...
    percentiles: tuple[Quantile, ...] = ...

class DescribeDiscrete(DescribeBase, frozen=True):
    mean: float | None = ...
    std: float | None = ...
    var: float | None = ...
    min: float | None = ...
    p25: float | None = ...
    p50: float | None = ...
    p75: float | None = ...
    max: float | None = ...
    sum: float | None = ...
    levels: tuple[Freq, ...] = ...

class DescribeDatetime(DescribeBase, frozen=True):
    min: dt.datetime | dt.date | dt.time | None = ...
    max: dt.datetime | dt.date | dt.time | None = ...
    tz: str | None = ...

class DescribeNominal(DescribeBase, frozen=True):
    levels: tuple[Freq, ...]
    n_levels: int
    mode: Any | None = ...
    truncated: bool = ...

class DescribeOrdinal(DescribeBase, frozen=True):
    levels: tuple[Freq, ...]
    n_levels: int
    mode: Any | None = ...
    truncated: bool = ...

class DescribeBoolean(DescribeBase, frozen=True):
    false: Freq | None = ...
    true: Freq | None = ...

class DescribeString(DescribeBase, frozen=True):
    n_unique: int | None = ...
    top: tuple[Freq, ...] = ...
    truncated: bool = ...
    len_min: int | None = ...
    len_p50: float | None = ...
    len_mean: float | None = ...
    len_max: int | None = ...

DescribeItem: TypeAlias = (
    DescribeContinuous
    | DescribeDiscrete
    | DescribeDatetime
    | DescribeNominal
    | DescribeOrdinal
    | DescribeBoolean
    | DescribeString
)

class DescribeResult(msgspec.Struct, frozen=True):
    """
    Container for a whole describe() call.
    Keep global knobs (used/returned) so repr()/str() can show them and UIs can reconstruct.
    """

    items: tuple[DescribeItem, ...]
    weighted: bool
    weight_col: str | None
    drop_nulls: bool
    top_k: int
    percentiles: tuple[float, ...]
    generated_at: dt.datetime
    notes: str | None = ...
    PRINT_WIDTH: int | None = ...
    def __rich_console__(self, console, options) -> Generator[Incomplete]: ...
