from _typeshed import Incomplete

from svy.core.types import Category as Category

log: Incomplete

class MissingSpec:
    def __init__(
        self,
        dont_know: list[Category] | None = None,
        refusal: list[Category] | None = None,
        skipped: list[Category] | None = None,
        system_missing: list[Category] | None = None,
        not_applicable: list[Category] | None = None,
        prefer_not_to_answer: list[Category] | None = None,
        missing_by_design: list[Category] | None = None,
    ) -> None: ...
    @property
    def dont_know(self) -> list[Category]: ...
    @property
    def refusal(self) -> list[Category]: ...
    @property
    def skipped(self) -> list[Category]: ...
    @property
    def system_missing(self) -> list[Category]: ...
    @property
    def not_applicable(self) -> list[Category]: ...
    @property
    def prefer_not_to_answer(self) -> list[Category]: ...
    @property
    def missing_by_design(self) -> list[Category]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def get_all_missing_codes(self) -> set[Category]: ...
    def is_missing_code(self, value: Category) -> bool: ...
