# coding: utf-8

"""
    Gomtm API

    The Gomtm API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DevGomtmBuildOutput(BaseModel):
    """
    DevGomtmBuildOutput
    """ # noqa: E501
    filename: StrictStr = Field(description="Output file name")
    type: StrictStr = Field(description="Type of output")
    platform: StrictStr = Field(description="Target platform")
    size: Optional[StrictInt] = Field(default=None, description="File size in bytes (for files)")
    url: Optional[StrictStr] = Field(default=None, description="Download URL or registry URL")
    version: Optional[StrictStr] = Field(default=None, description="Version number")
    checksum: Optional[StrictStr] = Field(default=None, description="File checksum (SHA256)")
    __properties: ClassVar[List[str]] = ["filename", "type", "platform", "size", "url", "version", "checksum"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['binary', 'npm-package', 'docker-image', 'log']):
            raise ValueError("must be one of enum values ('binary', 'npm-package', 'docker-image', 'log')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DevGomtmBuildOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DevGomtmBuildOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in DevGomtmBuildOutput) in the input: " + _key)

        _obj = cls.model_validate({
            "filename": obj.get("filename"),
            "type": obj.get("type"),
            "platform": obj.get("platform"),
            "size": obj.get("size"),
            "url": obj.get("url"),
            "version": obj.get("version"),
            "checksum": obj.get("checksum")
        })
        return _obj


