from py_wlcommands.utils.logging import log_info as log_info

def remove_log_files() -> None: ...
def remove_pycache_dirs() -> None: ...
def remove_egg_info_dirs() -> None: ...
def clean_build_artifacts() -> None: ...
