"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from finance_dev.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class CancelOrderRequestTypedDict(TypedDict):
    order_id: int
    r"""Order ID to cancel"""


class CancelOrderRequest(BaseModel):
    order_id: Annotated[int, pydantic.Field(alias="orderId")]
    r"""Order ID to cancel"""
