"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from finance_dev.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CodeTypedDict(TypedDict):
    code: NotRequired[str]
    r"""Error code"""
    description: NotRequired[str]
    r"""Error description"""


class Code(BaseModel):
    code: Optional[str] = None
    r"""Error code"""

    description: Optional[str] = None
    r"""Error description"""
