"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from finance_dev.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class InitAuthResponseTypedDict(TypedDict):
    access_token: NotRequired[str]
    r"""JWT access token"""
    refresh_token: NotRequired[str]
    r"""JWT refresh token"""
    role: NotRequired[str]
    r"""User role"""


class InitAuthResponse(BaseModel):
    access_token: Optional[str] = None
    r"""JWT access token"""

    refresh_token: Optional[str] = None
    r"""JWT refresh token"""

    role: Optional[str] = None
    r"""User role"""
