"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .watchlistitem import WatchlistItem, WatchlistItemTypedDict
from finance_dev.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class WatchlistAccountResponseTypedDict(TypedDict):
    account_id: NotRequired[str]
    r"""The trading account identifier"""
    watchlist: NotRequired[List[WatchlistItemTypedDict]]
    r"""Array of watchlists associated with this account"""


class WatchlistAccountResponse(BaseModel):
    account_id: Optional[str] = None
    r"""The trading account identifier"""

    watchlist: Optional[List[WatchlistItem]] = None
    r"""Array of watchlists associated with this account"""
