
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import com.github.javacliparser
import com.yahoo.labs.samoa.instances
import java.lang
import moa.classifiers
import moa.classifiers.semisupervised.attributeSimilarity
import moa.core
import moa.options
import moa.tasks
import typing



class ClusterAndLabelClassifier(moa.classifiers.AbstractClassifier, moa.classifiers.SemiSupervisedLearner):
    clustererOption: moa.options.ClassOption = ...
    usePseudoLabelOption: com.github.javacliparser.FlagOption = ...
    debugModeOption: com.github.javacliparser.FlagOption = ...
    kNearestClusterOption: com.github.javacliparser.IntOption = ...
    def __init__(self): ...
    def addInitialWarmupTrainingInstances(self) -> None: ...
    def getModelDescription(self, stringBuilder: java.lang.StringBuilder, int: int) -> None: ...
    def getPurposeString(self) -> str: ...
    @typing.overload
    def getVotesForInstance(self, example: moa.core.Example[com.yahoo.labs.samoa.instances.Instance]) -> typing.MutableSequence[float]: ...
    @typing.overload
    def getVotesForInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> typing.MutableSequence[float]: ...
    def isRandomizable(self) -> bool: ...
    def prepareForUseImpl(self, taskMonitor: moa.tasks.TaskMonitor, objectRepository: typing.Union[moa.core.ObjectRepository, typing.Callable]) -> None: ...
    def resetLearningImpl(self) -> None: ...
    def trainOnInstanceImpl(self, instance: com.yahoo.labs.samoa.instances.Instance) -> None: ...
    def trainOnUnlabeledInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> int: ...

class SLEADE(moa.classifiers.AbstractClassifier, moa.classifiers.SemiSupervisedLearner, moa.classifiers.MultiClassClassifier):
    baseEnsembleOption: moa.options.ClassOption = ...
    confidenceStrategyOption: com.github.javacliparser.MultiChoiceOption = ...
    enableRandomThresholdOption: com.github.javacliparser.FlagOption = ...
    autoWeightShrinkageOption: com.github.javacliparser.MultiChoiceOption = ...
    SSLStrategyOption: com.github.javacliparser.MultiChoiceOption = ...
    SSL_minConfidenceOption: com.github.javacliparser.FloatOption = ...
    weightFunctionOption: com.github.javacliparser.MultiChoiceOption = ...
    pairingFunctionOption: com.github.javacliparser.MultiChoiceOption = ...
    SSL_weightShrinkageOption: com.github.javacliparser.FloatOption = ...
    useUnsupervisedDriftDetectionOption: com.github.javacliparser.FlagOption = ...
    studentLearnerForUnsupervisedDriftDetectionOption: moa.options.ClassOption = ...
    driftDetectionMethodOption: moa.options.ClassOption = ...
    unsupervisedDetectionWeightWindowOption: com.github.javacliparser.IntOption = ...
    labeledWindowLimitOption: com.github.javacliparser.IntOption = ...
    debugEnsembleDiversityOption: com.github.javacliparser.FlagOption = ...
    debugOutputFileOption: com.github.javacliparser.FileOption = ...
    debugOutputDriftFileOption: com.github.javacliparser.FileOption = ...
    debugOutputConfidencePredictionsFileOption: com.github.javacliparser.FileOption = ...
    debugFrequencyOption: com.github.javacliparser.IntOption = ...
    debugPerfectPseudoLabelingOption: com.github.javacliparser.FlagOption = ...
    gtDriftLocationOption: com.github.javacliparser.StringOption = ...
    AUTO_WEIGHT_SHRINKAGE_CONSTANT: typing.ClassVar[int] = ...
    AUTO_WEIGHT_SHRINKAGE_LABELED_DIV_TOTAL: typing.ClassVar[int] = ...
    AUTO_WEIGHT_SHRINKAGE_LABELED_IGNORE_WARMUP_DIV_TOTAL: typing.ClassVar[int] = ...
    SSL_STRATEGY_NO_CHECKS: typing.ClassVar[int] = ...
    SSL_STRATEGY_CHECK_CONFIDENCE_AND_OTHERS: typing.ClassVar[int] = ...
    SSL_WEIGHT_CONSTANT_1: typing.ClassVar[int] = ...
    SSL_WEIGHT_CONFIDENCE: typing.ClassVar[int] = ...
    SSL_WEIGHT_CONFIDENCE_WS: typing.ClassVar[int] = ...
    SSL_WEIGHT_UNSUPERVISED_DETECTION_WEIGHT_SHRINKAGE: typing.ClassVar[int] = ...
    SSL_PAIRING_MIN_KAPPA: typing.ClassVar[int] = ...
    SSL_PAIRING_RANDOM: typing.ClassVar[int] = ...
    SSL_PAIRING_MAJORITY_TRAINS_MINORITY: typing.ClassVar[int] = ...
    SSL_CONFIDENCE_STRATEGY_SUM: typing.ClassVar[int] = ...
    SSL_CONFIDENCE_STRATEGY_ARGMAX: typing.ClassVar[int] = ...
    def __init__(self): ...
    def addInitialWarmupTrainingInstances(self) -> None: ...
    def getModelDescription(self, stringBuilder: java.lang.StringBuilder, int: int) -> None: ...
    @typing.overload
    def getVotesForInstance(self, example: moa.core.Example[com.yahoo.labs.samoa.instances.Instance]) -> typing.MutableSequence[float]: ...
    @typing.overload
    def getVotesForInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> typing.MutableSequence[float]: ...
    def isRandomizable(self) -> bool: ...
    def resetLearningImpl(self) -> None: ...
    def setModelContext(self, instancesHeader: com.yahoo.labs.samoa.instances.InstancesHeader) -> None: ...
    def trainOnInstanceImpl(self, instance: com.yahoo.labs.samoa.instances.Instance) -> None: ...
    def trainOnUnlabeledInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> int: ...

class SSLTaskTester(moa.classifiers.AbstractClassifier, moa.classifiers.SemiSupervisedLearner):
    def __init__(self): ...
    def addInitialWarmupTrainingInstances(self) -> None: ...
    def getModelDescription(self, stringBuilder: java.lang.StringBuilder, int: int) -> None: ...
    @typing.overload
    def getVotesForInstance(self, example: moa.core.Example[com.yahoo.labs.samoa.instances.Instance]) -> typing.MutableSequence[float]: ...
    @typing.overload
    def getVotesForInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> typing.MutableSequence[float]: ...
    def isRandomizable(self) -> bool: ...
    def prepareForUseImpl(self, taskMonitor: moa.tasks.TaskMonitor, objectRepository: typing.Union[moa.core.ObjectRepository, typing.Callable]) -> None: ...
    def resetLearningImpl(self) -> None: ...
    def trainOnInstanceImpl(self, instance: com.yahoo.labs.samoa.instances.Instance) -> None: ...
    def trainOnUnlabeledInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> int: ...

class SelfTrainingClassifier(moa.classifiers.AbstractClassifier, moa.classifiers.SemiSupervisedLearner):
    learnerOption: moa.options.ClassOption = ...
    batchSizeOption: com.github.javacliparser.IntOption = ...
    thresholdChoiceOption: com.github.javacliparser.MultiChoiceOption = ...
    thresholdOption: com.github.javacliparser.FloatOption = ...
    horizonOption: com.github.javacliparser.IntOption = ...
    ratioThresholdOption: com.github.javacliparser.FloatOption = ...
    confidenceOption: com.github.javacliparser.MultiChoiceOption = ...
    def __init__(self): ...
    def addInitialWarmupTrainingInstances(self) -> None: ...
    def getModelDescription(self, stringBuilder: java.lang.StringBuilder, int: int) -> None: ...
    def getPurposeString(self) -> str: ...
    @typing.overload
    def getVotesForInstance(self, example: moa.core.Example[com.yahoo.labs.samoa.instances.Instance]) -> typing.MutableSequence[float]: ...
    @typing.overload
    def getVotesForInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> typing.MutableSequence[float]: ...
    def isRandomizable(self) -> bool: ...
    def prepareForUseImpl(self, taskMonitor: moa.tasks.TaskMonitor, objectRepository: typing.Union[moa.core.ObjectRepository, typing.Callable]) -> None: ...
    def resetLearningImpl(self) -> None: ...
    def trainOnInstanceImpl(self, instance: com.yahoo.labs.samoa.instances.Instance) -> None: ...
    def trainOnUnlabeledInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> int: ...

class SelfTrainingIncrementalClassifier(moa.classifiers.AbstractClassifier, moa.classifiers.SemiSupervisedLearner):
    learnerOption: moa.options.ClassOption = ...
    thresholdChoiceOption: com.github.javacliparser.MultiChoiceOption = ...
    thresholdOption: com.github.javacliparser.FloatOption = ...
    horizonOption: com.github.javacliparser.IntOption = ...
    ratioThresholdOption: com.github.javacliparser.FloatOption = ...
    def __init__(self): ...
    def addInitialWarmupTrainingInstances(self) -> None: ...
    def getModelDescription(self, stringBuilder: java.lang.StringBuilder, int: int) -> None: ...
    def getPurposeString(self) -> str: ...
    @typing.overload
    def getVotesForInstance(self, example: moa.core.Example[com.yahoo.labs.samoa.instances.Instance]) -> typing.MutableSequence[float]: ...
    @typing.overload
    def getVotesForInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> typing.MutableSequence[float]: ...
    def isRandomizable(self) -> bool: ...
    def prepareForUseImpl(self, taskMonitor: moa.tasks.TaskMonitor, objectRepository: typing.Union[moa.core.ObjectRepository, typing.Callable]) -> None: ...
    def resetLearningImpl(self) -> None: ...
    def trainOnInstanceImpl(self, instance: com.yahoo.labs.samoa.instances.Instance) -> None: ...
    def trainOnUnlabeledInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> int: ...

class SelfTrainingWeightingClassifier(moa.classifiers.AbstractClassifier, moa.classifiers.SemiSupervisedLearner):
    learnerOption: moa.options.ClassOption = ...
    equalWeightOption: com.github.javacliparser.FlagOption = ...
    def __init__(self): ...
    def addInitialWarmupTrainingInstances(self) -> None: ...
    def getModelDescription(self, stringBuilder: java.lang.StringBuilder, int: int) -> None: ...
    def getPurposeString(self) -> str: ...
    @typing.overload
    def getVotesForInstance(self, example: moa.core.Example[com.yahoo.labs.samoa.instances.Instance]) -> typing.MutableSequence[float]: ...
    @typing.overload
    def getVotesForInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> typing.MutableSequence[float]: ...
    def isRandomizable(self) -> bool: ...
    def prepareForUseImpl(self, taskMonitor: moa.tasks.TaskMonitor, objectRepository: typing.Union[moa.core.ObjectRepository, typing.Callable]) -> None: ...
    def resetLearningImpl(self) -> None: ...
    def trainOnInstanceImpl(self, instance: com.yahoo.labs.samoa.instances.Instance) -> None: ...
    def trainOnUnlabeledInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> int: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("moa.classifiers.semisupervised")``.

    ClusterAndLabelClassifier: typing.Type[ClusterAndLabelClassifier]
    SLEADE: typing.Type[SLEADE]
    SSLTaskTester: typing.Type[SSLTaskTester]
    SelfTrainingClassifier: typing.Type[SelfTrainingClassifier]
    SelfTrainingIncrementalClassifier: typing.Type[SelfTrainingIncrementalClassifier]
    SelfTrainingWeightingClassifier: typing.Type[SelfTrainingWeightingClassifier]
    attributeSimilarity: moa.classifiers.semisupervised.attributeSimilarity.__module_protocol__
