"""Type stubs for objects module."""

from typing import Any, Dict, List, Tuple

def getById(object_id: int) -> Dict[str, Any] | None: ...
def getByName(name: str, exact: bool = False) -> List[Dict[str, Any]]: ...
def getLocations(object_id: int) -> List[Tuple[int, int, int]]: ...
def getNearby(x: int, y: int, plane: int = 0, radius: int = 10) -> List[Dict[str, Any]]: ...
def searchByAction(action: str) -> List[Dict[str, Any]]: ...
def countObjects() -> int: ...
def countLocations() -> int: ...
def executeQuery(query: str, params: tuple = ()) -> List[Dict[str, Any]]: ...
def close() -> None: ...
