from dataclasses import dataclass

from _typeshed import Incomplete

log: Incomplete
PALETTE: dict[str, dict[str, str]]

@dataclass(frozen=True)
class Components:
    panel_border: str = ...
    header_style: str = ...
    title_style: str = ...
    sample_border: str = ...
    estimate_border: str = ...
    ttest_border: str = ...
    size_border: str = ...
    error_border: str = ...
    error_header_style: str = ...
    error_title_style: str = ...

@dataclass(frozen=True)
class Theme:
    components: Components = ...

THEME: Incomplete

def set_theme(theme: Theme) -> None:
    """Replace the active theme."""
