from __future__ import annotations
__all__: list[str] = ['BUILD_STUB_FILES', 'BUILD_UMFPACK', 'CMAKE_CUDA_COMPILER', 'CMAKE_CXX_COMPILER', 'CMAKE_CXX_COMPILER_LAUNCHER', 'CMAKE_C_COMPILER', 'CMAKE_INSTALL_PREFIX', 'CMAKE_LINKER', 'ENABLE_UNIT_TESTS', 'INSTALL_DEPENDENCIES', 'MKL_LINK', 'NETGEN_DIR', 'NGSOLVE_COMPILE_DEFINITIONS', 'NGSOLVE_COMPILE_DEFINITIONS_PRIVATE', 'NGSOLVE_COMPILE_INCLUDE_DIRS', 'NGSOLVE_COMPILE_OPTIONS', 'NGSOLVE_INSTALL_DIR_BIN', 'NGSOLVE_INSTALL_DIR_CMAKE', 'NGSOLVE_INSTALL_DIR_INCLUDE', 'NGSOLVE_INSTALL_DIR_LIB', 'NGSOLVE_INSTALL_DIR_PYTHON', 'NGSOLVE_INSTALL_DIR_RES', 'NGSOLVE_VERSION', 'NGSOLVE_VERSION_GIT', 'NGSOLVE_VERSION_HASH', 'NGSOLVE_VERSION_MAJOR', 'NGSOLVE_VERSION_MINOR', 'NGSOLVE_VERSION_PATCH', 'NGSOLVE_VERSION_PYTHON', 'NGSOLVE_VERSION_TWEAK', 'USE_CCACHE', 'USE_HYPRE', 'USE_LAPACK', 'USE_MKL', 'USE_MUMPS', 'USE_PARDISO', 'USE_UMFPACK', 'get_cmake_dir', 'is_python_package', 'version']
def _cmake_to_bool(s):
    ...
def get_cmake_dir():
    ...
BUILD_STUB_FILES: bool = True
BUILD_UMFPACK: bool = False
CMAKE_CUDA_COMPILER: str = ''
CMAKE_CXX_COMPILER: str = '/Library/Developer/CommandLineTools/usr/bin/c++'
CMAKE_CXX_COMPILER_LAUNCHER: str = '/usr/local/bin/ccache'
CMAKE_C_COMPILER: str = '/Library/Developer/CommandLineTools/usr/bin/cc'
CMAKE_INSTALL_PREFIX: str = '/Users/gitlab-runner/builds/builds/rL7WHzyj/0/ngsolve/ngsolve/_skbuild/macosx-10.15-universal2-3.14/cmake-install'
CMAKE_LINKER: str = '/Library/Developer/CommandLineTools/usr/bin/ld'
ENABLE_UNIT_TESTS: bool = False
INSTALL_DEPENDENCIES: bool = False
MKL_LINK: str = ''
NETGEN_DIR: str = '/Users/gitlab-runner/Library/Python/3.14/lib/python/site-packages'
NGSOLVE_COMPILE_DEFINITIONS: str = 'HAVE_NETGEN_SOURCES;HAVE_DLFCN_H;HAVE_CXA_DEMANGLE;USE_TIMEOFDAY;MSG_NOSIGNAL=0;TCL;LAPACK;NGS_PYTHON;USE_UMFPACK'
NGSOLVE_COMPILE_DEFINITIONS_PRIVATE: str = ''
NGSOLVE_COMPILE_INCLUDE_DIRS: str = ''
NGSOLVE_COMPILE_OPTIONS: str = '$<$<COMPILE_LANGUAGE:CXX>:-std=c++17>;$<$<COMPILE_LANGUAGE:CXX>:-Wno-undefined-var-template;-Wno-vla-extension>;-DMAX_SYS_DIM=3'
NGSOLVE_INSTALL_DIR_BIN: str = 'bin'
NGSOLVE_INSTALL_DIR_CMAKE: str = 'ngsolve/cmake'
NGSOLVE_INSTALL_DIR_INCLUDE: str = 'netgen/include'
NGSOLVE_INSTALL_DIR_LIB: str = 'netgen'
NGSOLVE_INSTALL_DIR_PYTHON: str = '.'
NGSOLVE_INSTALL_DIR_RES: str = 'share'
NGSOLVE_VERSION: str = '6.2.2506-199-gbbeadc99a'
NGSOLVE_VERSION_GIT: str = 'v6.2.2506-199-gbbeadc99a'
NGSOLVE_VERSION_HASH: str = 'gbbeadc99a'
NGSOLVE_VERSION_MAJOR: str = '6'
NGSOLVE_VERSION_MINOR: str = '2'
NGSOLVE_VERSION_PATCH: str = '2506'
NGSOLVE_VERSION_PYTHON: str = '6.2.2506.post199.dev0'
NGSOLVE_VERSION_TWEAK: str = '199'
USE_CCACHE: bool = True
USE_HYPRE: bool = False
USE_LAPACK: bool = True
USE_MKL: bool = False
USE_MUMPS: bool = False
USE_PARDISO: bool = False
USE_UMFPACK: bool = True
is_python_package: bool = True
version: str = 'v6.2.2506-199-gbbeadc99a'
