class PlatformAdapter:
    def __init__(self) -> None: ...
    @staticmethod
    def get_system() -> str: ...
    @staticmethod
    def is_windows() -> bool: ...
    @staticmethod
    def get_env() -> dict[str, str]: ...
    @staticmethod
    def get_encoding() -> str: ...
