
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-12-19T09:53:38+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "afb231aec5bbd77563b4857880ccc3c9e6ef3a33",
 "version": "1.3.1.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
