from typing import Any, Callable, TypeVar

T = TypeVar('T')

class DependencyInjectionContainer:
    def __new__(cls): ...
    def __init__(self) -> None: ...
    def register_singleton(self, name: str, factory: Callable[[], Any]) -> None: ...
    def register_transient(self, name: str, factory: Callable[[], Any]) -> None: ...
    def register_instance(self, name: str, instance: Any) -> None: ...
    def resolve(self, name: str) -> Any: ...
    def resolve_by_type(self, type_: type[T]) -> T: ...
    def clear(self) -> None: ...

def get_container() -> DependencyInjectionContainer: ...
def register_singleton(name: str, factory: Callable[[], Any]) -> None: ...
def register_transient(name: str, factory: Callable[[], Any]) -> None: ...
def register_instance(name: str, instance: Any) -> None: ...
def resolve(name: str) -> Any: ...
def resolve_by_type(type_: type[T]) -> T: ...
