from ....utils.log_levels import LogLevel as LogLevel
from ....utils.logging import StructuredLogger as StructuredLogger, get_logger as get_logger, log_debug as log_debug, log_error as log_error, log_info as log_info, log_warning as log_warning
from collections.abc import Callable as Callable
from typing import Any

class LogManager:
    logger: StructuredLogger
    def __init__(self, name: str = 'initenv') -> None: ...
    def set_level(self, level: int) -> None: ...
    def info(self, message: str, lang: str = 'en') -> None: ...
    def warning(self, message: str) -> None: ...
    def error(self, message: str) -> None: ...
    def debug(self, message: str) -> None: ...

def performance_monitor(func: Callable[..., Any]) -> Callable[..., Any]: ...
