from py_wlcommands.utils.logging import log_info as log_info

class PreCommitManager:
    def create_pre_commit_config(self) -> None: ...
    def verify_pre_commit_config(self) -> None: ...
    def create_pre_commit_hook(self) -> None: ...
    def verify_pre_commit_hook(self) -> None: ...
