"""
ActionEngine Actions interface.
"""
from __future__ import annotations
import actionengine._C.data
import collections.abc
import typing
__all__: list[str] = ['Action', 'ActionRegistry', 'ActionSchema']
class Action:
    @typing.overload
    def __init__(self, arg0: Action) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: ActionSchema, arg1: str) -> None:
        ...
    def _hint_run(self) -> None:
        ...
    def bind_handler(self, handler: collections.abc.Callable) -> None:
        ...
    def bind_node_map(self, node_map: ...) -> None:
        ...
    def bind_streams_on_inputs_by_default(self, bind: bool) -> None:
        ...
    def bind_streams_on_outputs_by_default(self, bind: bool) -> None:
        ...
    def call(self) -> None:
        ...
    def cancel(self) -> None:
        ...
    def cancelled(self) -> bool:
        ...
    def clear_inputs_after_run(self, clear: bool = True) -> None:
        ...
    def clear_outputs_after_run(self, clear: bool = True) -> None:
        ...
    def get_id(self) -> str:
        ...
    def get_input(self, name: str, bind_stream: bool | None = None) -> ...:
        ...
    def get_node(self, node_id: str) -> ...:
        ...
    def get_node_map(self) -> ...:
        ...
    def get_output(self, name: str, bind_stream: bool | None = None) -> ...:
        ...
    def get_registry(self) -> ActionRegistry:
        ...
    def get_schema(self) -> ActionSchema:
        ...
    def get_session(self) -> ...:
        ...
    def get_stream(self) -> ...:
        ...
    def make_action_in_same_session(self, name: str, action_id: str = '') -> Action:
        ...
    def run(self) -> Action:
        ...
    def wait_until_complete(self) -> None:
        ...
class ActionRegistry:
    """
    Registry for action schemas and handlers.
    """
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: ActionRegistry) -> None:
        ...
    def get_schema(self, name: str) -> ActionSchema:
        ...
    def is_registered(self, name: str) -> bool:
        ...
    def list_registered_actions(self) -> list[str]:
        ...
    def make_action(self, name: str, action_id: str = '', node_map: ... = None, stream: ... = None, session: ... = None) -> ...:
        ...
    def make_action_message(self, name: str, action_id: str) -> actionengine._C.data.ActionMessage:
        ...
    def register(self, name: str, definition: ActionSchema, handler: collections.abc.Callable) -> None:
        ...
class ActionSchema:
    """
    An action schema.
    """
    description: str
    name: str
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: ActionSchema) -> None:
        ...
    @typing.overload
    def __init__(self, *, name: str, inputs: collections.abc.Sequence[tuple[str, str]] = [], outputs: collections.abc.Sequence[tuple[str, str]] = [], description: str = '') -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def inputs(self) -> dict[str, str]:
        ...
    @inputs.setter
    def inputs(self, arg0: collections.abc.Mapping[str, str]) -> None:
        ...
    @property
    def outputs(self) -> dict[str, str]:
        ...
    @outputs.setter
    def outputs(self, arg0: collections.abc.Mapping[str, str]) -> None:
        ...
