# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...commons.types.links import Links
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .included_resource import IncludedResource
from .offer_attributes import OfferAttributes
from .offer_relationships import OfferRelationships


class OfferResponse(UniversalBaseModel):
    type: typing.Literal["standardOffer"] = "standardOffer"
    id: str = pydantic.Field()
    """
    Offer ID in Kard's system
    """

    attributes: OfferAttributes
    links: typing.Optional[Links] = None
    relationships: typing.Optional[OfferRelationships] = pydantic.Field(default=None)
    """
    Related resources references
    """

    included: typing.Optional[typing.List[IncludedResource]] = pydantic.Field(default=None)
    """
    Included related resources
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
