from _typeshed import Incomplete
from py_wlcommands.utils.logging import log_info as log_info

class BranchCreator:
    git_utility: Incomplete
    def __init__(self, git_utility) -> None: ...
    def setup_initial_branches(self) -> None: ...
    def check_and_pull_branch(self, branch_name: str) -> None: ...
    def create_git_flow_branch(self, work_type: str, source_branch: str) -> None: ...
