from enum import StrEnum


class AutoChessSkillTriggerType(StrEnum):
    DEFAULT = "DEFAULT"
    ALWAYS = "ALWAYS"
    SEARCH = "SEARCH"
    MLYSS_WTRMAN = "MLYSS_WTRMAN"
    MARCILS2 = "MARCILS2"
    TRY_SEARCH_ENEMY_SKILL = "TRY_SEARCH_ENEMY_SKILL"
    TRY_SEARCH_ALLY_SKILL = "TRY_SEARCH_ALLY_SKILL"
    CUSTOM_RANGE_SEARCH_ENEMY = "CUSTOM_RANGE_SEARCH_ENEMY"
    CUSTOM_RANGE_SEARCH_ALLY = "CUSTOM_RANGE_SEARCH_ALLY"
    GDGLOW_SKILL_2 = "GDGLOW_SKILL_2"
    ACT_DEFAULT = "ACT_DEFAULT"
    AUTO_STOP = "AUTO_STOP"
