from enum import StrEnum


class PlayerRoguelikeState(StrEnum):
    NONE = "NONE"
    GAME_REWARD_RELIC = "GAME_REWARD_RELIC"
    GAME_REWARD_SCENE = "GAME_REWARD_SCENE"
    GAME_REWARD_RECRUIT = "GAME_REWARD_RECRUIT"
    MOVE_WAIT = "MOVE_WAIT"
    BUY_WAIT = "BUY_WAIT"
    CHOICE_WAIT = "CHOICE_WAIT"
    REWARD_WAIT = "REWARD_WAIT"
    BATTLE_WAIT_START = "BATTLE_WAIT_START"
    BATTLE_WAIT_END = "BATTLE_WAIT_END"
    GAME_END = "GAME_END"
