from enum import StrEnum


class RoguelikeSkyZoneNodeType(StrEnum):
    NONE = "NONE"
    ORIGIN = "ORIGIN"
    BATTLE = "BATTLE"
    TRIAL_GATE = "TRIAL_GATE"
    INCIDENT = "INCIDENT"
    TREASURE = "TREASURE"
    SHOP = "SHOP"
    SACRIFICE = "SACRIFICE"
    ENTERTAINMENT = "ENTERTAINMENT"
    MARKET = "MARKET"
    BATTLE_HARD = "BATTLE_HARD"
    INCIDENT_BOSS = "INCIDENT_BOSS"
    INCIDENT_BOSS_ONLY = "INCIDENT_BOSS_ONLY"
    CHOICES = "CHOICES"
    BATTLES = "BATTLES"
