from enum import StrEnum


class RoguelikeChoiceHintType(StrEnum):
    NONE = "NONE"
    ITEM = "ITEM"
    CANDLED_CHAR = "CANDLED_CHAR"
    GUIDED_CHAR = "GUIDED_CHAR"
    SACRIFICE = "SACRIFICE"
    SACRIFICE_TOTEM = "SACRIFICE_TOTEM"
    EXPEDITION = "EXPEDITION"
    CANDLE = "CANDLE"
    GUIDED = "GUIDED"
    HP = "HP"
    VISION = "VISION"
    STASHED_RECRUIT = "STASHED_RECRUIT"
    CHAOS = "CHAOS"
    FRAGMENT = "FRAGMENT"
    SP_ZONE_AP = "SP_ZONE_AP"
    COPPER_LUCK = "COPPER_LUCK"
