from enum import StrEnum


class ShopRouteTarget(StrEnum):
    RECOMMENDSHOP = "RECOMMENDSHOP"
    CASHSHOP = "CASHSHOP"
    GIFTPACKAGE = "GIFTPACKAGE"
    SKINSHOP = "SKINSHOP"
    HQCSHOP = "HQCSHOP"
    LQCSHOP = "LQCSHOP"
    EXQCSHOP = "EXQCSHOP"
    SOCAILSHOP = "SOCAILSHOP"
    FURNSHOP = "FURNSHOP"
    REPSHOP = "REPSHOP"
    LMGTSSHOP = "LMGTSSHOP"
    EPGSSHOP = "EPGSSHOP"
    CLASSICSHOP = "CLASSICSHOP"
    NONE = "NONE"
