from psutil import net_if_addrs as net_if_addrs
from pyvqnet.distributed.runner.common.utils import _cache
from pyvqnet.distributed.runner.util import threads as threads
from socket import AF_INET as AF_INET

@_cache
def get_local_host_addresses(): ...
def resolve_host_address(host_name): ...
def filter_local_addresses(all_host_names): ...
