from enum import Enum


class ErrorCode(str, Enum):
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
    BILLING_TRANSACTION_FAILED = "BILLING_TRANSACTION_FAILED"
    CONFIGURATION_ERROR = "CONFIGURATION_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    DATASET_REJECTED = "DATASET_REJECTED"
    INFERENCE_ERROR = "INFERENCE_ERROR"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    INVALID_API_KEY = "INVALID_API_KEY"
    INVALID_DTYPE = "INVALID_DTYPE"
    INVALID_MODEL_INPUT = "INVALID_MODEL_INPUT"
    INVALID_PARAMETER = "INVALID_PARAMETER"
    INVALID_SHAPE = "INVALID_SHAPE"
    INVALID_VALUE_RANGE = "INVALID_VALUE_RANGE"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    MODEL_INITIALIZATION_ERROR = "MODEL_INITIALIZATION_ERROR"
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
    OUT_OF_MEMORY = "OUT_OF_MEMORY"
    PRICING_NOT_FOUND = "PRICING_NOT_FOUND"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    REQUEST_TOO_LARGE = "REQUEST_TOO_LARGE"
    RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    TIMEOUT_ERROR = "TIMEOUT_ERROR"
    TRITON_CONNECTION_ERROR = "TRITON_CONNECTION_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"

    def __str__(self) -> str:
        return str(self.value)
