
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import com.github.javacliparser
import com.yahoo.labs.samoa.instances
import java.lang
import moa.classifiers
import moa.classifiers.rules.multilabel.meta
import moa.core
import moa.options
import typing



class RandomAMRules(moa.classifiers.rules.multilabel.meta.MultiLabelRandomAMRules, moa.classifiers.Regressor):
    def __init__(self): ...

class RandomAMRulesOld(moa.classifiers.AbstractClassifier, moa.classifiers.Regressor):
    VerbosityOption: com.github.javacliparser.IntOption = ...
    baseLearnerOption: moa.options.ClassOption = ...
    ensembleSizeOption: com.github.javacliparser.IntOption = ...
    numAttributesPercentageOption: com.github.javacliparser.FloatOption = ...
    useBaggingOption: com.github.javacliparser.FlagOption = ...
    votingFunctionOption: moa.options.ClassOption = ...
    votingTypeOption: com.github.javacliparser.MultiChoiceOption = ...
    fadingErrorFactorOption: com.github.javacliparser.FloatOption = ...
    randomSeedOption: com.github.javacliparser.IntOption = ...
    def __init__(self): ...
    def getModelDescription(self, stringBuilder: java.lang.StringBuilder, int: int) -> None: ...
    def getPurposeString(self) -> str: ...
    def getSubClassifiers(self) -> typing.MutableSequence[moa.classifiers.Classifier]: ...
    @typing.overload
    def getVotesForInstance(self, example: moa.core.Example[com.yahoo.labs.samoa.instances.Instance]) -> typing.MutableSequence[float]: ...
    @typing.overload
    def getVotesForInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> typing.MutableSequence[float]: ...
    def isRandomizable(self) -> bool: ...
    def resetLearningImpl(self) -> None: ...
    def trainOnInstanceImpl(self, instance: com.yahoo.labs.samoa.instances.Instance) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("moa.classifiers.rules.meta")``.

    RandomAMRules: typing.Type[RandomAMRules]
    RandomAMRulesOld: typing.Type[RandomAMRulesOld]
