"""
OpenGeode-Inspector Python binding
"""
from __future__ import annotations
import opengeode.lib64.opengeode_py_basic
import opengeode.lib64.opengeode_py_mesh
import opengeode.lib64.opengeode_py_model
import pybind11_stubgen.typing_ext
import typing
__all__: list[str] = ['BRepBlocksTopologyInspectionResult', 'BRepComponentMeshesAdjacency', 'BRepComponentMeshesColocation', 'BRepComponentMeshesDegeneration', 'BRepComponentMeshesManifold', 'BRepCornersTopologyInspectionResult', 'BRepInspectionResult', 'BRepInspector', 'BRepLinesTopologyInspectionResult', 'BRepMeshesAdjacencyInspectionResult', 'BRepMeshesDegenerationInspectionResult', 'BRepMeshesInspectionResult', 'BRepMeshesInspector', 'BRepMeshesIntersections', 'BRepMeshesManifoldInspectionResult', 'BRepNonManifoldEdge', 'BRepSurfacesTopologyInspectionResult', 'BRepTopologyInspectionResult', 'BRepTopologyInspector', 'BRepUniqueVerticesColocation', 'EdgedCurveColocation2D', 'EdgedCurveColocation3D', 'EdgedCurveDegeneration2D', 'EdgedCurveDegeneration3D', 'EdgedCurveInspectionResult', 'EdgedCurveInspector2D', 'EdgedCurveInspector3D', 'ElementsIntersectionsInspectionResult', 'InspectionIssuesArrayIndex2', 'InspectionIssuesBRepNonManifoldEdge', 'InspectionIssuesIndex', 'InspectionIssuesMapArrayIndex2', 'InspectionIssuesMapBRepNonManifoldEdge', 'InspectionIssuesMapIndex', 'InspectionIssuesMapPairComponentMeshElement', 'InspectionIssuesMapPairIndex', 'InspectionIssuesMapPolygonEdge', 'InspectionIssuesMapPolyhedronFacet', 'InspectionIssuesMapPolyhedronFacetVertices', 'InspectionIssuesMapUUID', 'InspectionIssuesMapVectorIndex', 'InspectionIssuesPairComponentMeshElement', 'InspectionIssuesPairIndex', 'InspectionIssuesPolygonEdge', 'InspectionIssuesPolyhedronFacet', 'InspectionIssuesPolyhedronFacetVertices', 'InspectionIssuesUUID', 'InspectionIssuesVectorIndex', 'InspectorInspectorLibrary', 'MeshesColocationInspectionResult', 'PointSetColocation2D', 'PointSetColocation3D', 'PointSetInspectionResult', 'PointSetInspector2D', 'PointSetInspector3D', 'SectionComponentMeshesAdjacency', 'SectionComponentMeshesColocation', 'SectionComponentMeshesDegeneration', 'SectionComponentMeshesManifold', 'SectionCornersTopologyInspectionResult', 'SectionInspectionResult', 'SectionInspector', 'SectionLinesTopologyInspectionResult', 'SectionMeshesAdjacencyInspectionResult', 'SectionMeshesDegenerationInspectionResult', 'SectionMeshesInspectionResult', 'SectionMeshesInspector', 'SectionMeshesIntersections', 'SectionMeshesManifoldInspectionResult', 'SectionSurfacesTopologyInspectionResult', 'SectionTopologyInspectionResult', 'SectionTopologyInspector', 'SectionUniqueVerticesColocation', 'SolidInspectionResult', 'SolidMeshAdjacency3D', 'SolidMeshColocation3D', 'SolidMeshDegeneration3D', 'SolidMeshEdgeManifold3D', 'SolidMeshFacetManifold3D', 'SolidMeshInspector3D', 'SolidMeshVertexManifold3D', 'SurfaceCurveIntersections2D', 'SurfaceCurveIntersections3D', 'SurfaceInspectionResult', 'SurfaceMeshAdjacency2D', 'SurfaceMeshAdjacency3D', 'SurfaceMeshColocation2D', 'SurfaceMeshColocation3D', 'SurfaceMeshDegeneration2D', 'SurfaceMeshDegeneration3D', 'SurfaceMeshEdgeManifold2D', 'SurfaceMeshEdgeManifold3D', 'SurfaceMeshInspector2D', 'SurfaceMeshInspector3D', 'SurfaceMeshIntersections2D', 'SurfaceMeshIntersections3D', 'SurfaceMeshVertexManifold2D', 'SurfaceMeshVertexManifold3D', 'UniqueVerticesInspectionResult', 'inspect_brep', 'inspect_edged_curve2D', 'inspect_edged_curve3D', 'inspect_point_set2D', 'inspect_point_set3D', 'inspect_section', 'inspect_solid3D', 'inspect_surface2D', 'inspect_surface3D']
class BRepBlocksTopologyInspectionResult:
    blocks_not_linked_to_a_unique_vertex: InspectionIssuesMapIndex
    blocks_with_not_closed_boundary_surfaces: InspectionIssuesUUID
    model_boundaries_dont_form_a_closed_surface: InspectionIssuesIndex
    some_blocks_not_meshed: InspectionIssuesUUID
    unique_vertex_linked_to_multiple_invalid_surfaces: InspectionIssuesIndex
    unique_vertices_linked_to_a_single_and_invalid_surface: InspectionIssuesIndex
    unique_vertices_linked_to_surface_with_wrong_relationship_to_blocks: InspectionIssuesIndex
    unique_vertices_part_of_two_blocks_and_no_boundary_surface: InspectionIssuesIndex
    unique_vertices_with_incorrect_block_cmvs_count: InspectionIssuesIndex
    wrong_block_boundary_surface: InspectionIssuesUUID
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class BRepComponentMeshesAdjacency:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.BRep) -> None:
        ...
    def inspect_brep_meshes_adjacencies(self) -> BRepMeshesAdjacencyInspectionResult:
        ...
class BRepComponentMeshesColocation:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.BRep) -> None:
        ...
    def inspect_meshes_point_colocations(self) -> MeshesColocationInspectionResult:
        ...
class BRepComponentMeshesDegeneration:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.BRep) -> None:
        ...
    def inspect_edges_degeneration(self, arg0: float) -> BRepMeshesDegenerationInspectionResult:
        ...
    def inspect_elements_degeneration(self) -> BRepMeshesDegenerationInspectionResult:
        ...
    def inspect_polygons_degeneration(self, arg0: float) -> BRepMeshesDegenerationInspectionResult:
        ...
    def inspect_polyhedra_degeneration(self, arg0: float) -> BRepMeshesDegenerationInspectionResult:
        ...
class BRepComponentMeshesManifold:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.BRep) -> None:
        ...
    def inspect_brep_manifold(self) -> BRepMeshesManifoldInspectionResult:
        ...
class BRepCornersTopologyInspectionResult:
    corners_not_linked_to_a_unique_vertex: InspectionIssuesMapIndex
    corners_not_meshed: InspectionIssuesUUID
    unique_vertices_liked_to_not_boundary_line_corner: InspectionIssuesIndex
    unique_vertices_linked_to_multiple_corners: InspectionIssuesIndex
    unique_vertices_linked_to_not_internal_nor_boundary_corner: InspectionIssuesIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class BRepInspectionResult:
    meshes: BRepMeshesInspectionResult
    topology: BRepTopologyInspectionResult
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class BRepInspector(BRepMeshesInspector, BRepTopologyInspector):
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.BRep) -> None:
        ...
    def inspect_brep(self) -> BRepInspectionResult:
        ...
class BRepLinesTopologyInspectionResult:
    line_edges_with_wrong_component_edges_around: InspectionIssuesMapIndex
    lines_not_linked_to_a_unique_vertex: InspectionIssuesMapIndex
    lines_not_meshed: InspectionIssuesUUID
    unique_vertices_linked_to_a_line_with_invalid_embeddings: InspectionIssuesIndex
    unique_vertices_linked_to_a_single_and_invalid_line: InspectionIssuesIndex
    unique_vertices_linked_to_line_with_wrong_relationship_to_surface: InspectionIssuesIndex
    unique_vertices_linked_to_several_lines_but_not_linked_to_a_corner: InspectionIssuesIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class BRepMeshesAdjacencyInspectionResult:
    blocks_facets_with_wrong_adjacencies: InspectionIssuesMapPolyhedronFacet
    surfaces_edges_with_wrong_adjacencies: InspectionIssuesMapPolygonEdge
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class BRepMeshesDegenerationInspectionResult:
    degenerated_edges: InspectionIssuesMapIndex
    degenerated_polygons: InspectionIssuesMapIndex
    degenerated_polyhedra: InspectionIssuesMapIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class BRepMeshesInspectionResult:
    meshes_adjacencies: BRepMeshesAdjacencyInspectionResult
    meshes_colocation: MeshesColocationInspectionResult
    meshes_degenerations: BRepMeshesDegenerationInspectionResult
    meshes_intersections: ElementsIntersectionsInspectionResult
    meshes_non_manifolds: BRepMeshesManifoldInspectionResult
    unique_vertices_colocation: UniqueVerticesInspectionResult
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class BRepMeshesInspector(BRepUniqueVerticesColocation, BRepComponentMeshesAdjacency, BRepComponentMeshesColocation, BRepComponentMeshesDegeneration, BRepComponentMeshesManifold, BRepMeshesIntersections):
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.BRep) -> None:
        ...
    def inspect_brep_meshes(self) -> BRepMeshesInspectionResult:
        ...
class BRepMeshesIntersections:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.BRep) -> None:
        ...
    def inspect_intersections(self) -> ElementsIntersectionsInspectionResult:
        ...
    def model_has_intersecting_surfaces(self) -> bool:
        ...
class BRepMeshesManifoldInspectionResult:
    brep_non_manifold_edges: InspectionIssuesBRepNonManifoldEdge
    meshes_non_manifold_edges: InspectionIssuesMapArrayIndex2
    meshes_non_manifold_facets: InspectionIssuesMapPolyhedronFacetVertices
    meshes_non_manifold_vertices: InspectionIssuesMapIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class BRepNonManifoldEdge:
    component_ids: list[opengeode.lib64.opengeode_py_basic.uuid]
    edge: typing.Annotated[list[int], pybind11_stubgen.typing_ext.FixedSize(2)]
    def __init__(self) -> None:
        ...
class BRepSurfacesTopologyInspectionResult:
    surface_polygons_with_wrong_component_facets_around: InspectionIssuesMapIndex
    surfaces_not_linked_to_a_unique_vertex: InspectionIssuesMapIndex
    surfaces_not_meshed: InspectionIssuesUUID
    unique_vertices_linked_to_a_line_but_is_not_on_a_surface_border: InspectionIssuesIndex
    unique_vertices_linked_to_a_surface_with_invalid_embbedings: InspectionIssuesIndex
    unique_vertices_linked_to_several_and_invalid_surfaces: InspectionIssuesIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class BRepTopologyInspectionResult:
    blocks: BRepBlocksTopologyInspectionResult
    corners: BRepCornersTopologyInspectionResult
    lines: BRepLinesTopologyInspectionResult
    surfaces: BRepSurfacesTopologyInspectionResult
    unique_vertices_not_linked_to_any_component: InspectionIssuesIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class BRepTopologyInspector:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.BRep) -> None:
        ...
    def brep_topology_is_valid(self) -> bool:
        ...
    def brep_unique_vertices_are_bijectively_linked_to_an_existing_component_vertex(self) -> bool:
        ...
    def inspect_brep_topology(self) -> BRepTopologyInspectionResult:
        ...
class BRepUniqueVerticesColocation:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.BRep) -> None:
        ...
    def inspect_unique_vertices(self) -> UniqueVerticesInspectionResult:
        ...
    def model_has_colocated_unique_vertices(self) -> bool:
        ...
    def model_has_unique_vertices_linked_to_different_points(self) -> bool:
        ...
class EdgedCurveColocation2D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.EdgedCurve2D) -> None:
        ...
    def colocated_points_groups(self) -> InspectionIssuesVectorIndex:
        ...
    def mesh_has_colocated_points(self) -> bool:
        ...
class EdgedCurveColocation3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.EdgedCurve3D) -> None:
        ...
    def colocated_points_groups(self) -> InspectionIssuesVectorIndex:
        ...
    def mesh_has_colocated_points(self) -> bool:
        ...
class EdgedCurveDegeneration2D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.EdgedCurve2D) -> None:
        ...
    def degenerated_edges(self) -> InspectionIssuesIndex:
        ...
    def is_mesh_degenerated(self) -> bool:
        ...
    def small_edges(self, arg0: float) -> InspectionIssuesIndex:
        ...
class EdgedCurveDegeneration3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.EdgedCurve3D) -> None:
        ...
    def degenerated_edges(self) -> InspectionIssuesIndex:
        ...
    def is_mesh_degenerated(self) -> bool:
        ...
    def small_edges(self, arg0: float) -> InspectionIssuesIndex:
        ...
class EdgedCurveInspectionResult:
    colocated_points_groups: InspectionIssuesVectorIndex
    degenerated_edges: InspectionIssuesIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class EdgedCurveInspector2D(EdgedCurveColocation2D, EdgedCurveDegeneration2D):
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.EdgedCurve2D) -> None:
        ...
    def inspect_edged_curve(self) -> EdgedCurveInspectionResult:
        ...
class EdgedCurveInspector3D(EdgedCurveColocation3D, EdgedCurveDegeneration3D):
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.EdgedCurve3D) -> None:
        ...
    def inspect_edged_curve(self) -> EdgedCurveInspectionResult:
        ...
class ElementsIntersectionsInspectionResult:
    elements_intersections: InspectionIssuesPairComponentMeshElement
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesArrayIndex2:
    def description(self) -> str:
        ...
    def issues(self) -> list[typing.Annotated[list[int], pybind11_stubgen.typing_ext.FixedSize(2)]]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesBRepNonManifoldEdge:
    def description(self) -> str:
        ...
    def issues(self) -> list[BRepNonManifoldEdge]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesIndex:
    def description(self) -> str:
        ...
    def issues(self) -> list[int]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesMapArrayIndex2:
    def description(self) -> str:
        ...
    def issues_map(self) -> dict[opengeode.lib64.opengeode_py_basic.uuid, InspectionIssuesArrayIndex2]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesMapBRepNonManifoldEdge:
    def description(self) -> str:
        ...
    def issues_map(self) -> dict[opengeode.lib64.opengeode_py_basic.uuid, InspectionIssuesBRepNonManifoldEdge]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesMapIndex:
    def description(self) -> str:
        ...
    def issues_map(self) -> dict[opengeode.lib64.opengeode_py_basic.uuid, InspectionIssuesIndex]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesMapPairComponentMeshElement:
    def description(self) -> str:
        ...
    def issues_map(self) -> dict[opengeode.lib64.opengeode_py_basic.uuid, InspectionIssuesPairComponentMeshElement]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesMapPairIndex:
    def description(self) -> str:
        ...
    def issues_map(self) -> dict[opengeode.lib64.opengeode_py_basic.uuid, InspectionIssuesPairIndex]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesMapPolygonEdge:
    def description(self) -> str:
        ...
    def issues_map(self) -> dict[opengeode.lib64.opengeode_py_basic.uuid, InspectionIssuesPolygonEdge]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesMapPolyhedronFacet:
    def description(self) -> str:
        ...
    def issues_map(self) -> dict[opengeode.lib64.opengeode_py_basic.uuid, InspectionIssuesPolyhedronFacet]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesMapPolyhedronFacetVertices:
    def description(self) -> str:
        ...
    def issues_map(self) -> dict[opengeode.lib64.opengeode_py_basic.uuid, InspectionIssuesPolyhedronFacetVertices]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesMapUUID:
    def description(self) -> str:
        ...
    def issues_map(self) -> dict[opengeode.lib64.opengeode_py_basic.uuid, InspectionIssuesUUID]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesMapVectorIndex:
    def description(self) -> str:
        ...
    def issues_map(self) -> dict[opengeode.lib64.opengeode_py_basic.uuid, InspectionIssuesVectorIndex]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesPairComponentMeshElement:
    def description(self) -> str:
        ...
    def issues(self) -> list[tuple[opengeode.lib64.opengeode_py_model.ComponentMeshElement, opengeode.lib64.opengeode_py_model.ComponentMeshElement]]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesPairIndex:
    def description(self) -> str:
        ...
    def issues(self) -> list[tuple[int, int]]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesPolygonEdge:
    def description(self) -> str:
        ...
    def issues(self) -> list[opengeode.lib64.opengeode_py_mesh.PolygonEdge]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesPolyhedronFacet:
    def description(self) -> str:
        ...
    def issues(self) -> list[opengeode.lib64.opengeode_py_mesh.PolyhedronFacet]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesPolyhedronFacetVertices:
    def description(self) -> str:
        ...
    def issues(self) -> list[list[int]]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesUUID:
    def description(self) -> str:
        ...
    def issues(self) -> list[opengeode.lib64.opengeode_py_basic.uuid]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectionIssuesVectorIndex:
    def description(self) -> str:
        ...
    def issues(self) -> list[list[int]]:
        ...
    def nb_issues(self) -> int:
        ...
    def set_description(self, arg0: str) -> None:
        ...
    def string(self) -> str:
        ...
class InspectorInspectorLibrary:
    @staticmethod
    def initialize() -> None:
        ...
class MeshesColocationInspectionResult:
    colocated_points_groups: InspectionIssuesMapVectorIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class PointSetColocation2D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.PointSet2D) -> None:
        ...
    def colocated_points_groups(self) -> InspectionIssuesVectorIndex:
        ...
    def mesh_has_colocated_points(self) -> bool:
        ...
class PointSetColocation3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.PointSet3D) -> None:
        ...
    def colocated_points_groups(self) -> InspectionIssuesVectorIndex:
        ...
    def mesh_has_colocated_points(self) -> bool:
        ...
class PointSetInspectionResult:
    colocated_points_groups: InspectionIssuesVectorIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class PointSetInspector2D(PointSetColocation2D):
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.PointSet2D) -> None:
        ...
    def inspect_point_set(self) -> PointSetInspectionResult:
        ...
class PointSetInspector3D(PointSetColocation3D):
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.PointSet3D) -> None:
        ...
    def inspect_point_set(self) -> PointSetInspectionResult:
        ...
class SectionComponentMeshesAdjacency:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.Section) -> None:
        ...
    def inspect_section_meshes_adjacencies(self) -> SectionMeshesAdjacencyInspectionResult:
        ...
class SectionComponentMeshesColocation:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.Section) -> None:
        ...
    def inspect_meshes_point_colocations(self) -> MeshesColocationInspectionResult:
        ...
class SectionComponentMeshesDegeneration:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.Section) -> None:
        ...
    def inspect_elements_degeneration(self) -> SectionMeshesDegenerationInspectionResult:
        ...
class SectionComponentMeshesManifold:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.Section) -> None:
        ...
    def inspect_section_manifold(self) -> SectionMeshesManifoldInspectionResult:
        ...
class SectionCornersTopologyInspectionResult:
    corners_not_linked_to_a_unique_vertex: InspectionIssuesMapIndex
    corners_not_meshed: InspectionIssuesUUID
    unique_vertices_linked_to_multiple_corners: InspectionIssuesIndex
    unique_vertices_linked_to_multiple_internals_corner: InspectionIssuesIndex
    unique_vertices_linked_to_not_boundary_line_corner: InspectionIssuesIndex
    unique_vertices_linked_to_not_internal_nor_boundary_corner: InspectionIssuesIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class SectionInspectionResult:
    meshes: SectionMeshesInspectionResult
    topology: SectionTopologyInspectionResult
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class SectionInspector(SectionMeshesInspector, SectionTopologyInspector):
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.Section) -> None:
        ...
    def inspect_section(self) -> SectionInspectionResult:
        ...
class SectionLinesTopologyInspectionResult:
    lines_not_linked_to_a_unique_vertex: InspectionIssuesMapIndex
    lines_not_meshed: InspectionIssuesUUID
    unique_vertices_linked_to_a_line_with_invalid_embeddings: InspectionIssuesIndex
    unique_vertices_linked_to_a_single_and_invalid_line: InspectionIssuesIndex
    unique_vertices_linked_to_line_with_wrong_relationship_to_surface: InspectionIssuesIndex
    unique_vertices_linked_to_several_lines_but_not_linked_to_a_corner: InspectionIssuesIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class SectionMeshesAdjacencyInspectionResult:
    surfaces_edges_with_wrong_adjacencies: InspectionIssuesMapPolygonEdge
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class SectionMeshesDegenerationInspectionResult:
    degenerated_edges: InspectionIssuesMapIndex
    degenerated_polygons: InspectionIssuesMapIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class SectionMeshesInspectionResult:
    meshes_adjacencies: SectionMeshesAdjacencyInspectionResult
    meshes_colocation: MeshesColocationInspectionResult
    meshes_degenerations: SectionMeshesDegenerationInspectionResult
    meshes_intersections: ElementsIntersectionsInspectionResult
    meshes_non_manifolds: SectionMeshesManifoldInspectionResult
    unique_vertices_colocation: UniqueVerticesInspectionResult
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class SectionMeshesInspector(SectionUniqueVerticesColocation, SectionComponentMeshesAdjacency, SectionComponentMeshesColocation, SectionComponentMeshesDegeneration, SectionComponentMeshesManifold, SectionMeshesIntersections):
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.Section) -> None:
        ...
    def inspect_section_meshes(self) -> SectionMeshesInspectionResult:
        ...
class SectionMeshesIntersections:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.Section) -> None:
        ...
    def inspect_intersections(self) -> ElementsIntersectionsInspectionResult:
        ...
    def model_has_intersecting_surfaces(self) -> bool:
        ...
class SectionMeshesManifoldInspectionResult:
    meshes_non_manifold_edges: InspectionIssuesMapArrayIndex2
    meshes_non_manifold_vertices: InspectionIssuesMapIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class SectionSurfacesTopologyInspectionResult:
    surfaces_not_linked_to_a_unique_vertex: InspectionIssuesMapIndex
    surfaces_not_meshed: InspectionIssuesUUID
    unique_vertices_linked_to_a_line_but_is_not_on_a_surface_border: InspectionIssuesIndex
    unique_vertices_linked_to_a_surface_with_invalid_embbedings: InspectionIssuesIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class SectionTopologyInspectionResult:
    corners: SectionCornersTopologyInspectionResult
    lines: SectionLinesTopologyInspectionResult
    surfaces: SectionSurfacesTopologyInspectionResult
    unique_vertices_not_linked_to_any_component: InspectionIssuesIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class SectionTopologyInspector:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.Section) -> None:
        ...
    def inspect_section_topology(self) -> SectionTopologyInspectionResult:
        ...
    def section_topology_is_valid(self) -> bool:
        ...
    def section_unique_vertices_are_bijectively_linked_to_an_existing_component_vertex(self) -> bool:
        ...
class SectionUniqueVerticesColocation:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_model.Section) -> None:
        ...
    def inspect_unique_vertices(self) -> UniqueVerticesInspectionResult:
        ...
    def model_has_colocated_unique_vertices(self) -> bool:
        ...
    def model_has_unique_vertices_linked_to_different_points(self) -> bool:
        ...
class SolidInspectionResult:
    colocated_points_groups: InspectionIssuesVectorIndex
    degenerated_edges: InspectionIssuesIndex
    degenerated_polyhedra: InspectionIssuesIndex
    non_manifold_edges: InspectionIssuesArrayIndex2
    non_manifold_facets: InspectionIssuesPolyhedronFacetVertices
    non_manifold_vertices: InspectionIssuesIndex
    polyhedron_facets_with_wrong_adjacency: InspectionIssuesPolyhedronFacet
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class SolidMeshAdjacency3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SolidMesh3D) -> None:
        ...
    def mesh_has_wrong_adjacencies(self) -> bool:
        ...
    def polyhedron_facets_with_wrong_adjacency(self) -> InspectionIssuesPolyhedronFacet:
        ...
class SolidMeshColocation3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SolidMesh3D) -> None:
        ...
    def colocated_points_groups(self) -> InspectionIssuesVectorIndex:
        ...
    def mesh_has_colocated_points(self) -> bool:
        ...
class SolidMeshDegeneration3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SolidMesh3D) -> None:
        ...
    def degenerated_edges(self) -> InspectionIssuesIndex:
        ...
    def degenerated_polyhedra(self) -> InspectionIssuesIndex:
        ...
    def is_mesh_degenerated(self) -> bool:
        ...
    def small_edges(self, arg0: float) -> InspectionIssuesIndex:
        ...
    def small_height_polyhedra(self, arg0: float) -> InspectionIssuesIndex:
        ...
class SolidMeshEdgeManifold3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SolidMesh3D) -> None:
        ...
    def mesh_edges_are_manifold(self) -> bool:
        ...
    def non_manifold_edges(self) -> InspectionIssuesArrayIndex2:
        ...
class SolidMeshFacetManifold3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SolidMesh3D) -> None:
        ...
    def mesh_facets_are_manifold(self) -> bool:
        ...
    def non_manifold_facets(self) -> InspectionIssuesPolyhedronFacetVertices:
        ...
class SolidMeshInspector3D(SolidMeshAdjacency3D, SolidMeshColocation3D, SolidMeshDegeneration3D, SolidMeshVertexManifold3D, SolidMeshEdgeManifold3D, SolidMeshFacetManifold3D):
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SolidMesh3D) -> None:
        ...
    def inspect_solid(self) -> SolidInspectionResult:
        ...
class SolidMeshVertexManifold3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SolidMesh3D) -> None:
        ...
    def mesh_vertices_are_manifold(self) -> bool:
        ...
    def non_manifold_vertices(self) -> InspectionIssuesIndex:
        ...
class SurfaceCurveIntersections2D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.TriangulatedSurface2D, arg1: opengeode.lib64.opengeode_py_mesh.EdgedCurve2D) -> None:
        ...
    def intersecting_elements(self) -> InspectionIssuesPairIndex:
        ...
    def meshes_have_intersections(self) -> bool:
        ...
class SurfaceCurveIntersections3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.TriangulatedSurface3D, arg1: opengeode.lib64.opengeode_py_mesh.EdgedCurve3D) -> None:
        ...
    def intersecting_elements(self) -> InspectionIssuesPairIndex:
        ...
    def meshes_have_intersections(self) -> bool:
        ...
class SurfaceInspectionResult:
    colocated_points_groups: InspectionIssuesVectorIndex
    degenerated_edges: InspectionIssuesIndex
    degenerated_polygons: InspectionIssuesIndex
    intersecting_elements: InspectionIssuesPairIndex
    non_manifold_edges: InspectionIssuesArrayIndex2
    non_manifold_vertices: InspectionIssuesIndex
    polygon_edges_with_wrong_adjacency: InspectionIssuesPolygonEdge
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
class SurfaceMeshAdjacency2D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh2D) -> None:
        ...
    def mesh_has_wrong_adjacencies(self) -> bool:
        ...
    def polygon_edges_with_wrong_adjacency(self) -> InspectionIssuesPolygonEdge:
        ...
class SurfaceMeshAdjacency3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh3D) -> None:
        ...
    def mesh_has_wrong_adjacencies(self) -> bool:
        ...
    def polygon_edges_with_wrong_adjacency(self) -> InspectionIssuesPolygonEdge:
        ...
class SurfaceMeshColocation2D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh2D) -> None:
        ...
    def colocated_points_groups(self) -> InspectionIssuesVectorIndex:
        ...
    def mesh_has_colocated_points(self) -> bool:
        ...
class SurfaceMeshColocation3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh3D) -> None:
        ...
    def colocated_points_groups(self) -> InspectionIssuesVectorIndex:
        ...
    def mesh_has_colocated_points(self) -> bool:
        ...
class SurfaceMeshDegeneration2D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh2D) -> None:
        ...
    def degenerated_edges(self) -> InspectionIssuesIndex:
        ...
    def degenerated_polygons(self) -> InspectionIssuesIndex:
        ...
    def is_mesh_degenerated(self) -> bool:
        ...
    def small_edges(self, arg0: float) -> InspectionIssuesIndex:
        ...
    def small_height_polygons(self, arg0: float) -> InspectionIssuesIndex:
        ...
class SurfaceMeshDegeneration3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh3D) -> None:
        ...
    def degenerated_edges(self) -> InspectionIssuesIndex:
        ...
    def degenerated_polygons(self) -> InspectionIssuesIndex:
        ...
    def is_mesh_degenerated(self) -> bool:
        ...
    def small_edges(self, arg0: float) -> InspectionIssuesIndex:
        ...
    def small_height_polygons(self, arg0: float) -> InspectionIssuesIndex:
        ...
class SurfaceMeshEdgeManifold2D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh2D) -> None:
        ...
    def mesh_edges_are_manifold(self) -> bool:
        ...
    def non_manifold_edges(self) -> InspectionIssuesArrayIndex2:
        ...
class SurfaceMeshEdgeManifold3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh3D) -> None:
        ...
    def mesh_edges_are_manifold(self) -> bool:
        ...
    def non_manifold_edges(self) -> InspectionIssuesArrayIndex2:
        ...
class SurfaceMeshInspector2D(SurfaceMeshAdjacency2D, SurfaceMeshColocation2D, SurfaceMeshDegeneration2D, SurfaceMeshEdgeManifold2D, SurfaceMeshVertexManifold2D, SurfaceMeshIntersections2D):
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh2D) -> None:
        ...
    def inspect_surface(self) -> SurfaceInspectionResult:
        ...
class SurfaceMeshInspector3D(SurfaceMeshAdjacency3D, SurfaceMeshColocation3D, SurfaceMeshDegeneration3D, SurfaceMeshEdgeManifold3D, SurfaceMeshVertexManifold3D, SurfaceMeshIntersections3D):
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh3D) -> None:
        ...
    def inspect_surface(self) -> SurfaceInspectionResult:
        ...
class SurfaceMeshIntersections2D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh2D) -> None:
        ...
    def intersecting_elements(self) -> InspectionIssuesPairIndex:
        ...
    def mesh_has_self_intersections(self) -> bool:
        ...
class SurfaceMeshIntersections3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh3D) -> None:
        ...
    def intersecting_elements(self) -> InspectionIssuesPairIndex:
        ...
    def mesh_has_self_intersections(self) -> bool:
        ...
class SurfaceMeshVertexManifold2D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh2D) -> None:
        ...
    def mesh_vertices_are_manifold(self) -> bool:
        ...
    def non_manifold_vertices(self) -> InspectionIssuesIndex:
        ...
class SurfaceMeshVertexManifold3D:
    def __init__(self, arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh3D) -> None:
        ...
    def mesh_vertices_are_manifold(self) -> bool:
        ...
    def non_manifold_vertices(self) -> InspectionIssuesIndex:
        ...
class UniqueVerticesInspectionResult:
    colocated_unique_vertices_groups: InspectionIssuesVectorIndex
    unique_vertices_linked_to_different_points: InspectionIssuesIndex
    def __init__(self) -> None:
        ...
    def inspection_type(self) -> str:
        ...
    def string(self) -> str:
        ...
def inspect_brep(arg0: opengeode.lib64.opengeode_py_model.BRep) -> BRepInspectionResult:
    ...
def inspect_edged_curve2D(arg0: opengeode.lib64.opengeode_py_mesh.EdgedCurve2D) -> EdgedCurveInspectionResult:
    ...
def inspect_edged_curve3D(arg0: opengeode.lib64.opengeode_py_mesh.EdgedCurve3D) -> EdgedCurveInspectionResult:
    ...
def inspect_point_set2D(arg0: opengeode.lib64.opengeode_py_mesh.PointSet2D) -> PointSetInspectionResult:
    ...
def inspect_point_set3D(arg0: opengeode.lib64.opengeode_py_mesh.PointSet3D) -> PointSetInspectionResult:
    ...
def inspect_section(arg0: opengeode.lib64.opengeode_py_model.Section) -> SectionInspectionResult:
    ...
def inspect_solid3D(arg0: opengeode.lib64.opengeode_py_mesh.SolidMesh3D) -> SolidInspectionResult:
    ...
def inspect_surface2D(arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh2D) -> SurfaceInspectionResult:
    ...
def inspect_surface3D(arg0: opengeode.lib64.opengeode_py_mesh.SurfaceMesh3D) -> SurfaceInspectionResult:
    ...
