# Extension to language mapping for markdown code block formatting

EXT_TO_LANGUAGE = {
    'py': 'python',
    'js': 'javascript',
    'ts': 'typescript',
    'java': 'java',
    'c': 'c',
    'cpp': 'cpp',
    'h': 'cpp',
    'cs': 'csharp',
    'rb': 'ruby',
    'php': 'php',
    'html': 'html',
    'htm': 'html',
    'css': 'css',
    'scss': 'scss',
    'sass': 'sass',
    'go': 'go',
    'rs': 'rust',
    'swift': 'swift',
    'sh': 'bash',
    'bash': 'bash',
    'zsh': 'zsh',
    'lua': 'lua',
    'r': 'r',
    'sql': 'sql',
    'json': 'json',
    'yaml': 'yaml',
    'yml': 'yaml',
    'toml': 'toml',
    'ini': 'ini',
    'md': 'markdown',
    'xml': 'xml',
    'graphql': 'graphql',
    'jl': 'julia',
    'pl': 'perl',
    'pm': 'perl',
    'asm': 'assembly',
    'ps1': 'powershell',
    'bat': 'batch',
    'dockerfile': 'docker'
}