from .base import CommandBase as CommandBase
from .error_codes import ErrorCode as ErrorCode
from .registry import get_command as get_command, list_commands as list_commands, register_alias as register_alias, register_command as register_command, resolve_command_name as resolve_command_name
from collections.abc import Callable
from typing import Any

__all__ = ['Command', 'CommandBase', 'ErrorCode', 'get_command', 'list_commands', 'register_alias', 'register_command', 'resolve_command_name', 'validate_command_args']

class Command(CommandBase):
    def __init__(self, **dependencies: Any) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def help(self) -> str: ...
    def execute(self, *args: Any, **kwargs: Any) -> None: ...
    def add_arguments(self, parser) -> None: ...

def validate_command_args(**validators: Callable[[Any], bool]) -> Callable: ...
