from .base import CommandBase as CommandBase
from .dependency_resolver import resolve_dependencies as resolve_dependencies
from collections.abc import Callable as Callable

def register_command(name: str) -> Callable[[type[CommandBase]], type[CommandBase]]: ...
def register_alias(alias: str, command_name: str) -> None: ...
def resolve_command_name(name: str) -> str: ...
def list_commands() -> dict[str, type[CommandBase]]: ...
def get_command(name: str) -> CommandBase: ...
