class VersionComparator:
    @staticmethod
    def is_version_increment_valid(old_version: str, new_version: str) -> bool: ...
    @staticmethod
    def get_greater_version(version1: str, version2: str) -> str: ...
    @staticmethod
    def is_version_greater(version1: str, version2: str) -> bool: ...
    @staticmethod
    def increment_version_from_base(base_version: str) -> str: ...
