from ...commands import Command as Command, register_command as register_command, validate_command_args as validate_command_args

class ConfigCommand(Command):
    @property
    def name(self) -> str: ...
    @property
    def help(self) -> str: ...
    @classmethod
    def add_arguments(cls, parser) -> None: ...
    def execute(self, config_action: str | None = None, key: str | None = None, value: str | None = None, **kwargs) -> None: ...
