# Helper function to find alloy root
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + "/src")

from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .integrated_nodes import NODE_CLASS_MAPPINGS as INTEGRATED_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as INTEGRATED_DISPLAY_MAPPINGS
from .advanced_nodes import NODE_CLASS_MAPPINGS as ADVANCED_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ADVANCED_DISPLAY_MAPPINGS
from .converter_nodes import NODE_CLASS_MAPPINGS as CONVERTER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONVERTER_DISPLAY_MAPPINGS
from .lora_nodes import NODE_CLASS_MAPPINGS as LORA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LORA_DISPLAY_MAPPINGS

# Merge all mappings
NODE_CLASS_MAPPINGS.update(INTEGRATED_MAPPINGS)
NODE_CLASS_MAPPINGS.update(ADVANCED_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CONVERTER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LORA_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(INTEGRATED_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(ADVANCED_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(CONVERTER_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LORA_DISPLAY_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
