from enum import Enum


class KlassifiseringsMetode(str, Enum):
    BEREGNETFRATERRENGOVERFLATEN = "BEREGNETFRATERRENGOVERFLATEN"
    OBSERVASJON = "OBSERVASJON"
    TOLKETBERGBORING = "TOLKETBERGBORING"
    TOLKETBERGBORING3METER = "TOLKETBERGBORING3METER"
    TOLKETFELTSONDERING = "TOLKETFELTSONDERING"
    TOLKETLAB = "TOLKETLAB"
    TOLKETPRØVETAK = "TOLKETPRØVETAK"
    TOLKETTEGNING = "TOLKETTEGNING"
    USPESIFISERT = "USPESIFISERT"

    def __str__(self) -> str:
        return str(self.value)
