from enum import Enum


class RepresentasjonKvalitet(str, Enum):
    POLYGON_FOR_GU_MED_KUN_ET_ENKELT_BOREHULL_100X100M = "POLYGON_FOR_GU_MED_KUN_ET_ENKELT_BOREHULL_100X100M_"
    POLYGON_HENTET_FRA_BOREHULL_I_GU_MIN_OG_MAKS_KOORDINATER = (
        "POLYGON_HENTET_FRA_BOREHULL_I_GU_MIN_OG_MAKS_KOORDINATER_"
    )
    POLYGON_SOM_AVGRENSER_BOREHULL_I_GU = "POLYGON_SOM_AVGRENSER_BOREHULL_I_GU_"
    POLYGON_SOM_REPRESENTERER_PROSJEKTOMRÅDE = "POLYGON_SOM_REPRESENTERER_PROSJEKTOMRÅDE_"
    REPRESENTASJONSPUNKT_FOR_KOMMUNALT_REGIONALT_GU_OMRÅDE = "REPRESENTASJONSPUNKT_FOR_KOMMUNALT_REGIONALT_GU_OMRÅDE_"
    REPRESENTASJONSPUNKT_FOR_MINDRE_GU_OMRÅDE_OPPTIL_CA_10_MÅL = (
        "REPRESENTASJONSPUNKT_FOR_MINDRE_GU_OMRÅDE_OPPTIL_CA_10_MÅL_"
    )
    REPRESENTASJONSPUNKT_FOR_STØRRE_GU_OMRÅDE_OVER_CA_10_MÅL_ELLER_LENGRE_ENN_CA_0_5_KM = (
        "REPRESENTASJONSPUNKT_FOR_STØRRE_GU_OMRÅDE_OVER_CA_10_MÅL_ELLER_LENGRE_ENN_CA_0_5_KM"
    )
    UKJENT = "UKJENT"

    def __str__(self) -> str:
        return str(self.value)
