"""
ActionEngine ChunkStore interface.
"""
from __future__ import annotations
import actionengine._C.data
import typing
__all__: list[str] = ['ChunkStore', 'ChunkStoreReaderOptions', 'ChunkStoreVirtualBase', 'LocalChunkStore']
class ChunkStore(ChunkStoreVirtualBase):
    """
    An ActionEngine ChunkStore interface.
    """
    def __contains__(self, arg0: typing.SupportsInt) -> bool:
        ...
    def __len__(self) -> int:
        ...
    def contains(self, arg0: typing.SupportsInt) -> bool:
        ...
    def get(self, seq: typing.SupportsInt, timeout: typing.SupportsFloat = -1) -> actionengine._C.data.Chunk:
        ...
    def get_by_arrival_order(self, seq: typing.SupportsInt, timeout: typing.SupportsFloat = -1) -> actionengine._C.data.Chunk:
        ...
    def get_final_seq(self) -> int:
        ...
    def get_id(self) -> str:
        ...
    def get_seq_for_arrival_offset(self, arrival_offset: typing.SupportsInt) -> int:
        ...
    def no_further_puts(self, arg0: None) -> None:
        ...
    def pop(self, seq: typing.SupportsInt) -> actionengine._C.data.Chunk | None:
        ...
    def put(self, seq: typing.SupportsInt, chunk: actionengine._C.data.Chunk, final: bool = False) -> None:
        ...
    def set_id(self, arg0: str) -> None:
        ...
    def size(self) -> int:
        ...
class ChunkStoreReaderOptions:
    """
    Options for reading from a ChunkStore.
    """
    ordered: bool
    remove_chunks: bool
    timeout: ...
    def __init__(self) -> None:
        ...
    @property
    def n_chunks_to_buffer(self) -> int:
        ...
    @n_chunks_to_buffer.setter
    def n_chunks_to_buffer(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def start_seq_or_offset(self) -> int:
        ...
    @start_seq_or_offset.setter
    def start_seq_or_offset(self, arg0: typing.SupportsInt) -> None:
        ...
class ChunkStoreVirtualBase:
    """
    An ActionEngine ChunkStore interface.
    """
    def __contains__(self, arg0: typing.SupportsInt) -> bool:
        ...
    def __len__(self) -> int:
        ...
    def contains(self, arg0: typing.SupportsInt) -> bool:
        ...
    def get(self, seq: typing.SupportsInt, timeout: typing.SupportsFloat = -1) -> actionengine._C.data.Chunk:
        ...
    def get_by_arrival_order(self, seq: typing.SupportsInt, timeout: typing.SupportsFloat = -1) -> actionengine._C.data.Chunk:
        ...
    def get_final_seq(self) -> int:
        ...
    def get_id(self) -> str:
        ...
    def get_seq_for_arrival_offset(self, arrival_offset: typing.SupportsInt) -> int:
        ...
    def no_further_puts(self, arg0: None) -> None:
        ...
    def pop(self, seq: typing.SupportsInt) -> actionengine._C.data.Chunk | None:
        ...
    def put(self, seq: typing.SupportsInt, chunk: actionengine._C.data.Chunk, final: bool = False) -> None:
        ...
    def set_id(self, arg0: str) -> None:
        ...
    def size(self) -> int:
        ...
class LocalChunkStore(ChunkStoreVirtualBase):
    """
    ActionEngine LocalChunkStore.
    """
    def __contains__(self, arg0: typing.SupportsInt) -> bool:
        ...
    def __init__(self) -> None:
        ...
    def __len__(self) -> int:
        ...
    def contains(self, arg0: typing.SupportsInt) -> bool:
        ...
    def get(self, seq: typing.SupportsInt, timeout: typing.SupportsFloat = -1) -> actionengine._C.data.Chunk:
        ...
    def get_by_arrival_order(self, seq: typing.SupportsInt, timeout: typing.SupportsFloat = -1) -> actionengine._C.data.Chunk:
        ...
    def get_final_seq(self) -> int:
        ...
    def get_id(self) -> str:
        ...
    def get_seq_for_arrival_offset(self, arrival_offset: typing.SupportsInt) -> int:
        ...
    def no_further_puts(self, arg0: None) -> None:
        ...
    def pop(self, seq: typing.SupportsInt) -> actionengine._C.data.Chunk | None:
        ...
    def put(self, seq: typing.SupportsInt, chunk: actionengine._C.data.Chunk, final: bool = False) -> None:
        ...
    def set_id(self, arg0: str) -> None:
        ...
    def size(self) -> int:
        ...
