from setuptools import setup, find_packages

setup(
    name='llm_utility_pack',
    version='4.3',
    author='Carlo Moro',
    author_email='cnmoro@gmail.com',
    description="Mega pack of utilities for LLMs, pdfs and other resources.",
    packages=find_packages(),
    package_data={
        "utility_pack": ["resources/*"]
    },
    include_package_data=True,
    install_requires=[
        "cloudpickle",
        "pytz",
        "ollama",
        "requests",
        "aiohttp",
        "asyncio",
        "lmdb",
        "markdown",
        "lingua-language-detector",
        "deskew",
        "semantic-compressor>=2.43",
        "PyMuPDF",
        "pytesseract",
        "opencv-python-headless",
        "scikit-image",
        "Pillow",
        "pandas",
        "scikit-learn",
        "faiss-cpu",
        "numpy",
        "thefuzz[speedup]",
        "strive-ranker>=2.42",
        "shortuuid",
        "prophet",
        "prince",
        "scipy",
        "onnxruntime",
        "onnxruntime_extensions",
        "tokenizers",
        "tqdm",
        "chonkie",
        "pymongo",
        "openai",
        "tiktoken",
        "xxhash",
        "fastapi",
        "APScheduler",
        "uvicorn",
        "pydantic",
        "sqlalchemy",
        "orjson",
        "duckdb",
        "lightning-disk-kv>=1.1.1"
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.7'
)