from _typeshed import Incomplete
from pathlib import Path
from typing import Any

class ConfigManager:
    config_file: Incomplete
    config: dict[str, Any]
    def __init__(self, config_file: str = 'config.json') -> None: ...
    def load_config(self) -> None: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def save_config(self) -> None: ...
    def get_vendor_config_path(self, config_file: str) -> Path: ...
    def load_vendor_config(self, config_file: str) -> dict[str, Any]: ...
    def load_template(self, template_file: str) -> str: ...
