from .deploy_config import DEPLOY_WHITELIST as DEPLOY_WHITELIST

def find_py_directories() -> list[str]: ...
def is_ignored_directory(dir_name: str) -> bool: ...
def is_excluded_file(file_name: str) -> bool: ...
def is_in_whitelist(path: str, source_dir: str) -> bool: ...
