from .file_operations import get_file_operations as get_file_operations
from pathlib import Path

def find_project_root(start_path: Path | None = None) -> Path: ...
def clear_project_root_cache() -> None: ...
