# coding: utf-8

"""
    Forward Compute API

    Forward Compute API for managing machines, contracts, and compute resources

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fwd_sdk.models.chat_create_completion_post_request_messages_inner_tool_calls_inner_function import ChatCreateCompletionPostRequestMessagesInnerToolCallsInnerFunction

class TestChatCreateCompletionPostRequestMessagesInnerToolCallsInnerFunction(unittest.TestCase):
    """ChatCreateCompletionPostRequestMessagesInnerToolCallsInnerFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatCreateCompletionPostRequestMessagesInnerToolCallsInnerFunction:
        """Test ChatCreateCompletionPostRequestMessagesInnerToolCallsInnerFunction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatCreateCompletionPostRequestMessagesInnerToolCallsInnerFunction`
        """
        model = ChatCreateCompletionPostRequestMessagesInnerToolCallsInnerFunction()
        if include_optional:
            return ChatCreateCompletionPostRequestMessagesInnerToolCallsInnerFunction(
                arguments = '',
                name = ''
            )
        else:
            return ChatCreateCompletionPostRequestMessagesInnerToolCallsInnerFunction(
                arguments = '',
                name = '',
        )
        """

    def testChatCreateCompletionPostRequestMessagesInnerToolCallsInnerFunction(self):
        """Test ChatCreateCompletionPostRequestMessagesInnerToolCallsInnerFunction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
