from typing import Any

def read_json(path: str) -> dict[str, Any]: ...
def coverage_totals(data: dict[str, Any]) -> tuple[float | None, float | None, int, int, int]: ...
def file_entries(data: dict[str, Any], project_root: str) -> list[tuple[str, float | None, float | None]]: ...
