from typing import Optional, Final, Callable, NoReturn, Any
from collections import deque

BREAK: Final = object()

class FrameCounter:
    timestamps: deque
    def __init__(self, average: int = 50) -> None: ...
    def stamp(self) -> float: ...
    def __call__(self) -> float: ...

class FrameLimit:
    start: float
    next_tick: float
    fps: float
    def __init__(self, fps: float) -> None: ...
    @property
    def delta_time(self) -> float: ...
    @property
    def elapsed(self) -> float: ...
    def try_frame(self) -> bool: ...
    def try_assert(self) -> None: ...
    def wait(self, update: bool = True) -> Optional[bool]: 
        """Wait for the next frame. Returns wether the frame has elapsed, if `update` is provisioned as True."""
    def loop(self, func: Callable[[], Any]) -> Optional[NoReturn]: 
        """Iterate over the given function until it returns a `BREAK`."""
    def __call__(self) -> bool: ...

class Clock:
    """The clock is a singleton and shouldn't be relied on in complex applications."""
    limiter: Optional[FrameLimit]
    counter: FrameCounter
    @classmethod
    def target_fps(cls, fps: float) -> None: ...
    @classmethod
    def get_fps(cls) -> float: ...
    @classmethod
    def get_elapsed(cls) -> float: ...
    @classmethod
    def get_delta_time(cls) -> float: ...
    @classmethod
    def try_frame(cls) -> bool: ...
    @classmethod
    def try_assert(cls) -> None: ...
    @classmethod
    def wait(self, update: bool = True) -> Optional[bool]: ...
    @classmethod
    def loop(self, func: Callable[[], Any]) -> Optional[NoReturn]: 
        """Iterate over the given function until it returns a `BREAK`."""