from ...commands import Command
from .lint_command import LintCommandImpl as LintCommandImpl
from pathlib import Path as Path
from typing import Any

class LintCommand(Command):
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def help(self) -> str: ...
    def add_arguments(self, parser: Any) -> None: ...
    def execute(self, *args: Any, **kwargs: Any) -> None: ...
