# filename: gemini.py
# @Time    : 2025/12/12 13:17
# @Author  : JQQ
# @Email   : jqq1716@gmail.com
# @Software: PyCharm
"""
Google Gemini 模型家族配置 / Google Gemini model family configurations
"""

from whosellm.capabilities import ModelCapabilities
from whosellm.models.base import ModelFamily
from whosellm.models.config import ModelFamilyConfig, SpecificModelConfig
from whosellm.provider import Provider

# ==========================================================================
# Gemini 系列 / Gemini Series
# 注意Image系列模型。当前虽然标记为不支持thinking，在实际调试中发现 image 系列也会有思考内容产生，但需要注意接口并不支持配置thinking行为，
# 因此权当不支持处理
# ==========================================================================

GEMINI = ModelFamilyConfig(
    family=ModelFamily.GEMINI,
    provider=Provider.GOOGLE,
    version_default="3.0",
    variant_default="flash",
    variant_priority_default=(1,),  # flash 的默认优先级 / default priority for flash
    patterns=[
        "gemini-{major:d}.{minor:d}-{variant}",
        "gemini-{major:d}.{minor:d}-{variant}-{suffix}",
        "gemini-{major:d}.{minor:d}-{variant}-preview-{date}",
        "gemini-{major:d}.{minor:d}-{variant}-preview",
        "gemini-{major:d}.{minor:d}-{variant}-image",
        "gemini-{major:d}.{minor:d}-{variant}-lite",
        "gemini-{major:d}.{minor:d}-{variant}-live",
        "gemini-{major:d}.{minor:d}-{variant}-native-audio-preview-{date}",
        "gemini-{major:d}.{minor:d}-preview-tts",
        "gemini-{major:d}.{minor:d}-preview-{date}",
        "gemini-{major:d}.{minor:d}-preview",
        "gemini-{major:d}.{minor:d}",
        "gemini-{variant}",
        "gemini-{variant}-preview",
        "gemini-{variant}-latest",
    ],
    capabilities=ModelCapabilities(
        supports_vision=True,
        supports_audio=True,
        supports_video=True,
        supports_pdf=True,
        supports_thinking=True,
        supports_function_calling=True,
        supports_streaming=True,
        supports_structured_outputs=True,
        supports_json_outputs=True,
        supports_web_search=True,
        supports_file_search=True,
        supports_code_interpreter=True,
        max_tokens=65536,
        context_window=1048576,
    ),
    specific_models={
        # Gemini 3 Pro 系列 - 最智能的多模态模型
        "gemini-3-pro": SpecificModelConfig(
            version_default="3.0",
            variant_default="pro",
            variant_priority=(5,),
            capabilities=ModelCapabilities(
                supports_vision=True,
                supports_audio=True,
                supports_video=True,
                supports_pdf=True,
                supports_thinking=True,
                supports_function_calling=True,
                supports_streaming=True,
                supports_structured_outputs=True,
                supports_json_outputs=True,
                supports_web_search=True,
                supports_file_search=True,
                supports_code_interpreter=True,
                max_tokens=65536,
                context_window=1048576,
            ),
            patterns=["gemini-3-pro"],
        ),
        "gemini-3-pro-preview": SpecificModelConfig(
            version_default="3.0",
            variant_default="pro",
            variant_priority=(5,),
            capabilities=ModelCapabilities(
                supports_vision=True,
                supports_audio=True,
                supports_video=True,
                supports_pdf=True,
                supports_thinking=True,
                supports_function_calling=True,
                supports_streaming=True,
                supports_structured_outputs=True,
                supports_json_outputs=True,
                supports_web_search=True,
                supports_file_search=True,
                supports_code_interpreter=True,
                max_tokens=65536,
                context_window=1048576,
            ),
            patterns=["gemini-3-pro-preview"],
        ),
        "gemini-3-pro-image-preview": SpecificModelConfig(
            version_default="3.0",
            variant_default="pro-image",
            variant_priority=(4,),
            capabilities=ModelCapabilities(
                supports_vision=True,
                supports_image_generation=True,
                supports_thinking=False,
                supports_audio=False,
                supports_streaming=True,
                supports_structured_outputs=False,
                supports_json_outputs=True,
                supports_web_search=True,
                max_tokens=32768,
                context_window=65536,
            ),
            patterns=["gemini-3-pro-image-preview"],
        ),
        # Gemini 2.5 Flash 系列 - 性价比最高的模型
        "gemini-2.5-flash": SpecificModelConfig(
            version_default="2.5",
            variant_default="flash",
            variant_priority=(1,),
            capabilities=ModelCapabilities(
                supports_vision=True,
                supports_audio=True,
                supports_video=True,
                supports_pdf=False,
                supports_thinking=True,
                supports_function_calling=True,
                supports_streaming=True,
                supports_structured_outputs=True,
                supports_json_outputs=True,
                supports_web_search=True,
                supports_file_search=True,
                supports_code_interpreter=True,
                max_tokens=65536,
                context_window=1048576,
            ),
            patterns=["gemini-2.5-flash"],
        ),
        "gemini-2.5-flash-preview-09-2025": SpecificModelConfig(
            version_default="2.5",
            variant_default="flash",
            variant_priority=(1,),
            capabilities=ModelCapabilities(
                supports_vision=True,
                supports_audio=True,
                supports_video=True,
                supports_pdf=False,
                supports_thinking=True,
                supports_function_calling=True,
                supports_streaming=True,
                supports_structured_outputs=True,
                supports_json_outputs=True,
                supports_web_search=True,
                supports_file_search=True,
                supports_code_interpreter=True,
                max_tokens=65536,
                context_window=1048576,
            ),
            patterns=["gemini-2.5-flash-preview-09-2025"],
        ),
        "gemini-2.5-flash-image": SpecificModelConfig(
            version_default="2.5",
            variant_default="flash-image",
            variant_priority=(2,),
            capabilities=ModelCapabilities(
                supports_vision=True,
                supports_image_generation=True,
                supports_thinking=False,
                supports_audio=False,
                supports_pdf=False,
                supports_streaming=True,
                supports_structured_outputs=False,
                supports_json_outputs=True,
                max_tokens=32768,
                context_window=65536,
            ),
            patterns=["gemini-2.5-flash-image"],
        ),
        "gemini-2.5-flash-native-audio-preview-09-2025": SpecificModelConfig(
            version_default="2.5",
            variant_default="flash-live",
            variant_priority=(1,),
            capabilities=ModelCapabilities(
                supports_audio=True,
                supports_video=True,
                supports_pdf=False,
                supports_audio_generation=True,
                supports_thinking=True,
                supports_function_calling=True,
                supports_streaming=True,
                supports_web_search=True,
                max_tokens=8192,
                context_window=131072,
            ),
            patterns=["gemini-2.5-flash-native-audio-preview-09-2025"],
        ),
        "gemini-2.5-flash-preview-tts": SpecificModelConfig(
            version_default="2.5",
            variant_default="flash-tts",
            variant_priority=(0,),
            capabilities=ModelCapabilities(
                supports_audio_generation=True,
                supports_pdf=False,
                supports_streaming=True,
                max_tokens=16384,
                context_window=8192,
            ),
            patterns=["gemini-2.5-flash-preview-tts"],
        ),
        # Gemini 2.5 Flash-Lite 系列 - 最快的模型
        "gemini-2.5-flash-lite": SpecificModelConfig(
            version_default="2.5",
            variant_default="flash-lite",
            variant_priority=(0,),
            capabilities=ModelCapabilities(
                supports_vision=True,
                supports_audio=True,
                supports_video=True,
                supports_pdf=True,
                supports_thinking=True,
                supports_function_calling=True,
                supports_streaming=True,
                supports_structured_outputs=True,
                supports_json_outputs=True,
                supports_web_search=True,
                supports_file_search=True,
                supports_code_interpreter=True,
                max_tokens=65536,
                context_window=1048576,
            ),
            patterns=["gemini-2.5-flash-lite"],
        ),
        "gemini-2.5-flash-lite-preview-09-2025": SpecificModelConfig(
            version_default="2.5",
            variant_default="flash-lite",
            variant_priority=(0,),
            capabilities=ModelCapabilities(
                supports_vision=True,
                supports_audio=True,
                supports_video=True,
                supports_pdf=True,
                supports_thinking=True,
                supports_function_calling=True,
                supports_streaming=True,
                supports_structured_outputs=True,
                supports_json_outputs=True,
                supports_web_search=True,
                supports_file_search=True,
                supports_code_interpreter=True,
                max_tokens=65536,
                context_window=1048576,
            ),
            patterns=["gemini-2.5-flash-lite-preview-09-2025"],
        ),
        # Gemini 2.5 Pro 系列 - 高级思考模型
        "gemini-2.5-pro": SpecificModelConfig(
            version_default="2.5",
            variant_default="pro",
            variant_priority=(4,),
            capabilities=ModelCapabilities(
                supports_vision=True,
                supports_audio=True,
                supports_video=True,
                supports_pdf=True,
                supports_thinking=True,
                supports_function_calling=True,
                supports_streaming=True,
                supports_structured_outputs=True,
                supports_json_outputs=True,
                supports_web_search=True,
                supports_file_search=True,
                supports_code_interpreter=True,
                max_tokens=65536,
                context_window=1048576,
            ),
            patterns=["gemini-2.5-pro"],
        ),
        "gemini-2.5-pro-preview-tts": SpecificModelConfig(
            version_default="2.5",
            variant_default="pro-tts",
            variant_priority=(3,),
            capabilities=ModelCapabilities(
                supports_audio_generation=True,
                supports_streaming=True,
                max_tokens=16384,
                context_window=8192,
            ),
            patterns=["gemini-2.5-pro-preview-tts"],
        ),
        # Gemini 2.0 Flash 系列 - 第二代主力模型
        "gemini-2.0-flash": SpecificModelConfig(
            version_default="2.0",
            variant_default="flash",
            variant_priority=(1,),
            capabilities=ModelCapabilities(
                supports_vision=True,
                supports_audio=True,
                supports_video=True,
                supports_thinking=True,
                supports_function_calling=True,
                supports_streaming=True,
                supports_structured_outputs=True,
                supports_json_outputs=True,
                supports_web_search=True,
                supports_code_interpreter=True,
                max_tokens=8192,
                context_window=1048576,
            ),
            patterns=["gemini-2.0-flash", "gemini-2.0-flash-001", "gemini-2.0-flash-exp"],
        ),
        "gemini-2.0-flash-preview-image-generation": SpecificModelConfig(
            version_default="2.0",
            variant_default="flash-image",
            variant_priority=(2,),
            capabilities=ModelCapabilities(
                supports_vision=True,
                supports_thinking=False,
                supports_audio=False,
                supports_image_generation=True,
                supports_streaming=True,
                supports_structured_outputs=False,
                supports_json_outputs=True,
                max_tokens=8192,
                context_window=32768,
            ),
            patterns=["gemini-2.0-flash-preview-image-generation"],
        ),
        # Gemini 2.0 Flash-Lite 系列 - 第二代快速模型
        "gemini-2.0-flash-lite": SpecificModelConfig(
            version_default="2.0",
            variant_default="flash-lite",
            variant_priority=(0,),
            capabilities=ModelCapabilities(
                supports_vision=True,
                supports_audio=True,
                supports_video=True,
                supports_function_calling=True,
                supports_streaming=True,
                supports_structured_outputs=True,
                supports_json_outputs=True,
                max_tokens=8192,
                context_window=1048576,
            ),
            patterns=["gemini-2.0-flash-lite", "gemini-2.0-flash-lite-001"],
        ),
    },
)
