"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .user_data_properties import UserDataProperties, UserDataPropertiesTypedDict
from latitudesh_python_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UserDataMetaTypedDict(TypedDict):
    pass


class UserDataMeta(BaseModel):
    pass


class UserDataTypedDict(TypedDict):
    data: NotRequired[UserDataPropertiesTypedDict]
    meta: NotRequired[UserDataMetaTypedDict]


class UserData(BaseModel):
    data: Optional[UserDataProperties] = None

    meta: Optional[UserDataMeta] = None
