"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .region_resource_data import RegionResourceData, RegionResourceDataTypedDict
from enum import Enum
from latitudesh_python_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class VpnSessionDataWithPasswordType(str, Enum):
    VPN_SESSIONS = "vpn_sessions"


class VpnSessionDataWithPasswordStatus(str, Enum):
    r"""from Firewall Response"""

    ENABLE = "enable"
    DISABLE = "disable"


class VpnSessionDataWithPasswordAttributesTypedDict(TypedDict):
    user_name: NotRequired[str]
    r"""VPN username"""
    password: NotRequired[str]
    r"""VPN password"""
    port: NotRequired[str]
    r"""VPN port"""
    host: NotRequired[str]
    r"""VPN host"""
    region: NotRequired[RegionResourceDataTypedDict]
    status: NotRequired[VpnSessionDataWithPasswordStatus]
    r"""from Firewall Response"""
    expires_at: NotRequired[str]
    r"""Time to expiry"""
    created_at: NotRequired[str]
    updated_at: NotRequired[str]


class VpnSessionDataWithPasswordAttributes(BaseModel):
    user_name: Optional[str] = None
    r"""VPN username"""

    password: Optional[str] = None
    r"""VPN password"""

    port: Optional[str] = None
    r"""VPN port"""

    host: Optional[str] = None
    r"""VPN host"""

    region: Optional[RegionResourceData] = None

    status: Optional[VpnSessionDataWithPasswordStatus] = None
    r"""from Firewall Response"""

    expires_at: Optional[str] = None
    r"""Time to expiry"""

    created_at: Optional[str] = None

    updated_at: Optional[str] = None


class VpnSessionDataWithPasswordTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[VpnSessionDataWithPasswordType]
    attributes: NotRequired[VpnSessionDataWithPasswordAttributesTypedDict]


class VpnSessionDataWithPassword(BaseModel):
    id: Optional[str] = None

    type: Optional[VpnSessionDataWithPasswordType] = None

    attributes: Optional[VpnSessionDataWithPasswordAttributes] = None
