# coding: utf-8

"""
    Nexium Exchanger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Contact: info@nexium.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nexium_exchanger.models.payment_outgoing_request_snapshot import PaymentOutgoingRequestSnapshot

class TestPaymentOutgoingRequestSnapshot(unittest.TestCase):
    """PaymentOutgoingRequestSnapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentOutgoingRequestSnapshot:
        """Test PaymentOutgoingRequestSnapshot
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentOutgoingRequestSnapshot`
        """
        model = PaymentOutgoingRequestSnapshot()
        if include_optional:
            return PaymentOutgoingRequestSnapshot(
                id = 56,
                status = '',
                amount = 56,
                order_id = 56
            )
        else:
            return PaymentOutgoingRequestSnapshot(
                id = 56,
                status = '',
                amount = 56,
        )
        """

    def testPaymentOutgoingRequestSnapshot(self):
        """Test PaymentOutgoingRequestSnapshot"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
