# coding: utf-8

"""
    Nexium Exchanger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.6
    Contact: info@nexium.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nexium_exchanger.models.response_data_exchanger_admin_out import ResponseDataExchangerAdminOut

class TestResponseDataExchangerAdminOut(unittest.TestCase):
    """ResponseDataExchangerAdminOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseDataExchangerAdminOut:
        """Test ResponseDataExchangerAdminOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseDataExchangerAdminOut`
        """
        model = ResponseDataExchangerAdminOut()
        if include_optional:
            return ResponseDataExchangerAdminOut(
                data = nexium_exchanger.models.exchanger_admin_out.ExchangerAdminOut(
                    name = '0', 
                    ui_settings = { }, 
                    telegram_bot_webhook = '', 
                    id = 56, 
                    auth_entity_id = 56, 
                    signature_secret = '', )
            )
        else:
            return ResponseDataExchangerAdminOut(
                data = nexium_exchanger.models.exchanger_admin_out.ExchangerAdminOut(
                    name = '0', 
                    ui_settings = { }, 
                    telegram_bot_webhook = '', 
                    id = 56, 
                    auth_entity_id = 56, 
                    signature_secret = '', ),
        )
        """

    def testResponseDataExchangerAdminOut(self):
        """Test ResponseDataExchangerAdminOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
