class DatevLodasMapping:
    DEID4323 = {
      "11": "Kinderpflege mit Krankengeld",
      "14": "Vollst. Freistellung für Betreuung/Begleitung Pflegebedürftiger",
      "15": "Pflegezeit mit vollständiger Freistellung",
      "16": "Kurzzeitige Pflege",
      "19": "unwiderrufliche unbezahlte Freistellung",
      "21": "Unbezahlter Urlaub",
      "22": "Unbezahlte Fehlzeit",
      "23": "Unrechtmäßiger Streik",
      "24": "Kinderpflege ohne Krankengeld",
      "25": "Krank privat Versicherte ohne Krankentagegeld",
      "26": "Krank über 6 Wochen bei Erwerbsminderungs-/Altersrente",
      "27": "Krank über 6 Wochen geringfügig entlohnter AN",
      "28": "Aussteuerung",
      "29": "Einstellung Krankengeld w. voller Erwerbsm. Rente",
      "31": "Rechtmäßiger Streik",
      "32": "Aussperrung",
      "33": "Entgeltfortzahlung ohne AU-Bescheinigung",
      "41": "Krankentagegeld bei Krankheit oder Kur",
      "42": "Verletztengeld bei Krankheit oder Kur",
      "43": "Übergangsgeld bei Krankheit oder Kur",
      "44": "Versorgungskrankengeld bei Krankheit oder Kur",
      "45": "Mutterschutzfrist",
      "47": "Krank bei Eintritt ohne Entgeltfortzahlung",
      "51": "Elternzeit",
      "61": "Wehrdienst",
      "62": "Zivildienst",
      "63": "Wehrübung",
      "64": "Eignungsübung",
      "81": "Kug/S-Kug Krank",
      "103": "Entgeltfortzahlung mit AU-Bescheinigung",
      "105": "widerrufliche bezahlte Freistellung",
      "106": "Studienzeit (dualer Studiengang)",
      "200": "Kinderpflege mit Entgeltfortzahlung",
      "201": "Kinderpflege bei Schwersterkrankung",
      "210": "Pflegeunterstützungsgeld",
      "260": "Ende Bezug Krankengeld/Beginn Bezug Arbeitslosengeld",
      "300": "Entgeltfortzahlung wegen Organ-/Gewebespende",
      "301": "Freistellung im Rahmen sonstiger flexibler Arbeitszeitregelungen",
      "302": "Krankengeld bei Organ-/Blut/Gewebespende ohne EEL",
      "303": "Entschädigungszahlung wegen Quarantäne",
      "304": "Bezahlte Freistellung wegen angeordneter Quarantäne",
      "305": "Bezahlte Freistellung wegen freiwilliger Quarantäne",
      "306": "Unbezahlte Freistellung wegen freiwilliger Quarantäne",
      "307": "Entschädigungszahlung nach IfSG wegen Beaufsichtigung Kind",
      "308": "Berufliches Tätigkeitsverbot",
      "309": "Vorsorgliche Einstellung der beruflichen Tätigkeit",
      "310": "Krankengeld bei Mitaufnahme ins Krankenhaus"
    }
    DEID4323_REVERSE = {v: k for k, v in DEID4323.items()} #accidetnily wrote it wrong way.

    DEID4248 = {
      "0": "keine Angabe",
      "Bar": "Bar",
      "BAR": "BAR",
      "Baron": "Baron",
      "BARON": "BARON",
      "Baroness": "Baroness",
      "BARONESS": "BARONESS",
      "BARONESSE": "BARONESSE",
      "Baronesse": "Baronesse",
      "BARONIN": "BARONIN",
      "Baronin": "Baronin",
      "BRAND": "BRAND",
      "Brand": "Brand",
      "BURGGRAF": "BURGGRAF",
      "Burggraf": "Burggraf",
      "BURGGRÄFIN": "BURGGRÄFIN",
      "Burggräfin": "Burggräfin",
      "CONDESA": "CONDESA",
      "Condesa": "Condesa",
      "EARL": "EARL",
      "Earl": "Earl",
      "EDLE": "EDLE",
      "Edle": "Edle",
      "EDLER": "EDLER",
      "Edler": "Edler",
      "Erbgraf": "Erbgraf",
      "ERBGRAF": "ERBGRAF",
      "ERBGRÄFIN": "ERBGRÄFIN",
      "Erbgräfin": "Erbgräfin",
      "ERBPRINZ": "ERBPRINZ",
      "Erbprinz": "Erbprinz",
      "Erbprinzessin": "Erbprinzessin",
      "ERBPRINZESSIN": "ERBPRINZESSIN",
      "FFR": "FFR",
      "Ffr": "Ffr",
      "FREIFR": "FREIFR",
      "Freifr": "Freifr",
      "Freifrau": "Freifrau",
      "FREIFRAU": "FREIFRAU",
      "Freifräulein": "Freifräulein",
      "FREIFRÄULEIN": "FREIFRÄULEIN",
      "FREIH": "FREIH",
      "Freih": "Freih",
      "FREIHERR": "FREIHERR",
      "Freiherr": "Freiherr",
      "Freiin": "Freiin",
      "FREIIN": "FREIIN",
      "FRF": "FRF",
      "Frf": "Frf",
      "FRF.": "FRF.",
      "Frf.": "Frf.",
      "FRFR": "FRFR",
      "Frfr": "Frfr",
      "FRFR.": "FRFR.",
      "Frfr.": "Frfr.",
      "FRH": "FRH",
      "Frh": "Frh",
      "FRH.": "FRH.",
      "Frh.": "Frh.",
      "FRHR": "FRHR",
      "Frhr": "Frhr",
      "FRHR.": "FRHR.",
      "Frhr.": "Frhr.",
      "Fst": "Fst",
      "FST": "FST",
      "FST.": "FST.",
      "Fst.": "Fst.",
      "Fstn": "Fstn",
      "FSTN": "FSTN",
      "FSTN.": "FSTN.",
      "Fstn.": "Fstn.",
      "FÜRST": "FÜRST",
      "Fürst": "Fürst",
      "Fürstin": "Fürstin",
      "FÜRSTIN": "FÜRSTIN",
      "GR": "GR",
      "Gr": "Gr",
      "Graf": "Graf",
      "GRAF": "GRAF",
      "GRÄFIN": "GRÄFIN",
      "Gräfin": "Gräfin",
      "GRF": "GRF",
      "Grf": "Grf",
      "GRFN": "GRFN",
      "Grfn": "Grfn",
      "GROSSHERZOG": "GROSSHERZOG",
      "Grossherzog": "Grossherzog",
      "Großherzog": "Großherzog",
      "GROßHERZOG": "GROßHERZOG",
      "GROSSHERZOGIN": "GROSSHERZOGIN",
      "GROßHERZOGIN": "GROßHERZOGIN",
      "Großherzogin": "Großherzogin",
      "Grossherzogin": "Grossherzogin",
      "HERZOG": "HERZOG",
      "Herzog": "Herzog",
      "HERZOGIN": "HERZOGIN",
      "Herzogin": "Herzogin",
      "JHR": "JHR",
      "Jhr": "Jhr",
      "JHR.": "JHR.",
      "Jhr.": "Jhr.",
      "Jonkheer": "Jonkheer",
      "JONKHEER": "JONKHEER",
      "JUNKER": "JUNKER",
      "Junker": "Junker",
      "LANDGRAF": "LANDGRAF",
      "Landgraf": "Landgraf",
      "Landgräfin": "Landgräfin",
      "LANDGRÄFIN": "LANDGRÄFIN",
      "MARKGRAF": "MARKGRAF",
      "Markgraf": "Markgraf",
      "Markgräfi": "Markgräfin",
      "MARKGRÄFIN": "MARKGRÄFIN",
      "Marques": "Marques",
      "MARQUES": "MARQUES",
      "MARQUIS": "MARQUIS",
      "Marquis": "Marquis",
      "MARSCHALL": "MARSCHALL",
      "Marschall": "Marschall",
      "Ostoja": "Ostoja",
      "OSTOJA": "OSTOJA",
      "Prinz": "Prinz",
      "PRINZ": "PRINZ",
      "PRINZESSIN": "PRINZESSIN",
      "Prinzessin": "Prinzessin",
      "PRZIN": "PRZIN",
      "Przin": "Przin",
      "Rabe": "Rabe",
      "RABE": "RABE",
      "REICHSGRAF": "REICHSGRAF",
      "Reichsgraf": "Reichsgraf",
      "REICHSGRÄFIN": "REICHSGRÄFIN",
      "Reichsgräfin": "Reichsgräfin",
      "RITTER": "RITTER",
      "Ritter": "Ritter",
      "Rr": "Rr",
      "RR": "RR",
      "TRUCHSEß": "TRUCHSEß",
      "Truchseß": "Truchseß",
      "Truchsess": "Truchsess",
      "TRUCHSESS": "TRUCHSESS"
    }

    DEID4249 = {
      "0": "keine Angabe",
      "A": "A",
      "a": "a",
      "aan de": "aan de",
      "AAN DE": "AAN DE",
      "AAN DEN": "AAN DEN",
      "aan den": "aan den",
      "AL": "AL",
      "al": "al",
      "AM": "AM",
      "am": "am",
      "an": "an",
      "AN": "AN",
      "AN DER": "AN DER",
      "an der": "an der",
      "AUF": "AUF",
      "auf": "auf",
      "AUF DEM": "AUF DEM",
      "auf dem": "auf dem",
      "AUF DER": "AUF DER",
      "auf der": "auf der",
      "AUF M": "AUF M",
      "auf m": "auf m",
      "AUFM": "AUFM",
      "aufm": "aufm",
      "AUFF M": "AUFF M",
      "auff m": "auff m",
      "AUS": "AUS",
      "aus": "aus",
      "AUS DEM": "AUS DEM",
      "aus dem": "aus dem",
      "AUS DEN": "AUS DEN",
      "aus den": "aus den",
      "AUS DER": "AUS DER",
      "aus der": "aus der",
      "B": "B",
      "b": "b",
      "BE": "BE",
      "be": "be",
      "bei": "bei",
      "BEI": "BEI",
      "BEI DER": "BEI DER",
      "bei der": "bei der",
      "BEIM": "BEIM",
      "beim": "beim",
      "BEN": "BEN",
      "ben": "ben",
      "BEY": "BEY",
      "bey": "bey",
      "BEY DER": "BEY DER",
      "bey der": "bey der",
      "CHE": "CHE",
      "Che": "Che",
      "CID": "CID",
      "Cid": "Cid",
      "D": "D",
      "d": "d",
      "D'": "D'",
      "d'": "d'",
      "D.": "D.",
      "d.": "d.",
      "DA": "DA",
      "da": "da",
      "DA COSTA": "DA COSTA",
      "da costa": "da costa",
      "DA LAS": "DA LAS",
      "da las": "da las",
      "DA SILVA": "DA SILVA",
      "da silva": "da silva",
      "DAL": "DAL",
      "dal": "dal",
      "DALL": "DALL",
      "dall": "dall",
      "DALL'": "DALL'",
      "dall'": "dall'",
      "DALLA": "DALLA",
      "dalla": "dalla",
      "DALLE": "DALLE",
      "dalle": "dalle",
      "DALLO": "DALLO",
      "dallo": "dallo",
      "DAS": "DAS",
      "das": "das",
      "DE": "DE",
      "de": "de",
      "de l'": "de l'",
      "DE L'": "DE L'",
      "DE LA": "DE LA",
      "de la": "de la",
      "DE LAS": "DE LAS",
      "de las": "de las",
      "DE LE": "DE LE",
      "de le": "de le",
      "DEGLI": "DEGLI",
      "degli": "degli",
      "DEI": "DEI",
      "dei": "dei",
      "DEL": "DEL",
      "del": "del",
      "DEL COZ": "DEL COZ",
      "del coz": "del coz",
      "DELI": "DELI",
      "deli": "deli",
      "DELL": "DELL",
      "dell": "dell",
      "DELL'": "DELL'",
      "dell'": "dell'",
      "DELLA": "DELLA",
      "della": "della",
      "DELLE": "DELLE",
      "delle": "delle",
      "DELLI": "DELLI",
      "delli": "delli",
      "DELLO": "DELLO",
      "dello": "dello",
      "DEN": "DEN",
      "den": "den",
      "DER": "DER",
      "der": "der",
      "DES": "DES",
      "des": "des",
      "DI": "DI",
      "di": "di",
      "DIT": "DIT",
      "dit": "dit",
      "DO": "DO",
      "do": "do",
      "do ceu": "do ceu",
      "DO CEU": "DO CEU",
      "DON": "DON",
      "Don": "Don",
      "Don le": "Don le",
      "DON LE": "DON LE",
      "DOS": "DOS",
      "dos": "dos",
      "DOS SANTOS": "DOS SANTOS",
      "dos Santos": "dos Santos",
      "DU": "DU",
      "du": "du",
      "DY": "DY",
      "dy": "dy",
      "EL": "EL",
      "el": "el",
      "G": "G",
      "g": "g",
      "GEN": "GEN",
      "gen": "gen",
      "GIL": "GIL",
      "Gil": "Gil",
      "GLI": "GLI",
      "gli": "gli",
      "Grosse": "Grosse",
      "GROSSE": "GROSSE",
      "GROßE": "GROßE",
      "Große": "Große",
      "I": "I",
      "i": "i",
      "IM": "IM",
      "im": "im",
      "IN": "IN",
      "in": "in",
      "IN DEN": "IN DEN",
      "in den": "in den",
      "IN DER": "IN DER",
      "in der": "in der",
      "IN HET": "IN HET",
      "in het": "in het",
      "IN'T": "IN'T",
      "in't": "in't",
      "KL": "KL",
      "kl": "kl",
      "KLEINE": "KLEINE",
      "kleine": "kleine",
      "L": "L",
      "l": "l",
      "L'": "L'",
      "l'": "l'",
      "L.": "L.",
      "l.": "l.",
      "LA": "LA",
      "la": "la",
      "LE": "LE",
      "le": "le",
      "LEE": "LEE",
      "lee": "lee",
      "LI": "LI",
      "li": "li",
      "LO": "LO",
      "lo": "lo",
      "M": "M",
      "m": "m",
      "MAC": "MAC",
      "Mac": "Mac",
      "MC": "MC",
      "mc": "mc",
      "n": "n",
      "N": "N",
      "O": "O",
      "o": "o",
      "O'": "O'",
      "o'": "o'",
      "op": "op",
      "OP": "OP",
      "op de": "op de",
      "OP DE": "OP DE",
      "op den": "op den",
      "OP DEN": "OP DEN",
      "op gen": "op gen",
      "OP GEN": "OP GEN",
      "op het": "op het",
      "OP HET": "OP HET",
      "op te": "op te",
      "OP TE": "OP TE",
      "op ten": "op ten",
      "OP TEN": "OP TEN",
      "pla": "pla",
      "PLA": "PLA",
      "pro": "pro",
      "PRO": "PRO",
      "rr": "rr",
      "S": "S",
      "s": "s",
      "RR": "RR",
      "St.": "St.",
      "ST.": "ST.",
      "t": "t",
      "T": "T",
      "te": "te",
      "TE": "TE",
      "ten": "ten",
      "TEN": "TEN",
      "ter": "ter",
      "TER": "TER",
      "THI": "THI",
      "thi": "thi",
      "Tho": "Tho",
      "THO": "THO",
      "Thom": "Thom",
      "THOM": "THOM",
      "thor": "thor",
      "THOR": "THOR",
      "THUM": "THUM",
      "Thum": "Thum",
      "TO": "TO",
      "to": "to",
      "Tom": "Tom",
      "TOM": "TOM",
      "TOR": "TOR",
      "Tor": "Tor",
      "TU": "TU",
      "tu": "tu",
      "TUM": "TUM",
      "tum": "tum",
      "UNTEN": "UNTEN",
      "unten": "unten",
      "unter": "unter",
      "UNTER": "UNTER",
      "unterm": "unterm",
      "UNTERM": "UNTERM",
      "v.": "v.",
      "V.": "V.",
      "V. D.": "V. D.",
      "v. d.": "v. d.",
      "v. dem": "v. dem",
      "V. DEM": "V. DEM",
      "v. den": "v. den",
      "V. DEN": "V. DEN",
      "v. der": "v. der",
      "V. DER": "V. DER",
      "V.D.": "V.D.",
      "v.d.": "v.d.",
      "v.dem": "v.dem",
      "V.DEM": "V.DEM",
      "v.den": "v.den",
      "V.DEN": "V.DEN",
      "v.der": "v.der",
      "V.DER": "V.DER",
      "VAN": "VAN",
      "van": "van",
      "van de": "van de",
      "VAN DE": "VAN DE",
      "VAN DEM": "VAN DEM",
      "van dem": "van dem",
      "VAN DEN": "VAN DEN",
      "van den": "van den",
      "VAN DER": "VAN DER",
      "van der": "van der",
      "VAN GEN": "VAN GEN",
      "van gen": "van gen",
      "van het": "van het",
      "VAN HET": "VAN HET",
      "van t": "van t",
      "VAN T": "VAN T",
      "VANDE": "VANDE",
      "vande": "vande",
      "VANDEM": "VANDEM",
      "vandem": "vandem",
      "vanden": "vanden",
      "VANDEN": "VANDEN",
      "vander": "vander",
      "VANDER": "VANDER",
      "ven": "ven",
      "VEN": "VEN",
      "VEN DER": "VEN DER",
      "ven der": "ven der",
      "ver": "ver",
      "VER": "VER",
      "VO": "VO",
      "vo": "vo",
      "VOM": "VOM",
      "vom": "vom",
      "VOM UND ZU": "VOM UND ZU",
      "vom und zu": "vom und zu",
      "von": "von",
      "VON": "VON",
      "VON DE": "VON DE",
      "von de": "von de",
      "von dem": "von dem",
      "VON DEM": "VON DEM",
      "VON DEN": "VON DEN",
      "von den": "von den",
      "VON DER": "VON DER",
      "von der": "von der",
      "VON EINEM": "VON EINEM",
      "von einem": "von einem",
      "VON LA": "VON LA",
      "von la": "von la",
      "von Mast": "von Mast",
      "VON MAST": "VON MAST",
      "VON UND ZU DER": "VON UND ZU DER",
      "von und zu der": "von und zu der",
      "VON UND ZUR": "VON UND ZUR",
      "von und zur": "von und zur",
      "von zu": "von zu",
      "VON ZU": "VON ZU",
      "von zum": "von zum",
      "VON ZUM": "VON ZUM",
      "VON ZUR": "VON ZUR",
      "von zur": "von zur",
      "vonde": "vonde",
      "VONDE": "VONDE",
      "vondem": "vondem",
      "VONDEM": "VONDEM",
      "vonden": "vonden",
      "VONDEN": "VONDEN",
      "VONDER": "VONDER",
      "vonder": "vonder",
      "VOR": "VOR",
      "vor": "vor",
      "VOR DEM": "VOR DEM",
      "vor dem": "vor dem",
      "VOR DEN": "VOR DEN",
      "vor den": "vor den",
      "VOR DER": "VOR DER",
      "vor der": "vor der",
      "VORM": "VORM",
      "vorm": "vorm",
      "vorn": "vorn",
      "VORN": "VORN",
      "Y": "Y",
      "y": "y",
      "Y DEL": "Y DEL",
      "y del": "y del",
      "ZU": "ZU",
      "zu": "zu",
      "zum": "zum",
      "ZUM": "ZUM",
      "zur": "zur",
      "ZUR": "ZUR"
    }

    DEID4213 = {
      "0": "keine Angabe",
      "A": "Österreich",
      "AFG": "Afghanistan",
      "AGO": "Angola",
      "AJ": "Amerikanische Jungferninseln",
      "AL": "Albanien",
      "AND": "Andorra",
      "ANG": "Anguilla",
      "ANT": "Antigua und Barbuda",
      "AQ": "Antarktische Territorien",
      "AQU": "Äquatorialguinea",
      "ARM": "Armenien",
      "AS": "Amerikanisch Samoa",
      "ASE": "Aserbaidschan",
      "AU": "Korallenmeer-, Ashmore- und Cartierinseln",
      "AUS": "Australien",
      "AW": "Aruba",
      "AX": "Åland",
      "B": "Belgien",
      "BD": "Bangladesch",
      "BDS": "Barbados",
      "BER": "Bermuda",
      "BG": "Bulgarien",
      "BH": "Belize",
      "BHT": "Bhutan",
      "BIH": "Bosnien und Herzegowina",
      "BIO": "Malediven",
      "BJ": "Britische Jungferninseln",
      "BL": "St. Barthélemy",
      "BOL": "Bolivien",
      "BQ": "Bonaire, Saba, St. Eustatius",
      "BR": "Brasilien",
      "BRN": "Bahrain",
      "BRU": "Brunei Darussalam",
      "BS": "Bahamas",
      "BV": "Bouvetinsel",
      "BY": "Weissrussland",
      "C": "Kuba",
      "CAM": "Kamerun",
      "CC": "Kokosinseln",
      "CDN": "Kanada",
      "CH": "Schweiz",
      "CHD": "Tschad",
      "CI": "Côte d‘Ivoire",
      "CL": "Sri Lanka",
      "CO": "Kolumbien",
      "COI": "Cookinseln",
      "CP": "Clipperton",
      "CR": "Costa Rica",
      "CV": "Cabo Verde",
      "CW": "Curaçao",
      "CY": "Zypern",
      "CX": "Weihnachtsinsel",
      "CZ": "Tschechien",
      "DK": "Dänemark",
      "DOM": "Dominikanische Republik",
      "DSC": "Dschibuti",
      "DY": "Benin",
      "DZ": "Algerien",
      "E": "Spanien",
      "EAK": "Kenia",
      "EAT": "Tansania",
      "EAU": "Uganda",
      "EC": "Ecuador",
      "EH": "Westsahara",
      "ERI": "Eritrea",
      "ES": "El Salvador",
      "EST": "Estland",
      "ET": "Ägypten",
      "ETH": "Äthiopien",
      "F": "Frankreich",
      "FAL": "Falklandinseln",
      "FG": "Französisch Guayana",
      "FIN": "Finnland",
      "FJI": "Fidschi",
      "FL": "Liechtenstein",
      "FP": "Franz.-Polynesien",
      "FR": "Färöer",
      "GAB": "Gabun",
      "GB": "Vereinigtes Königreich",
      "GCA": "Guatemala",
      "GEO": "Georgien",
      "GG": "Guernsey",
      "GH": "Ghana",
      "GIB": "Gibraltar",
      "GR": "Griechenland",
      "GRO": "Grönland",
      "GS": "Südgeorgien und die südlichen Sandwichinseln",
      "GUA": "Guadeloupe",
      "GUB": "Guinea-Bissau",
      "GUM": "Guam",
      "GUY": "Guyana",
      "H": "Ungarn",
      "HCA": "Honduras",
      "HEL": "St. Helena /Ascension / Tristan da Cunha",
      "HKG": "Hongkong",
      "HR": "Kroatien",
      "HM": "Heard und McDonaldinseln",
      "HV": "Burkina Faso",
      "I": "Italien",
      "IL": "Israel",
      "IND": "Indien",
      "IR": "Iran",
      "IRL": "Irland",
      "IRQ": "Irak",
      "IS": "Island",
      "IO": "Britisches Territorium im Indischen Ozean",
      "J": "Japan",
      "JA": "Jamaika",
      "JE": "Jersey",
      "JOR": "Jordanien",
      "K": "Kambodscha",
      "KAI": "Kaimaninseln",
      "KAN": "Kanalinseln",
      "KAS": "Kasachstan",
      "KIB": "Kiribati",
      "KIS": "Kirgisistan",
      "KOM": "Komoren",
      "KOR": "Korea, Demokratische Volksrepublik (Nordkorea)",
      "KOS": "Kosovo",
      "KWT": "Kuwait",
      "L": "Luxemburg",
      "LAO": "Laos",
      "LAR": "Libyen",
      "LB": "Liberia",
      "LS": "Lesotho",
      "LT": "Litauen",
      "LV": "Lettland",
      "M": "Malta",
      "MA": "Marokko",
      "MAC": "Macau",
      "MAL": "Malaysia",
      "MAN": "Insel Man",
      "MAO": "Oman",
      "MAR": "Marshallinseln",
      "MAT": "Martinique",
      "MAY": "Mayotte",
      "MC": "Monaco",
      "MD": "Moldau",
      "MEX": "Mexiko",
      "MF": "St. Martin (französischer Teil)",
      "MIK": "Mikronesien",
      "MK": "Nordmazedonien",
      "MNE": "Montenegro",
      "MON": "Mongolei",
      "MOT": "Montserrat",
      "MOZ": "Mosambik",
      "MS": "Mauritius",
      "MW": "Malawi",
      "MYA": "Myanmar",
      "N": "Norwegen",
      "NAU": "Nauru",
      "NEP": "Nepal",
      "NF": "Norfolkinseln",
      "NIC": "Nicaragua",
      "NIU": "Niue",
      "NKA": "Neukaledonien",
      "NL": "Niederlande",
      "NLA": "Niederländische Antillen",
      "NMA": "Nördliche Marianen",
      "NZ": "Neuseeland",
      "P": "Portugal",
      "PA": "Panama",
      "PAL": "Palau",
      "PE": "Peru",
      "PIE": "St. Pierre und Miquelon",
      "PIT": "Pitcairninseln",
      "PK": "Pakistan",
      "PL": "Polen",
      "PNG": "Papua-Neuguinea",
      "PRI": "Puerto Rico",
      "PSE": "Palästinensische Gebiete",
      "PY": "Paraguay",
      "QAT": "Katar",
      "RA": "Argentinien",
      "RB": "Botsuana",
      "RCA": "Zentralafrikanische Republik",
      "RCB": "Kongo",
      "RCH": "Chile",
      "REU": "Réunion",
      "RG": "Guinea",
      "RH": "Haiti",
      "RI": "Indonesien",
      "RIM": "Mauretanien",
      "RL": "Libanon",
      "RM": "Madagaskar",
      "RMM": "Mali",
      "RN": "Niger",
      "RO": "Rumänien",
      "ROK": "Korea, Republik (Südkorea)",
      "ROU": "Uruguay",
      "RP": "Philippinen",
      "RSM": "San Marino",
      "RU": "Burundi",
      "RUS": "Russische Föderation",
      "RWA": "Ruanda",
      "S": "Schweden",
      "SAU": "Saudi-Arabien",
      "SCG": "Serbien und Montenegro",
      "SCN": "St. Kitts und Nevis",
      "SDN": "Sudan",
      "SGP": "Singapur",
      "SJ": "Svalbard und Jan Mayen",
      "SK": "Slowakei",
      "SLO": "Slowenien",
      "SME": "Suriname",
      "SN": "Senegal",
      "SOL": "Salomonen",
      "SP": "Somalia",
      "SRB": "Serbien",
      "SSD": "Südsudan",
      "STP": "São Tomé und Príncipe",
      "SWA": "Namibia",
      "SWZ": "Eswatini",
      "SY": "Seychellen",
      "SYR": "Syrien",
      "SX": "St. Martin (niederländischer Teil)",
      "T": "Thailand",
      "TAD": "Tadschikistan",
      "TF": "Französische Süd- und Antarktisgebiete",
      "TG": "Togo",
      "TJ": "China",
      "TN": "Tunesien",
      "TOK": "Tokelau",
      "TON": "Tonga",
      "TR": "Türkei",
      "TT": "Trinidad und Tobago",
      "TUC": "Turks- und Caicosinseln",
      "TUR": "Turkmenistan",
      "TUV": "Tuvalu",
      "TWN": "Taiwan",
      "UA": "Ukraine",
      "UAE": "Vereinigte Arabische Emirate",
      "UM": "Navassa / kleinere amerikanische Überseeinseln",
      "USA": "Vereinigte Staaten",
      "USB": "Usbekistan",
      "V": "Vatikanstadt",
      "VAN": "Vanuatu",
      "VN": "Vietnam",
      "WAG": "Gambia",
      "WAL": "Sierra Leone",
      "WAN": "Nigeria",
      "WD": "Dominica",
      "WF": "Wallis und Futuna",
      "WG": "Grenada",
      "WL": "St. Lucia",
      "WS": "Samoa",
      "WV": "St. Vincent und die Grenadinen",
      "YEM": "Jemen",
      "YU": "Jugoslawien",
      "YV": "Venezuela",
      "Z": "Sambia",
      "ZA": "Südafrika",
      "ZRE": "Kongo, Demokratische Republik",
      "ZW": "Simbabwe"
    }

    DEID4214 = {
      "000": "Deutschland",
      "121": "Albanien",
      "122": "Bosnien und Herzegowina",
      "123": "Andorra",
      "124": "Belgien",
      "125": "Bulgarien",
      "126": "Dänemark",
      "127": "Estland",
      "128": "Finnland",
      "129": "Frankreich",
      "130": "Kroatien",
      "131": "Slowenien",
      "132": "Serbien und Montenegro",
      "133": "Serbien (einschl. Kosovo)",
      "134": "Griechenland",
      "135": "Irland",
      "136": "Island",
      "137": "Italien",
      "138": "Jugoslawien",
      "139": "Lettland",
      "140": "Montenegro",
      "141": "Liechtenstein",
      "142": "Litauen",
      "143": "Luxemburg",
      "144": "Nordmazedonien",
      "145": "Malta",
      "146": "Moldau",
      "147": "Monaco",
      "148": "Niederlande",
      "149": "Norwegen",
      "150": "Kosovo",
      "151": "Österreich",
      "152": "Polen",
      "153": "Portugal",
      "154": "Rumänien",
      "155": "Slowakei",
      "156": "San Marino",
      "157": "Schweden",
      "158": "Schweiz",
      "160": "Russische Föderation",
      "161": "Spanien",
      "163": "Türkei",
      "164": "Tschechien",
      "165": "Ungarn",
      "166": "Ukraine",
      "167": "Vatikanstadt",
      "168": "Vereinigtes Königreich",
      "169": "Weissrussland",
      "170": "Serbien",
      "181": "Zypern",
      "195": "Gibraltar",
      "199": "Übriges Europa",
      "221": "Algerien",
      "223": "Angola",
      "224": "Eritrea",
      "225": "Äthiopien",
      "226": "Lesotho",
      "227": "Botsuana",
      "229": "Benin",
      "230": "Dschibuti",
      "231": "Côte d‘Ivoire",
      "232": "Nigeria",
      "233": "Simbabwe",
      "236": "Gabun",
      "237": "Gambia",
      "238": "Ghana",
      "239": "Mauretanien",
      "242": "Cabo Verde",
      "243": "Kenia",
      "244": "Komoren",
      "245": "Kongo",
      "246": "Kongo, Demokratische Republik",
      "247": "Liberia",
      "248": "Libyen",
      "249": "Madagaskar",
      "251": "Mali",
      "252": "Marokko",
      "253": "Mauritius",
      "254": "Mosambik",
      "255": "Niger",
      "256": "Malawi",
      "257": "Sambia",
      "258": "Burkina Faso",
      "259": "Guinea-Bissau",
      "261": "Guinea",
      "262": "Kamerun",
      "263": "Südafrika",
      "265": "Ruanda",
      "267": "Namibia",
      "268": "São Tomé und Príncipe",
      "269": "Senegal",
      "271": "Seychellen",
      "272": "Sierra Leone",
      "273": "Somalia",
      "274": "Äquatorialguinea",
      "276": "Sudan (vor der Teilung des Landes)",
      "277": "Sudan",
      "278": "Südsudan",
      "281": "Eswatini",
      "282": "Tansania",
      "283": "Togo",
      "284": "Tschad",
      "285": "Tunesien",
      "286": "Uganda",
      "287": "Ägypten",
      "289": "Zentralafrikanische Republik",
      "291": "Burundi",
      "295": "Britisch abhängige Gebiete in Afrika",
      "299": "Übriges Afrika",
      "320": "Antigua und Barbuda",
      "322": "Barbados",
      "323": "Argentinien",
      "324": "Bahamas",
      "326": "Bolivien",
      "327": "Brasilien",
      "328": "Guyana",
      "330": "Belize",
      "332": "Chile",
      "333": "Dominica",
      "334": "Costa Rica",
      "335": "Dominikanische Republik",
      "336": "Ecuador",
      "337": "El Salvador",
      "340": "Grenada",
      "345": "Guatemala",
      "346": "Haiti",
      "347": "Honduras",
      "348": "Kanada",
      "349": "Kolumbien",
      "351": "Kuba",
      "353": "Mexiko",
      "354": "Nicaragua",
      "355": "Jamaika",
      "357": "Panama",
      "359": "Paraguay",
      "361": "Peru",
      "364": "Suriname",
      "365": "Uruguay",
      "366": "St. Lucia",
      "367": "Venezuela",
      "368": "Vereinigte Staaten",
      "369": "St. Vincent und die Grenadinen",
      "370": "St. Kitts und Nevis",
      "371": "Trinidad und Tobago",
      "395": "Britisch abhängige Gebiete in Amerika",
      "399": "Übriges Amerika",
      "411": "Hongkong",
      "412": "Macau",
      "421": "Jemen",
      "422": "Armenien",
      "423": "Afghanistan",
      "424": "Bahrain",
      "425": "Aserbaidschan",
      "426": "Bhutan",
      "427": "Myanmar",
      "429": "Brunei Darussalam",
      "430": "Georgien",
      "431": "Sri Lanka",
      "432": "Vietnam",
      "434": "Korea, Demokratische Volksrepublik (Nordkorea)",
      "436": "Indien",
      "437": "Indonesien",
      "438": "Irak",
      "439": "Iran",
      "441": "Israel",
      "442": "Japan",
      "444": "Kasachstan",
      "445": "Jordanien",
      "446": "Kambodscha",
      "447": "Katar",
      "448": "Kuwait",
      "449": "Laos",
      "450": "Kirgisistan",
      "451": "Libanon",
      "454": "Malediven",
      "456": "Oman",
      "457": "Mongolei",
      "458": "Nepal",
      "459": "Palästinensische Gebiete",
      "460": "Bangladesch",
      "461": "Pakistan",
      "462": "Philippinen",
      "465": "Taiwan",
      "467": "Korea, Republik (Südkorea)",
      "469": "Vereinigte Arabische Emirate",
      "470": "Tadschikistan",
      "471": "Turkmenistan",
      "472": "Saudi-Arabien",
      "474": "Singapur",
      "475": "Syrien",
      "476": "Thailand",
      "477": "Usbekistan",
      "479": "China",
      "482": "Malaysia",
      "499": "Übriges Asien",
      "523": "Australien",
      "524": "Salomonen",
      "525": "Nördliche Marianen",
      "526": "Fidschi",
      "530": "Kiribati",
      "531": "Nauru",
      "532": "Vanuatu",
      "536": "Neuseeland",
      "537": "Palau",
      "538": "Papua-Neuguinea",
      "540": "Tuvalu",
      "541": "Tonga",
      "543": "Samoa",
      "544": "Marshallinseln",
      "545": "Mikronesien",
      "595": "Britisch abhängige Gebiete in Australien/Ozeanien",
      "599": "Übriges Ozeanien",
      "996": "Unbekanntes Ausland",
      "997": "staatenlos",
      "998": "ungeklärt",
      "999": "ohne Angabe"
    }

    DEID4003 = {
      "0": "Männlich",
      "1": "Weiblich",
      "2": "Divers",
      "3": "Unbestimmt"
    }

    DEID440 = {
      "0": "Nein",
      "1": "Ja"
    }

    DEID4181 = {
      "0": "Kein Zahlungsverkehr",
      "1": "Scheck",
      "4": "Barzahlung",
      "5": "SEPA-Überweisung"
    }

    DEID4636 = {
      "0": "wie Mandantendaten",
      "1": "Ja",
      "2": "Nein"
    }

    DEID4794 = {
      "0": "Wie Mandantendaten",
      "1": "Lohn/Gehalt MM/JJ bzw. Abschlag/Vorschuss MM/JJ",
      "2": "Abweichende Angaben"
    }

    DEID4574 = {
      "0": "unbefristet",
      "1": "befristet",
      "2": "zweckbefristet"
    }

    DEID4097 = {
      "0": "Arbeiter",
      "1": "Angestellte"
    }

    DEID4209 = {
      "0": "keine Angabe",
      "101": "Sozialversicherungspflichtig Beschäftigte ohne besondere Merkmale",
      "102": "Auszubildende ohne besondere Merkmale",
      "103": "Beschäftigte in Altersteilzeit",
      "104": "Hausgewerbetreibende (nicht Heimarbeiter)",
      "105": "Praktikanten",
      "106": "Werkstudenten",
      "107": "Behinderte Menschen in anerkannten Werkstätten oder gleichartigen Einrichtungen",
      "108": "Bezieher von Vorruhestandsgeld",
      "109": "Geringfügig entlohnte Beschäftigte nach §8 Abs. 1 Nr. 1 SGB IV",
      "110": "Kurzfristig Beschäftigte nach §8 Abs. 1 Nr. 2 SGB IV",
      "111": "Personen in Berufsfördernden Maßnahmen zur Rehabilitation",
      "112": "Mitarbeitende Familienangehörige in der Landwirtschaft",
      "113": "Nebenerwerbslandwirte",
      "114": "Nebenerwerbslandwirte - saisonal beschäftigt",
      "116": "Ausgleichsgeldempfänger nach dem FELEG",
      "118": "Unständig Beschäftigte",
      "119": "Versicherungsfr. Altersvollrentner/Versorgungsbezieher wg. Alters",
      "120": "Versicherungspfl. Altersvollrentner/Versorgungsbezieher wg. Alters",
      "121": "Auszubildende, deren Arbeitsentgelt die Geringverdienergrenze nicht übersteigt",
      "122": "Auszubildende in einer außerbetrieblichen Einrichtung",
      "123": "Personen, die ein freiwilliges soziales oder ökologisches Jahr oder BFD leisten",
      "124": "Heimarbeiter ohne Entgeltfortzahlungsanspruch",
      "127": "Behinderte Menschen, die in einem Integrationsprojekt beschäftigt sind",
      "140": "Seeleute",
      "141": "Auszubildende in der Seefahrt (mit Arbeitsentgelt)",
      "142": "Seeleute in Altersteilzeit",
      "143": "Seelotsen",
      "144": "Auszubildende in der Seefahrt, Arbeitsentgelt bis zur Geringverdienergrenze",
      "149": "In Seefahrt beschäftigte versicherungsfr. Altersvollrentner/Versorgungsbezieher wg. Alters",
      "150": "In Seefahrt beschäftigte versicherungspfl. Altersvollrentner/Versorgungsbezieher wg. Alters",
      "190": "Beschäftigte, die nur in der gesetzlichen Unfallversicherung versichert",
      "900": "Nicht meldepflichtig Beschäftigte"
    }

    DEID4127 = {
      "0": "Erstabrechnung komplett bzw. keine Eingabe",
      "1": "Erstabrechnung 1. Gruppe",
      "2": "Erstabrechnung 2. Gruppe",
      "3": "Vorwegabrechnung, vor Erstabrechnung komplett oder 1. Gruppe",
      "4": "Vorwegabrechnung, vor Erstabrechnung 2. Gruppe"
    }

    DEID4604 = {
      "0": "keine Angabe",
      "1": "Ohne Schulabschluss",
      "2": "Haupt-/Volksschulabschluss",
      "3": "Mittlere Reife oder gleichwertiger Abschluss",
      "4": "Abitur/Fachabitur",
      "9": "Abschluss unbekannt"
    }

    DEID4601 = {
      "0": "keine Angabe",
      "1": "Ohne beruflichen Ausbildungsabschluss",
      "2": "Abschluss einer anerkannten Berufsausbildung",
      "3": "Meister-/Techniker- oder gleichwertiger Fachschulabschluss",
      "4": "Bachelor",
      "5": "Diplom/Magister/Master/Staatsexamen",
      "6": "Promotion",
      "9": "Abschluss unbekannt"
    }

    DEID4602 = {
      "0": "wie Mandantendaten",
      "1": "nein",
      "2": "ja"
    }

    DEID4603 = {
      "0": "keine Angabe",
      "1": "Unbefristet Vollzeit",
      "2": "Unbefristet Teilzeit",
      "3": "Befristet Vollzeit",
      "4": "Befristet Teilzeit"
    }

    DEID4202 = {
      "0": "0",
      "1": "1",
      "2": "2",
      "3": "3",
      "4": "4",
      "5": "5",
      "6": "6",
    }

    DEID4624 = {
      "0": "Konfessionslos / Keine Kirchensteuerberechnung",
      "1": "Evangelische Kirchensteuer",
      "10": "Israelitische Religionsgemeinschaft Baden",
      "11": "Jüdische Kultussteuer",
      "12": "Israelitische Kultussteuer der kultusberechtigten Gemeinden",
      "13": "Israelitische / Jüdische Kultussteuer",
      "14": "Israelitische Religionsgemeinschaft Württembergs",
      "15": "Jüdische Kultussteuer",
      "16": "Jüdische Kultussteuer",
      "17": "Evangelisch lutherisch (bis 12/2015)",
      "18": "Evangelisch reformiert (bis 12/2015)",
      "2": "Römisch-Katholische Kirchensteuer",
      "3": "Altkatholische Kirchensteuer",
      "4": "Freie Religionsgemeinschaft Alzey",
      "5": "Freireligiöse Landesgemeinde Baden",
      "6": "Freireligiöse Landesgemeinde Pfalz",
      "7": "Freireligiöse Gemeinde Mainz",
      "8": "Französisch reformiert (bis 12/2015)",
      "9": "Freireligiöse Gemeinde Offenbach/Main",
    }

    DEID4630 = {
      "0": "keine Angabe",
      "1": "Hauptarbeitgeber",
      "2": "Nebenarbeitgeber"
    }

    DEID4640 = {
      "0": "nein",
      "1": "2 Prozent",
      "2": "20 Prozent"
    }

    DEID4346 = {
      "0": "Übernahme gemäß MPD",
      "1": "Übernahme durch Arbeitnehmer",
      "2": "keine Übernahme durch Arbeitnehmer"
    }

    DEID4689 = {
      "0": "kein Beitrag (private KV oder frw. KV als Selbstzahler)",
      "1": "allgemeiner Beitrag",
      "3": "ermäßigter Beitrag",
      "4": "Beitrag zur landwirtschaftlichen KV",
      "5": "Arbeitgeberbeitrag zur landwirtschaftlichen KV",
      "6": "Pauschalbeitrag für geringfügig Beschäftigte",
      "9": "Firmenzahler"
    }

    DEID4687 = {
      "0": "kein Beitrag",
      "1": "voller Beitrag",
      "3": "halber Beitrag",
      "5": "Pauschalbeitrag für geringfügig Beschäftigte"
    }

    DEID4688 = {
      "0": "kein Beitrag",
      "1": "voller Beitrag",
      "2": "halber Beitrag"
    }

    DEID4690 = {
      "0": "kein Beitrag",
      "1": "voller Beitrag",
      "2": "halber Beitrag"
    }

    DEID4095 = {
      "0": "nicht umlagepflichtig",
      "1": "Umlage 1 und 2",
      "2": "Umlage 2"
    }

    DEID4118 = {
      "0": "Keine Behindertenabrechnung",
      "1": "Behinderte Menschen in geschützten Einrichtungen",
      "2": "Behinderte Menschen in berufsfördernden Einrichtungen"
    }

    DEID4092 = {
      "0": "kein Geringverdiener/-fügigkeit",
      "1": "Geringverdiener",
      "2": "geringf. entlohnter Besch., meldepfl.",
      "3": "kurzfr. Beschäftigter, meldepflichtig"
    }

    DEID4812 = {
      "0": "keine Angabe",
      "1": "gesetzlich krankenversichert",
      "2": "privat krankenversichert",
      "3": "anderweitig im Krankheitsfall abgesichert"
    }

    DEID4491 = {
      "0": "monatlich",
      "1": "wiederkehrend"
    }

    DEID4495 = {
      "1": "Januar",
      "2": "Februar",
      "3": "März",
      "4": "April",
      "5": "Mai",
      "6": "Juni",
      "7": "Juli",
      "8": "August",
      "9": "September",
      "10": "Oktober",
      "11": "November",
      "12": "Dezember"
    }

    DEID4679 = {
      "0": "Teilmonat kürzen/Ausfallmonat kürzen",
      "1": "Teilmonat nicht kürzen/Ausfallmonat nicht kürzen",
      "2": "Teilmonat nicht kürzen/Ausfallmonat kürzen"
    }

    DEID4552 = {
      "0": "Grundstellung",
      "1": "Monatsgrundlohn (max. 1 pro Monat zulässig)",
      "2": "Basis für ML-Berechnung"
    }
