"""
AWS CloudFormation AppRunner Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 227.0.0
  Generator Version: 1.0.0
  Combined: spec-227.0.0_gen-1.0.0
  Generated: 2025-12-15 17:57:10

To regenerate this file:
    uv run python -m cloudformation_dataclasses.codegen.generator --service AppRunner
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


@dataclass
class AutoScalingConfiguration(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appru"""

    resource_type: ClassVar[str] = "AWS::AppRunner::AutoScalingConfiguration"

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    min_size: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    max_concurrency: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    auto_scaling_configuration_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    max_size: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    def _get_properties(self) -> dict[str, Any]:
        """Serialize resource properties to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.min_size is not None:
            # Serialize min_size (handle intrinsic functions)
            if hasattr(self.min_size, 'to_dict'):
                props["MinSize"] = self.min_size.to_dict()
            elif isinstance(self.min_size, list):
                # Serialize list items (may contain intrinsic functions)
                props['MinSize'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.min_size
                ]
            else:
                props["MinSize"] = self.min_size

        if self.max_concurrency is not None:
            # Serialize max_concurrency (handle intrinsic functions)
            if hasattr(self.max_concurrency, 'to_dict'):
                props["MaxConcurrency"] = self.max_concurrency.to_dict()
            elif isinstance(self.max_concurrency, list):
                # Serialize list items (may contain intrinsic functions)
                props['MaxConcurrency'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.max_concurrency
                ]
            else:
                props["MaxConcurrency"] = self.max_concurrency

        if self.auto_scaling_configuration_name is not None:
            # Serialize auto_scaling_configuration_name (handle intrinsic functions)
            if hasattr(self.auto_scaling_configuration_name, 'to_dict'):
                props["AutoScalingConfigurationName"] = self.auto_scaling_configuration_name.to_dict()
            elif isinstance(self.auto_scaling_configuration_name, list):
                # Serialize list items (may contain intrinsic functions)
                props['AutoScalingConfigurationName'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.auto_scaling_configuration_name
                ]
            else:
                props["AutoScalingConfigurationName"] = self.auto_scaling_configuration_name

        if self.max_size is not None:
            # Serialize max_size (handle intrinsic functions)
            if hasattr(self.max_size, 'to_dict'):
                props["MaxSize"] = self.max_size.to_dict()
            elif isinstance(self.max_size, list):
                # Serialize list items (may contain intrinsic functions)
                props['MaxSize'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.max_size
                ]
            else:
                props["MaxSize"] = self.max_size

        # Serialize tags - use all_tags to include context tags
        merged_tags = self.all_tags
        if merged_tags:
            props['Tags'] = [
                item.to_dict() if hasattr(item, 'to_dict') else item
                for item in merged_tags
            ]

        return props

    @property
    def attr_auto_scaling_configuration_revision(self) -> GetAtt:
        """Get the AutoScalingConfigurationRevision attribute."""
        return self.get_att("AutoScalingConfigurationRevision")

    @property
    def attr_auto_scaling_configuration_arn(self) -> GetAtt:
        """Get the AutoScalingConfigurationArn attribute."""
        return self.get_att("AutoScalingConfigurationArn")

    @property
    def attr_latest(self) -> GetAtt:
        """Get the Latest attribute."""
        return self.get_att("Latest")




@dataclass
class TraceConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    vendor: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.vendor is not None:
            if hasattr(self.vendor, 'to_dict'):
                props['Vendor'] = self.vendor.to_dict()
            elif isinstance(self.vendor, list):
                props['Vendor'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.vendor
                ]
            else:
                props['Vendor'] = self.vendor

        return props


@dataclass
class ObservabilityConfiguration(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appru"""

    resource_type: ClassVar[str] = "AWS::AppRunner::ObservabilityConfiguration"

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    trace_configuration: Optional[TraceConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    observability_configuration_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    def _get_properties(self) -> dict[str, Any]:
        """Serialize resource properties to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.trace_configuration is not None:
            # Serialize trace_configuration (handle intrinsic functions)
            if hasattr(self.trace_configuration, 'to_dict'):
                props["TraceConfiguration"] = self.trace_configuration.to_dict()
            elif isinstance(self.trace_configuration, list):
                # Serialize list items (may contain intrinsic functions)
                props['TraceConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.trace_configuration
                ]
            else:
                props["TraceConfiguration"] = self.trace_configuration

        if self.observability_configuration_name is not None:
            # Serialize observability_configuration_name (handle intrinsic functions)
            if hasattr(self.observability_configuration_name, 'to_dict'):
                props["ObservabilityConfigurationName"] = self.observability_configuration_name.to_dict()
            elif isinstance(self.observability_configuration_name, list):
                # Serialize list items (may contain intrinsic functions)
                props['ObservabilityConfigurationName'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.observability_configuration_name
                ]
            else:
                props["ObservabilityConfigurationName"] = self.observability_configuration_name

        # Serialize tags - use all_tags to include context tags
        merged_tags = self.all_tags
        if merged_tags:
            props['Tags'] = [
                item.to_dict() if hasattr(item, 'to_dict') else item
                for item in merged_tags
            ]

        return props

    @property
    def attr_observability_configuration_revision(self) -> GetAtt:
        """Get the ObservabilityConfigurationRevision attribute."""
        return self.get_att("ObservabilityConfigurationRevision")

    @property
    def attr_observability_configuration_arn(self) -> GetAtt:
        """Get the ObservabilityConfigurationArn attribute."""
        return self.get_att("ObservabilityConfigurationArn")

    @property
    def attr_latest(self) -> GetAtt:
        """Get the Latest attribute."""
        return self.get_att("Latest")




@dataclass
class AuthenticationConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    access_role_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    connection_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.access_role_arn is not None:
            if hasattr(self.access_role_arn, 'to_dict'):
                props['AccessRoleArn'] = self.access_role_arn.to_dict()
            elif isinstance(self.access_role_arn, list):
                props['AccessRoleArn'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.access_role_arn
                ]
            else:
                props['AccessRoleArn'] = self.access_role_arn

        if self.connection_arn is not None:
            if hasattr(self.connection_arn, 'to_dict'):
                props['ConnectionArn'] = self.connection_arn.to_dict()
            elif isinstance(self.connection_arn, list):
                props['ConnectionArn'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.connection_arn
                ]
            else:
                props['ConnectionArn'] = self.connection_arn

        return props


@dataclass
class CodeConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    configuration_source: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    code_configuration_values: Optional[CodeConfigurationValues] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.configuration_source is not None:
            if hasattr(self.configuration_source, 'to_dict'):
                props['ConfigurationSource'] = self.configuration_source.to_dict()
            elif isinstance(self.configuration_source, list):
                props['ConfigurationSource'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.configuration_source
                ]
            else:
                props['ConfigurationSource'] = self.configuration_source

        if self.code_configuration_values is not None:
            if hasattr(self.code_configuration_values, 'to_dict'):
                props['CodeConfigurationValues'] = self.code_configuration_values.to_dict()
            elif isinstance(self.code_configuration_values, list):
                props['CodeConfigurationValues'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.code_configuration_values
                ]
            else:
                props['CodeConfigurationValues'] = self.code_configuration_values

        return props


@dataclass
class CodeConfigurationValues:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    runtime_environment_secrets: Optional[list[KeyValuePair]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    runtime: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    start_command: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    runtime_environment_variables: Optional[list[KeyValuePair]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    build_command: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.runtime_environment_secrets is not None:
            if hasattr(self.runtime_environment_secrets, 'to_dict'):
                props['RuntimeEnvironmentSecrets'] = self.runtime_environment_secrets.to_dict()
            elif isinstance(self.runtime_environment_secrets, list):
                props['RuntimeEnvironmentSecrets'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.runtime_environment_secrets
                ]
            else:
                props['RuntimeEnvironmentSecrets'] = self.runtime_environment_secrets

        if self.runtime is not None:
            if hasattr(self.runtime, 'to_dict'):
                props['Runtime'] = self.runtime.to_dict()
            elif isinstance(self.runtime, list):
                props['Runtime'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.runtime
                ]
            else:
                props['Runtime'] = self.runtime

        if self.start_command is not None:
            if hasattr(self.start_command, 'to_dict'):
                props['StartCommand'] = self.start_command.to_dict()
            elif isinstance(self.start_command, list):
                props['StartCommand'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.start_command
                ]
            else:
                props['StartCommand'] = self.start_command

        if self.runtime_environment_variables is not None:
            if hasattr(self.runtime_environment_variables, 'to_dict'):
                props['RuntimeEnvironmentVariables'] = self.runtime_environment_variables.to_dict()
            elif isinstance(self.runtime_environment_variables, list):
                props['RuntimeEnvironmentVariables'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.runtime_environment_variables
                ]
            else:
                props['RuntimeEnvironmentVariables'] = self.runtime_environment_variables

        if self.port is not None:
            if hasattr(self.port, 'to_dict'):
                props['Port'] = self.port.to_dict()
            elif isinstance(self.port, list):
                props['Port'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.port
                ]
            else:
                props['Port'] = self.port

        if self.build_command is not None:
            if hasattr(self.build_command, 'to_dict'):
                props['BuildCommand'] = self.build_command.to_dict()
            elif isinstance(self.build_command, list):
                props['BuildCommand'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.build_command
                ]
            else:
                props['BuildCommand'] = self.build_command

        return props


@dataclass
class CodeRepository:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    source_code_version: Optional[SourceCodeVersion] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    code_configuration: Optional[CodeConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    source_directory: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    repository_url: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.source_code_version is not None:
            if hasattr(self.source_code_version, 'to_dict'):
                props['SourceCodeVersion'] = self.source_code_version.to_dict()
            elif isinstance(self.source_code_version, list):
                props['SourceCodeVersion'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.source_code_version
                ]
            else:
                props['SourceCodeVersion'] = self.source_code_version

        if self.code_configuration is not None:
            if hasattr(self.code_configuration, 'to_dict'):
                props['CodeConfiguration'] = self.code_configuration.to_dict()
            elif isinstance(self.code_configuration, list):
                props['CodeConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.code_configuration
                ]
            else:
                props['CodeConfiguration'] = self.code_configuration

        if self.source_directory is not None:
            if hasattr(self.source_directory, 'to_dict'):
                props['SourceDirectory'] = self.source_directory.to_dict()
            elif isinstance(self.source_directory, list):
                props['SourceDirectory'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.source_directory
                ]
            else:
                props['SourceDirectory'] = self.source_directory

        if self.repository_url is not None:
            if hasattr(self.repository_url, 'to_dict'):
                props['RepositoryUrl'] = self.repository_url.to_dict()
            elif isinstance(self.repository_url, list):
                props['RepositoryUrl'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.repository_url
                ]
            else:
                props['RepositoryUrl'] = self.repository_url

        return props


@dataclass
class EgressConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    vpc_connector_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    egress_type: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.vpc_connector_arn is not None:
            if hasattr(self.vpc_connector_arn, 'to_dict'):
                props['VpcConnectorArn'] = self.vpc_connector_arn.to_dict()
            elif isinstance(self.vpc_connector_arn, list):
                props['VpcConnectorArn'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.vpc_connector_arn
                ]
            else:
                props['VpcConnectorArn'] = self.vpc_connector_arn

        if self.egress_type is not None:
            if hasattr(self.egress_type, 'to_dict'):
                props['EgressType'] = self.egress_type.to_dict()
            elif isinstance(self.egress_type, list):
                props['EgressType'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.egress_type
                ]
            else:
                props['EgressType'] = self.egress_type

        return props


@dataclass
class EncryptionConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    kms_key: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.kms_key is not None:
            if hasattr(self.kms_key, 'to_dict'):
                props['KmsKey'] = self.kms_key.to_dict()
            elif isinstance(self.kms_key, list):
                props['KmsKey'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.kms_key
                ]
            else:
                props['KmsKey'] = self.kms_key

        return props


@dataclass
class HealthCheckConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    path: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    unhealthy_threshold: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    timeout: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    healthy_threshold: Optional[Union[int, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    protocol: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    interval: Optional[Union[int, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.path is not None:
            if hasattr(self.path, 'to_dict'):
                props['Path'] = self.path.to_dict()
            elif isinstance(self.path, list):
                props['Path'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.path
                ]
            else:
                props['Path'] = self.path

        if self.unhealthy_threshold is not None:
            if hasattr(self.unhealthy_threshold, 'to_dict'):
                props['UnhealthyThreshold'] = self.unhealthy_threshold.to_dict()
            elif isinstance(self.unhealthy_threshold, list):
                props['UnhealthyThreshold'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.unhealthy_threshold
                ]
            else:
                props['UnhealthyThreshold'] = self.unhealthy_threshold

        if self.timeout is not None:
            if hasattr(self.timeout, 'to_dict'):
                props['Timeout'] = self.timeout.to_dict()
            elif isinstance(self.timeout, list):
                props['Timeout'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.timeout
                ]
            else:
                props['Timeout'] = self.timeout

        if self.healthy_threshold is not None:
            if hasattr(self.healthy_threshold, 'to_dict'):
                props['HealthyThreshold'] = self.healthy_threshold.to_dict()
            elif isinstance(self.healthy_threshold, list):
                props['HealthyThreshold'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.healthy_threshold
                ]
            else:
                props['HealthyThreshold'] = self.healthy_threshold

        if self.protocol is not None:
            if hasattr(self.protocol, 'to_dict'):
                props['Protocol'] = self.protocol.to_dict()
            elif isinstance(self.protocol, list):
                props['Protocol'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.protocol
                ]
            else:
                props['Protocol'] = self.protocol

        if self.interval is not None:
            if hasattr(self.interval, 'to_dict'):
                props['Interval'] = self.interval.to_dict()
            elif isinstance(self.interval, list):
                props['Interval'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.interval
                ]
            else:
                props['Interval'] = self.interval

        return props


@dataclass
class ImageConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    runtime_environment_secrets: Optional[list[KeyValuePair]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    start_command: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    runtime_environment_variables: Optional[list[KeyValuePair]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    port: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.runtime_environment_secrets is not None:
            if hasattr(self.runtime_environment_secrets, 'to_dict'):
                props['RuntimeEnvironmentSecrets'] = self.runtime_environment_secrets.to_dict()
            elif isinstance(self.runtime_environment_secrets, list):
                props['RuntimeEnvironmentSecrets'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.runtime_environment_secrets
                ]
            else:
                props['RuntimeEnvironmentSecrets'] = self.runtime_environment_secrets

        if self.start_command is not None:
            if hasattr(self.start_command, 'to_dict'):
                props['StartCommand'] = self.start_command.to_dict()
            elif isinstance(self.start_command, list):
                props['StartCommand'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.start_command
                ]
            else:
                props['StartCommand'] = self.start_command

        if self.runtime_environment_variables is not None:
            if hasattr(self.runtime_environment_variables, 'to_dict'):
                props['RuntimeEnvironmentVariables'] = self.runtime_environment_variables.to_dict()
            elif isinstance(self.runtime_environment_variables, list):
                props['RuntimeEnvironmentVariables'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.runtime_environment_variables
                ]
            else:
                props['RuntimeEnvironmentVariables'] = self.runtime_environment_variables

        if self.port is not None:
            if hasattr(self.port, 'to_dict'):
                props['Port'] = self.port.to_dict()
            elif isinstance(self.port, list):
                props['Port'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.port
                ]
            else:
                props['Port'] = self.port

        return props


@dataclass
class ImageRepository:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    image_identifier: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    image_configuration: Optional[ImageConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    image_repository_type: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.image_identifier is not None:
            if hasattr(self.image_identifier, 'to_dict'):
                props['ImageIdentifier'] = self.image_identifier.to_dict()
            elif isinstance(self.image_identifier, list):
                props['ImageIdentifier'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.image_identifier
                ]
            else:
                props['ImageIdentifier'] = self.image_identifier

        if self.image_configuration is not None:
            if hasattr(self.image_configuration, 'to_dict'):
                props['ImageConfiguration'] = self.image_configuration.to_dict()
            elif isinstance(self.image_configuration, list):
                props['ImageConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.image_configuration
                ]
            else:
                props['ImageConfiguration'] = self.image_configuration

        if self.image_repository_type is not None:
            if hasattr(self.image_repository_type, 'to_dict'):
                props['ImageRepositoryType'] = self.image_repository_type.to_dict()
            elif isinstance(self.image_repository_type, list):
                props['ImageRepositoryType'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.image_repository_type
                ]
            else:
                props['ImageRepositoryType'] = self.image_repository_type

        return props


@dataclass
class IngressConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    is_publicly_accessible: Optional[Union[bool, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.is_publicly_accessible is not None:
            if hasattr(self.is_publicly_accessible, 'to_dict'):
                props['IsPubliclyAccessible'] = self.is_publicly_accessible.to_dict()
            elif isinstance(self.is_publicly_accessible, list):
                props['IsPubliclyAccessible'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.is_publicly_accessible
                ]
            else:
                props['IsPubliclyAccessible'] = self.is_publicly_accessible

        return props


@dataclass
class InstanceConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    instance_role_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    memory: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    cpu: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.instance_role_arn is not None:
            if hasattr(self.instance_role_arn, 'to_dict'):
                props['InstanceRoleArn'] = self.instance_role_arn.to_dict()
            elif isinstance(self.instance_role_arn, list):
                props['InstanceRoleArn'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.instance_role_arn
                ]
            else:
                props['InstanceRoleArn'] = self.instance_role_arn

        if self.memory is not None:
            if hasattr(self.memory, 'to_dict'):
                props['Memory'] = self.memory.to_dict()
            elif isinstance(self.memory, list):
                props['Memory'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.memory
                ]
            else:
                props['Memory'] = self.memory

        if self.cpu is not None:
            if hasattr(self.cpu, 'to_dict'):
                props['Cpu'] = self.cpu.to_dict()
            elif isinstance(self.cpu, list):
                props['Cpu'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.cpu
                ]
            else:
                props['Cpu'] = self.cpu

        return props


@dataclass
class KeyValuePair:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    value: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    name: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.value is not None:
            if hasattr(self.value, 'to_dict'):
                props['Value'] = self.value.to_dict()
            elif isinstance(self.value, list):
                props['Value'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.value
                ]
            else:
                props['Value'] = self.value

        if self.name is not None:
            if hasattr(self.name, 'to_dict'):
                props['Name'] = self.name.to_dict()
            elif isinstance(self.name, list):
                props['Name'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.name
                ]
            else:
                props['Name'] = self.name

        return props


@dataclass
class NetworkConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    ip_address_type: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    egress_configuration: Optional[EgressConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    ingress_configuration: Optional[IngressConfiguration] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.ip_address_type is not None:
            if hasattr(self.ip_address_type, 'to_dict'):
                props['IpAddressType'] = self.ip_address_type.to_dict()
            elif isinstance(self.ip_address_type, list):
                props['IpAddressType'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.ip_address_type
                ]
            else:
                props['IpAddressType'] = self.ip_address_type

        if self.egress_configuration is not None:
            if hasattr(self.egress_configuration, 'to_dict'):
                props['EgressConfiguration'] = self.egress_configuration.to_dict()
            elif isinstance(self.egress_configuration, list):
                props['EgressConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.egress_configuration
                ]
            else:
                props['EgressConfiguration'] = self.egress_configuration

        if self.ingress_configuration is not None:
            if hasattr(self.ingress_configuration, 'to_dict'):
                props['IngressConfiguration'] = self.ingress_configuration.to_dict()
            elif isinstance(self.ingress_configuration, list):
                props['IngressConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.ingress_configuration
                ]
            else:
                props['IngressConfiguration'] = self.ingress_configuration

        return props


@dataclass
class ServiceObservabilityConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    observability_enabled: Optional[Union[bool, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    observability_configuration_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.observability_enabled is not None:
            if hasattr(self.observability_enabled, 'to_dict'):
                props['ObservabilityEnabled'] = self.observability_enabled.to_dict()
            elif isinstance(self.observability_enabled, list):
                props['ObservabilityEnabled'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.observability_enabled
                ]
            else:
                props['ObservabilityEnabled'] = self.observability_enabled

        if self.observability_configuration_arn is not None:
            if hasattr(self.observability_configuration_arn, 'to_dict'):
                props['ObservabilityConfigurationArn'] = self.observability_configuration_arn.to_dict()
            elif isinstance(self.observability_configuration_arn, list):
                props['ObservabilityConfigurationArn'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.observability_configuration_arn
                ]
            else:
                props['ObservabilityConfigurationArn'] = self.observability_configuration_arn

        return props


@dataclass
class SourceCodeVersion:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    type_: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    value: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.type_ is not None:
            if hasattr(self.type_, 'to_dict'):
                props['Type'] = self.type_.to_dict()
            elif isinstance(self.type_, list):
                props['Type'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.type_
                ]
            else:
                props['Type'] = self.type_

        if self.value is not None:
            if hasattr(self.value, 'to_dict'):
                props['Value'] = self.value.to_dict()
            elif isinstance(self.value, list):
                props['Value'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.value
                ]
            else:
                props['Value'] = self.value

        return props


@dataclass
class SourceConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    authentication_configuration: Optional[AuthenticationConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    code_repository: Optional[CodeRepository] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    image_repository: Optional[ImageRepository] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    auto_deployments_enabled: Optional[Union[bool, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.authentication_configuration is not None:
            if hasattr(self.authentication_configuration, 'to_dict'):
                props['AuthenticationConfiguration'] = self.authentication_configuration.to_dict()
            elif isinstance(self.authentication_configuration, list):
                props['AuthenticationConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.authentication_configuration
                ]
            else:
                props['AuthenticationConfiguration'] = self.authentication_configuration

        if self.code_repository is not None:
            if hasattr(self.code_repository, 'to_dict'):
                props['CodeRepository'] = self.code_repository.to_dict()
            elif isinstance(self.code_repository, list):
                props['CodeRepository'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.code_repository
                ]
            else:
                props['CodeRepository'] = self.code_repository

        if self.image_repository is not None:
            if hasattr(self.image_repository, 'to_dict'):
                props['ImageRepository'] = self.image_repository.to_dict()
            elif isinstance(self.image_repository, list):
                props['ImageRepository'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.image_repository
                ]
            else:
                props['ImageRepository'] = self.image_repository

        if self.auto_deployments_enabled is not None:
            if hasattr(self.auto_deployments_enabled, 'to_dict'):
                props['AutoDeploymentsEnabled'] = self.auto_deployments_enabled.to_dict()
            elif isinstance(self.auto_deployments_enabled, list):
                props['AutoDeploymentsEnabled'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.auto_deployments_enabled
                ]
            else:
                props['AutoDeploymentsEnabled'] = self.auto_deployments_enabled

        return props


@dataclass
class Service(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appru"""

    resource_type: ClassVar[str] = "AWS::AppRunner::Service"

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    health_check_configuration: Optional[HealthCheckConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    instance_configuration: Optional[InstanceConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    encryption_configuration: Optional[EncryptionConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    service_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    observability_configuration: Optional[ServiceObservabilityConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    source_configuration: Optional[SourceConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    auto_scaling_configuration_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    network_configuration: Optional[NetworkConfiguration] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    def _get_properties(self) -> dict[str, Any]:
        """Serialize resource properties to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.health_check_configuration is not None:
            # Serialize health_check_configuration (handle intrinsic functions)
            if hasattr(self.health_check_configuration, 'to_dict'):
                props["HealthCheckConfiguration"] = self.health_check_configuration.to_dict()
            elif isinstance(self.health_check_configuration, list):
                # Serialize list items (may contain intrinsic functions)
                props['HealthCheckConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.health_check_configuration
                ]
            else:
                props["HealthCheckConfiguration"] = self.health_check_configuration

        if self.instance_configuration is not None:
            # Serialize instance_configuration (handle intrinsic functions)
            if hasattr(self.instance_configuration, 'to_dict'):
                props["InstanceConfiguration"] = self.instance_configuration.to_dict()
            elif isinstance(self.instance_configuration, list):
                # Serialize list items (may contain intrinsic functions)
                props['InstanceConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.instance_configuration
                ]
            else:
                props["InstanceConfiguration"] = self.instance_configuration

        if self.encryption_configuration is not None:
            # Serialize encryption_configuration (handle intrinsic functions)
            if hasattr(self.encryption_configuration, 'to_dict'):
                props["EncryptionConfiguration"] = self.encryption_configuration.to_dict()
            elif isinstance(self.encryption_configuration, list):
                # Serialize list items (may contain intrinsic functions)
                props['EncryptionConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.encryption_configuration
                ]
            else:
                props["EncryptionConfiguration"] = self.encryption_configuration

        if self.service_name is not None:
            # Serialize service_name (handle intrinsic functions)
            if hasattr(self.service_name, 'to_dict'):
                props["ServiceName"] = self.service_name.to_dict()
            elif isinstance(self.service_name, list):
                # Serialize list items (may contain intrinsic functions)
                props['ServiceName'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.service_name
                ]
            else:
                props["ServiceName"] = self.service_name

        if self.observability_configuration is not None:
            # Serialize observability_configuration (handle intrinsic functions)
            if hasattr(self.observability_configuration, 'to_dict'):
                props["ObservabilityConfiguration"] = self.observability_configuration.to_dict()
            elif isinstance(self.observability_configuration, list):
                # Serialize list items (may contain intrinsic functions)
                props['ObservabilityConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.observability_configuration
                ]
            else:
                props["ObservabilityConfiguration"] = self.observability_configuration

        if self.source_configuration is not None:
            # Serialize source_configuration (handle intrinsic functions)
            if hasattr(self.source_configuration, 'to_dict'):
                props["SourceConfiguration"] = self.source_configuration.to_dict()
            elif isinstance(self.source_configuration, list):
                # Serialize list items (may contain intrinsic functions)
                props['SourceConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.source_configuration
                ]
            else:
                props["SourceConfiguration"] = self.source_configuration

        if self.auto_scaling_configuration_arn is not None:
            # Serialize auto_scaling_configuration_arn (handle intrinsic functions)
            if hasattr(self.auto_scaling_configuration_arn, 'to_dict'):
                props["AutoScalingConfigurationArn"] = self.auto_scaling_configuration_arn.to_dict()
            elif isinstance(self.auto_scaling_configuration_arn, list):
                # Serialize list items (may contain intrinsic functions)
                props['AutoScalingConfigurationArn'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.auto_scaling_configuration_arn
                ]
            else:
                props["AutoScalingConfigurationArn"] = self.auto_scaling_configuration_arn

        if self.network_configuration is not None:
            # Serialize network_configuration (handle intrinsic functions)
            if hasattr(self.network_configuration, 'to_dict'):
                props["NetworkConfiguration"] = self.network_configuration.to_dict()
            elif isinstance(self.network_configuration, list):
                # Serialize list items (may contain intrinsic functions)
                props['NetworkConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.network_configuration
                ]
            else:
                props["NetworkConfiguration"] = self.network_configuration

        # Serialize tags - use all_tags to include context tags
        merged_tags = self.all_tags
        if merged_tags:
            props['Tags'] = [
                item.to_dict() if hasattr(item, 'to_dict') else item
                for item in merged_tags
            ]

        return props

    @property
    def attr_status(self) -> GetAtt:
        """Get the Status attribute."""
        return self.get_att("Status")

    @property
    def attr_service_url(self) -> GetAtt:
        """Get the ServiceUrl attribute."""
        return self.get_att("ServiceUrl")

    @property
    def attr_service_arn(self) -> GetAtt:
        """Get the ServiceArn attribute."""
        return self.get_att("ServiceArn")

    @property
    def attr_service_id(self) -> GetAtt:
        """Get the ServiceId attribute."""
        return self.get_att("ServiceId")




@dataclass
class VpcConnector(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appru"""

    resource_type: ClassVar[str] = "AWS::AppRunner::VpcConnector"

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    security_groups: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    subnets: Optional[Union[list[str], Ref]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    vpc_connector_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None

    def _get_properties(self) -> dict[str, Any]:
        """Serialize resource properties to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.security_groups is not None:
            # Serialize security_groups (handle intrinsic functions)
            if hasattr(self.security_groups, 'to_dict'):
                props["SecurityGroups"] = self.security_groups.to_dict()
            elif isinstance(self.security_groups, list):
                # Serialize list items (may contain intrinsic functions)
                props['SecurityGroups'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.security_groups
                ]
            else:
                props["SecurityGroups"] = self.security_groups

        if self.subnets is not None:
            # Serialize subnets (handle intrinsic functions)
            if hasattr(self.subnets, 'to_dict'):
                props["Subnets"] = self.subnets.to_dict()
            elif isinstance(self.subnets, list):
                # Serialize list items (may contain intrinsic functions)
                props['Subnets'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.subnets
                ]
            else:
                props["Subnets"] = self.subnets

        if self.vpc_connector_name is not None:
            # Serialize vpc_connector_name (handle intrinsic functions)
            if hasattr(self.vpc_connector_name, 'to_dict'):
                props["VpcConnectorName"] = self.vpc_connector_name.to_dict()
            elif isinstance(self.vpc_connector_name, list):
                # Serialize list items (may contain intrinsic functions)
                props['VpcConnectorName'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.vpc_connector_name
                ]
            else:
                props["VpcConnectorName"] = self.vpc_connector_name

        # Serialize tags - use all_tags to include context tags
        merged_tags = self.all_tags
        if merged_tags:
            props['Tags'] = [
                item.to_dict() if hasattr(item, 'to_dict') else item
                for item in merged_tags
            ]

        return props

    @property
    def attr_vpc_connector_arn(self) -> GetAtt:
        """Get the VpcConnectorArn attribute."""
        return self.get_att("VpcConnectorArn")

    @property
    def attr_vpc_connector_revision(self) -> GetAtt:
        """Get the VpcConnectorRevision attribute."""
        return self.get_att("VpcConnectorRevision")




@dataclass
class IngressVpcConfiguration:
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-app"""

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    vpc_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuid
    vpc_endpoint_id: Optional[Union[str, Ref, GetAtt, Sub]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.vpc_id is not None:
            if hasattr(self.vpc_id, 'to_dict'):
                props['VpcId'] = self.vpc_id.to_dict()
            elif isinstance(self.vpc_id, list):
                props['VpcId'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.vpc_id
                ]
            else:
                props['VpcId'] = self.vpc_id

        if self.vpc_endpoint_id is not None:
            if hasattr(self.vpc_endpoint_id, 'to_dict'):
                props['VpcEndpointId'] = self.vpc_endpoint_id.to_dict()
            elif isinstance(self.vpc_endpoint_id, list):
                props['VpcEndpointId'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.vpc_endpoint_id
                ]
            else:
                props['VpcEndpointId'] = self.vpc_endpoint_id

        return props


@dataclass
class VpcIngressConnection(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appru"""

    resource_type: ClassVar[str] = "AWS::AppRunner::VpcIngressConnection"

    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    vpc_ingress_connection_name: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    service_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    tags: Optional[list[Tag]] = None
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-reso
    ingress_vpc_configuration: Optional[IngressVpcConfiguration] = None

    def _get_properties(self) -> dict[str, Any]:
        """Serialize resource properties to CloudFormation format."""
        props: dict[str, Any] = {}

        if self.vpc_ingress_connection_name is not None:
            # Serialize vpc_ingress_connection_name (handle intrinsic functions)
            if hasattr(self.vpc_ingress_connection_name, 'to_dict'):
                props["VpcIngressConnectionName"] = self.vpc_ingress_connection_name.to_dict()
            elif isinstance(self.vpc_ingress_connection_name, list):
                # Serialize list items (may contain intrinsic functions)
                props['VpcIngressConnectionName'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.vpc_ingress_connection_name
                ]
            else:
                props["VpcIngressConnectionName"] = self.vpc_ingress_connection_name

        if self.service_arn is not None:
            # Serialize service_arn (handle intrinsic functions)
            if hasattr(self.service_arn, 'to_dict'):
                props["ServiceArn"] = self.service_arn.to_dict()
            elif isinstance(self.service_arn, list):
                # Serialize list items (may contain intrinsic functions)
                props['ServiceArn'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.service_arn
                ]
            else:
                props["ServiceArn"] = self.service_arn

        # Serialize tags - use all_tags to include context tags
        merged_tags = self.all_tags
        if merged_tags:
            props['Tags'] = [
                item.to_dict() if hasattr(item, 'to_dict') else item
                for item in merged_tags
            ]

        if self.ingress_vpc_configuration is not None:
            # Serialize ingress_vpc_configuration (handle intrinsic functions)
            if hasattr(self.ingress_vpc_configuration, 'to_dict'):
                props["IngressVpcConfiguration"] = self.ingress_vpc_configuration.to_dict()
            elif isinstance(self.ingress_vpc_configuration, list):
                # Serialize list items (may contain intrinsic functions)
                props['IngressVpcConfiguration'] = [
                    item.to_dict() if hasattr(item, 'to_dict') else item
                    for item in self.ingress_vpc_configuration
                ]
            else:
                props["IngressVpcConfiguration"] = self.ingress_vpc_configuration

        return props

    @property
    def attr_status(self) -> GetAtt:
        """Get the Status attribute."""
        return self.get_att("Status")

    @property
    def attr_domain_name(self) -> GetAtt:
        """Get the DomainName attribute."""
        return self.get_att("DomainName")

    @property
    def attr_vpc_ingress_connection_arn(self) -> GetAtt:
        """Get the VpcIngressConnectionArn attribute."""
        return self.get_att("VpcIngressConnectionArn")



