# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .configurable_prop_base import ConfigurablePropBase
from .configurable_prop_sql_auth import ConfigurablePropSqlAuth
from .configurable_prop_sql_options_item import ConfigurablePropSqlOptionsItem
from .configured_prop_value_sql import ConfiguredPropValueSql


class ConfigurablePropSql(ConfigurablePropBase):
    auth: typing.Optional[ConfigurablePropSqlAuth] = None
    default: typing.Optional[ConfiguredPropValueSql] = None
    options: typing.Optional[typing.List[ConfigurablePropSqlOptionsItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
