# This file was auto-generated by Fern from our API Definition.

import typing

from .configured_prop_value_any import ConfiguredPropValueAny
from .configured_prop_value_app import ConfiguredPropValueApp
from .configured_prop_value_boolean import ConfiguredPropValueBoolean
from .configured_prop_value_integer import ConfiguredPropValueInteger
from .configured_prop_value_object import ConfiguredPropValueObject
from .configured_prop_value_sql import ConfiguredPropValueSql
from .configured_prop_value_string import ConfiguredPropValueString
from .configured_prop_value_string_array import ConfiguredPropValueStringArray

ConfiguredPropValue = typing.Union[
    ConfiguredPropValueAny,
    ConfiguredPropValueApp,
    ConfiguredPropValueBoolean,
    ConfiguredPropValueInteger,
    ConfiguredPropValueObject,
    ConfiguredPropValueSql,
    ConfiguredPropValueString,
    ConfiguredPropValueStringArray,
]
