from enum import StrEnum


class ActivityThemeType(StrEnum):
    NONE = "NONE"
    ACTIVITY = "ACTIVITY"
    CRISIS = "CRISIS"
    MAINLINE = "MAINLINE"
    ROGUELIKE = "ROGUELIKE"
    CRISISV2 = "CRISISV2"
    SANDBOX_PERM = "SANDBOX_PERM"
    ACTIVITY_COMP = "ACTIVITY_COMP"
