from enum import StrEnum


class EnemyDuelBetStrategy(StrEnum):
    DEFAULT = "DEFAULT"
    CHOOSE_WIN = "CHOOSE_WIN"
    CHOOSE_ODD = "CHOOSE_ODD"
    FOLLOW_FEWER = "FOLLOW_FEWER"
    FOLLOW_MORE = "FOLLOW_MORE"
    CHOOSE_ODD_ENEMY_COUNT = "CHOOSE_ODD_ENEMY_COUNT"
    CHOOSE_EVEN_ENEMY_COUNT = "CHOOSE_EVEN_ENEMY_COUNT"
    ALWAYS_LEFT = "ALWAYS_LEFT"
