from enum import StrEnum


class RoguelikeGameShopDialogType(StrEnum):
    NONE = "NONE"
    MAIN = "MAIN"
    RELIC = "RELIC"
    RECRUIT_TICKET = "RECRUIT_TICKET"
    ACTIVE_TOOL = "ACTIVE_TOOL"
    BANK_ENTRY = "BANK_ENTRY"
    BANK_INVEST = "BANK_INVEST"
    BANK_WITHDRAWAL = "BANK_WITHDRAWAL"
    BANK_FAULTY = "BANK_FAULTY"
    BANK_REWARD_UNLOCK = "BANK_REWARD_UNLOCK"
    OUTER_NORMAL = "OUTER_NORMAL"
    OUTER_REWARD = "OUTER_REWARD"
    FIGHT_BOSS = "FIGHT_BOSS"
    TOTEM = "TOTEM"
    VISION = "VISION"
