from enum import StrEnum


class StageDropType(StrEnum):
    NONE = "NONE"
    ONCE = "ONCE"
    NORMAL = "NORMAL"
    SPECIAL = "SPECIAL"
    ADDITIONAL = "ADDITIONAL"
    APRETURN = "APRETURN"
    DIAMOND_MATERIAL = "DIAMOND_MATERIAL"
    FUNITURE_DROP = "FUNITURE_DROP"
    COMPLETE = "COMPLETE"
    CHARM_DROP = "CHARM_DROP"
    OVERRIDE_DROP = "OVERRIDE_DROP"
    ITEM_RETURN = "ITEM_RETURN"
    CONDITION_DROP = "CONDITION_DROP"
