from .platform_adapter import PlatformAdapter as PlatformAdapter
from _typeshed import Incomplete
from typing import Any

class ConfigManager:
    config_file: Incomplete
    def __init__(self, config_file: str | None = None) -> None: ...
    def get(self, key: str, default: Any = None, auto_reload: bool = True) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def get_all(self, auto_reload: bool = True) -> dict[str, Any]: ...
    def reload(self) -> None: ...
    def hot_reload(self) -> bool: ...

def get_config_manager() -> ConfigManager: ...
def get_config(key: str, default: Any = None) -> Any: ...
def reload_config() -> bool: ...
