# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindowUI.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QToolBar, QWidget)

class Ui_SasView(object):
    def setupUi(self, SasView):
        if not SasView.objectName():
            SasView.setObjectName(u"SasView")
        SasView.resize(915, 607)
        icon = QIcon()
        icon.addFile(u":/res/ball.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        SasView.setWindowIcon(icon)
        self.actionReset = QAction(SasView)
        self.actionReset.setObjectName(u"actionReset")
        icon1 = QIcon()
        icon1.addFile(u":/res/reset.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionReset.setIcon(icon1)
        self.actionSave = QAction(SasView)
        self.actionSave.setObjectName(u"actionSave")
        icon2 = QIcon()
        icon2.addFile(u":/res/save.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave.setIcon(icon2)
        self.actionReport = QAction(SasView)
        self.actionReport.setObjectName(u"actionReport")
        icon3 = QIcon()
        icon3.addFile(u":/res/report.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionReport.setIcon(icon3)
        self.actionUndo = QAction(SasView)
        self.actionUndo.setObjectName(u"actionUndo")
        icon4 = QIcon()
        icon4.addFile(u":/res/undo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon4.addFile(u"res/undo.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionUndo.setIcon(icon4)
        self.actionRedo = QAction(SasView)
        self.actionRedo.setObjectName(u"actionRedo")
        icon5 = QIcon()
        icon5.addFile(u":/res/redo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRedo.setIcon(icon5)
        self.actionCopy = QAction(SasView)
        self.actionCopy.setObjectName(u"actionCopy")
        icon6 = QIcon()
        icon6.addFile(u":/res/copy.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCopy.setIcon(icon6)
        self.actionPaste = QAction(SasView)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionPaste.setEnabled(True)
        icon7 = QIcon()
        icon7.addFile(u":/res/paste.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPaste.setIcon(icon7)
        self.actionSaveParamsAs = QAction(SasView)
        self.actionSaveParamsAs.setObjectName(u"actionSaveParamsAs")
        self.actionPerspective = QAction(SasView)
        self.actionPerspective.setObjectName(u"actionPerspective")
        self.actionLoadData = QAction(SasView)
        self.actionLoadData.setObjectName(u"actionLoadData")
        self.actionLoad_Data_Folder = QAction(SasView)
        self.actionLoad_Data_Folder.setObjectName(u"actionLoad_Data_Folder")
        self.actionOpen_Project = QAction(SasView)
        self.actionOpen_Project.setObjectName(u"actionOpen_Project")
        self.actionOpen_Analysis = QAction(SasView)
        self.actionOpen_Analysis.setObjectName(u"actionOpen_Analysis")
        self.actionSave_Analysis = QAction(SasView)
        self.actionSave_Analysis.setObjectName(u"actionSave_Analysis")
        self.actionQuit = QAction(SasView)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionHide_Toolbar = QAction(SasView)
        self.actionHide_Toolbar.setObjectName(u"actionHide_Toolbar")
        self.actionStartup_Settings = QAction(SasView)
        self.actionStartup_Settings.setObjectName(u"actionStartup_Settings")
        self.actionData_Operation = QAction(SasView)
        self.actionData_Operation.setObjectName(u"actionData_Operation")
        self.actionSLD_Calculator = QAction(SasView)
        self.actionSLD_Calculator.setObjectName(u"actionSLD_Calculator")
        self.actionDensity_Volume_Calculator = QAction(SasView)
        self.actionDensity_Volume_Calculator.setObjectName(u"actionDensity_Volume_Calculator")
        self.actionSlit_Size_Calculator = QAction(SasView)
        self.actionSlit_Size_Calculator.setObjectName(u"actionSlit_Size_Calculator")
        self.actionSAS_Resolution_Estimator = QAction(SasView)
        self.actionSAS_Resolution_Estimator.setObjectName(u"actionSAS_Resolution_Estimator")
        self.actionShape2SAS_Calculator = QAction(SasView)
        self.actionShape2SAS_Calculator.setObjectName(u"actionShape2SAS_Calculator")
        self.actionGeneric_Scattering_Calculator = QAction(SasView)
        self.actionGeneric_Scattering_Calculator.setObjectName(u"actionGeneric_Scattering_Calculator")
        self.actionPython_Shell_Editor = QAction(SasView)
        self.actionPython_Shell_Editor.setObjectName(u"actionPython_Shell_Editor")
        self.actionImage_Viewer = QAction(SasView)
        self.actionImage_Viewer.setObjectName(u"actionImage_Viewer")
        self.actionFile_Converter = QAction(SasView)
        self.actionFile_Converter.setObjectName(u"actionFile_Converter")
        self.actionNew_Fit_Page = QAction(SasView)
        self.actionNew_Fit_Page.setObjectName(u"actionNew_Fit_Page")
        self.actionConstrained_Fit = QAction(SasView)
        self.actionConstrained_Fit.setObjectName(u"actionConstrained_Fit")
        self.actionCombine_Batch_Fit = QAction(SasView)
        self.actionCombine_Batch_Fit.setObjectName(u"actionCombine_Batch_Fit")
        self.actionFit_Options = QAction(SasView)
        self.actionFit_Options.setObjectName(u"actionFit_Options")
        self.actionFit_Results = QAction(SasView)
        self.actionFit_Results.setObjectName(u"actionFit_Results")
        self.actionChain_Fitting = QAction(SasView)
        self.actionChain_Fitting.setObjectName(u"actionChain_Fitting")
        self.actionEdit_Custom_Model = QAction(SasView)
        self.actionEdit_Custom_Model.setObjectName(u"actionEdit_Custom_Model")
        self.actionEditMask = QAction(SasView)
        self.actionEditMask.setObjectName(u"actionEditMask")
        self.actionCascade = QAction(SasView)
        self.actionCascade.setObjectName(u"actionCascade")
        self.actionTile = QAction(SasView)
        self.actionTile.setObjectName(u"actionTile")
        self.actionTile_Vertically = QAction(SasView)
        self.actionTile_Vertically.setObjectName(u"actionTile_Vertically")
        self.actionArrange_Icons = QAction(SasView)
        self.actionArrange_Icons.setObjectName(u"actionArrange_Icons")
        self.actionNext = QAction(SasView)
        self.actionNext.setObjectName(u"actionNext")
        icon8 = QIcon()
        icon8.addFile(u":/res/right-round.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNext.setIcon(icon8)
        self.actionPrevious = QAction(SasView)
        self.actionPrevious.setObjectName(u"actionPrevious")
        icon9 = QIcon()
        icon9.addFile(u":/res/left-round.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrevious.setIcon(icon9)
        self.actionFitting = QAction(SasView)
        self.actionFitting.setObjectName(u"actionFitting")
        self.actionFitting.setCheckable(True)
        self.actionInversion = QAction(SasView)
        self.actionInversion.setObjectName(u"actionInversion")
        self.actionInversion.setCheckable(True)
        self.actionInvariant = QAction(SasView)
        self.actionInvariant.setObjectName(u"actionInvariant")
        self.actionInvariant.setCheckable(True)
        self.actionSizeDistribution = QAction(SasView)
        self.actionSizeDistribution.setObjectName(u"actionSizeDistribution")
        self.actionSizeDistribution.setCheckable(True)
        self.actionDocumentation = QAction(SasView)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.actionTutorial = QAction(SasView)
        self.actionTutorial.setObjectName(u"actionTutorial")
        self.actionAcknowledge = QAction(SasView)
        self.actionAcknowledge.setObjectName(u"actionAcknowledge")
        self.actionAbout = QAction(SasView)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionCheck_for_update = QAction(SasView)
        self.actionCheck_for_update.setObjectName(u"actionCheck_for_update")
        self.actionExcel = QAction(SasView)
        self.actionExcel.setObjectName(u"actionExcel")
        self.actionLatex = QAction(SasView)
        self.actionLatex.setObjectName(u"actionLatex")
        self.actionKeissig_Calculator = QAction(SasView)
        self.actionKeissig_Calculator.setObjectName(u"actionKeissig_Calculator")
        self.actionGPU_Options = QAction(SasView)
        self.actionGPU_Options.setObjectName(u"actionGPU_Options")
        self.actionAdd_Custom_Model = QAction(SasView)
        self.actionAdd_Custom_Model.setObjectName(u"actionAdd_Custom_Model")
        self.actionReparameterize_Model = QAction(SasView)
        self.actionReparameterize_Model.setObjectName(u"actionReparameterize_Model")
        self.actionManage_Custom_Models = QAction(SasView)
        self.actionManage_Custom_Models.setObjectName(u"actionManage_Custom_Models")
        self.actionCorfunc = QAction(SasView)
        self.actionCorfunc.setObjectName(u"actionCorfunc")
        self.actionCorfunc.setCheckable(True)
        self.actionAddMult_Models = QAction(SasView)
        self.actionAddMult_Models.setObjectName(u"actionAddMult_Models")
        self.actionOrientation_Viewer = QAction(SasView)
        self.actionOrientation_Viewer.setObjectName(u"actionOrientation_Viewer")
        self.actionFreeze_Theory = QAction(SasView)
        self.actionFreeze_Theory.setObjectName(u"actionFreeze_Theory")
        self.actionHide_DataExplorer = QAction(SasView)
        self.actionHide_DataExplorer.setObjectName(u"actionHide_DataExplorer")
        self.actionWelcomeWidget = QAction(SasView)
        self.actionWelcomeWidget.setObjectName(u"actionWelcomeWidget")
        self.actionHide_LogExplorer = QAction(SasView)
        self.actionHide_LogExplorer.setObjectName(u"actionHide_LogExplorer")
        self.actionCategory_Manager = QAction(SasView)
        self.actionCategory_Manager.setObjectName(u"actionCategory_Manager")
        self.actionShow_Grid_Window = QAction(SasView)
        self.actionShow_Grid_Window.setObjectName(u"actionShow_Grid_Window")
        self.actionMinimizePlots = QAction(SasView)
        self.actionMinimizePlots.setObjectName(u"actionMinimizePlots")
        self.actionClosePlots = QAction(SasView)
        self.actionClosePlots.setObjectName(u"actionClosePlots")
        self.actionModel_Marketplace = QAction(SasView)
        self.actionModel_Marketplace.setObjectName(u"actionModel_Marketplace")
        self.actionPreferences = QAction(SasView)
        self.actionPreferences.setObjectName(u"actionPreferences")
        icon10 = QIcon()
        icon10.addFile(u":/res/settings.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPreferences.setIcon(icon10)
        self.actionMuMag_Fitter = QAction(SasView)
        self.actionMuMag_Fitter.setObjectName(u"actionMuMag_Fitter")
        self.actionWhat_s_New = QAction(SasView)
        self.actionWhat_s_New.setObjectName(u"actionWhat_s_New")
        self.centralwidget = QWidget(SasView)
        self.centralwidget.setObjectName(u"centralwidget")
        SasView.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(SasView)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 915, 20))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuCopy_Params_As = QMenu(self.menuEdit)
        self.menuCopy_Params_As.setObjectName(u"menuCopy_Params_As")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuTool = QMenu(self.menubar)
        self.menuTool.setObjectName(u"menuTool")
        self.menuFitting = QMenu(self.menubar)
        self.menuFitting.setObjectName(u"menuFitting")
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuAnalysis = QMenu(self.menubar)
        self.menuAnalysis.setObjectName(u"menuAnalysis")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        SasView.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(SasView)
        self.statusbar.setObjectName(u"statusbar")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        SasView.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(SasView)
        self.toolBar.setObjectName(u"toolBar")
        SasView.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuFitting.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menu_File.addAction(self.actionLoadData)
        self.menu_File.addAction(self.actionLoad_Data_Folder)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionOpen_Project)
        self.menu_File.addAction(self.actionOpen_Analysis)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSave_Analysis)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionPreferences)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuCopy_Params_As.menuAction())
        self.menuEdit.addAction(self.actionSaveParamsAs)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionReport)
        self.menuEdit.addAction(self.actionReset)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionFreeze_Theory)
        self.menuCopy_Params_As.addAction(self.actionExcel)
        self.menuCopy_Params_As.addAction(self.actionLatex)
        self.menuView.addAction(self.actionHide_Toolbar)
        self.menuView.addAction(self.actionHide_DataExplorer)
        self.menuView.addAction(self.actionHide_LogExplorer)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionStartup_Settings)
        self.menuTool.addAction(self.actionData_Operation)
        self.menuTool.addAction(self.actionFile_Converter)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.actionSLD_Calculator)
        self.menuTool.addAction(self.actionDensity_Volume_Calculator)
        self.menuTool.addAction(self.actionSlit_Size_Calculator)
        self.menuTool.addAction(self.actionKeissig_Calculator)
        self.menuTool.addAction(self.actionSAS_Resolution_Estimator)
        self.menuTool.addAction(self.actionMuMag_Fitter)
        self.menuTool.addAction(self.actionGeneric_Scattering_Calculator)
        self.menuTool.addAction(self.actionShape2SAS_Calculator)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.actionImage_Viewer)
        self.menuTool.addAction(self.actionOrientation_Viewer)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.actionPython_Shell_Editor)
        self.menuFitting.addAction(self.actionNew_Fit_Page)
        self.menuFitting.addSeparator()
        self.menuFitting.addAction(self.actionConstrained_Fit)
        self.menuFitting.addAction(self.actionCombine_Batch_Fit)
        self.menuFitting.addSeparator()
        self.menuFitting.addAction(self.actionShow_Grid_Window)
        self.menuFitting.addSeparator()
        self.menuFitting.addAction(self.actionFit_Options)
        self.menuFitting.addAction(self.actionGPU_Options)
        self.menuFitting.addAction(self.actionFit_Results)
        self.menuFitting.addSeparator()
        self.menuFitting.addAction(self.actionCategory_Manager)
        self.menuFitting.addAction(self.actionAdd_Custom_Model)
        self.menuFitting.addAction(self.actionEdit_Custom_Model)
        self.menuFitting.addAction(self.actionManage_Custom_Models)
        self.menuFitting.addAction(self.actionReparameterize_Model)
        self.menuFitting.addAction(self.actionAddMult_Models)
        self.menuFitting.addSeparator()
        self.menuFitting.addAction(self.actionEditMask)
        self.menuWindow.addAction(self.actionCascade)
        self.menuWindow.addAction(self.actionTile)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionNext)
        self.menuWindow.addAction(self.actionPrevious)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionMinimizePlots)
        self.menuWindow.addAction(self.actionClosePlots)
        self.menuAnalysis.addAction(self.actionCorfunc)
        self.menuAnalysis.addAction(self.actionFitting)
        self.menuAnalysis.addAction(self.actionInvariant)
        self.menuAnalysis.addAction(self.actionInversion)
        self.menuAnalysis.addAction(self.actionSizeDistribution)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionTutorial)
        self.menuHelp.addAction(self.actionModel_Marketplace)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAcknowledge)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionWelcomeWidget)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionCheck_for_update)
        self.menuHelp.addAction(self.actionWhat_s_New)
        self.toolBar.addAction(self.actionReset)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionReport)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrevious)
        self.toolBar.addAction(self.actionNext)

        self.retranslateUi(SasView)

        QMetaObject.connectSlotsByName(SasView)
    # setupUi

    def retranslateUi(self, SasView):
        SasView.setWindowTitle(QCoreApplication.translate("SasView", u"SasView", None))
        self.actionReset.setText(QCoreApplication.translate("SasView", u"Reset Page", None))
#if QT_CONFIG(tooltip)
        self.actionReset.setToolTip(QCoreApplication.translate("SasView", u"Reset", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave.setText(QCoreApplication.translate("SasView", u"Save Project", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("SasView", u"Save", None))
#endif // QT_CONFIG(tooltip)
        self.actionReport.setText(QCoreApplication.translate("SasView", u"Report Results", None))
#if QT_CONFIG(tooltip)
        self.actionReport.setToolTip(QCoreApplication.translate("SasView", u"report", None))
#endif // QT_CONFIG(tooltip)
        self.actionUndo.setText(QCoreApplication.translate("SasView", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("SasView", u"Redo", None))
#if QT_CONFIG(tooltip)
        self.actionRedo.setToolTip(QCoreApplication.translate("SasView", u"Redo", None))
#endif // QT_CONFIG(tooltip)
        self.actionCopy.setText(QCoreApplication.translate("SasView", u"Copy Params", None))
#if QT_CONFIG(tooltip)
        self.actionCopy.setToolTip(QCoreApplication.translate("SasView", u"Copy parameter values", None))
#endif // QT_CONFIG(tooltip)
        self.actionPaste.setText(QCoreApplication.translate("SasView", u"Paste Params", None))
#if QT_CONFIG(tooltip)
        self.actionPaste.setToolTip(QCoreApplication.translate("SasView", u"Paste parameter values", None))
#endif // QT_CONFIG(tooltip)
        self.actionSaveParamsAs.setText(QCoreApplication.translate("SasView", u"Save Params to File", None))
        self.actionPerspective.setText(QCoreApplication.translate("SasView", u"Perspective", None))
        self.actionLoadData.setText(QCoreApplication.translate("SasView", u"Load Data File(s)", None))
        self.actionLoad_Data_Folder.setText(QCoreApplication.translate("SasView", u"Load Data Folder", None))
        self.actionOpen_Project.setText(QCoreApplication.translate("SasView", u"Open Project", None))
        self.actionOpen_Analysis.setText(QCoreApplication.translate("SasView", u"Open Analysis", None))
        self.actionSave_Analysis.setText(QCoreApplication.translate("SasView", u"Save Analysis", None))
        self.actionQuit.setText(QCoreApplication.translate("SasView", u"Quit", None))
        self.actionHide_Toolbar.setText(QCoreApplication.translate("SasView", u"Hide Toolbar", None))
        self.actionStartup_Settings.setText(QCoreApplication.translate("SasView", u"Startup Settings", None))
        self.actionData_Operation.setText(QCoreApplication.translate("SasView", u"Data Operation", None))
        self.actionSLD_Calculator.setText(QCoreApplication.translate("SasView", u"SLD Calculator", None))
        self.actionDensity_Volume_Calculator.setText(QCoreApplication.translate("SasView", u"Density/Volume Calculator", None))
        self.actionSlit_Size_Calculator.setText(QCoreApplication.translate("SasView", u"Slit Size Calculator", None))
        self.actionSAS_Resolution_Estimator.setText(QCoreApplication.translate("SasView", u"Q Resolution Estimator", None))
        self.actionShape2SAS_Calculator.setText(QCoreApplication.translate("SasView", u"Shape2SAS Calculator (Experimental)", None))
        self.actionGeneric_Scattering_Calculator.setText(QCoreApplication.translate("SasView", u"Generic Scattering Calculator", None))
        self.actionPython_Shell_Editor.setText(QCoreApplication.translate("SasView", u"Python Shell/Editor", None))
        self.actionImage_Viewer.setText(QCoreApplication.translate("SasView", u"Image Viewer", None))
        self.actionFile_Converter.setText(QCoreApplication.translate("SasView", u"File Converter", None))
        self.actionNew_Fit_Page.setText(QCoreApplication.translate("SasView", u"New Fit Page", None))
        self.actionConstrained_Fit.setText(QCoreApplication.translate("SasView", u"Constrained or Simultaneous Fit", None))
        self.actionCombine_Batch_Fit.setText(QCoreApplication.translate("SasView", u"Combine Batch Fit", None))
        self.actionFit_Options.setText(QCoreApplication.translate("SasView", u"Fit Algorithms", None))
        self.actionFit_Results.setText(QCoreApplication.translate("SasView", u"Fit Results", None))
        self.actionChain_Fitting.setText(QCoreApplication.translate("SasView", u"Chain Fitting (BatchFit only)", None))
        self.actionEdit_Custom_Model.setText(QCoreApplication.translate("SasView", u"Edit Custom Model", None))
        self.actionEditMask.setText(QCoreApplication.translate("SasView", u"Edit Mask", None))
        self.actionCascade.setText(QCoreApplication.translate("SasView", u"Cascade", None))
        self.actionTile.setText(QCoreApplication.translate("SasView", u"Tile", None))
        self.actionTile_Vertically.setText(QCoreApplication.translate("SasView", u"Tile Vertically", None))
        self.actionArrange_Icons.setText(QCoreApplication.translate("SasView", u"Arrange Icons", None))
        self.actionNext.setText(QCoreApplication.translate("SasView", u"Next window", None))
        self.actionPrevious.setText(QCoreApplication.translate("SasView", u"Previous window", None))
        self.actionFitting.setText(QCoreApplication.translate("SasView", u"Fitting", None))
        self.actionInversion.setText(QCoreApplication.translate("SasView", u"Pr Inversion", None))
        self.actionInvariant.setText(QCoreApplication.translate("SasView", u"Invariant", None))
        self.actionSizeDistribution.setText(QCoreApplication.translate("SasView", u"Size Distribution", None))
        self.actionDocumentation.setText(QCoreApplication.translate("SasView", u"Documentation", None))
        self.actionTutorial.setText(QCoreApplication.translate("SasView", u"Tutorial", None))
        self.actionAcknowledge.setText(QCoreApplication.translate("SasView", u"Cite Sasview", None))
        self.actionAbout.setText(QCoreApplication.translate("SasView", u"About", None))
        self.actionCheck_for_update.setText(QCoreApplication.translate("SasView", u"Check for update", None))
        self.actionExcel.setText(QCoreApplication.translate("SasView", u"Excel", None))
        self.actionLatex.setText(QCoreApplication.translate("SasView", u"Latex", None))
        self.actionKeissig_Calculator.setText(QCoreApplication.translate("SasView", u"Kiessig Thickness Calculator", None))
        self.actionGPU_Options.setText(QCoreApplication.translate("SasView", u"GPU Options", None))
        self.actionAdd_Custom_Model.setText(QCoreApplication.translate("SasView", u"Add Custom Model", None))
        self.actionReparameterize_Model.setText(QCoreApplication.translate("SasView", u"Reparameterize A Model", None))
        self.actionManage_Custom_Models.setText(QCoreApplication.translate("SasView", u"Manage Custom Models", None))
        self.actionCorfunc.setText(QCoreApplication.translate("SasView", u"Correlation Function", None))
        self.actionAddMult_Models.setText(QCoreApplication.translate("SasView", u"Add/Multiply Models", None))
        self.actionOrientation_Viewer.setText(QCoreApplication.translate("SasView", u"Orientation Viewer", None))
        self.actionFreeze_Theory.setText(QCoreApplication.translate("SasView", u"Freeze Fit Results", None))
        self.actionHide_DataExplorer.setText(QCoreApplication.translate("SasView", u"Hide Data Explorer", None))
        self.actionWelcomeWidget.setText(QCoreApplication.translate("SasView", u"Welcome to SasView", None))
        self.actionHide_LogExplorer.setText(QCoreApplication.translate("SasView", u"Show Log Explorer", None))
        self.actionCategory_Manager.setText(QCoreApplication.translate("SasView", u"Category Manager", None))
        self.actionShow_Grid_Window.setText(QCoreApplication.translate("SasView", u"Show Grid Window", None))
        self.actionMinimizePlots.setText(QCoreApplication.translate("SasView", u"Minimize All Plots", None))
        self.actionClosePlots.setText(QCoreApplication.translate("SasView", u"Close All Plots", None))
        self.actionModel_Marketplace.setText(QCoreApplication.translate("SasView", u"Model Marketplace", None))
        self.actionPreferences.setText(QCoreApplication.translate("SasView", u"Preferences...", None))
        self.actionMuMag_Fitter.setText(QCoreApplication.translate("SasView", u"MuMag Fitter (Experimental)", None))
        self.actionWhat_s_New.setText(QCoreApplication.translate("SasView", u"What's New", None))
        self.menu_File.setTitle(QCoreApplication.translate("SasView", u"&File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("SasView", u"Edit", None))
        self.menuCopy_Params_As.setTitle(QCoreApplication.translate("SasView", u"Copy Params To Format...", None))
        self.menuView.setTitle(QCoreApplication.translate("SasView", u"View", None))
        self.menuTool.setTitle(QCoreApplication.translate("SasView", u"Tools", None))
        self.menuFitting.setTitle(QCoreApplication.translate("SasView", u"Fitting", None))
        self.menuWindow.setTitle(QCoreApplication.translate("SasView", u"Window", None))
        self.menuAnalysis.setTitle(QCoreApplication.translate("SasView", u"Analysis", None))
        self.menuHelp.setTitle(QCoreApplication.translate("SasView", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("SasView", u"toolBar", None))
    # retranslateUi

