# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .aks_kube_config import *
from .eks_kube_config import *
from .gke_kube_config import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "kubeconfig",
  "mod": "index",
  "fqn": "pierskarsenbarg_pulumi_kubeconfig",
  "classes": {
   "kubeconfig:index:AksKubeConfig": "AksKubeConfig",
   "kubeconfig:index:EksKubeConfig": "EksKubeConfig",
   "kubeconfig:index:GkeKubeConfig": "GkeKubeConfig"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "kubeconfig",
  "token": "pulumi:providers:kubeconfig",
  "fqn": "pierskarsenbarg_pulumi_kubeconfig",
  "class": "Provider"
 }
]
"""
)
