from .helpers import test_vat_normalizer, test_bank_utils
from .listeners import (
    test_contract_line_listener,
    test_contract_listener,
)
from .models import (
    # test_account_move_line,
    # test_account_payment_order,
    # test_account_payment_return_gateway,
    test_aged_partner_balance,
    test_aged_partner_balance_xlsx,
    test_broadband_isp_info,
    test_contract,
    test_contract_line,
    test_crm_lead,
    test_crm_lead_line,
    test_mail_activity,
    test_mobile_isp_info,
    # test_payment_return,
    test_previous_provider,
    test_product_category_technology_supplier,
    test_product_product,
    test_product_template,
    # test_production_lot,
    test_res_partner,
    test_res_partner_bank,
    test_server_action,
    test_service_catalog,
    test_service_supplier,
    # test_stock_move_line,
)
from .services import (
    # test_account_invoice_service,
    test_product_catalog_service,
    test_product_one_shot_catalog_service,
    test_provider_service,
    test_fiber_contract_to_pack_service,
)
from .wizards import (
    #    test_account_payment_line_create,
    test_contract_address_change_wizard,
    test_contract_compensation_wizard,
    test_contract_holder_change,
    test_contract_iban_change_wizard,
    #    test_contract_invoice_payment_wizard,
    test_contract_mobile_check_consumption,
    test_contract_one_shot_request_wizard,
    test_contract_tariff_change_wizard,
    test_create_lead_add_mobile_line,
    test_create_lead_from_partner_wizard,
    test_crm_lead_remesa_wizard,
    test_crm_leads_validate_wizard,
    test_mail_compose_message_wizard,
    test_partner_email_change_wizard,
    #    test_payment_order_generated_to_upload_queued_wizard,
)
