"""
Reason codes for v2 signal explanations.
"""

# Detection reason codes
MEDICAL_TERM = "MEDICAL_TERM"
FINANCIAL_TERM = "FINANCIAL_TERM"
CREDENTIAL_PATTERN = "CREDENTIAL_PATTERN"
EMAIL_PATTERN = "EMAIL_PATTERN"
PHONE_PATTERN = "PHONE_PATTERN"
FREE_TEXT_EXPOSURE = "FREE_TEXT_EXPOSURE"
NESTED_PAYLOAD = "NESTED_PAYLOAD"

__all__ = [
    "MEDICAL_TERM",
    "FINANCIAL_TERM",
    "CREDENTIAL_PATTERN",
    "EMAIL_PATTERN",
    "PHONE_PATTERN",
    "FREE_TEXT_EXPOSURE",
    "NESTED_PAYLOAD",
]

