from datetime import datetime
from enum import IntEnum, StrEnum
from typing import Any, Iterable, Sequence

import msgspec

from _typeshed import Incomplete

from svy.errors.base_errors import SvyError as SvyError

log: Incomplete

class Severity(IntEnum):
    INFO = 10
    WARNING = 20
    ERROR = 30

class WarnCode(StrEnum):
    MISSING_LABELS = "MISSING_LABELS"
    UNKNOWN_CATEGORY = "UNKNOWN_CATEGORY"
    ZERO_WEIGHT = "ZERO_WEIGHT"
    NEGATIVE_WEIGHT = "NEGATIVE_WEIGHT"
    SINGLETON_PSU = "SINGLETON_PSU"
    STRATUM_WITH_ONE_PSU = "STRATUM_WITH_ONE_PSU"
    COLLAPSED_STRATA = "COLLAPSED_STRATA"
    POSTSTRATA_EMPTY = "POSTSTRATA_EMPTY"
    CONTROL_MISMATCH = "CONTROL_MISMATCH"
    DESIGN_INCOMPLETE = "DESIGN_INCOMPLETE"

class SvyWarning(msgspec.Struct, frozen=True):
    """
    Lightweight, typed, immutable warning that can render like SvyError.
    Use (title, detail) to match SvyError ergonomics.
    """

    code: WarnCode | str
    title: str
    detail: str
    where: str | None = ...
    level: Severity = ...
    param: str | None = ...
    expected: Any = ...
    got: Any = ...
    hint: str | None = ...
    docs_url: str | None = ...
    extra: dict[str, Any] | None = ...
    var: str | None = ...
    rows: tuple[int, ...] | None = ...
    ts: datetime = msgspec.field(default_factory=Incomplete)
    def text(self, *, indent: int = 2, surround: bool = True) -> str: ...
    def ansi(self) -> str: ...
    def markdown(self) -> str: ...
    def html(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def key(self) -> tuple[Any, ...]: ...

class SvyWarningsError(SvyError):
    """
    Escalation exception that keeps your formatting surfaces.
    """
    @classmethod
    def from_warnings(
        cls,
        warnings: Sequence[SvyWarning],
        *,
        where: str | None = None,
        code: str = "SVY_WARNINGS_ERROR",
    ) -> SvyWarningsError: ...

class WarningStore:
    """
    Attach this to Sample._warnings.
    - De-dupes by SvyWarning.key()
    - Optional per-code cap to avoid floods
    """
    def __init__(self, *, dedupe: bool = True, max_per_code: int | None = 100) -> None: ...
    def add(self, w: SvyWarning) -> None: ...
    def extend(self, warnings: Iterable[SvyWarning]) -> None: ...
    def clear(self) -> None: ...
    def list(
        self,
        *,
        min_level: Severity | None = None,
        code: WarnCode | str | None = None,
        where_contains: str | None = None,
    ) -> list[SvyWarning]: ...
    def counts(self) -> dict[str, int]: ...
    def raise_if_errors(self) -> None: ...
    def escalate(self, *, min_level: Severity = ...) -> None: ...
    def to_dicts(self) -> list[dict[str, Any]]: ...
    def to_json(self) -> bytes: ...
    def to_polars(self): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
