{
    "name": "Odoo Som Connexió OTRS integration",
    "version": "16.0.1.2.5",
    "summary": "Integration with OTRS for Som Connexió.",
    "author": "Coopdevs Treball SCCL, Som Connexió SCCL",
    "website": "https://coopdevs.org",
    "license": "AGPL-3",
    "category": "Cooperative management",
    "depends": [
        "somconnexio",
        "switchboard_somconnexio",
        "delivery_somconnexio",
        "contract_api_somconnexio",
    ],
    "data": [
        "crons/activate_change_tariff_OTRS_tickets_cron.xml",
        "wizards/contract_address_change/contract_address_change.xml",
        "wizards/contract_mobile_tariff_change/contract_mobile_tariff_change.xml",
        "wizards/create_lead_from_partner/create_lead_from_partner.xml",
        "views/broadband_isp_info_view.xml",
        "views/contract_view.xml",
        "views/crm_lead_line_view.xml",
        "security/ir.model.access.csv",
    ],
    "demo": [],
    "external_dependencies": {"python": ["otrs_somconnexio"]},
    "application": False,
    "installable": True,
}
