# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from across.sdk.v2.api.telescope_api import TelescopeApi


class TestTelescopeApi(unittest.TestCase):
    """TelescopeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TelescopeApi()

    def tearDown(self) -> None:
        pass

    def test_get_telescope(self) -> None:
        """Test case for get_telescope

        Read an telescope
        """
        pass

    def test_get_telescopes(self) -> None:
        """Test case for get_telescopes

        Read telescopes(s)
        """
        pass


if __name__ == '__main__':
    unittest.main()
