from ..subprocess_utils import SubprocessExecutor as SubprocessExecutor
from pathlib import Path

def check_pyproject_workspace(root: Path) -> bool: ...
def check_uv_lock_workspace(root: Path) -> bool: ...
def check_init_workspace(root: Path, executor: SubprocessExecutor) -> bool: ...
def check_tree_workspace(root: Path, executor: SubprocessExecutor, min_roots: int = 2) -> bool: ...
def parse_root_packages(lines: list[str]) -> list[str]: ...
def is_valid_version(version: str) -> bool: ...
