"""Shared environment variable names used for container setup."""

AICAGE_UID = "AICAGE_UID"
AICAGE_GID = "AICAGE_GID"
AICAGE_USER = "AICAGE_USER"

AICAGE_TOOL_PATH = "AICAGE_TOOL_PATH"
AICAGE_GITCONFIG_TARGET = "AICAGE_GITCONFIG_TARGET"
AICAGE_GNUPG_TARGET = "AICAGE_GNUPG_TARGET"
AICAGE_SSH_TARGET = "AICAGE_SSH_TARGET"

GNUPGHOME = "GNUPGHOME"
