EXPECTED_MPI_VERSION: str
EXPECTED_MPI_IMPL: str

def detect_mpi_version(): ...
def verify_mpi_compatibility() -> None: ...
def print_install_help() -> None: ...
def check_mpi_available() -> None: ...
