"""Enum of all engine operation names."""
from enum import Enum


class OperationNames(str, Enum):
    """Enum of all engine operation names."""

    OPS_BLENDER_FBX_EXPORT = "OpsBlenderFBXExport"
    OPS_CALIBRATE_ARUCO = "OpsCalibrateAruco"
    OPS_CALIBRATE = "OpsCalibrate"
    OPS_CORRECT_CALIB = "OpsCorrectCalib"
    OPS_DETECT_MARKER_OBJECTS = "OpsDetectMarkerObjects"
    OPS_DETECT_OBJECTS = "OpsDetectObjects"
    OPS_DOWNLOAD_DATASET = "OpsDownloadDataset"
    OPS_DOWNLOAD_INPUTS = "OpsDownloadInputs"
    OPS_EXTRACT_MOVE_FILE = "OpsExtractMoveFile"
    OPS_FINALIZE_A_RUN = "OpsFinalizeARun"
    OPS_FLOOR_PLANE_ROOT_ADJUSTMENT = "OpsFloorPlaneRootAdjustment"
    OPS_HAND3D_POSE_ON_TRACKS = "OpsHand3dPoseOnTracks"
    OPS_INPUT_VIDEOS_AUDIOS = "OpsInputVideosAudios"
    OPS_JERSEY_CLASSIFY = "OpsJerseyClassify"
    OPS_KALMAN_MONOCULAR = "OpsKalmanMonocular"
    OPS_KALMAN = "OpsKalman"
    OPS_MARKER_KALMAN_FILTER = "OpsMarkerKalmanFilter"
    OPS_MARKERS_TO_BLEND = "OpsMarkersToBlend"
    OPS_MAYA_EXPORT = "OpsMayaExport"
    OPS_MDC_DETECTIONS = "OpsMdcDetections"
    OPS_MDC_TRACKING = "OpsMdcTracking"
    OPS_MOCAP = "OpsMocap"
    OPS_ON_FAILURE = "OpsOnFailure"
    OPS_POSE2D_SINGLE_FRAME = "OpsPose2dSingleFrame"
    OPS_POSE3D_MONO = "OpsPose3dMono"
    OPS_POSE3D_MULTIVIEW = "OpsPose3dMultiview"
    OPS_PREP_KALMAN_DATA = "OpsPrepKalmanData"
    OPS_PREPARE_ACTOR_PROFILE = "OpsPrepareActorProfile"
    OPS_PREPARE_RUN_DATA = "OpsPrepareRunData"
    OPS_QUALITY_METRICS = "OpsQualityMetrics"
    OPS_REPORT_CALIB = "OpsReportCalib"
    OPS_RIGS_PREP_CONSTRAIN_TO_URDF = "OpsRigsPrepConstrainToUrdf"
    OPS_RIGS_PREP_FBX_TO_BLEND = "OpsRigsPrepFbxToBlend"
    OPS_RIGS_PREP_RENDER_360_PREVIEW = "OpsRigsPrepRender360Preview"
    OPS_SYNC_MULTIVIEW_VIDEOS = "OpsSyncMultiviewVideos"
    OPS_TRACKING_CALIB = "OpsTrackingCalib"
    OPS_UPLOAD_OUTPUTS = "OpsUploadOutputs"
    OPS_VISUALIZATION = "OpsVisualization"
    OPS_ZIP_DATA = "OpsZipData"
    OPS_UNKNOWN = "OpsUnknown"
    OPS_PREP_KALMAN_V2 = "OpsPrepKalmanV2"
    OPS_KALMAN_V2 = "OpsKalmanV2"
    OPS_BLENDER_V2_EXPORT = "OpsBlenderV2Export"
    OPS_ANIMATION_FILES_EXPORTS = "OpsAnimationFilesExports"
    OPS_BLEND_FILES_CREATION = "OpsBlendFilesCreation"
    OPS_HANDS_GEN2 = "OpsHandsGen2"
    OPS_ONLINE_BALL_TRACKING = "OpsOnlineBallTracking"
