"""Type stubs for varps module."""

from typing import Any, Dict

def extractBits(value: int, start_bit: int, end_bit: int) -> int: ...
def getVarbitInfo(varbit_id: int) -> Dict[str, Any] | None: ...
def getVarpByName(name: str) -> int | None: ...
def getVarpByIndex(varp_id: int) -> int | None: ...
def getVarbitByIndex(varbit_id: int) -> int | None: ...
def getVarbitByName(name: str) -> int | None: ...
def listVarps(filter_name: str | None = None) -> Dict[int, Dict[str, Any]]: ...
def listVarbits(filter_name: str | None = None) -> Dict[int, Dict[str, Any]]: ...
def getVarcValue(varc_id: int) -> Any | None: ...
def getVarcName(varc_id: int) -> str | None: ...
