"""
Stripe API Schema Definitions

Based on official Stripe API documentation:
https://docs.stripe.com/api

These schemas ensure tables are created with proper columns even with 0 rows,
enabling downstream dbt modeling without waiting for data.
"""

from typing import Dict, List

# Schema definitions for each Stripe endpoint
# Based on Stripe API v2022-11-15

STRIPE_SCHEMAS: Dict[str, List[Dict]] = {
    "Charge": [
        {"name": "id", "data_type": "text", "nullable": False},
        {"name": "object", "data_type": "text", "nullable": True},
        {"name": "amount", "data_type": "bigint", "nullable": True},
        {"name": "amount_captured", "data_type": "bigint", "nullable": True},
        {"name": "amount_refunded", "data_type": "bigint", "nullable": True},
        {"name": "application", "data_type": "text", "nullable": True},
        {"name": "application_fee", "data_type": "text", "nullable": True},
        {"name": "balance_transaction", "data_type": "text", "nullable": True},
        {"name": "billing_details", "data_type": "complex", "nullable": True},
        {"name": "calculated_statement_descriptor", "data_type": "text", "nullable": True},
        {"name": "captured", "data_type": "bool", "nullable": True},
        {"name": "created", "data_type": "bigint", "nullable": True},
        {"name": "currency", "data_type": "text", "nullable": True},
        {"name": "customer", "data_type": "text", "nullable": True},
        {"name": "description", "data_type": "text", "nullable": True},
        {"name": "destination", "data_type": "text", "nullable": True},
        {"name": "dispute", "data_type": "text", "nullable": True},
        {"name": "disputed", "data_type": "bool", "nullable": True},
        {"name": "failure_balance_transaction", "data_type": "text", "nullable": True},
        {"name": "failure_code", "data_type": "text", "nullable": True},
        {"name": "failure_message", "data_type": "text", "nullable": True},
        {"name": "fraud_details", "data_type": "complex", "nullable": True},
        {"name": "invoice", "data_type": "text", "nullable": True},
        {"name": "livemode", "data_type": "bool", "nullable": True},
        {"name": "metadata", "data_type": "complex", "nullable": True},
        {"name": "on_behalf_of", "data_type": "text", "nullable": True},
        {"name": "order", "data_type": "text", "nullable": True},
        {"name": "outcome", "data_type": "complex", "nullable": True},
        {"name": "paid", "data_type": "bool", "nullable": True},
        {"name": "payment_intent", "data_type": "text", "nullable": True},
        {"name": "payment_method", "data_type": "text", "nullable": True},
        {"name": "payment_method_details", "data_type": "complex", "nullable": True},
        {"name": "receipt_email", "data_type": "text", "nullable": True},
        {"name": "receipt_number", "data_type": "text", "nullable": True},
        {"name": "receipt_url", "data_type": "text", "nullable": True},
        {"name": "refunded", "data_type": "bool", "nullable": True},
        {"name": "refunds", "data_type": "complex", "nullable": True},
        {"name": "review", "data_type": "text", "nullable": True},
        {"name": "shipping", "data_type": "complex", "nullable": True},
        {"name": "source", "data_type": "complex", "nullable": True},
        {"name": "source_transfer", "data_type": "text", "nullable": True},
        {"name": "statement_descriptor", "data_type": "text", "nullable": True},
        {"name": "statement_descriptor_suffix", "data_type": "text", "nullable": True},
        {"name": "status", "data_type": "text", "nullable": True},
        {"name": "transfer_data", "data_type": "complex", "nullable": True},
        {"name": "transfer_group", "data_type": "text", "nullable": True},
    ],

    "Customer": [
        {"name": "id", "data_type": "text", "nullable": False},
        {"name": "object", "data_type": "text", "nullable": True},
        {"name": "address", "data_type": "complex", "nullable": True},
        {"name": "balance", "data_type": "bigint", "nullable": True},
        {"name": "created", "data_type": "bigint", "nullable": True},
        {"name": "currency", "data_type": "text", "nullable": True},
        {"name": "default_source", "data_type": "text", "nullable": True},
        {"name": "delinquent", "data_type": "bool", "nullable": True},
        {"name": "description", "data_type": "text", "nullable": True},
        {"name": "discount", "data_type": "complex", "nullable": True},
        {"name": "email", "data_type": "text", "nullable": True},
        {"name": "invoice_prefix", "data_type": "text", "nullable": True},
        {"name": "invoice_settings", "data_type": "complex", "nullable": True},
        {"name": "livemode", "data_type": "bool", "nullable": True},
        {"name": "metadata", "data_type": "complex", "nullable": True},
        {"name": "name", "data_type": "text", "nullable": True},
        {"name": "next_invoice_sequence", "data_type": "bigint", "nullable": True},
        {"name": "phone", "data_type": "text", "nullable": True},
        {"name": "preferred_locales", "data_type": "complex", "nullable": True},
        {"name": "shipping", "data_type": "complex", "nullable": True},
        {"name": "tax_exempt", "data_type": "text", "nullable": True},
        {"name": "test_clock", "data_type": "text", "nullable": True},
    ],

    "Subscription": [
        {"name": "id", "data_type": "text", "nullable": False},
        {"name": "object", "data_type": "text", "nullable": True},
        {"name": "application", "data_type": "text", "nullable": True},
        {"name": "application_fee_percent", "data_type": "double", "nullable": True},
        {"name": "automatic_tax", "data_type": "complex", "nullable": True},
        {"name": "billing_cycle_anchor", "data_type": "bigint", "nullable": True},
        {"name": "billing_thresholds", "data_type": "complex", "nullable": True},
        {"name": "cancel_at", "data_type": "bigint", "nullable": True},
        {"name": "cancel_at_period_end", "data_type": "bool", "nullable": True},
        {"name": "canceled_at", "data_type": "bigint", "nullable": True},
        {"name": "collection_method", "data_type": "text", "nullable": True},
        {"name": "created", "data_type": "bigint", "nullable": True},
        {"name": "currency", "data_type": "text", "nullable": True},
        {"name": "current_period_end", "data_type": "bigint", "nullable": True},
        {"name": "current_period_start", "data_type": "bigint", "nullable": True},
        {"name": "customer", "data_type": "text", "nullable": True},
        {"name": "days_until_due", "data_type": "bigint", "nullable": True},
        {"name": "default_payment_method", "data_type": "text", "nullable": True},
        {"name": "default_source", "data_type": "text", "nullable": True},
        {"name": "default_tax_rates", "data_type": "complex", "nullable": True},
        {"name": "description", "data_type": "text", "nullable": True},
        {"name": "discount", "data_type": "complex", "nullable": True},
        {"name": "ended_at", "data_type": "bigint", "nullable": True},
        {"name": "items", "data_type": "complex", "nullable": True},
        {"name": "latest_invoice", "data_type": "text", "nullable": True},
        {"name": "livemode", "data_type": "bool", "nullable": True},
        {"name": "metadata", "data_type": "complex", "nullable": True},
        {"name": "next_pending_invoice_item_invoice", "data_type": "bigint", "nullable": True},
        {"name": "on_behalf_of", "data_type": "text", "nullable": True},
        {"name": "pause_collection", "data_type": "complex", "nullable": True},
        {"name": "payment_settings", "data_type": "complex", "nullable": True},
        {"name": "pending_invoice_item_interval", "data_type": "complex", "nullable": True},
        {"name": "pending_setup_intent", "data_type": "text", "nullable": True},
        {"name": "pending_update", "data_type": "complex", "nullable": True},
        {"name": "schedule", "data_type": "text", "nullable": True},
        {"name": "start_date", "data_type": "bigint", "nullable": True},
        {"name": "status", "data_type": "text", "nullable": True},
        {"name": "test_clock", "data_type": "text", "nullable": True},
        {"name": "transfer_data", "data_type": "complex", "nullable": True},
        {"name": "trial_end", "data_type": "bigint", "nullable": True},
        {"name": "trial_start", "data_type": "bigint", "nullable": True},
    ],

    "Invoice": [
        {"name": "id", "data_type": "text", "nullable": False},
        {"name": "object", "data_type": "text", "nullable": True},
        {"name": "account_country", "data_type": "text", "nullable": True},
        {"name": "account_name", "data_type": "text", "nullable": True},
        {"name": "account_tax_ids", "data_type": "complex", "nullable": True},
        {"name": "amount_due", "data_type": "bigint", "nullable": True},
        {"name": "amount_paid", "data_type": "bigint", "nullable": True},
        {"name": "amount_remaining", "data_type": "bigint", "nullable": True},
        {"name": "application", "data_type": "text", "nullable": True},
        {"name": "application_fee_amount", "data_type": "bigint", "nullable": True},
        {"name": "attempt_count", "data_type": "bigint", "nullable": True},
        {"name": "attempted", "data_type": "bool", "nullable": True},
        {"name": "auto_advance", "data_type": "bool", "nullable": True},
        {"name": "automatic_tax", "data_type": "complex", "nullable": True},
        {"name": "billing_reason", "data_type": "text", "nullable": True},
        {"name": "charge", "data_type": "text", "nullable": True},
        {"name": "collection_method", "data_type": "text", "nullable": True},
        {"name": "created", "data_type": "bigint", "nullable": True},
        {"name": "currency", "data_type": "text", "nullable": True},
        {"name": "custom_fields", "data_type": "complex", "nullable": True},
        {"name": "customer", "data_type": "text", "nullable": True},
        {"name": "customer_address", "data_type": "complex", "nullable": True},
        {"name": "customer_email", "data_type": "text", "nullable": True},
        {"name": "customer_name", "data_type": "text", "nullable": True},
        {"name": "customer_phone", "data_type": "text", "nullable": True},
        {"name": "customer_shipping", "data_type": "complex", "nullable": True},
        {"name": "customer_tax_exempt", "data_type": "text", "nullable": True},
        {"name": "customer_tax_ids", "data_type": "complex", "nullable": True},
        {"name": "default_payment_method", "data_type": "text", "nullable": True},
        {"name": "default_source", "data_type": "text", "nullable": True},
        {"name": "default_tax_rates", "data_type": "complex", "nullable": True},
        {"name": "description", "data_type": "text", "nullable": True},
        {"name": "discount", "data_type": "complex", "nullable": True},
        {"name": "discounts", "data_type": "complex", "nullable": True},
        {"name": "due_date", "data_type": "bigint", "nullable": True},
        {"name": "ending_balance", "data_type": "bigint", "nullable": True},
        {"name": "footer", "data_type": "text", "nullable": True},
        {"name": "hosted_invoice_url", "data_type": "text", "nullable": True},
        {"name": "invoice_pdf", "data_type": "text", "nullable": True},
        {"name": "last_finalization_error", "data_type": "complex", "nullable": True},
        {"name": "lines", "data_type": "complex", "nullable": True},
        {"name": "livemode", "data_type": "bool", "nullable": True},
        {"name": "metadata", "data_type": "complex", "nullable": True},
        {"name": "next_payment_attempt", "data_type": "bigint", "nullable": True},
        {"name": "number", "data_type": "text", "nullable": True},
        {"name": "on_behalf_of", "data_type": "text", "nullable": True},
        {"name": "paid", "data_type": "bool", "nullable": True},
        {"name": "paid_out_of_band", "data_type": "bool", "nullable": True},
        {"name": "payment_intent", "data_type": "text", "nullable": True},
        {"name": "payment_settings", "data_type": "complex", "nullable": True},
        {"name": "period_end", "data_type": "bigint", "nullable": True},
        {"name": "period_start", "data_type": "bigint", "nullable": True},
        {"name": "post_payment_credit_notes_amount", "data_type": "bigint", "nullable": True},
        {"name": "pre_payment_credit_notes_amount", "data_type": "bigint", "nullable": True},
        {"name": "quote", "data_type": "text", "nullable": True},
        {"name": "receipt_number", "data_type": "text", "nullable": True},
        {"name": "rendering_options", "data_type": "complex", "nullable": True},
        {"name": "starting_balance", "data_type": "bigint", "nullable": True},
        {"name": "statement_descriptor", "data_type": "text", "nullable": True},
        {"name": "status", "data_type": "text", "nullable": True},
        {"name": "status_transitions", "data_type": "complex", "nullable": True},
        {"name": "subscription", "data_type": "text", "nullable": True},
        {"name": "subtotal", "data_type": "bigint", "nullable": True},
        {"name": "subtotal_excluding_tax", "data_type": "bigint", "nullable": True},
        {"name": "tax", "data_type": "bigint", "nullable": True},
        {"name": "test_clock", "data_type": "text", "nullable": True},
        {"name": "total", "data_type": "bigint", "nullable": True},
        {"name": "total_discount_amounts", "data_type": "complex", "nullable": True},
        {"name": "total_excluding_tax", "data_type": "bigint", "nullable": True},
        {"name": "total_tax_amounts", "data_type": "complex", "nullable": True},
        {"name": "transfer_data", "data_type": "complex", "nullable": True},
        {"name": "webhooks_delivered_at", "data_type": "bigint", "nullable": True},
    ],

    "Product": [
        {"name": "id", "data_type": "text", "nullable": False},
        {"name": "object", "data_type": "text", "nullable": True},
        {"name": "active", "data_type": "bool", "nullable": True},
        {"name": "created", "data_type": "bigint", "nullable": True},
        {"name": "default_price", "data_type": "text", "nullable": True},
        {"name": "description", "data_type": "text", "nullable": True},
        {"name": "images", "data_type": "complex", "nullable": True},
        {"name": "livemode", "data_type": "bool", "nullable": True},
        {"name": "metadata", "data_type": "complex", "nullable": True},
        {"name": "name", "data_type": "text", "nullable": True},
        {"name": "package_dimensions", "data_type": "complex", "nullable": True},
        {"name": "shippable", "data_type": "bool", "nullable": True},
        {"name": "statement_descriptor", "data_type": "text", "nullable": True},
        {"name": "tax_code", "data_type": "text", "nullable": True},
        {"name": "unit_label", "data_type": "text", "nullable": True},
        {"name": "updated", "data_type": "bigint", "nullable": True},
        {"name": "url", "data_type": "text", "nullable": True},
    ],

    "Price": [
        {"name": "id", "data_type": "text", "nullable": False},
        {"name": "object", "data_type": "text", "nullable": True},
        {"name": "active", "data_type": "bool", "nullable": True},
        {"name": "billing_scheme", "data_type": "text", "nullable": True},
        {"name": "created", "data_type": "bigint", "nullable": True},
        {"name": "currency", "data_type": "text", "nullable": True},
        {"name": "custom_unit_amount", "data_type": "complex", "nullable": True},
        {"name": "livemode", "data_type": "bool", "nullable": True},
        {"name": "lookup_key", "data_type": "text", "nullable": True},
        {"name": "metadata", "data_type": "complex", "nullable": True},
        {"name": "nickname", "data_type": "text", "nullable": True},
        {"name": "product", "data_type": "text", "nullable": True},
        {"name": "recurring", "data_type": "complex", "nullable": True},
        {"name": "tax_behavior", "data_type": "text", "nullable": True},
        {"name": "tiers_mode", "data_type": "text", "nullable": True},
        {"name": "transform_quantity", "data_type": "complex", "nullable": True},
        {"name": "type", "data_type": "text", "nullable": True},
        {"name": "unit_amount", "data_type": "bigint", "nullable": True},
        {"name": "unit_amount_decimal", "data_type": "text", "nullable": True},
    ],

    "PaymentIntent": [
        {"name": "id", "data_type": "text", "nullable": False},
        {"name": "object", "data_type": "text", "nullable": True},
        {"name": "amount", "data_type": "bigint", "nullable": True},
        {"name": "amount_capturable", "data_type": "bigint", "nullable": True},
        {"name": "amount_details", "data_type": "complex", "nullable": True},
        {"name": "amount_received", "data_type": "bigint", "nullable": True},
        {"name": "application", "data_type": "text", "nullable": True},
        {"name": "application_fee_amount", "data_type": "bigint", "nullable": True},
        {"name": "automatic_payment_methods", "data_type": "complex", "nullable": True},
        {"name": "canceled_at", "data_type": "bigint", "nullable": True},
        {"name": "cancellation_reason", "data_type": "text", "nullable": True},
        {"name": "capture_method", "data_type": "text", "nullable": True},
        {"name": "charges", "data_type": "complex", "nullable": True},
        {"name": "client_secret", "data_type": "text", "nullable": True},
        {"name": "confirmation_method", "data_type": "text", "nullable": True},
        {"name": "created", "data_type": "bigint", "nullable": True},
        {"name": "currency", "data_type": "text", "nullable": True},
        {"name": "customer", "data_type": "text", "nullable": True},
        {"name": "description", "data_type": "text", "nullable": True},
        {"name": "invoice", "data_type": "text", "nullable": True},
        {"name": "last_payment_error", "data_type": "complex", "nullable": True},
        {"name": "latest_charge", "data_type": "text", "nullable": True},
        {"name": "livemode", "data_type": "bool", "nullable": True},
        {"name": "metadata", "data_type": "complex", "nullable": True},
        {"name": "next_action", "data_type": "complex", "nullable": True},
        {"name": "on_behalf_of", "data_type": "text", "nullable": True},
        {"name": "payment_method", "data_type": "text", "nullable": True},
        {"name": "payment_method_options", "data_type": "complex", "nullable": True},
        {"name": "payment_method_types", "data_type": "complex", "nullable": True},
        {"name": "processing", "data_type": "complex", "nullable": True},
        {"name": "receipt_email", "data_type": "text", "nullable": True},
        {"name": "review", "data_type": "text", "nullable": True},
        {"name": "setup_future_usage", "data_type": "text", "nullable": True},
        {"name": "shipping", "data_type": "complex", "nullable": True},
        {"name": "statement_descriptor", "data_type": "text", "nullable": True},
        {"name": "statement_descriptor_suffix", "data_type": "text", "nullable": True},
        {"name": "status", "data_type": "text", "nullable": True},
        {"name": "transfer_data", "data_type": "complex", "nullable": True},
        {"name": "transfer_group", "data_type": "text", "nullable": True},
    ],
}


def get_schema_for_endpoint(endpoint: str) -> List[Dict]:
    """
    Get schema definition for a Stripe endpoint.

    Args:
        endpoint: Stripe endpoint name (e.g., "Charge", "Customer")

    Returns:
        List of column definitions for dlt
    """
    return STRIPE_SCHEMAS.get(endpoint, [
        # Fallback minimal schema if endpoint not defined
        {"name": "id", "data_type": "text", "nullable": True},
        {"name": "created", "data_type": "bigint", "nullable": True},
        {"name": "object", "data_type": "text", "nullable": True},
    ])
