# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class TriggerMerchantInvoiceRequestBody(UniversalBaseModel):
    """
    Examples
    --------
    import datetime

    from kard.billing_service import TriggerMerchantInvoiceRequestBody

    TriggerMerchantInvoiceRequestBody(
        start_date=datetime.datetime.fromisoformat(
            "2025-01-01 00:00:00+00:00",
        ),
        end_date=datetime.datetime.fromisoformat(
            "2025-02-01 00:00:00+00:00",
        ),
        invoice_name="2025-jan",
    )
    """

    start_date: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="startDate")] = pydantic.Field()
    """
    RFC3339 time indicating the start of the billing period (inclusive)
    """

    end_date: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="endDate")] = pydantic.Field()
    """
    RFC3339 time indicating the end of the billing period (exclusive)
    """

    invoice_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="invoiceName")] = (
        pydantic.Field(default=None)
    )
    """
    optional name for the invoice. If none is provided, one will be generated.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
