error_messages = {
    "ConnectionFailure": "Connection failure occurred.",
    "OperationFailure": "Operation failure occurred.",
    "ServerSelectionTimeoutError": "Server selection timeout error occurred.",
    "CollectionInvalid": "Collection invalid error occurred.",
    "ConfigurationError": "Configuration error occurred.",
    "DuplicateKeyError": "Duplicate key error occurred.",
    "InvalidURI": "Invalid URI error occurred.",
    "WriteError": "Write error occurred.",
    "WriteConcernError": "Write concern error occurred.",
    "NetworkTimeout": "Network timeout error occurred.",
    "InvalidName": "Invalid name error occurred.",
    "InvalidOperation": "Invalid operation error occurred.",
    "ConnectionError": "Connection error occurred.",
    "RetryError": "Retry error occurred.",
    "TimeoutError": "Timeout error occurred.",
    "ValueError": "Value error occurred.",
    "TypeError": "Type error occurred.",
    "KeyError": "Key error occurred.",
    "IndexError": "Index error occurred.",
    "AttributeError": "Attribute error occurred.",
    "JSONDecodeError": "JSON decode error occurred.",
    "DatabaseError": "Database error occurred.",
    "IntegrityError": "Integrity error occurred.",
    "OperationalError": "Operational error occurred.",
    "ProgrammingError": "Programming error occurred.",
    "DataError": "Data error occurred.",
    "NotSupportedError": "Not supported error occurred.",
    "FileNotFoundError": "File not found error occurred.",
    "PermissionError": "Permission error occurred.",
    "IsADirectoryError": "Is a directory error occurred.",
    "NotADirectoryError": "Not a directory error occurred.",
    "OSError": "OS error occurred.",
    "ZeroDivisionError": "Division by zero error occurred.",
    "ImportError": "Import error occurred.",
    "ModuleNotFoundError": "Module not found error occurred.",
    "MemoryError": "Memory error occurred.",
    "OverflowError": "Overflow error occurred.",
    "RecursionError": "Recursion error occurred.",
    "ReferenceError": "Reference error occurred.",
    "RuntimeError": "Runtime error occurred.",
    "SyntaxError": "Syntax error occurred.",
    "IndentationError": "Indentation error occurred.",
    "TabError": "Tab error occurred.",
    "SystemError": "System error occurred.",
    "SystemExit": "System exit occurred.",
    "KeyboardInterrupt": "Keyboard interrupt occurred.",
    "GeneratorExit": "Generator exit occurred.",
    "StopIteration": "Stop iteration occurred.",
    "StopAsyncIteration": "Stop async iteration occurred."
}