from py_wlcommands.lib import HAS_RUST_EXTENSION as HAS_RUST_EXTENSION, sum_as_string as sum_as_string

def test_sum_as_string() -> None: ...
def test_sum_as_string_rust_available() -> None: ...
def test_sum_as_string_fallback() -> None: ...
