import argparse
from ...commands.base import BaseCommand
from .format_coordinator import FormatCoordinator as FormatCoordinator
from _typeshed import Incomplete
from pathlib import Path as Path

class FormatCommand(BaseCommand):
    coordinator: Incomplete
    def __init__(self) -> None: ...
    def run(self, *args, **kwargs): ...
    @property
    def name(self) -> str: ...
    @property
    def help(self) -> str: ...
    def add_arguments(self, parser: argparse.ArgumentParser) -> None: ...
    def execute(self, *args, **kwargs) -> None: ...
