import types
from ..exceptions import CommandError as CommandError
from _typeshed import Incomplete

class ErrorHandler:
    @staticmethod
    def handle_error(error: Exception, context: str | None = None) -> None: ...
    @staticmethod
    def wrap_command_execution(func, *args, **kwargs): ...

class ErrorContext:
    context: Incomplete
    def __init__(self, context: str) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None): ...
