from _typeshed import Incomplete
from pathlib import Path

class FileOperationResult:
    success: Incomplete
    message: Incomplete
    files_affected: Incomplete
    def __init__(self, success: bool, message: str = '', files_affected: list[str] | None = None) -> None: ...

class FileOperationsCache:
    def __init__(self) -> None: ...
    def clear(self) -> None: ...

class FileOperations:
    cache: Incomplete
    def __init__(self) -> None: ...
    def exists(self, path: str | Path) -> bool: ...
    def get_files_in_directory(self, directory: str | Path, pattern: str = '*', recursive: bool = True) -> list[Path]: ...
    def copy_file(self, src: str | Path, dst: str | Path) -> FileOperationResult: ...
    def copy_directory(self, src: str | Path, dst: str | Path, exclude_patterns: list[str] | None = None) -> FileOperationResult: ...
    def remove_directory(self, directory: str | Path) -> FileOperationResult: ...
    def clear_cache(self) -> None: ...

def get_file_operations() -> FileOperations: ...
