from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

@dataclass
class PerformanceMetrics:
    operation_name: str
    execution_time: float
    start_time: float
    end_time: float
    success: bool
    additional_data: dict[str, Any] = field(default_factory=dict)

class PerformanceMonitor:
    def __init__(self) -> None: ...
    def start_operation(self, operation_name: str) -> None: ...
    def end_operation(self, operation_name: str, success: bool = True, **additional_data: Any) -> PerformanceMetrics: ...
    def record_operation(self, operation_name: str, execution_time: float, success: bool = True, **additional_data: Any) -> PerformanceMetrics: ...
    @contextmanager
    def monitor_operation(self, operation_name: str, **additional_data: Any): ...
    def get_metrics(self) -> list[PerformanceMetrics]: ...
    def get_average_execution_time(self, operation_name: str) -> float | None: ...
    def clear_metrics(self) -> None: ...
    def export_metrics(self, file_path: Path) -> None: ...

def monitor_performance(operation_name: str, **additional_data: Any): ...
def get_performance_monitor() -> PerformanceMonitor: ...
def start_operation(operation_name: str) -> None: ...
def end_operation(operation_name: str, success: bool = True, **additional_data: Any) -> PerformanceMetrics: ...
@contextmanager
def monitor_operation(operation_name: str, **additional_data: Any): ...
