from pathlib import Path

def is_running_in_uv_tool() -> bool: ...
def get_uv_tool_python_path() -> str | None: ...
def get_uv_tool_bin_path() -> Path | None: ...
def get_uv_tool_env() -> dict[str, str]: ...
def should_use_direct_execution(command: list[str]) -> bool: ...
def get_direct_command(command: list[str]) -> list[str]: ...
