from .logging import log_info as log_info
from .subprocess_utils import SubprocessExecutor as SubprocessExecutor
from pathlib import Path

class UVWorkspaceDetector:
    def __init__(self) -> None: ...
    def is_workspace(self, project_root: Path | None = None) -> bool: ...
    def clear_cache(self) -> None: ...

def is_uv_workspace(project_root: Path | None = None) -> bool: ...
def clear_uv_workspace_cache() -> None: ...
