-- Unity Catalog Delta table for d_promotion_3_0
CREATE TABLE IF NOT EXISTS catalog.schema.d_promotion_3_0 (
    promotionid STRING NOT NULL,
    promotioncode STRING,
    promotiondescription STRING,
    promotiontype STRING,
    promotionstartdate TIMESTAMP,
    promotionenddate TIMESTAMP,
    couponmin INT,
    couponmax INT,
    promotionskus STRING,
    excld_promo_sku STRING,
    promo_elements STRING,
    tieredskus STRING,
    excld_tier_sku STRING,
    bundleskus STRING,
    excld_bundle_sku STRING,
    discount_sku STRING,
    discount_excld_sku STRING,
    discountinfo STRING,
    key STRING,
    uniquepromoflag BOOLEAN,
    sitewideflag BOOLEAN,
    prepaidflag BOOLEAN,
    personalizedpromoflag BOOLEAN,
    marketinitiative STRING,
    partnerid STRING,
    program STRING,
    campaigntype STRING,
    campaignname STRING,
    vertical STRING,
    mediatype STRING,
    marketingbranch STRING,
    eventinstime TIMESTAMP,
    eventupdtime TIMESTAMP,
    dailystarttime STRING,
    dailyendtime STRING,
    limitsglobal BIGINT,
    limitsorder BIGINT,
    limitscustomer BIGINT,
    deliverymethod STRING,
    deliveryoption STRING,
    sourcegroups STRING,
    skuspurchasetype STRING,
    purchasetype STRING,
    redemptionmethod STRING,
    tags STRING,
    minimumpurchase DECIMAL(10,2),
    maximumdiscounted DECIMAL(10,2),
    promo_properties STRING,
    periscopeid STRING,
    dwcreatedby STRING,
    dwcreatedat TIMESTAMP,
    etl_created_at TIMESTAMP,
    etl_created_by STRING
)
USING DELTA
PARTITIONED BY (promotiontype)
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
);