# Description: This file contains the data for the countries and their synonyms.
COUNTRIES_SYNONYMS = {
    "afghanistan": [],
    "albania": [],
    "algeria": [],
    "andorra": [],
    "angola": [],
    "antigua and barbuda": [],
    "argentina": [],
    "armenia": [],
    "australia": [],
    "austria": [],
    "azerbaijan": [],
    "bahamas": [],
    "bahrain": [],
    "bangladesh": [],
    "barbados": [],
    "belarus": [],
    "belgium": [],
    "belize": [],
    "benin": [],
    "bhutan": [],
    "bolivia": [],
    "bosnia and herzegovina": [],
    "botswana": [],
    "brazil": [],
    "brunei": [],
    "bulgaria": [],
    "burkina faso": [],
    "burundi": [],
    "cabo verde": ["cape verde"],
    "cambodia": [],
    "cameroon": [],
    "canada": [],
    "central african republic": [],
    "chad": [],
    "chile": [],
    "china": [],
    "colombia": [],
    "comoros": [],
    "congo (congo-brazzaville)": ["republic of the congo"],
    "costa rica": [],
    "croatia": [],
    "cuba": [],
    "cyprus": [],
    "czechia (czech republic)": ["czechia", "czech republic"],
    "democratic republic of the congo": ["dr congo", "drc", "congo-kinshasa"],
    "denmark": [],
    "djibouti": [],
    "dominica": [],
    "dominican republic": [],
    "ecuador": [],
    "egypt": [],
    "el salvador": [],
    "equatorial guinea": [],
    "eritrea": [],
    "estonia": [],
    "eswatini": ["swaziland"],
    "ethiopia": [],
    "fiji": [],
    "finland": [],
    "france": [],
    "gabon": [],
    "gambia": [],
    "georgia": [],
    "germany": [],
    "ghana": [],
    "greece": [],
    "grenada": [],
    "guatemala": [],
    "guinea": [],
    "guinea-bissau": [],
    "guyana": [],
    "haiti": [],
    "holy see": ["vatican city"],
    "honduras": [],
    "hungary": [],
    "iceland": [],
    "india": [],
    "indonesia": [],
    "iran": [],
    "iraq": [],
    "ireland": [],
    "israel": [],
    "italy": [],
    "jamaica": [],
    "japan": [],
    "jordan": [],
    "kazakhstan": [],
    "kenya": [],
    "kiribati": [],
    "kuwait": [],
    "kyrgyzstan": [],
    "laos": [],
    "latvia": [],
    "lebanon": [],
    "lesotho": [],
    "liberia": [],
    "libya": [],
    "liechtenstein": [],
    "lithuania": [],
    "luxembourg": [],
    "madagascar": [],
    "malawi": [],
    "malaysia": [],
    "maldives": [],
    "mali": [],
    "malta": [],
    "marshall islands": [],
    "mauritania": [],
    "mauritius": [],
    "mexico": [],
    "micronesia": [],
    "moldova": [],
    "monaco": [],
    "mongolia": [],
    "montenegro": [],
    "morocco": [],
    "mozambique": [],
    "myanmar": ["burma"],
    "namibia": [],
    "nauru": [],
    "nepal": [],
    "netherlands": ["holland"],
    "new zealand": [],
    "nicaragua": [],
    "niger": [],
    "nigeria": [],
    "north korea": [],
    "north macedonia": [],
    "norway": [],
    "oman": [],
    "pakistan": [],
    "palau": [],
    "palestine state": ["palestine"],
    "panama": [],
    "papua new guinea": [],
    "paraguay": [],
    "peru": [],
    "philippines": [],
    "poland": [],
    "portugal": [],
    "qatar": [],
    "romania": [],
    "russia": ["russian federation"],
    "rwanda": [],
    "saint kitts and nevis": [],
    "saint lucia": [],
    "saint vincent and the grenadines": [],
    "samoa": [],
    "san marino": [],
    "sao tome and principe": [],
    "saudi arabia": [],
    "senegal": [],
    "serbia": [],
    "seychelles": [],
    "sierra leone": [],
    "singapore": [],
    "slovakia": [],
    "slovenia": [],
    "solomon islands": [],
    "somalia": [],
    "south africa": [],
    "south korea": [],
    "south sudan": [],
    "spain": [],
    "sri lanka": [],
    "sudan": [],
    "suriname": [],
    "sweden": [],
    "switzerland": [],
    "syria": [],
    "tajikistan": [],
    "tanzania": [],
    "thailand": [],
    "timor-leste": ["east timor"],
    "togo": [],
    "tonga": [],
    "trinidad and tobago": [],
    "tunisia": [],
    "turkey": [],
    "turkmenistan": [],
    "tuvalu": [],
    "uganda": [],
    "ukraine": [],
    "united arab emirates": ["uae"],
    "united kingdom": ["uk", "great britain", "britain"],
    "united states of america": ["usa", "us", "america"],
    "uruguay": [],
    "uzbekistan": [],
    "vanuatu": [],
    "venezuela": [],
    "vietnam": [],
    "yemen": [],
    "zambia": [],
    "zimbabwe": [],
}

human_entity_roles = [
    "person",
    "doctor",
    "provider",
    "scientist",
    "patient",
    "nurse",
    "surgeon",
    "teacher",
    "student",
    "lawyer",
    "engineer",
    "architect",
    "carpenter",
    "police officer",
    "firefighter",
    "actor",
    "singer",
    "athlete",
    "manager",
    "assistant",
    "driver",
    "chef",
    "scientist",
    "researcher",
    "president",
    "CEO",
    "clerk",
    "administrator",
    "accountant",
    "plumber",
    "electrician",
    "mechanic",
    "consultant",
    "analyst",
]
