from _typeshed import Incomplete

EXTENSIONS: Incomplete

def extension_available(ext_base_name, verbose: bool = False): ...
@_cache
def gpu_available(ext_base_name, verbose: bool = False): ...
@_cache
def mpi_built(verbose: bool = False): ...
@_cache
def nccl_built(verbose: bool = False): ...
