# Copyright 2023 OpenSynergy Indonesia
# Copyright 2023 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Equipment Request",
    "version": "14.0.4.2.0",
    "website": "https://simetri-sinergi.id",
    "author": "PT. Simetri Sinergi Indonesia, OpenSynergy Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "depends": [
        "ssi_stock",
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_ready_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_terminate_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_date_due_mixin",
        "ssi_product_line_price_mixin",
        "ssi_employee_document_mixin",
        "base_automation",
        "ssi_product",
        "ssi_m2o_configurator_mixin",
        "ssi_stock_location_m2o_configurator_mixin",
        "ssi_stock_route_m2o_configurator_mixin",
        "ssi_stock_warehouse_m2o_configurator_mixin",
        "ssi_hr_employee_stock",
        "ssi_stock_equipment_operation",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/res_group_data.xml",
        "security/ir.model.access.csv",
        "security/ir_rule_data.xml",
        "data/ir_sequence_data.xml",
        "data/sequence_template_data.xml",
        "data/policy_template_data.xml",
        "data/approval_template_data.xml",
        "data/equipment_request_policy_field_data.xml",
        "data/equipment_request_policy_data.xml",
        "data/equipment_request_operation_data.xml",
        "menu.xml",
        "data/ir_actions_server_data.xml",
        "data/base_automation_data.xml",
        "views/equipment_request_policy_field_view.xml",
        "views/equipment_request_policy_view.xml",
        "views/equipment_request_operation.xml",
        "views/equipment_request_type_views.xml",
        "views/equipment_request_views.xml",
        "views/hr_employee_views.xml",
    ],
    "demo": [],
    "images": [],
}
