import setuptools

with open("odoo/addons/somconnexio/README.rst") as f:
    long_description = f.read()

setuptools.setup(
    setup_requires=["setuptools-odoo"],
    long_description=long_description,
    long_description_content_type="text/x-rst",
    odoo_addon={
#        "depends_override": {
#            "account_asset_management": "odoo-addon-account-asset-management==16.0.1.1.1.5",
#            "account_banking_sepa_credit_transfer": "odoo-addon-account-banking-sepa-credit-transfer==16.0.1.1.3",
#            "account_banking_sepa_direct_debit": "odoo-addon-account-banking-sepa-direct-debit==16.0.1.4.3",
#            "account_chart_update": "odoo-addon-account-chart-update==16.0.2.0.3",
#            "account_due_list": "odoo-addon-account-due-list==16.0.1.2.0.1",
#            "account_financial_report": "odoo-addon-account-financial-report==16.0.1.4.0",
#            # "account_invoice_validation_queued": "odoo-addon-account-invoice-validation-queued==12.0.1.0.0.99.dev3",
#            "account_payment_mode": "odoo-addon-account-payment-mode==16.0.1.2.0.4",
#            "account_payment_order": "odoo-addon-account-payment-order==16.0.1.11.3",
#            "account_payment_partner": "odoo-addon-account-payment-partner==16.0.1.2.2",
#            "account_payment_return": "odoo-addon-account-payment-return==16.0.1.0.2",
#            "auth_oidc": "odoo-addon-auth-oidc==16.0.1.0.2",
#            "base_import_async": "odoo-addon-base-import-async==16.0.1.1.0.3",
#            # "check_concurrent_update": "odoo-addon-check-concurrent-update==12.0.1.0.0",
#            "component": "odoo-addon-component==16.0.1.1.1.1",
#            "component_event": "odoo-addon-component-event==16.0.1.0.1.3",
#            "contract": "odoo-addon-contract==16.0.2.0.0.1",
#            # "contract_group": "odoo-addon-contract-group==12.0.0.0.0",
#            # "contract_mandate": "odoo-addon-contract-mandate==12.0.1.0.2",
#            "contract_payment_mode": "odoo-addon-contract-payment-mode==16.0.1.0.0.4",
#            # "crm_lead_product": "git+https://github.com/coopdevs/crm@16.0-mig-crm-lead-product#egg=odoo-addon-crm-lead-product&subdirectory=setup/crm_lead_product",
#            "date_range": "odoo-addon-date-range==16.0.1.0.9",
#            "disable_login": "odoo-addon-disable-login==16.0.1.0.0.3",
#            # "email_template_config": "odoo-addon-email-template-config==12.0.1.0.0.99.dev3",
#            "hr_attendance_report_theoretical_time": "odoo-addon-hr-attendance-report-theoretical-time==16.0.1.1.0.6",
#            "hr_holidays_public": "odoo-addon-hr-holidays-public==16.0.1.1.3",
#            "l10n_es_account_asset": "odoo-addon-l10n-es-account-asset==16.0.1.1.0",
#            "l10n_es_account_bank_statement_import_n43": "odoo-addon-l10n-es-account-bank-statement-import-n43==16.0.1.0.3",
#            "l10n_es_aeat": "odoo-addon-l10n-es-aeat==16.0.2.1.8",
#            "l10n_es_aeat_mod111": "odoo-addon-l10n-es-aeat-mod111==16.0.1.1.0",
#            "l10n_es_aeat_mod190": "odoo-addon-l10n-es-aeat-mod190==16.0.1.1.0",
#            "l10n_es_aeat_mod303": "odoo-addon-l10n-es-aeat-mod303==16.0.2.3.2.4.0",
#            "l10n_es_aeat_mod347": "odoo-addon-l10n-es-aeat-mod347==16.0.2.0.0.99.dev2",
#            "l10n_es_aeat_mod349": "odoo-addon-l10n-es-aeat-mod349==16.0.1.1.2",
#            "l10n_es_aeat_mod390": "odoo-addon-l10n-es-aeat-mod390==16.0.2.2.2.4.0",
#            "l10n_es_mis_report": "odoo-addon-l10n-es-mis-report==16.0.1.1.0",
#            "l10n_es_partner": "odoo-addon-l10n-es-partner==16.0.2.1.0",
#            "l10n_es_toponyms": "odoo-addon-l10n-es-toponyms==16.0.1.0.0.99.dev9",
#            "mail_activity_board": "odoo-addon-mail-activity-board==16.0.1.1.1",
#            "mail_activity_done": "odoo-addon-mail-activity-done==16.0.1.1.0",
#            "mandate_partner_bank_creation": "odoo-addon-mandate-partner-bank-creation==16.0.1.0.0",
#            "mass_editing": "odoo-addon-mass-editing==16.0.2.2.0",
#            "mass_mailing_list_dynamic": "odoo-addon-mass-mailing-list-dynamic==16.0.1.0.3",
#            "mass_mailing_patern": "odoo-addon-mass-mailing-partner==16.0.1.0.7",
#            "mis_builder": "odoo-addon-mis-builder==16.0.5.1.7",
#            "mis_builder_budget": "odoo-addon-mis-builder-budget==16.0.5.0.3",
#            "partner_firstname": "odoo-addon-partner-firstname==16.0.1.0.1.9",
#            "product_pack": "odoo-addon-product-pack==16.0.1.1.0.1",
#            "queue_job": "odoo-addon-queue-job==16.0.1.5.0",
#            "server_environment": "odoo-addon-server-environment==16.0.1.0.3.2",
#            "web_m2x_options": "odoo-addon-web-m2x-options==16.0.1.1.2",
#            "web_decimal_numpad_dot": "odoo-addon-web-decimal-numpad-dot==16.0.1.0.0.99.dev9",
#            "web_favicon": "odoo-addon-web-favicon==16.0.1.0.0.99.dev14",
#            "web_no_bubble": "odoo-addon-web-no-bubble==16.0.1.0.0.99.dev8",
#            "web_responsive": "odoo-addon-web-responsive==16.0.1.2.4",
#            "web_searchbar_full_width": "odoo-addon-web-searchbar-full-width==16.0.1.0.0.99.dev6",
#            "web_widget_open_tab": "odoo-addon-web-widget-open-tab==16.0.1.0.1.99.dev2",
#        },
        "external_dependencies_override": {
            "python": {
                "factory": "factory-boy",
                "faker": "faker==9.3.1",
                "hashids": "hashids==1.3.1",
                "mm_proxy_python_client": "mm-proxy-python-client==0.1.0",
                "stdnum": "python-stdnum==1.14",
            },
        },
    },
)
