class InstallationManager:
    def prepare_environment(self) -> tuple[str, dict]: ...
    def uninstall_existing(self, uv_path: str, env: dict) -> None: ...
    def is_file_in_use_error(self, error_msg: str) -> bool: ...
    def detect_installation_method(self) -> str: ...
