# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class AuditEventAuthor_User(UniversalBaseModel):
    """
    Author of an action, either a user or a system

    Examples
    --------
    from kard.commons import AuditEventAuthor_User

    AuditEventAuthor_User(
        id="507f1f77bcf86cd799439011",
    )
    """

    type: typing.Literal["user"] = "user"
    id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AuditEventAuthor_System(UniversalBaseModel):
    """
    Author of an action, either a user or a system

    Examples
    --------
    from kard.commons import AuditEventAuthor_User

    AuditEventAuthor_User(
        id="507f1f77bcf86cd799439011",
    )
    """

    type: typing.Literal["system"] = "system"
    id: str
    display_name: typing_extensions.Annotated[str, FieldMetadata(alias="displayName")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


"""
from kard.commons import AuditEventAuthor_User

AuditEventAuthor_User(
    id="507f1f77bcf86cd799439011",
)
"""
AuditEventAuthor = typing_extensions.Annotated[
    typing.Union[AuditEventAuthor_User, AuditEventAuthor_System], pydantic.Field(discriminator="type")
]
