from typing import Any

class LogFormatter:
    def format_human_log(self, record: dict[str, Any]) -> str: ...
    def format_console_log(self, record: dict[str, Any]) -> str: ...
    def format_json_log(self, record: dict[str, Any]) -> str: ...
