from collections.abc import Generator
from dataclasses import dataclass
from typing import Any, Mapping

from _typeshed import Incomplete

@dataclass(eq=False)
class SvyError(Exception):
    """
    Base svy error with rich context + multiple renderers.
    Keep `title` short; put specifics in `detail`.
    """

    title: str
    detail: str
    code: str = ...
    where: str | None = ...
    param: str | None = ...
    got: Any = ...
    expected: Any = ...
    hint: str | None = ...
    docs_url: str | None = ...
    extra: Mapping[str, Any] | None = ...
    http_status: int = ...
    def text(self, *, indent: int = 2, surround: bool = True) -> str: ...
    def summary(self) -> str: ...
    def ansi(self) -> str: ...
    def markdown(self) -> str: ...
    def html(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __rich_console__(self, console, options) -> Generator[Incomplete]: ...
