# Copyright (C) 2025-2025 Pico Technology Ltd. See LICENSE file for terms.
# flake8: noqa
# pylint: skip-file

ERROR_STRING = {
    0: "Pico Ok: The PicoScope is functioning correctly.",
    1: "Pico Max Units Opened: An attempt has been made to open more than MAX_UNITS.",
    2: "Pico Memory Fail: Not enough memory could be allocated on the host machine.",
    3: "Pico Not Found: No Pico Technology device could be found.",
    4: "Pico Fw Fail: Unable to download firmware.",
    5: "Pico Open Operation In Progress: The driver is busy opening a device.",
    6: "Pico Operation Failed: An unspecified failure occurred.",
    7: "Pico Not Responding: The PicoScope is not responding to commands from the PC.",
    8: "Pico Config Fail: The configuration information in the PicoScope is corrupt or missing.",
    9: "Pico Kernel Driver Too Old: The picopp.sys file is too old to be used with the device driver.",
    10: "Pico Eeprom Corrupt: The EEPROM has become corrupt, so the device will use a default setting.",
    11: "Pico Os Not Supported: The operating system on the PC is not supported by this driver.",
    12: "Pico Invalid Handle: There is no device with the handle value passed.",
    13: "Pico Invalid Parameter: A parameter value is not valid.",
    14: "Pico Invalid Timebase: The timebase is not supported or is invalid.",
    15: "Pico Invalid Voltage Range: The voltage range is not supported or is invalid.",
    16: "Pico Invalid Channel: The channel number is not valid or no channels have been set.",
    17: "Pico Invalid Trigger Channel: The channel set for a trigger is not available on this device.",
    18: "Pico Invalid Condition Channel: The channel set for a condition is not available on this device.",
    19: "Pico No Signal Generator: The device does not have a signal generator.",
    20: "Pico Streaming Failed: Streaming has failed to start or has stopped without user request.",
    21: "Pico Block Mode Failed: Block failed to start - a parameter may have been set wrongly.",
    22: "Pico Null Parameter: A parameter that was required is NULL.",
    23: "Pico Ets Mode Set: The current functionality is not available while using ETS capture mode.",
    24: "Pico Data Not Available: No data is available from a run block call.",
    25: "Pico String Buffer To Small: The buffer passed for the information was too small.",
    26: "Pico Ets Not Supported: ETS is not supported on this device.",
    27: "Pico Auto Trigger Time To Short: Auto trigger time is less than pre-trigger data collection time.",
    28: "Pico Buffer Stall: The collection of data has stalled as unread data would be overwritten.",
    29: "Pico Too Many Samples: Number of samples requested is more than available in the current segment.",
    30: "Pico Too Many Segments: Not possible to create number of segments requested.",
    31: "Pico Pulse Width Qualifier: A null pointer or out of range parameter in trigger function.",
    32: "Pico Delay: One or more of the hold-off parameters are out of range.",
    33: "Pico Source Details: One or more of the source details are incorrect.",
    34: "Pico Conditions: One or more of the conditions are incorrect.",
    35: "Pico User Callback: Driver thread in Ready callback; action cannot be carried out.",
    36: "Pico Device Sampling: Getting data while streaming. Stop, or use GetStreamingLatestValues.",
    37: "Pico No Samples Available: Data is unavailable because a run has not been completed.",
    38: "Pico Segment Out Of Range: The memory segment index is out of range.",
    39: "Pico Busy: The device is busy so data cannot be returned yet.",
    40: "Pico Startindex Invalid: The start time to get stored data is out of range.",
    41: "Pico Invalid Info: The information number requested is not a valid number.",
    42: "Pico Info Unavailable: Handle is invalid. Only PICO_DRIVER_VERSION is available.",
    43: "Pico Invalid Sample Interval: The sample interval selected for streaming is out of range.",
    44: "Pico Trigger Error: ETS is set but no trigger has been set. A trigger is required for ETS.",
    45: "Pico Memory: Driver cannot allocate memory.",
    46: "Pico Sig Gen Param: Incorrect parameter passed to the signal generator.",
    47: "Pico Shots Sweeps Warning: Conflict between the shots and sweeps parameters for signal generator.",
    48: "Pico Siggen Trigger Source: Software trigger sent but trigger source is not software trigger.",
    49: "Pico Aux Output Conflict: SetTrigger call found a conflict between trigger source and AUX output.",
    50: "Pico Aux Output Ets Conflict: ETS mode is being used and AUX is set as an input.",
    51: "Pico Warning Ext Threshold Conflict: Different EXT thresholds set for sig gen and scope trigger.",
    52: "Pico Warning Aux Output Conflict: SetTrigger set AUX as output, but sig gen is using it as trigger.",
    53: "Pico Siggen Output Over Voltage: Siggen Vpp + offset exceeds the maximum generator voltage.",
    54: "Pico Delay Null: NULL pointer passed as delay parameter.",
    55: "Pico Invalid Buffer: The buffers for overview data have not been set while streaming.",
    56: "Pico Siggen Offset Voltage: The analog offset voltage is out of range.",
    57: "Pico Siggen Pk To Pk: The analog peak-to-peak voltage is out of range.",
    58: "Pico Cancelled: A block collection has been cancelled.",
    59: "Pico Segment Not Used: The segment index is not currently being used.",
    60: "Pico Invalid Call: The wrong GetValues function has been called for the collection mode.",
    61: "Pico Get Values Interrupted: Get Values Interrupted.",
    63: "Pico Not Used: The function is not available.",
    64: "Pico Invalid Sampleratio: The aggregation ratio requested is out of range.",
    65: "Pico Invalid State: Device is in an invalid state.",
    66: "Pico Not Enough Segments: Segments allocated is fewer than the number of captures requested.",
    67: "Pico Driver Function: A driver function has already been called and not yet finished.",
    68: "Pico Reserved: Not used.",
    69: "Pico Invalid Coupling: An invalid coupling type was specified in SetChannel.",
    70: "Pico Buffers Not Set: Attempt to get data before a data buffer was defined.",
    71: "Pico Ratio Mode Not Supported: The selected downsampling mode is not allowed.",
    72: "Pico Rapid Not Support Aggregation: Aggregation was requested in rapid block mode.",
    73: "Pico Invalid Trigger Property: An invalid parameter was passed to SetTriggerChannelProperties(V2).",
    74: "Pico Interface Not Connected: The driver was unable to contact the oscilloscope.",
    75: "Pico Resistance And Probe Not Allowed: Resistance-measuring mode not allowed with specified probe.",
    76: "Pico Power Failed: The device was unexpectedly powered down.",
    77: "Pico Siggen Waveform Setup Failed: Problem in SetSigGenBuiltIn or SetSigGenArbitrary.",
    78: "Pico Fpga Fail: FPGA not successfully set up.",
    79: "Pico Power Manager: Power Manager.",
    80: "Pico Invalid Analogue Offset: An impossible analog offset value was specified in SetChannel.",
    81: "Pico Pll Lock Failed: There is an error within the device hardware.",
    82: "Pico Analog Board: There is an error within the device hardware.",
    83: "Pico Config Fail Awg: Unable to configure the signal generator.",
    84: "Pico Initialise Fpga: The FPGA cannot be initialized, so unit cannot be opened.",
    86: "Pico External Frequency Invalid: Frequency for external clock is not within 15% of nominal value.",
    87: "Pico Clock Change Error: The FPGA could not lock the clock signal.",
    88: "Pico Trigger And External Clock Clash: AUX input configured as both trigger and reference clock.",
    89: "Pico Pwq And External Clock Clash: AUX input configured as both pulse width qualifier and reference clock.",
    90: "Pico Unable To Open Scaling File: The requested scaling file cannot be opened.",
    91: "Pico Memory Clock Frequency: The frequency of the memory is reporting incorrectly.",
    92: "Pico I2c Not Responding: The I2C that is being actioned is not responding to requests.",
    93: "Pico No Captures Available: There are no captures available; no data can be returned.",
    94: "Pico Not Used In This Capture Mode: Capture mode does not support the current request.",
    95: "Pico Too Many Trigger Channels In Use: Too many trigger channels (> 4). (PS4824 exception).",
    96: "Pico Invalid Trigger Direction: Invalid trigger direction (e.g. PICO_ABOVE without crossing).",
    97: "Pico Invalid Trigger States: More than 4 trigger channels set and states not CONDITION_TRUE.",
    259: "Pico Get Data Active: Get Data Active.",
    260: "Pico Ip Networked: Device is IP networked; call is not supported.",
    261: "Pico Invalid Ip Address: An incorrect IP address has been passed to the driver.",
    262: "Pico Ipsocket Failed: The IP socket has failed.",
    263: "Pico Ipsocket Timedout: The IP socket has timed out.",
    264: "Pico Settings Failed: Failed to apply the requested settings.",
    265: "Pico Network Failed: The network connection has failed.",
    266: "Pico Ws2 32 Dll Not Loaded: Unable to load the WS2_32.DLL.",
    267: "Pico Invalid Ip Port: The specified IP port is invalid.",
    268: "Pico Coupling Not Supported: The type of coupling requested is not supported on the opened device.",
    269: "Pico Bandwidth Not Supported: Bandwidth limiting is not supported on the opened device.",
    270: "Pico Invalid Bandwidth: The value requested for the bandwidth limit is out of range.",
    271: "Pico Awg Not Supported: The arbitrary waveform generator is not supported by the opened device.",
    272: "Pico Ets Not Running: Data requested with ETS mode set but run block/stop has been called.",
    273: "Pico Sig Gen Whitenoise Not Supported: White noise output is not supported on the opened device.",
    274: "Pico Sig Gen Wavetype Not Supported: The wave type requested is not supported by the opened device.",
    275: "Pico Invalid Digital Port: The requested digital port number is out of range (MSOs only).",
    276: "Pico Invalid Digital Channel: The digital channel is not in the supported range.",
    277: "Pico Invalid Digital Trigger Direction: The digital trigger direction is not a valid trigger direction.",
    278: "Pico Sig Gen Prbs Not Supported: Signal generator does not generate pseudo-random binary sequence.",
    279: "Pico Ets Not Available With Logic Channels: When a digital port is enabled, ETS is not available.",
    280: "Pico Warning Repeat Value: No new sample taken; this value has already been returned previously.",
    281: "Pico Power Supply Connected: The DC power supply is connected.",
    282: "Pico Power Supply Not Connected: DC power supply not connected. Feature set restricted.",
    283: "Pico Power Supply Request Invalid: Incorrect power mode passed for current power source.",
    284: "Pico Power Supply Undervoltage: The supply voltage from the USB source is too low.",
    285: "Pico Capturing Data: The oscilloscope is in the process of capturing data.",
    286: "Pico Usb3 0 Device Non Usb3 0 Port: A USB 3.0 device is connected to a non-USB 3.0 port.",
    287: "Pico Not Supported By This Device: A function has been called that is not supported by the device.",
    288: "Pico Invalid Device Resolution: The device resolution is invalid (out of range).",
    289: "Pico Invalid Number Channels For Resolution: Channel limit in 15/16-bit modes (Flex Res scopes).",
    290: "Pico Channel Disabled Due To Usb Powered: USB power not sufficient for all requested channels.",
    291: "Pico Siggen Dc Voltage Not Configurable: Sig gen does not have a configurable DC offset.",
    292: "Pico No Trigger Enabled For Trigger In Pre Trig: Defining pre-trigger delay without trigger enabled.",
    293: "Pico Trigger Within Pre Trig Not Armed: Defining pre-trigger delay without trigger armed.",
    294: "Pico Trigger Within Pre Not Allowed With Delay: Pre-trigger delay and post-trigger delay conflict.",
    295: "Pico Trigger Index Unavailable: The array index points to a nonexistent trigger.",
    296: "Pico Awg Clock Frequency: Awg Clock Frequency.",
    297: "Pico Too Many Channels In Use: More than 4 analog channels with a trigger condition set.",
    298: "Pico Null Conditions: The condition parameter is a null pointer.",
    299: "Pico Duplicate Condition Source: More than one condition pertaining to the same channel.",
    300: "Pico Invalid Condition Info: The parameter relating to condition information is out of range.",
    301: "Pico Settings Read Failed: Reading the meta data has failed.",
    302: "Pico Settings Write Failed: Writing the meta data has failed.",
    303: "Pico Argument Out Of Range: A parameter has a value out of the expected range.",
    304: "Pico Hardware Version Not Supported: Driver does not support the hardware variant connected.",
    305: "Pico Digital Hardware Version Not Supported: Driver does not support the digital hardware variant.",
    306: "Pico Analogue Hardware Version Not Supported: Driver does not support the analog hardware variant.",
    307: "Pico Unable To Convert To Resistance: Converting a channel's ADC value to resistance has failed.",
    308: "Pico Duplicated Channel: The channel is listed more than once in the function call.",
    309: "Pico Invalid Resistance Conversion: The range cannot have resistance conversion applied.",
    310: "Pico Invalid Value In Max Buffer: An invalid value is in the max buffer.",
    311: "Pico Invalid Value In Min Buffer: An invalid value is in the min buffer.",
    312: "Pico Siggen Frequency Out Of Range: Siggen frequency for phase conversion is out of range.",
    313: "Pico Eeprom2 Corrupt: Device's EEPROM is corrupt. Contact Pico Technology support.",
    314: "Pico Eeprom2 Fail: The EEPROM has failed.",
    315: "Pico Serial Buffer Too Small: The serial buffer is too small for the required information.",
    316: "Pico Siggen Trigger And External Clock Clash: Sig gen trigger and external clock both set.",
    317: "Pico Warning Siggen Auxio Trigger Disabled: AUX trigger disabled due to external clock enabling.",
    318: "Pico Siggen Gating Auxio Not Available: AUX I/O set as scope trigger, cannot be sig gen gating.",
    319: "Pico Siggen Gating Auxio Enabled: AUX I/O set as sig gen gating, cannot be scope trigger.",
    320: "Pico Resource Error: A resource has failed to initialise.",
    321: "Pico Temperature Type Invalid: The temperature type is out of range.",
    322: "Pico Temperature Type Not Supported: A requested temperature type is not supported on this device.",
    323: "Pico Timeout: A read/write to the device has timed out.",
    324: "Pico Device Not Functioning: The device cannot be connected correctly.",
    325: "Pico Internal Error: The driver has experienced an unknown error and is unable to recover.",
    326: "Pico Multiple Devices Found: Opening via IP and multiple units have the same IP address.",
    327: "Pico Warning Number Of Segments Reduced: Warning Number Of Segments Reduced.",
    328: "Pico Cal Pins States: The calibration pin states argument is out of range.",
    329: "Pico Cal Pins Frequency: The calibration pin frequency argument is out of range.",
    330: "Pico Cal Pins Amplitude: The calibration pin amplitude argument is out of range.",
    331: "Pico Cal Pins Wavetype: The calibration pin wavetype argument is out of range.",
    332: "Pico Cal Pins Offset: The calibration pin offset argument is out of range.",
    333: "Pico Probe Fault: The probe's identity has a problem.",
    334: "Pico Probe Identity Unknown: The probe has not been identified.",
    335: "Pico Probe Power Dc Power Supply Required: Enabling probe exceeds current limit. DC power required.",
    336: "Pico Probe Not Powered With Dc Power Supply: DC power connected; enabling probe exceeds current limit.",
    337: "Pico Probe Config Failure: Failed to complete probe configuration.",
    338: "Pico Probe Interaction Callback: Failed to set callback, as currently in current callback.",
    339: "Pico Unknown Intelligent Probe: The probe has been verified but not known on this driver.",
    340: "Pico Intelligent Probe Corrupt: The intelligent probe cannot be verified.",
    341: "Pico Probe Collection Not Started: Callback is null; probe collection not started.",
    342: "Pico Probe Power Consumption Exceeded: Current drawn by the probe(s) has exceeded the allowed limit.",
    343: "Pico Warning Probe Channel Out Of Sync: Channel range limits changed due to probe; channel enabled.",
    344: "Pico Endpoint Missing: Endpoint Missing.",
    345: "Pico Unknown Endpoint Request: Unknown Endpoint Request.",
    346: "Pico Adc Type Error: The ADC on board the device has not been correctly identified.",
    347: "Pico Fpga2 Failed: Fpga2 Failed.",
    348: "Pico Fpga2 Device Status: Fpga2 Device Status.",
    349: "Pico Enable Program Fpga2 Failed: Enable Program Fpga2 Failed.",
    350: "Pico No Channels Or Ports Enabled: No Channels Or Ports Enabled.",
    351: "Pico Invalid Ratio Mode: Invalid Ratio Mode.",
    352: "Pico Reads Not Supported In Current Capture Mode: Reads Not Supported In Current Capture Mode.",
    353: "Pico Trigger Read Selection Check Failed: Selection tests can be masked (0x161 to 0x16F).",
    354: "Pico Data Read1 Selection Check Failed: Data Read1 Selection Check Failed.",
    356: "Pico Data Read2 Selection Check Failed: Data Read2 Selection Check Failed.",
    360: "Pico Data Read3 Selection Check Failed: Data Read3 Selection Check Failed.",
    368: "Pico Read Selection Out Of Range: The requested read is not one of the available selections.",
    369: "Pico Multiple Ratio Modes: The downsample ratio options cannot be combined for this request.",
    370: "Pico No Samples Read: The enPicoReadSelection request has no samples available.",
    371: "Pico Ratio Mode Not Requested: ReadSelection did not include one of the downsample ratios.",
    372: "Pico No User Read Requests Set: No read requests have been made.",
    373: "Pico Zero Samples Invalid: The parameter for <number of values> cannot be zero.",
    374: "Pico Analogue Hardware Missing: Analog hardware cannot be identified; contact Pico Support.",
    375: "Pico Analogue Hardware Pins: Setting of the analog hardware pins failed.",
    376: "Pico Analogue Hardware Smps Fault: An SMPS fault has occurred.",
    377: "Pico Digital Analogue Hardware Conflict: Hardware conflict in device; contact Pico Support.",
    378: "Pico Ratio Mode Buffer Not Set: One or more enPicoRatioMode requested do not have a data buffer.",
    379: "Pico Resolution Not Supported By Variant: Resolution is valid but not supported by this device.",
    380: "Pico Threshold Out Of Range: Trigger threshold out of range for current device resolution.",
    381: "Pico Invalid Simple Trigger Direction: Simple trigger only supports upper edge direction options.",
    382: "Pico Aux Not Supported: The aux trigger is not supported on this variant.",
    383: "Pico Null Directions: The trigger directions pointer may not be null.",
    384: "Pico Null Channel Properties: The trigger channel properties pointer may not be null.",
    385: "Pico Trigger Channel Not Enabled: A trigger is set on a channel that has not been enabled.",
    386: "Pico Condition Has No Trigger Property: Trigger condition set but trigger property not set.",
    387: "Pico Ratio Mode Trigger Masking Invalid: Trigger data option only combinable with segment header.",
    388: "Pico Trigger Data Requires Min Buffer Size Of 40 Samples: Trigger data buffer must be 40+ samples.",
    389: "Pico No Of Captures Out Of Range: Requested waveforms > allocated memory segments.",
    390: "Pico Ratio Mode Segment Header Does Not Require Buffers: Segment header does not require a buffer.",
    391: "Pico For Segment Header Use Gettriggerinfo: Use GetTriggerInfo to retrieve segment header info.",
    392: "Pico Read Not Set: A read request has not been set.",
    393: "Pico Adc Setting Mismatch: The expected and actual states of the ADCs do not match.",
    394: "Pico Datatype Invalid: The requested data type is not one of the enPicoDataType listed.",
    395: "Pico Ratio Mode Does Not Support Datatype: Down sample ratio mode does not support enPicoDataType.",
    396: "Pico Channel Combination Not Valid In This Resolution: Channel combination not valid for resolution.",
    397: "Pico Use 8bit Resolution: Use 8bit Resolution.",
    398: "Pico Aggregate Buffers Same Pointer: Buffer for min data and max data are the same.",
    399: "Pico Overlapped Read Values Out Of Range: Overlapped read samples > total samples to capture.",
    400: "Pico Overlapped Read Segments Out Of Range: Overlapped read request has more segments than allocated.",
    401: "Pico Channelflagscombinations Array Size Too Small: Channel combinations array size too small.",
    402: "Pico Captures Exceeds No Of Supported Segments: Captures > maximum segments allowed for device.",
    403: "Pico Time Units Out Of Range: The time unit requested is not one of the enPicoTimeUnits.",
    404: "Pico No Samples Requested: The number of samples parameter may not be zero.",
    405: "Pico Invalid Action: The action requested is not listed in enPicoAction.",
    406: "Pico No Of Samples Need To Be Equal When Adding Buffers: Buffers for same read must be same size.",
    407: "Pico Waiting For Data Buffers: Data processing, but no empty data buffers available.",
    408: "Pico Streaming Only Supports One Read: When streaming data, only one read option is available.",
    409: "Pico Clear Data Buffer Invalid: A clear read request is not one of the enPicoAction listed.",
    410: "Pico Invalid Action Flags Combination: The combination of action flags are not allowed.",
    411: "Pico Both Min And Max Null Buffers Cannot Be Added: PICO_ADD request made but both data buffers are null.",
    412: "Pico Conflict In Set Data Buffers Call Remove Data Buffer To Reset: Data buffer conflict. Use PICO_CLEAR_ALL.",
    413: "Pico Removing Data Buffer Entries Not Allowed While Data Processing: Cannot remove buffers while processing.",
    512: "Pico Cyusb Request Failed: An USB request has failed.",
    513: "Pico Streaming Data Required: Request for latest streaming data has null pointer or zero size array.",
    514: "Pico Invalid Number Of Samples: A buffer being set has a length that is invalid (ie less than zero).",
    515: "Pico Invalid Distribution: The distribution size may not be zero.",
    516: "Pico Buffer Length Greater Than Int32 T: The buffer length in bytes is greater than a 4-byte word.",
    521: "Pico Pll Mux Out Failed: The PLL has failed.",
    522: "Pico One Pulse Width Direction Allowed: Pulse width only supports one direction.",
    523: "Pico External Trigger Not Supported: No external trigger available on the device specified by the handle.",
    524: "Pico No Trigger Conditions Set: The condition parameter is a null pointer.",
    525: "Pico No Of Channel Trigger Properties Out Of Range: Number of trigger channel properties < 0.",
    526: "Pico Probe Component Error: Probe plugged in, but cannot be identified correctly.",
    527: "Pico Incompatible Probe: Probe is incompatible with the device channel it is connected to.",
    528: "Pico Invalid Trigger Channel For Ets: The requested channel for ETS triggering is not supported.",
    529: "Pico Not Available When Streaming Is Running: While device is streaming, get values is not available.",
    530: "Pico Invalid Trigger Within Pre Trigger State: State not one of enSharedTriggerWithinPreTrigger values.",
    531: "Pico Zero Number Of Captures Invalid: The number of captures has to be greater than zero.",
    532: "Pico Invalid Length: The quantifier for a pointer, defining the length in bytes, is invalid.",
    768: "Pico Trigger Delay Out Of Range: The trigger delay is greater than supported by the hardware.",
    769: "Pico Invalid Threshold Direction: Requested threshold direction not allowed with specified channel.",
    770: "Pico Invalid Threshold Mode: Requested threshold mode not allowed with specified channel.",
    771: "Pico Timebase Not Supported By Resolution: The timebase is not supported or is invalid.",
    4096: "Pico Invalid Variant: The device variant is not supported by this current driver.",
    4097: "Pico Memory Module Error: Actual memory module does not match the expected memory module.",
    8192: "Pico Pulse Width Qualifier Lower Upper Confilct: Pulse width qualifier lower/upper conflict.",
    8193: "Pico Pulse Width Qualifier Type: The pulse width qualifier type is not one of the listed options.",
    8194: "Pico Pulse Width Qualifier Direction: The pulse width qualifier direction is not one of the listed options.",
    8195: "Pico Threshold Mode Out Of Range: The threshold range is not one of the listed options.",
    8196: "Pico Trigger And Pulsewidth Direction In Conflict: Trigger direction and pulse width option conflict.",
    8197: "Pico Threshold Upper Lower Mismatch: The thresholds upper limits and lower limits conflict.",
    8198: "Pico Pulse Width Lower Out Of Range: The pulse width lower count is out of range.",
    8199: "Pico Pulse Width Upper Out Of Range: The pulse width upper count is out of range.",
    8200: "Pico Front Panel Error: The devices front panel has caused an error.",
    8203: "Pico Front Panel Mode: The actual and expected mode of the front panel do not match.",
    8204: "Pico Front Panel Feature: A front panel feature is not available or failed to configure.",
    8205: "Pico No Pulse Width Conditions Set: Pulse width conditions pointer is null or num conditions is zero.",
    8206: "Pico Trigger Port Not Enabled: A trigger condition exists for a port, but the port is not enabled.",
    8207: "Pico Digital Direction Not Set: Trigger condition exists for port, but no digital directions set.",
    8208: "Pico I2c Device Invalid Read Command: I2c Device Invalid Read Command.",
    8209: "Pico I2c Device Invalid Response: I2c Device Invalid Response.",
    8210: "Pico I2c Device Invalid Write Command: I2c Device Invalid Write Command.",
    8211: "Pico I2c Device Argument Out Of Range: I2c Device Argument Out Of Range.",
    8212: "Pico I2c Device Mode: The actual and expected mode do not match.",
    8213: "Pico I2c Device Setup Failed: While trying to configure the device, set up failed.",
    8214: "Pico I2c Device Feature: A feature is not available or failed to configure.",
    8215: "Pico I2c Device Validation Failed: The device did not pass the validation checks.",
    8216: "Pico Internal Header Error: Internal Header Error.",
    8217: "Pico Failed To Write Hardware Fault: Device couldn't write channel settings due to hardware fault.",
    12288: "Pico Mso Too Many Edge Transitions When Using Pulse Width: MSO edge transitions not supported.",
    12289: "Pico Invalid Probe Led Position: Requested probe LED position is not a valid enum.",
    12290: "Pico Probe Led Position Not Supported: The LED position is not supported by the selected variant.",
    12291: "Pico Duplicate Probe Channel Led Position: Channel has more than one of the same LED position.",
    12292: "Pico Probe Led Failure: Setting the probes LED has failed.",
    12293: "Pico Probe Not Supported By This Device: Probe is not supported by the selected variant.",
    12294: "Pico Invalid Probe Name: The probe name is not in the list of enPicoConnectProbe enums.",
    12295: "Pico No Probe Colour Settings: Number of colour settings are zero or a null pointer passed.",
    12296: "Pico No Probe Connected On Requested Channel: Channel has no probe connected to it.",
    12297: "Pico Probe Does Not Require Calibration: Connected probe does not require calibration.",
    12298: "Pico Probe Calibration Failed: Connected probe could not be calibrated - hardware fault possible.",
    12299: "Pico Probe Version Error: A probe has been connected, but the version is not recognised.",
    12300: "Pico Probe Does Not Support Frequency Counter: Probe on freq counter channel does not support this feature.",
    16384: "Pico Auto Trigger Time Too Long: The requested trigger time is too long for the selected variant.",
    20480: "Pico Mso Pod Validation Failed: The MSO pod did not pass the validation checks.",
    20481: "Pico No Mso Pod Connected: No MSO pod found on the requested digital port.",
    20482: "Pico Digital Port Hysteresis Out Of Range: Digital port enum value not in enPicoDigitalPortHysteresis.",
    20483: "Pico Mso Pod Failed Unit: Mso Pod Failed Unit.",
    20484: "Pico Attenuation Failed: Device's EEPROM is corrupt. Contact Pico Technology support.",
    20485: "Pico Dc 50ohm Overvoltage Tripped: A channel set to 50 Ohm Path has Tripped due to input signal.",
    20486: "Pico Mso Over Current Tripped: The MSO pod over current protection activated. Replug MSO pod.",
    20496: "Pico Not Responding Overheated: Status error for when the device has overheated.",
    20736: "Pico Usb Version Not Supported: The USB version of the port is not supported by this variant.",
    24576: "Pico Hardware Capture Timeout: Waiting for the device to capture timed out.",
    24577: "Pico Hardware Ready Timeout: Waiting for the device be ready for capture timed out.",
    24578: "Pico Hardware Capturing Call Stop: Driver is capturing. Call Stop on the device first to interrupt.",
    28672: "Pico Too Few Requested Streaming Samples: Number of samples is less than the minimum number allowed.",
    28673: "Pico Streaming Reread Data Not Available: Streaming capture made but re-reading data is not allowed.",
    28674: "Pico Streaming Combination Of Raw Data And One Aggregation Data Type Allowed: Streaming allows Raw + one aggregation type (MinMax, Decimate, Avg/Sum).",
    16777216: "Pico Device Time Stamp Reset: The time stamp per waveform segment has been reset.",
    33554433: "Pico Trigger Time Not Requested: TriggerTimeOffset requested but trigger time not set.",
    33554434: "Pico Trigger Time Buffer Not Set: Trigger time buffer not set.",
    33554436: "Pico Trigger Time Failed To Calculate: The trigger time failed to be calculated.",
    33554440: "Pico Trigger Within A Pre Trigger Failed To Calculate: Trigger time failed to be calculated.",
    33554688: "Pico Trigger Time Stamp Not Requested: The trigger time stamp was not requested.",
    35651584: "Pico Ratio Mode Trigger Data For Time Calculation Does Not Require Buffers: RATIO_MODE_TRIGGER_DATA_FOR_TIME_CALCULATION cannot have a buffer set.",
    35651585: "Pico Ratio Mode Trigger Data For Time Calculation Does Not Have Buffers: Cannot set buffer for RATIO_MODE_TRIGGER_DATA_FOR_TIME_CALCULATION.",
    35651586: "Pico Ratio Mode Trigger Data For Time Calculation Use Gettriggerinfo: Use GetTriggerInfo or GetTriggerTimeOffset for trigger time.",
    35651587: "Pico Streaming Does Not Support Trigger Ratio Modes: PICO_RATIO_MDOE_TRIGGER not supported in streaming.",
    35651588: "Pico Use The Trigger Read: Only PICO_TRIGGER_READ may be used to read PICO_RATIO_MODE_TRIGGER.",
    35651589: "Pico Use A Data Read: One of the PICO_DATA_READs should be used for this ratio mode.",
    35651590: "Pico Trigger Read Requires Int16 T Data Type: Trigger data always requires a PICO_INT16_T data type.",
    35651591: "Pico Ratio Mode Requires Number Of Samples To Be Set: Ratio mode requires number of samples > 0.",
    50331664: "Pico Siggen Settings Mismatch: Attempted to set up sig gen with an inconsistent configuration.",
    50331665: "Pico Siggen Settings Changed Call Apply: Sig gen reconfigured; new settings must be applied.",
    50331666: "Pico Siggen Wavetype Not Supported: The wave type is not listed in enPicoWaveType.",
    50331667: "Pico Siggen Triggertype Not Supported: The trigger type is not listed in enSigGenTrigType.",
    50331668: "Pico Siggen Triggersource Not Supported: The trigger source is not listed in enSigGenTrigSource.",
    50331669: "Pico Siggen Filter State Not Supported: The filter state is not listed in enPicoSigGenFilterState.",
    50331680: "Pico Siggen Null Parameter: The arbitrary waveform buffer is a null pointer.",
    50331681: "Pico Siggen Empty Buffer Supplied: The arbitrary waveform buffer length is zero.",
    50331682: "Pico Siggen Range Not Supplied: The sig gen voltage offset and peak to peak have not been set.",
    50331683: "Pico Siggen Buffer Not Supplied: The sig gen arbitrary waveform buffer not been set.",
    50331684: "Pico Siggen Frequency Not Supplied: The sig gen frequency have not been set.",
    50331685: "Pico Siggen Sweep Info Not Supplied: The sig gen sweep information has not been set.",
    50331686: "Pico Siggen Trigger Info Not Supplied: The sig gen trigger information has not been set.",
    50331687: "Pico Siggen Clock Freq Not Supplied: The sig gen clock frequency have not been set.",
    50331696: "Pico Siggen Too Many Samples: The sig gen arbitrary waveform buffer length is too long.",
    50331697: "Pico Siggen Dutycycle Out Of Range: The duty cycle value is out of range.",
    50331698: "Pico Siggen Cycles Out Of Range: The number of cycles is out of range.",
    50331699: "Pico Siggen Prescale Out Of Range: The pre-scaler is out of range.",
    50331700: "Pico Siggen Sweeptype Invalid: The sweep type is not listed in enPicoSweepType.",
    50331701: "Pico Siggen Sweep Wavetype Mismatch: Mismatch occurred while checking the sweeps wave type.",
    50331702: "Pico Siggen Invalid Sweep Parameters: Sweeps/shots and trigger type are not valid when combined.",
    50331703: "Pico Siggen Sweep Prescale Not Supported: The sweep and prescaler are not valid when combined.",
    50331704: "Pico Awg Over Voltage Range: Potential applied to AWG output exceeds max voltage range.",
    50331705: "Pico Not Locked To Reference Frequency: The reference signal cannot be locked to.",
    50331712: "Pico Permissions Error: (Linux only) udev rules incorrect. User lacks r/w permissions.",
    50335872: "Pico Ports Without Analogue Channels Only Allowed In 8bit Resolution: Digital ports without analog channels only allowed in 8-bit.",
    50344961: "Pico Analogue Frontend Missing: Analogue Frontend Missing.",
    50344962: "Pico Front Panel Missing: Front Panel Missing.",
    50344963: "Pico Analogue Frontend And Front Panel Missing: Analogue Frontend And Front Panel Missing.",
    50347008: "Pico Digital Board Hardware Error: The digital board has reported an error to the driver.",
    50348032: "Pico Firmware Update Required To Use Device With This Driver: Firmware update required.",
    50348033: "Pico Update Required Null: Checking firmware update, the updateRequired parameter is null.",
    50348034: "Pico Firmware Up To Date: Firmware Up To Date.",
    50348035: "Pico Flash Fail: Flash Fail.",
    50348036: "Pico Internal Error Firmware Length Invalid: Internal Error Firmware Length Invalid.",
    50348037: "Pico Internal Error Firmware Null: Internal Error Firmware Null.",
    50348038: "Pico Firmware Failed To Be Changed: Firmware Failed To Be Changed.",
    50348039: "Pico Firmware Failed To Reload: Firmware Failed To Reload.",
    50348040: "Pico Firmware Failed To Be Update: Firmware Failed To Be Update.",
    50348041: "Pico Firmware Version Out Of Range: Firmware Version Out Of Range.",
    50352128: "Pico Optional Bootloader Update Available With This Driver: Optional Bootloader Update Available.",
    50352129: "Pico Bootloader Version Not Available: Bootloader Version Not Available.",
    50364416: "Pico No Apps Available: No Apps Available.",
    50364417: "Pico Unsupported App: Unsupported App.",
    50340096: "Pico Adc Powered Down: The adc is powered down when trying to capture data.",
    268435456: "Pico Watchdogtimer: An internal error has occurred and a watchdog timer has been called.",
    268435457: "Pico Ipp Not Found: The picoipp.dll has not been found.",
    268435458: "Pico Ipp No Function: A function in the picoipp.dll does not exist.",
    268435459: "Pico Ipp Error: The Pico IPP call has failed.",
    268435460: "Pico Shadow Cal Not Available: Shadow calibration is not available on this device.",
    268435461: "Pico Shadow Cal Disabled: Shadow calibration is currently disabled.",
    268435462: "Pico Shadow Cal Error: Shadow calibration error has occurred.",
    268435463: "Pico Shadow Cal Corrupt: The shadow calibration is corrupt.",
    268435464: "Pico Device Memory Overflow: The memory on board the device has overflowed.",
    268435472: "Pico Adc Test Failure: The device Adc test failed.",
    285212672: "Pico Reserved 1: Reserved 1.",
    536870912: "Pico Source Not Ready: The PicoSource device is not ready to accept instructions.",
    536870913: "Pico Source Invalid Baud Rate: Source Invalid Baud Rate.",
    536870914: "Pico Source Not Opened For Write: Source Not Opened For Write.",
    536870915: "Pico Source Failed To Write Device: Source Failed To Write Device.",
    536870916: "Pico Source Eeprom Fail: Source Eeprom Fail.",
    536870917: "Pico Source Eeprom Not Present: Source Eeprom Not Present.",
    536870918: "Pico Source Eeprom Not Programmed: Source Eeprom Not Programmed.",
    536870919: "Pico Source List Not Ready: Source List Not Ready.",
    536870920: "Pico Source Ftd2xx Not Found: Source Ftd2xx Not Found.",
    536870921: "Pico Source Ftd2xx No Function: Source Ftd2xx No Function.",
}