from _typeshed import Incomplete
from pathlib import Path
from typing import Any

PYO3_VERSION: str
PYO3_FEATURES: Incomplete

def load_toml(path: Path) -> dict[str, Any]: ...
def write_toml(data: dict[str, Any], path: Path) -> None: ...
def clean_cargo_name(name: str) -> str: ...
def extract_rust_crate_name(pyproject_data: dict[str, Any]) -> str | None: ...
def format_authors(authors_list: list[dict[str, str]]) -> list[str]: ...
def extract_pyproject_metadata(pyproject_data: dict[str, Any]) -> dict[str, Any]: ...
def update_cargo_package_section(cargo_data: dict[str, Any], metadata: dict[str, Any], rust_crate_name: str | None, cargo_path: Path) -> None: ...
def update_cargo_dependencies(cargo_data: dict[str, Any]) -> None: ...
def update_cargo_lib_section(cargo_data: dict[str, Any]) -> None: ...
def sync_toml_files(pyproject_path: Path, cargo_path: Path) -> None: ...
