from ....utils.logging import log_info as log_info
from .config_manager import ConfigManager as ConfigManager
from _typeshed import Incomplete
from typing import Any

def clean_cargo_name(name: str) -> str: ...
def clean_python_package_name(name: str) -> str: ...
def format_list(items: list[str]) -> list[str]: ...
def dump_toml(data: dict[str, Any], file_path: str) -> None: ...

class PyProjectGenerator:
    project_name_raw: Incomplete
    cleaned_python_name: Incomplete
    cleaned_rust_name: Incomplete
    version: Incomplete
    config: dict[str, Any]
    config_manager: Incomplete
    def __init__(self, project_name: str, version: str = '0.1.0') -> None: ...
    def set_project_info(self, description: str | None = None, authors: list[dict[str, str]] | None = None, python_version: str = '>=3.10', license_name: str = 'MIT', dependencies: list[str] | None = None) -> None: ...
    def set_build_system(self, is_rust: bool = False, is_qt: bool = False) -> None: ...
    def set_development_tools(self) -> None: ...
    def set_entry_points(self, entry_points: dict[str, Any]) -> None: ...
    def generate(self, output_path: str = 'pyproject.toml') -> None: ...
