COUNTRY_TO_STATE_ALIASES = {
    "CA": ["XA", "XC", "XM", "XB", "XW", "XT", "XN", "XV", "XO", "XP", "XQ", "XS", "XY"],
}

DEFAULT_CUSTOM_ALIASES = {

    # Common variants / colloquial
    "Cote d'Ivoire": "CI",
    "Côte d’Ivoire": "CI",
    "Cote d Ivoire": "CI",
    "South Korea": "KR",
    "North Korea": "KP",
    "UK": "GB",
    "United Kingdom": "GB",
    "Great Britain": "GB",
    "Russian Federation": "RU",
    "Vietnam": "VN",
    "Viet Nam": "VN",
    "Afeganist\u00e3o": "AF",
    "Afganistan": "AF",
    "Aland Islands": "AX",
    "Alandinseln": "AX",
    "Albanien": "AL",
    "Alb\u00e2nia": "AL",
    "Alemanha": "DE",
    "Alemania": "DE",
    "Algerien": "DZ",
    "Algieria": "DZ",
    "Amerikanisch-Samoa": "AS",
    "Amerikanische Jungferninseln": "VI",
    "Amerikanische \u00dcberseeinseln": "UM",
    "Andora": "AD",
    "Anguila": "AI",
    "Antarktis": "AQ",
    "Antarktyda": "AQ",
    "Antarktyka": "AQ",
    "Antigua & Barbuda": "AG",
    "Antigua i Barbuda": "AG",
    "Antigua und Barbuda": "AG",
    "Antigua y Barbuda": "AG",
    "Antilhas Neerlandesas": "AN",
    "Antillas Holandesas": "AN",
    "Ant\u00e1rtida": "AQ",
    "Ant\u00edgua e Barbuda": "AG",
    "Arabia Felix / Arabia euda\u00edm\u014dn": "YE",
    "Arabia Saudita": "SA",
    "Arabia Saudyjska": "SA",
    "Arabia Saud\u00ed": "SA",
    "Argelia": "DZ",
    "Argentinien": "AR",
    "Argentyna": "AR",
    "Armenien": "AM",
    "Arm\u00e9nia": "AM",
    "ARYM": "MK",
    "Aserbaidschan": "AZ",
    "Australien": "AU",
    "Austr\u00e1lia": "AU",
    "Azerbaij\u00e3o": "AZ",
    "Azerbaiy\u00e1n": "AZ",
    "Azerbejd\u017can": "AZ",
    "Bahamy": "BS",
    "Bahrajn": "BH",
    "Bahrein": "BH",
    "Bangladesch": "BD",
    "Bangladesz": "BD",
    "Bangladexe": "BD",
    "Banglad\u00e9s": "BD",
    "Barein": "BH",
    "Belgia": "BE",
    "Belgien": "BE",
    "Belice": "BZ",
    "Benim": "BJ",
    "Ben\u00edn": "BJ",
    "Bermudas": "BM",
    "Bermudy": "BM",
    "Bia\u0142oru\u015b": "BY",
    "Bielo-R\u00fassia": "BY",
    "Bielorrusia": "BY",
    "Bielorr\u00fassia": "BY",
    "Birma": "MM",
    "Birma (Myanmar)": "MM",
    "Birmania (Myanmar)": "MM",
    "Bolivia (Plurinational State of)": "BO",
    "Bolivien": "BO",
    "Boliwia": "BO",
    "Bol\u00edvia": "BO",
    "Bonaire, Saint Eustatius and Saba": "BQ",
    "Bonaire, Sint Eustatius i Saba": "BQ",
    "Borinquen": "PR",
    "Bosnia y Herzegovina": "BA",
    "Bosnien und Herzegowina": "BA",
    "Botsuana": "BW",
    "Bouvetinsel": "BV",
    "Bo\u015bnia i Hercegowina": "BA",
    "Brasil": "BR",
    "Brasilien": "BR",
    "Brazylia": "BR",
    "Britain": "GB",
    "Britische Jungferninseln": "VG",
    "Britisches Territorium im Indischen Ozean": "IO",
    "Brunei": "BN",
    "Brytyjskie Terytorium Oceanu Indyjskiego": "IO",
    "Brytyjskie Wyspy Dziewicze": "VG",
    "Bulgarien": "BG",
    "Bulg\u00e1ria": "BG",
    "Bundesrepublik Deutschland": "DE",
    "Burkina Fasso": "BF",
    "Burkina Fasso (Alto Volta)": "BF",
    "Burma": "MM",
    "Burquina Faso": "BF",
    "But\u00e1n": "BT",
    "But\u00e3o": "BT",
    "Bu\u0142garia": "BG",
    "BVI": "VG",
    "B\u00e9lgica": "BE",
    "B\u00f3snia e Herzegovina": "BA",
    "B\u00f3snia-Herzeg\u00f3vina": "BA",
    "Camar\u00f5es": "CM",
    "Camboja": "KH",
    "Camboya": "KH",
    "Camer\u00fan": "CM",
    "Canad\u00e1": "CA",
    "Caribbean Netherlands": "BQ",
    "Caribe neerland\u00e9s": "BQ",
    "Casaquist\u00e3o": "KZ",
    "Catar": "QA",
    "Cazaquist\u00e3o": "KZ",
    "Ceil\u00e1n": "LK",
    "Chade": "TD",
    "Chiny": "CN",
    "Chipre": "CY",
    "Chi\u0144ska Republika Ludowa": "CN",
    "Chorwacja": "HR",
    "Cingapura": "SG",
    "Ciudad del Vaticano": "VA",
    "Cocos Islands": "CC",
    "Colina do Vaticano": "VA",
    "Colony of the Falkland Islands": "FK",
    "Col\u00f4mbia": "CO",
    "Commonwealth of Puerto Rico": "PR",
    "Comoras": "KM",
    "Comores": "KM",
    "Congo (Brazzaville)": "CG",
    "Congo (DRC)": "CD",
    "Congo - Kinshasa": "CD",
    "Congo, The Democratic Republic Of": "CD",
    "Cookinseln": "CK",
    "Corea del Norte": "KP",
    "Coreia do Norte": "KP",
    "Coreia do Sul": "KR",
    "Coreia, Norte": "KP",
    "Cor\u00e9ia, Sul": "KR",
    "Country of Aruba": "AW",
    "Country of Cura\u00e7ao": "CW",
    "Country of Sint Maarten": "SX",
    "Croacia": "HR",
    "Curacao": "CW",
    "Cypr": "CY",
    "Czad": "TD",
    "Czarnog\u00f3ra": "ME",
    "Czechy": "CZ",
    "C\u00f4te d\u2019Ivoire": "CI",
    "Dalekie Wyspy Mniejsze Stan\u00f3w Zjednoczonych": "UM",
    "Dania": "DK",
    "Democratic Cambodia": "KH",
    "Democratic Kampuchea": "KH",
    "Democratic People\u2019s Republic of Korea": "KP",
    "Democratic Republic of Congo": "CD",
    "Democratic Republic of the Congo": "CD",
    "Demokratische Republik Kongo": "CD",
    "Demokratische Republik S\u00e3o Tom\u00e9 und Pr\u00edncipe": "ST",
    "Demokratische Volksrepublik Korea": "KP",
    "Demokratyczna Republika Konga": "CD",
    "Dinamarca": "DK",
    "Djibuti": "DJ",
    "Dominika": "DM",
    "Dominikana": "DO",
    "Dominikanische Republik": "DO",
    "DPRK": "KP",
    "Dschibuti": "DJ",
    "D\u00e4nemark": "DK",
    "D\u017cibuti": "DJ",
    "Egipt": "EG",
    "Egipto": "EG",
    "Egito": "EG",
    "Ekwador": "EC",
    "el pa\u00eds del cedro": "LB",
    "El S\u00e1hara Espa\u00f1ol": "EH",
    "El Vaticano": "VA",
    "Emirados \u00c1rabes Unidos": "AE",
    "Emiratos \u00c1rabes Unidos": "AE",
    "Equador": "EC",
    "Eritreia": "ER",
    "Erytrea": "ER",
    "Eslovenia": "SI",
    "Eslov\u00e1quia": "SK",
    "Espanha": "ES",
    "Espa\u00f1a": "ES",
    "Essuat\u00edni": "SZ",
    "Estado Espa\u00f1ol": "ES",
    "Estado Libre Asociado de Puerto Rico": "PR",
    "Estado Plurinacional de Bolivia": "BO",
    "Estados Federados da Micron\u00e9sia": "FM",
    "Estados Federados de Micronesia": "FM",
    "Estados Unidos": "US",
    "Estados Unidos de Venezuela": "VE",
    "Estados Unidos Mexicanos": "MX",
    "Estland": "EE",
    "Est\u00f3nia": "EE",
    "Esuatini": "SZ",
    "Etiopia": "ET",
    "EUA": "US",
    "Falkland Islands": "FK",
    "Falklandinseln": "FK",
    "Falklandy": "FK",
    "Federalne Stany Mikronezji": "FM",
    "Fidschi": "FJ",
    "Fid\u017ci": "FJ",
    "Filipinas": "PH",
    "Filipiny": "PH",
    "Finlandia": "FI",
    "Finnland": "FI",
    "Fiyi": "FJ",
    "Francia": "FR",
    "Francja": "FR",
    "Francuskie Terytoria Po\u0142udniowe i Antarktyczne": "TF",
    "Frankreich": "FR",
    "Franz\u00f6sisch-Guayana": "GF",
    "Franz\u00f6sisch-Polynesien": "PF",
    "Franz\u00f6sische S\u00fcd- und Antarktisgebiete": "TF",
    "Fran\u00e7a": "FR",
    "French Southern and Antarctic Lands": "TF",
    "F\u00e4r\u00f6er": "FO",
    "F\u00e4r\u00f6er-Inseln": "FO",
    "F\u00f6deration St. Kitts und Nevis": "KN",
    "F\u00f6derierte Staaten von Mikronesien": "FM",
    "F\u00fcrstentum Liechtenstein": "LI",
    "Gabun": "GA",
    "Gab\u00e3o": "GA",
    "Gab\u00f3n": "GA",
    "Gana": "GH",
    "Georgia Po\u0142udniowa i Sandwich Po\u0142udniowy": "GS",
    "Georgien": "GE",
    "Ge\u00f3rgia": "GE",
    "Granada": "GD",
    "Grecia": "GR",
    "Grecja": "GR",
    "Grenlandia": "GL",
    "Griechenland": "GR",
    "Groenlandia": "GL",
    "Gronel\u00e2ndia": "GL",
    "Gro\u00dfbritannien und Nordirland": "GB",
    "Gro\u00dfherzogtum Luxemburg": "LU",
    "Gruzja": "GE",
    "Gr\u00f6nland": "GL",
    "Guadalupe": "GP",
    "Guayana Francesa": "GF",
    "Guernesey": "GG",
    "Guiana": "GY",
    "Guiana Francesa": "GF",
    "Guinea Bissau": "GW",
    "Guinea Espa\u00f1ola": "GQ",
    "Guinea-Bis\u00e1u": "GW",
    "Guin\u00e9": "GN",
    "Guin\u00e9 Bissau": "GW",
    "Guin\u00e9 Equatorial": "GQ",
    "Gujana": "GY",
    "Gujana Francuska": "GF",
    "Gwadelupa": "GP",
    "Gwatemala": "GT",
    "Gwinea": "GN",
    "Gwinea Bissau": "GW",
    "Gwinea R\u00f3wnikowa": "GQ",
    "G\u00e2mbia": "GM",
    "Hait\u00ed": "HT",
    "Hait\u00ed Espa\u00f1ol": "DO",
    "Heard and McDonald Islands": "HM",
    "Heard und McDonaldinseln": "HM",
    "Heard- und McDonald-Inseln": "HM",
    "Hiszpania": "ES",
    "Holandia": "NL",
    "Holland": "NL",
    "Holy See": "VA",
    "Hong Kong S.A.R": "HK",
    "Hong Kong Special Administrative Region": "HK",
    "Hongkong": "HK",
    "Hungria": "HU",
    "Ilha Bouvet": "BV",
    "Ilha Christmas": "CX",
    "Ilha de Man": "IM",
    "Ilha de S\u00e3o Martinho": "SX",
    "Ilha Formosa": "TW",
    "Ilha Norfolk": "NF",
    "Ilhas Aland": "AX",
    "Ilhas Caiman": "KY",
    "Ilhas Cayman": "KY",
    "Ilhas Cocos (Keeling)": "CC",
    "Ilhas Comores": "KM",
    "Ilhas Cook": "CK",
    "Ilhas Faro\u00e9": "FO",
    "Ilhas Fero\u00e9": "FO",
    "Ilhas Ge\u00f3rgia do Sul e Sandwich do Sul": "GS",
    "Ilhas Heard e McDonald": "HM",
    "Ilhas Malvinas": "FK",
    "Ilhas Marianas do Norte": "MP",
    "Ilhas Marshall": "MH",
    "Ilhas Menores Distantes dos EUA": "UM",
    "Ilhas Pitcairn": "PN",
    "Ilhas Salom\u00e3o": "SB",
    "Ilhas Seychelles": "SC",
    "Ilhas Turcas e Caicos": "TC",
    "Ilhas Virgens Americanas": "VI",
    "Ilhas Virgens Brit\u00e2nicas": "VG",
    "Ilhas Wallis e Futuna": "WF",
    "Indie": "IN",
    "Indien": "IN",
    "Indonesien": "ID",
    "Indonezja": "ID",
    "Indon\u00e9sia": "ID",
    "Insel Man": "IM",
    "Inseln des Gr\u00fcnen Vorgebirges": "CV",
    "Irak": "IQ",
    "Iran (Islamische Republik)": "IR",
    "Iraque": "IQ",
    "Ire": "IE",
    "Irland": "IE",
    "Irlanda": "IE",
    "Irlandia": "IE",
    "Ir\u00e1n": "IR",
    "Ir\u00e1n (Rep\u00fablica Isl\u00e1mica)": "IR",
    "Ir\u00e3": "IR",
    "Ir\u00e3o": "IR",
    "Isla Bouvet": "BV",
    "Isla de Malta": "MT",
    "Isla de Man": "IM",
    "Isla de Navidad": "CX",
    "Isla de San Mart\u00edn": "MF",
    "Isla Juana": "CU",
    "Isla Niue": "NU",
    "Isla Norfolk": "NF",
    "Isla Trapobana": "LK",
    "Island": "IS",
    "Islandia": "IS",
    "Islas Aland": "AX",
    "Islas Caim\u00e1n": "KY",
    "Islas Cocos": "CC",
    "Islas Cook": "CK",
    "Islas de \u00c5land": "AX",
    "Islas Falkland (Malvinas)": "FK",
    "Islas Feroe": "FO",
    "Islas Georgia del Sur y Sandwich del Sur": "GS",
    "Islas Heard y McDonald": "HM",
    "Islas Malvinas": "FK",
    "Islas Marianas del Norte": "MP",
    "Islas Marshall": "MH",
    "Islas menores alejadas de EE. UU.": "UM",
    "Islas Pitcairn": "PN",
    "Islas Salom\u00f3n": "SB",
    "Islas Turcas y Caicos": "TC",
    "Islas V\u00edrgenes Brit\u00e1nicas": "VG",
    "Islas V\u00edrgenes de EE. UU.": "VI",
    "Italia": "IT",
    "Italien": "IT",
    "Ivory Coast": "CI",
    "Izrael": "IL",
    "I\u00e9men": "YE",
    "Jamaika": "JM",
    "Jamajka": "JM",
    "Japonia": "JP",
    "Jap\u00e3o": "JP",
    "Jap\u00f3n": "JP",
    "Jemen": "YE",
    "Jibuti": "DJ",
    "Jordania": "JO",
    "Jordanien": "JO",
    "Kaimaninseln": "KY",
    "Kajmany": "KY",
    "Kambodscha": "KH",
    "Kambod\u017ca": "KH",
    "Kamerun": "CM",
    "Kanada": "CA",
    "Kapverden": "CV",
    "Kapverdische Inseln": "CV",
    "Karibische Niederlande": "BQ",
    "Kasachstan": "KZ",
    "Katar": "QA",
    "Kazachstan": "KZ",
    "Kazajist\u00e1n": "KZ",
    "Kenia": "KE",
    "Khmer Republic": "KH",
    "Kirgisistan": "KG",
    "Kirgistan": "KG",
    "Kirgizist\u00e1n": "KG",
    "Kirguist\u00e1n": "KG",
    "Kirguizist\u00e1n": "KG",
    "Kokosinseln": "CC",
    "Kolumbia": "CO",
    "Kolumbien": "CO",
    "Komoren": "KM",
    "Komory": "KM",
    "Kongo": "CG",
    "Kongo (DRK)": "CD",
    "Kongo (Republik Kongo)": "CG",
    "Korea": "KR",
    "Korea (Demokratische Volksrepublik, Nordkorea)": "KP",
    "Korea (Republik Korea, S\u00fcdkorea)": "KR",
    "Korea Po\u0142udniowa": "KR",
    "Korea P\u00f3\u0142nocna": "KP",
    "Korea, Democratic People\u2019s Republic of": "KP",
    "Korea\u0144ska Republika Ludowo-Demokratyczna": "KP",
    "Kosovo": "XK",
    "Kosowo": "XK",
    "Kostaryka": "CR",
    "Kroatien": "HR",
    "Kuba": "CU",
    "Kuwejt": "KW",
    "K\u00f6nigreich Belgien": "BE",
    "La Reunion": "RE",
    "Lao People\u2019s Democratic Republic": "LA",
    "Laos (Demokratyczna Republika Ludowa)": "LA",
    "Lesoto": "LS",
    "Letonia": "LV",
    "Lettland": "LV",
    "Liban": "LB",
    "Libanon": "LB",
    "Libia": "LY",
    "Libia, Rep\u00fablica \u00c1rabe": "LY",
    "Libijska": "LY",
    "Libyen": "LY",
    "Lib\u00e9ria": "LR",
    "Lichtenstein": "LI",
    "Litauen": "LT",
    "Lituania": "LT",
    "Litwa": "LT",
    "Luksemburg": "LU",
    "Luxemburg": "LU",
    "Luxemburgo": "LU",
    "L\u00edbano": "LB",
    "L\u00edbia \u00c1rabe Jamahiriya": "LY",
    "Macao S.A.R": "MO",
    "Macao Special Administrative Region of the People's Republic of China": "MO",
    "Macau": "MO",
    "Macau Special Administrative Region": "MO",
    "Macedonia": "MK",
    "Macedonia del Norte": "MK",
    "Macedonia P\u00f3\u0142nocna": "MK",
    "Madagaskar": "MG",
    "Madag\u00e1scar": "MG",
    "Majotta": "YT",
    "Makau": "MO",
    "Malasia": "MY",
    "Malaui": "MW",
    "Malaysien": "MY",
    "Maldivas": "MV",
    "Malediven": "MV",
    "Malediwy": "MV",
    "Malezja": "MY",
    "Malta Island": "MT",
    "Marianas Setentrionais": "MP",
    "Mariany P\u00f3\u0142nocne": "MP",
    "Marokko": "MA",
    "Maroko": "MA",
    "Marrocos": "MA",
    "Marshall": "MH",
    "Marshall-Inseln": "MH",
    "Marshallinseln": "MH",
    "Martinica": "MQ",
    "Martynika": "MQ",
    "Mauretania": "MR",
    "Mauretanien": "MR",
    "Mauricio": "MU",
    "Maurit\u00e2nia": "MR",
    "Maur\u00edcia": "MU",
    "Meksyk": "MX",
    "Mexican Republic": "MX",
    "Mexiko": "MX",
    "Mianmar (Birm\u00e2nia)": "MM",
    "Micronesia": "FM",
    "Mikronesien": "FM",
    "Mikronezja": "FM",
    "Moldau (Republik Moldau)": "MD",
    "Moldavia": "MD",
    "Moldawien": "MD",
    "Moldova, Rep\u00fablica de": "MD",
    "Monako": "MC",
    "Mongol Peoples Republic": "MN",
    "Mongolei": "MN",
    "Mongolian People\u2019s Republic": "MN",
    "Mong\u00f3lia": "MN",
    "Mosambik": "MZ",
    "Mozambik": "MZ",
    "Mo\u00e7ambique": "MZ",
    "Mo\u0142dawia": "MD",
    "Mo\u0142dawia, Republika": "MD",
    "Municipio Especial de Bonaire": "BQ",
    "Myanmar (Birmania)": "MM",
    "M\u00e9jico": "MX",
    "M\u00e9xico": "MX",
    "M\u00f4naco": "MC",
    "Nam\u00edbia": "NA",
    "Netherlands Antilles": "AN",
    "Neukaledonien": "NC",
    "Neuseeland": "NZ",
    "Nicar\u00e1gua": "NI",
    "Niderlandy Karaibskie": "BQ",
    "Niederlande": "NL",
    "Niederl\u00e4ndische Antillen": "AN",
    "Niemcy": "DE",
    "Nig\u00e9ria": "NG",
    "Nikaragua": "NI",
    "Nordkorea": "KP",
    "Nordmazedonien": "MK",
    "Norfolk": "NF",
    "Norfolkinsel": "NF",
    "Northern Cyprus": "CY",
    "Noruega": "NO",
    "Norwegen": "NO",
    "Norwegia": "NO",
    "Nova Caled\u00f4nia": "NC",
    "Nova Zel\u00e2ndia": "NZ",
    "Nowa Kaledonia": "NC",
    "Nowa Zelandia": "NZ",
    "Nueva Caledonia": "NC",
    "Nueva Espa\u00f1a": "MX",
    "Nueva Zelanda": "NZ",
    "N\u00edger": "NE",
    "N\u00f6rdliche Marianen": "MP",
    "occupied Palestinian Territory": "PS",
    "Om\u00e1n": "OM",
    "Om\u00e3": "OM",
    "oPT": "PS",
    "Oriental Republic of Uruguay": "UY",
    "Pakist\u00e1n": "PK",
    "Palaos": "PW",
    "Palestina": "PS",
    "Palestine": "PS",
    "Palestinian Territories": "PS",
    "Palestinian Territory": "PS",
    "Palestyna": "PS",
    "Pal\u00e4stina": "PS",
    "Panam\u00e1": "PA",
    "Papua Nowa Gwinea": "PG",
    "Papua-Neuguinea": "PG",
    "Papua-Nova Guin\u00e9": "PG",
    "Pap\u00faa Nueva Guinea": "PG",
    "Paquist\u00e3o": "PK",
    "Paraguai": "PY",
    "Paragwaj": "PY",
    "Pa\u00eds de Curazao": "CW",
    "Pa\u00edses Baixos": "NL",
    "Pa\u00edses Baixos Caribenhos": "BQ",
    "Pa\u00edses Bajos": "NL",
    "Peoples Republic of Macedonia": "MK",
    "People\u2019s Democratic Republic of Algeria": "DZ",
    "People\u2019s Republic of China": "CN",
    "Persia": "IR",
    "Per\u00fa": "PE",
    "Philippinen": "PH",
    "Pitcairn Islands": "PN",
    "Pitcairninseln": "PN",
    "Polen": "PL",
    "Polinesia Francesa": "PF",
    "Polinezja Francuska": "PF",
    "Polonia": "PL",
    "Polska": "PL",
    "Porto Rico": "PR",
    "Portoryko": "PR",
    "Portugalia": "PT",
    "Posesiones Espa\u00f1olas del Golfo de Guinea": "GQ",
    "Po\u0142udniowa Afryka": "ZA",
    "Principado de Andorra": "AD",
    "Principado de M\u00f3naco": "MC",
    "Principado do M\u00f3naco": "MC",
    "Province of Sahara": "EH",
    "Province of \u00c5land": "AX",
    "Provincia de la Guinea Ecuatorial": "GQ",
    "Provincia del S\u00e1hara": "EH",
    "Provincia del S\u00e1hara Espa\u00f1ol": "EH",
    "Quirguist\u00e3o": "KG",
    "Quiribati": "KI",
    "Quisqueya": "DO",
    "Qu\u00e9nia": "KE",
    "RASD": "EH",
    "Regi\u00e3o Administrativa Especial de Macau": "MO",
    "Regi\u00e3o Administrativa Especial de Macau da Rep\u00fablica Popular da China": "MO",
    "Reino de Camboya": "KH",
    "Reino de Espa\u00f1a": "ES",
    "Reino de eSwatini": "SZ",
    "Reino de Marruecos": "MA",
    "Reino Unido": "GB",
    "Republic of Bolivia": "BO",
    "Republic of Cape Verde": "CV",
    "Republic of C\u00f4te d\u2019Ivoire": "CI",
    "Republic of Ireland": "IE",
    "Republic of Italy": "IT",
    "Republic of Korea": "KR",
    "Republic of Kosovo": "XK",
    "Republic of Lebanon": "LB",
    "Republic of Montenegro": "ME",
    "Republic of Niger": "NE",
    "Republic of Rwanda": "RW",
    "Republic of the Comoros": "KM",
    "Republic of the Union of Myanmar": "MM",
    "Republic of Turkey": "TR",
    "Republic of Venezuela": "VE",
    "Republik Botsuana": "BW",
    "Republik C\u00f4te d\u2019Ivoire": "CI",
    "Republik Kongo": "CG",
    "Republik Korea": "KR",
    "Republik Moldau": "MD",
    "Republik Nordmazedonien": "MK",
    "Republik Singapur": "SG",
    "Republik S\u00fcdafrika": "ZA",
    "Republik Zypern": "CY",
    "Republik \u00d6sterreich": "AT",
    "Republika Chi\u0144ska": "TW",
    "Republika Czeska": "CZ",
    "Republika Dominikany": "DO",
    "Republika Dominika\u0144ska": "DO",
    "Republika Konga": "CG",
    "Republika Korei": "KR",
    "Republika Po\u0142udniowej Afryki": "ZA",
    "Republika Zielonego Przyl\u0105dka": "CV",
    "Republika \u015arodkowej Afryki": "CF",
    "Republika \u015arodkowoafryka\u0144ska": "CF",
    "Rep\u00fablica Argentina": "AR",
    "Rep\u00fablica Bolivariana de Venezuela": "VE",
    "Rep\u00fablica Centro-Africana": "CF",
    "Rep\u00fablica Centroafricana": "CF",
    "Rep\u00fablica Checa": "CZ",
    "Rep\u00fablica da Cor\u00e9ia": "KR",
    "Rep\u00fablica da Guin\u00e9-Bissau": "GW",
    "Rep\u00fablica da Irlanda": "IE",
    "Rep\u00fablica da Maced\u00f3nia": "MK",
    "Rep\u00fablica da Maced\u00f3nia do Norte": "MK",
    "Rep\u00fablica de Angola": "AO",
    "Rep\u00fablica de Bolivia": "BO",
    "Rep\u00fablica de Cabo Verde": "CV",
    "Rep\u00fablica de Chile": "CL",
    "Rep\u00fablica de Colombia": "CO",
    "Rep\u00fablica de Corea": "KR",
    "Rep\u00fablica de Costa Rica": "CR",
    "Rep\u00fablica de Cuba": "CU",
    "Rep\u00fablica de El Salvador": "SV",
    "Rep\u00fablica de Guatemala": "GT",
    "Rep\u00fablica de Guinea Ecuatorial": "GQ",
    "Rep\u00fablica de Honduras": "HN",
    "Rep\u00fablica de Irlanda": "IE",
    "Rep\u00fablica de Macedonia del Norte": "MK",
    "Rep\u00fablica de Mauricio": "MU",
    "Rep\u00fablica de Mo\u00e7ambique": "MZ",
    "Rep\u00fablica de Nicaragua": "NI",
    "Rep\u00fablica de Panam\u00e1": "PA",
    "Rep\u00fablica de Santo Domingo": "DO",
    "Rep\u00fablica de Sud\u00e1n del Sur": "SS",
    "Rep\u00fablica de Venezuela": "VE",
    "Rep\u00fablica del Congo": "CG",
    "Rep\u00fablica del Ecuador": "EC",
    "Rep\u00fablica del Paraguay": "PY",
    "Rep\u00fablica del Per\u00fa": "PE",
    "Rep\u00fablica Democr\u00e1tica de S\u00e3o Tom\u00e9 e Pr\u00edncipe": "ST",
    "Rep\u00fablica Democr\u00e1tica de Timor-Leste": "TL",
    "Rep\u00fablica Democr\u00e1tica del Congo": "CD",
    "Rep\u00fablica Democr\u00e1tica do Congo": "CD",
    "Rep\u00fablica do Sud\u00e3o do Sul": "SS",
    "Rep\u00fablica Dominicana": "DO",
    "Rep\u00fablica dos Camar\u00f5es": "CM",
    "Rep\u00fablica Eslovaca": "SK",
    "Rep\u00fablica Federativa do Brasil": "BR",
    "Rep\u00fablica Isl\u00e2mica do Ir\u00e3": "IR",
    "Rep\u00fablica Italiana": "IT",
    "Rep\u00fablica Mejicana": "MX",
    "Rep\u00fablica Oriental del Uruguay": "UY",
    "Rep\u00fablica Popular China": "CN",
    "Rep\u00fablica Popular da China": "CN",
    "Rep\u00fablica Popular Democr\u00e1tica da Coreia": "KP",
    "Rep\u00fablica Popular Democr\u00e1tica de Corea": "KP",
    "Rep\u00fablica Popular Democr\u00e1tica do Laos": "LA",
    "Rep\u00fablica Portuguesa": "PT",
    "Rep\u00fablica Tcheca": "CZ",
    "Rep\u00fablica \u00c1rabe Saharaui Democr\u00e1tica": "EH",
    "Reunion": "RE",
    "Reuni\u00e3o": "RE",
    "Rodezja P\u00f3\u0142nocna": "ZM",
    "Rom\u00e9nia": "RO",
    "Rosja": "RU",
    "Ruanda": "RW",
    "Ruman\u00eda": "RO",
    "Rumunia": "RO",
    "Rum\u00e4nien": "RO",
    "Rusia": "RU",
    "Russia": "RU",
    "Russische F\u00f6deration": "RU",
    "Russland": "RU",
    "Rzeczpospolita Polska": "PL",
    "Saara Ocidental": "EH",
    "Sahara Zachodnia": "EH",
    "Saint Barthelemy": "BL",
    "Saint Helena": "SH",
    "Saint Kitts e Nevis": "KN",
    "Saint Kitts i Nevis": "KN",
    "Saint Martin": "MF",
    "Saint Vincent i Grenadyny": "VC",
    "Saint-Martin Collectivity": "MF",
    "Saint-Pierre i Miquelon": "PM",
    "Salomonen": "SB",
    "Salomoninseln": "SB",
    "Salom\u00f3n": "SB",
    "Salwador": "SV",
    "Sambia": "ZM",
    "Samoa Americana": "AS",
    "Samoa Ameryka\u0144skie": "AS",
    "San Bartolom\u00e9": "BL",
    "San Crist\u00f3bal y Nevis": "KN",
    "San Crist\u00f3bal y Nieves": "KN",
    "San Mart\u00edn": "MF",
    "San Pedro y Miquel\u00f3n": "PM",
    "San Vicente y las Granadinas": "VC",
    "Sankt Bartholom\u00e4us": "BL",
    "Santa Elena": "SH",
    "Santa Helena": "SH",
    "Santa Luc\u00eda": "LC",
    "Santa Sede": "VA",
    "Santa Sede (Estado de la Ciudad del Vaticano)": "VA",
    "Santa S\u00e9 (Cidade-Estado do Vaticano)": "VA",
    "Santo Tom\u00e9 y Pr\u00edncipe": "ST",
    "Saudi-Arabien": "SA",
    "Schweden": "SE",
    "Schweiz": "CH",
    "Schweizerische Eidgenossenschaft": "CH",
    "Serbia and Montenegro": "CS",
    "Serbia y Montenegro": "CS",
    "Serbien": "RS",
    "Serbien und Montenegro": "CS",
    "Serra Leoa": "SL",
    "Seszele": "SC",
    "Seychellen": "SC",
    "SGSSI": "GS",
    "Siam": "TH",
    "Sierra Leona": "SL",
    "Simbabwe": "ZW",
    "Singapur": "SG",
    "Singapura": "SG",
    "Sint Maarten": "SX",
    "Siria": "SY",
    "Slowakei (Slowakische Republik)": "SK",
    "Slowenien": "SI",
    "Socialist Republic of Montenegro": "ME",
    "Socialist Republic of Vietnam": "VN",
    "Solomon-Inseln": "SB",
    "Som\u00e1lia": "SO",
    "Sonderverwaltungszone Hongkong der Volksrepublik China": "HK",
    "Sonderverwaltungszone Macau": "MO",
    "Spanien": "ES",
    "Spanish Guinea": "GQ",
    "Spanish State": "ES",
    "Spitzbergen und Jan Mayen": "SJ",
    "St Kitts and Nevis": "KN",
    "St Lucia": "LC",
    "St Martin": "MF",
    "St Vincent and Grenadines": "VC",
    "St-Barth": "BL",
    "St. Barth\u00e9lemy": "BL",
    "St. Barts": "BL",
    "St. Helena": "SH",
    "St. Helena, Ascension and Tristan Da Cunha": "SH",
    "St. Kitts & Nevis": "KN",
    "St. Kitts und Nevis": "KN",
    "St. Martin (French Part)": "MF",
    "St. Pierre & Miquelon": "PM",
    "St. Pierre und Miquelon": "PM",
    "St. Vincent & Grenadines": "VC",
    "St. Vincent and the Grenadines": "VC",
    "St. Vincent und die Grenadinen": "VC",
    "Staat der Vatikanstadt": "VA",
    "Staat Libyen": "LY",
    "Staat Pal\u00e4stina": "PS",
    "State of Eritrea": "ER",
    "State of Libya": "LY",
    "State of Palestine": "PS",
    "State Union of Serbia and Montenegro": "CS",
    "Stolica Apostolska (Pa\u0144stwo Watyka\u0144skie)": "VA",
    "Stolica Apostolska (Watykan)": "VA",
    "Suazi": "SZ",
    "Sudan Po\u0142udniowy": "SS",
    "Sud\u00e1frica": "ZA",
    "Sud\u00e1n": "SD",
    "Sud\u00e3o": "SD",
    "Sud\u00e3o do Sul": "SS",
    "Suecia": "SE",
    "Suiza": "CH",
    "Surinam": "SR",
    "Su\u00ed\u00e7a": "CH",
    "Svalbard e Jan Mayen": "SJ",
    "Svalbard i Jan Mayen": "SJ",
    "Svalbard y Jan Mayen": "SJ",
    "Swasiland": "SZ",
    "Swaziland": "SZ",
    "Swazilandia": "SZ",
    "Syrien": "SY",
    "Szwajcaria": "CH",
    "Szwecja": "SE",
    "S\u00e3o Bartolomeu": "BL",
    "S\u00e3o Cristov\u00e3o e Nevis": "KN",
    "S\u00e3o Martinho": "MF",
    "S\u00e3o Pedro e Miquel\u00e3o": "PM",
    "S\u00e3o Tom\u00e9 & Pr\u00edncipe": "ST",
    "S\u00e3o Tom\u00e9 e Pr\u00edncipe": "ST",
    "S\u00e3o Tom\u00e9 und Pr\u00edncipe": "ST",
    "S\u00e3o Vicente e Granadinas": "VC",
    "S\u00e3o Vincente e Granadinas": "VC",
    "S\u00e9rvia": "RS",
    "S\u00e9rvia e Montenegro": "CS",
    "S\u00fcdgeorgien und die S\u00fcdlichen Sandwichinseln": "GS",
    "S\u00fcdsudan": "SS",
    "S\u0142owacja": "SK",
    "S\u0142owenia": "SI",
    "TAAF": "TF",
    "Tadjiquist\u00e3o": "TJ",
    "Tadschikistan": "TJ",
    "Tad\u017cykistan": "TJ",
    "Tailandia": "TH",
    "Taiwan R.O.C.": "TW",
    "Taiwan ROC": "TW",
    "Taiw\u00e1n": "TW",
    "Tajiquist\u00e3o": "TJ",
    "Tajlandia": "TH",
    "Tajwan": "TW",
    "Tansania": "TZ",
    "Tanz\u00e2nia": "TZ",
    "Tayikist\u00e1n": "TJ",
    "Tch\u00e9quia": "CZ",
    "Territorial collectivity of Saint-Barth\u00e9lemy": "BL",
    "Territorio Brit\u00e1nico del Oc\u00e9ano \u00cdndico": "IO",
    "Territorios Australes Franceses": "TF",
    "Territorios Espa\u00f1oles del Golfo de Guinea": "GQ",
    "Territory of New Caledonia and Dependencies": "NC",
    "Territ\u00f3rio Brit\u00e2nico do Oceano \u00cdndico": "IO",
    "Territ\u00f3rio Insular de Bonaire": "BQ",
    "Territ\u00f3rios Franceses do Sul": "TF",
    "Terytorium Brytyjskie Oceanu Indyjskiego": "IO",
    "The Bahamas": "BS",
    "The Gambia": "GM",
    "The Netherlands": "NL",
    "The Somali Republic": "SO",
    "Timor Leste": "TL",
    "Trapobana": "LK",
    "Trindade e Tobago": "TT",
    "Trinidad & Tobago": "TT",
    "Trinidad e Tobago": "TT",
    "Trinidad i Tobago": "TT",
    "Trinidad und Tobago": "TT",
    "Trinidad y Tobago": "TT",
    "Trynidad i Tobago": "TT",
    "Tschad": "TD",
    "Tschechien": "CZ",
    "Tschechische Republik": "CZ",
    "Tunesien": "TN",
    "Tunezja": "TN",
    "Tunisian Republic": "TN",
    "Tun\u00edsia": "TN",
    "Turcja": "TR",
    "Turcomenist\u00e3o": "TM",
    "Turkey": "TR",
    "Turkmenia": "TM",
    "Turkmenist\u00e1n": "TM",
    "Turks and Caicos": "TC",
    "Turks i Caicos": "TC",
    "Turks- und Caicosinseln": "TC",
    "Turquemenist\u00e3o": "TM",
    "Turquia": "TR",
    "T\u00fanez": "TN",
    "T\u00fcrkei": "TR",
    "U.K": "GB",
    "U.S.": "US",
    "U.S. Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
    "U.S.A.": "US",
    "UAE": "AE",
    "Ucrania": "UA",
    "Ukraina": "UA",
    "Ungarn": "HU",
    "Union of Burma": "MM",
    "United States of Venezuela": "VE",
    "Uni\u00f3n India": "IN",
    "Uruguai": "UY",
    "Urugwaj": "UY",
    "Usbekistan": "UZ",
    "Uzbekist\u00e1n": "UZ",
    "Uzbequist\u00e3o": "UZ",
    "Vatican": "VA",
    "Vatican City": "VA",
    "Vatican City State": "VA",
    "Vatican City State (Holy See)": "VA",
    "Vatican Hill": "VA",
    "Vereinigte Arabische Emirate": "AE",
    "Vereinigte K\u00f6nigreich Gro\u00dfbritannien und Nordirland": "GB",
    "Vereinigte Staaten": "US",
    "Vereinigten Staaten von Amerika": "US",
    "Vereinigtes K\u00f6nigreich": "GB",
    "Vietname": "VN",
    "Vietn\u00e3": "VN",
    "Virgin Islands (British)": "VG",
    "Virgin Islands (US)": "VI",
    "Volksrepublik China": "CN",
    "Wallis & Futuna": "WF",
    "Wallis e Futuna": "WF",
    "Wallis i Futuna": "WF",
    "Wallis und Futuna": "WF",
    "Wallis y Futuna": "WF",
    "Watykan": "VA",
    "Weihnachtsinsel": "CX",
    "Wenezuela": "VE",
    "Westsahara": "EH",
    "Wietnam": "VN",
    "Wyspa Bouveta": "BV",
    "Wyspa Bo\u017cego Narodzenia": "CX",
    "Wyspa Man": "IM",
    "Wyspa \u015awi\u0119tej Heleny": "SH",
    "Wyspy Alandzkie": "AX",
    "Wyspy Cooka": "CK",
    "Wyspy Dziewicze Stan\u00f3w Zjednoczonych": "VI",
    "Wyspy Heard i McDonalda": "HM",
    "Wyspy Kokosowe": "CC",
    "Wyspy Marshalla": "MH",
    "Wyspy Owcze": "FO",
    "Wyspy Salomona": "SB",
    "Wyspy Wallis i Futuna": "WF",
    "Wyspy \u015awi\u0119tego Tomasza i Ksi\u0105\u017c\u0119ca": "ST",
    "W\u0119gry": "HU",
    "W\u0142ochy": "IT",
    "Yibuti": "DJ",
    "Zentralafrikanische Republik": "CF",
    "Zimbabue": "ZW",
    "Zjednoczone Emiraty Arabskie": "AE",
    "Zjednoczone Kr\u00f3lestwo Wielkiej Brytanii": "GB",
    "Zypern": "CY",
    "Z\u00e2mbia": "ZM",
    "\u00c1frica do Sul": "ZA",
    "\u00c1ustria": "AT",
    "\u00c4gypten": "EG",
    "\u00c4quatorialguinea": "GQ",
    "\u00c4thiopien": "ET",
    "\u00c5land": "AX",
    "\u00cdndia": "IN",
    "\u0141otwa": "LV",
}
