from ...exceptions import CommandError as CommandError
from ...utils.logging import log_error as log_error, log_info as log_info
from ...utils.subprocess_utils import SubprocessExecutor as SubprocessExecutor
from _typeshed import Incomplete
from pathlib import Path

class Packager:
    executor: Incomplete
    def __init__(self) -> None: ...
    def clean_dist_directory(self) -> None: ...
    def build_distribution_packages(self) -> None: ...
    def get_dist_files(self) -> list[Path]: ...
    def collect_dist_files(self, dist_files: list[Path] | None = None) -> list[Path]: ...
    def extract_wheel_files(self, files: list[Path]) -> list[Path]: ...
