"""
ActionEngine Websocket interface.
"""
from __future__ import annotations
import actionengine._C.data
import actionengine._C.service
import typing
__all__: list[str] = ['WebsocketServer', 'WebsocketWireStream', 'make_websocket_stream']
class WebsocketServer:
    """
    A WebsocketServer interface.
    """
    def __init__(self, service: actionengine._C.service.Service, address: str = '0.0.0.0', port: typing.SupportsInt = 20000) -> None:
        ...
    def cancel(self) -> None:
        ...
    def join(self) -> None:
        ...
    def run(self) -> None:
        ...
class WebsocketWireStream(actionengine._C.service.WireStreamVirtualBase):
    """
    A WebsocketWireStream interface.
    """
    def __repr__(self) -> str:
        ...
    def accept(self) -> None:
        ...
    def get_id(self) -> str:
        ...
    def get_status(self) -> None:
        ...
    def half_close(self) -> None:
        ...
    def receive(self, arg0: ...) -> actionengine._C.data.WireMessage | None:
        ...
    def send(self, arg0: actionengine._C.data.WireMessage) -> None:
        ...
    def start(self) -> None:
        ...
def make_websocket_stream(address: str = 'localhost', target: str = '/', port: typing.SupportsInt = 20000) -> WebsocketWireStream:
    ...
