class LocalInstaller:
    def install(self, uv_path: str, env: dict) -> None: ...
    def run_installation_attempt(self, uv_path: str, env: dict, timeout_duration: int, use_alternative: bool = False) -> bool: ...
