from enum import Enum


class GetInstancesV2InstancesGetStatusInType0Item(str, Enum):
    STATUS_CONFIRMED = "STATUS_CONFIRMED"
    STATUS_ERROR = "STATUS_ERROR"
    STATUS_INITIALIZING = "STATUS_INITIALIZING"
    STATUS_NEW = "STATUS_NEW"
    STATUS_PAUSED = "STATUS_PAUSED"
    STATUS_PENDING = "STATUS_PENDING"
    STATUS_PREEMPTED = "STATUS_PREEMPTED"
    STATUS_PREEMPTING = "STATUS_PREEMPTING"
    STATUS_RELOCATING = "STATUS_RELOCATING"
    STATUS_REPLACED = "STATUS_REPLACED"
    STATUS_RUNNING = "STATUS_RUNNING"
    STATUS_SCHEDULED = "STATUS_SCHEDULED"
    STATUS_STARTING = "STATUS_STARTING"
    STATUS_STOPPED = "STATUS_STOPPED"
    STATUS_STOPPING = "STATUS_STOPPING"
    STATUS_TERMINATED = "STATUS_TERMINATED"

    def __str__(self) -> str:
        return str(self.value)
