"""
ActionEngine Service interface.
"""
from __future__ import annotations
import actionengine._C.actions
import actionengine._C.chunk_store
import actionengine._C.data
import actionengine._C.nodes
import collections.abc
import typing
__all__: list[str] = ['Service', 'Session', 'StreamToSessionConnection', 'WireStream', 'WireStreamVirtualBase']
class Service:
    def __init__(self, action_registry: actionengine._C.actions.ActionRegistry, connection_handler: collections.abc.Callable[[WireStreamVirtualBase, Session], None] = None) -> None:
        ...
    def establish_connection(self, arg0: WireStream) -> ...:
        ...
    def get_session(self, arg0: str) -> Session:
        ...
    def get_session_keys(self) -> list[str]:
        ...
    def get_stream(self, arg0: str) -> WireStreamVirtualBase:
        ...
    def join_connection(self, arg0: ...) -> None:
        ...
    def set_action_registry(self, action_registry: actionengine._C.actions.ActionRegistry) -> None:
        ...
class Session:
    @typing.overload
    def __init__(self, node_map: actionengine._C.nodes.NodeMap, action_registry: actionengine._C.actions.ActionRegistry = None) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: Session) -> None:
        ...
    def dispatch_from(self, stream: WireStreamVirtualBase, on_done: collections.abc.Callable[[], None] = None) -> None:
        ...
    def dispatch_message(self, arg0: actionengine._C.data.WireMessage, arg1: WireStreamVirtualBase) -> None:
        ...
    def get_action_registry(self) -> actionengine._C.actions.ActionRegistry:
        ...
    def get_node(self, id: str = '', chunk_store_factory: collections.abc.Callable[[str], actionengine._C.chunk_store.ChunkStoreVirtualBase] = None) -> actionengine._C.nodes.AsyncNode:
        ...
    def get_node_map(self) -> actionengine._C.nodes.NodeMap:
        ...
    def set_action_registry(self, action_registry: actionengine._C.actions.ActionRegistry) -> None:
        ...
    def stop_dispatching_from(self, arg0: WireStreamVirtualBase) -> None:
        ...
class StreamToSessionConnection:
    session_id: str
    stream_id: str
    @typing.overload
    def __init__(self, stream: WireStreamVirtualBase, session: Session) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: StreamToSessionConnection) -> None:
        ...
    def get_session(self) -> Session:
        ...
    def get_stream(self) -> WireStream:
        ...
class WireStream(WireStreamVirtualBase):
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: WireStream) -> None:
        ...
    def abort(self) -> None:
        ...
    def accept(self) -> None:
        ...
    def get_id(self) -> str:
        ...
    def get_status(self) -> None:
        ...
    def half_close(self) -> None:
        ...
    def receive(self, timeout: typing.SupportsFloat = -1.0) -> actionengine._C.data.WireMessage | None:
        ...
    def send(self, message: actionengine._C.data.WireMessage) -> None:
        ...
    def start(self) -> None:
        ...
class WireStreamVirtualBase:
    def abort(self) -> None:
        ...
    def accept(self) -> None:
        ...
    def get_id(self) -> str:
        ...
    def get_status(self) -> None:
        ...
    def half_close(self) -> None:
        ...
    def receive(self, timeout: typing.SupportsFloat = -1.0) -> actionengine._C.data.WireMessage | None:
        ...
    def send(self, arg0: actionengine._C.data.WireMessage) -> None:
        ...
    def start(self) -> None:
        ...
