= typed_classproperties

:project-root: .

:!example-caption:
:!table-caption:
:icons: font
:experimental:

:_url-wikipedia: https://wikipedia.org/wiki
:_url-github: https://github.com
:_url-github-wiki: https://docs.github.com
:_url-pypi: https://pypi.org

:url-project-repository: {_url-github}/CarrotManMatt/typed_classproperties
:url-project-pypi: {_url-pypi}/project/typed_classproperties
:url-project-bug-tracker: {url-project-repository}/issues
:url-python-home: https://python.org
:url-python: {url-python-home}
:url-python-download: {url-python-home}/downloads
:url-python-wiki: https://docs.python.org/3
:url-python-wiki-virtual-environments: {url-python-wiki}/tutorial/venv
:url-pre-commit-home: https://pre-commit.com
:url-pre-commit: {url-pre-commit-home}
:url-ruff-home: https://ruff.rs
:url-ruff: {url-ruff-home}
:url-mypy-home: https://mypy-lang.org
:url-mypy: {url-mypy-home}
:url-pypi-home: {_url-pypi}
:url-pypi: https://pypi.org
:url-uv-home: https://astral.sh/uv
:url-uv: {url-uv-home}
:url-uv-wiki: https://docs.astral.sh/uv
:url-uv-wiki-tools: {url-uv-wiki}/guides/tools
:url-uv-wiki-tools-installing: {url-uv-wiki-tools}#installing-tools
:url-uv-wiki-tools-upgrading: {url-uv-wiki-tools}#upgrading-tools
:url-uv-wiki-dependencies-adding: {url-uv-wiki}/concepts/projects#managing-dependencies
:url-pip-home: https://pip.pypa.io
:url-pip: {url-pip-home}
:url-library-typing-extensions: {_url-github}/python/typing_extensions

:labelled-url-python: {url-python}[Python]
:labelled-url-pypi: {url-pypi}[PyPI]
:labelled-url-pip: {url-pip}[pip]
:labelled-url-uv: {url-uv}[uv]
:labelled-url-mypy: {url-mypy}[mypy]
:labelled-url-library-typing-extensions: {url-library-typing-extensions}[typing_extensions]

image:https://img.shields.io/badge/%F0%9F%A5%95-typed__classproperties-blue[Pydowndoc,link={url-project-repository}]
image:https://img.shields.io/pypi/v/typed_classproperties[PyPI Version,link={url-project-pypi}]
image:https://img.shields.io/pypi/pyversions/typed_classproperties?logo=Python&logoColor=white&label=Python[Python Version,link={url-python-download}]
image:{url-project-repository}/actions/workflows/check-build-publish.yaml/badge.svg[Tests Status,link={url-project-repository}/actions/workflows/check-build-publish.yaml]
image:https://img.shields.io/badge/mypy-checked-%232EBB4E&label=mypy[mypy Status,link={url-mypy}]
image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit[pre-commit Status,link={url-pre-commit}]
image:https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/astral-sh/ruff/main/assets/badge/v2.json[Ruff,link={url-ruff}]
image:https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/astral-sh/uv/main/assets/badge/v0.json[uv,link={url-uv}]

****
Typed decorators for `+classproperty+` and `+cached_classproperty+`.

**Python 3 compatible only**. **No dependencies**footnote:[The library `{labelled-url-library-typing-extensions}` is required when running with a {labelled-url-python} version less than `3.12`].
****

== Installation

This package is hosted on {labelled-url-pypi} and can be installed using
{labelled-url-uv} or {labelled-url-pip}.

.Add to your {url-uv-wiki-dependencies-adding}[uv project/script's dependencies]
[source,bash]
uv add typed_classproperties

.Install using {labelled-url-pip} after {url-python-wiki-virtual-environments}[creating a virtual environment]
[source,bash]
path/to/venv/python -m pip install typed_classproperties

== Example Usage

[source,python]
----
from typing import override

from typed_classproperties import classproperty, cached_classproperty


class Foo:
    @override
    def __init__(self, bar: str) -> None:
        self.bar: str = bar

    @classproperty
    def BAR(cls) -> int:
        return 1


assert Foo.BAR == 1
assert Foo(bar="one").BAR == 1


class CachedFoo:
    @override
    def __init__(self, bar: str) -> None:
        self.bar: str = bar

    @cached_classproperty
    def BAR(cls) -> int:
        print("This will be executed only once")
        return 1


assert CachedFoo.BAR == 1
assert CachedFoo(bar="bar").FOO == 1
----

== Supported Type-Checkers

This package makes use of some reasonably advanced Python functionality, not supported by all static type checkers.
While we will attempt to fix type bugs in this project for alternative type-checkers, our focus is on the following officially supported type checkersfootnote:[The list of officially supported type checkers is subject to change between any minor version release]:

* {labelled-url-mypy}

IMPORTANT: Patches to fix bugs in this project for alternative type-checkers are welcome and much appreciated!

== Tests

See link:tests.py[] for further usage examples and expected behaviour.

.To run tests
[source,bash]
uv run --group test -- pytest

== Credits

Credits to Denis Ryzhkov, on Stack Overflow, for the original implementation of the `+@classproperty+` decorator:
https://stackoverflow.com/a/13624858/1280629
