
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import com.yahoo.labs.samoa.instances
import java.lang
import moa.capabilities
import moa.classifiers
import moa.core
import moa.options
import typing



class DriftDetectionMethodClassifier(moa.classifiers.AbstractClassifier, moa.classifiers.MultiClassClassifier, moa.capabilities.CapabilitiesHandler):
    baseLearnerOption: moa.options.ClassOption = ...
    driftDetectionMethodOption: moa.options.ClassOption = ...
    DDM_INCONTROL_LEVEL: typing.ClassVar[int] = ...
    DDM_WARNING_LEVEL: typing.ClassVar[int] = ...
    DDM_OUTCONTROL_LEVEL: typing.ClassVar[int] = ...
    def __init__(self): ...
    def defineImmutableCapabilities(self) -> moa.capabilities.ImmutableCapabilities: ...
    def getModelDescription(self, stringBuilder: java.lang.StringBuilder, int: int) -> None: ...
    def getPurposeString(self) -> str: ...
    @typing.overload
    def getVotesForInstance(self, example: moa.core.Example[com.yahoo.labs.samoa.instances.Instance]) -> typing.MutableSequence[float]: ...
    @typing.overload
    def getVotesForInstance(self, instance: com.yahoo.labs.samoa.instances.Instance) -> typing.MutableSequence[float]: ...
    def isChangeDetected(self) -> bool: ...
    def isRandomizable(self) -> bool: ...
    def isWarningDetected(self) -> bool: ...
    def resetLearningImpl(self) -> None: ...
    def trainOnInstanceImpl(self, instance: com.yahoo.labs.samoa.instances.Instance) -> None: ...

class SingleClassifierDrift(DriftDetectionMethodClassifier):
    def __init__(self): ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("moa.classifiers.drift")``.

    DriftDetectionMethodClassifier: typing.Type[DriftDetectionMethodClassifier]
    SingleClassifierDrift: typing.Type[SingleClassifierDrift]
