// @generated by protoc-gen-es v2.6.3
// @generated from file ar/v1/action_info.proto (package ar.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_ar_v1_action } from "./action_pb";
import { file_ar_v1_events } from "./events_pb";

/**
 * Describes the file ar/v1/action_info.proto.
 */
export const file_ar_v1_action_info = /*@__PURE__*/
  fileDesc("Chdhci92MS9hY3Rpb25faW5mby5wcm90bxIFYXIudjEi8wEKEUFjdGlvbkluZm9NZXNzYWdlEgwKBG5hbWUYAiABKAkSDAoEaWNvbhgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCRIfCgR0eXBlGAUgASgOMhEuYXIudjEuQWN0aW9uVHlwZRINCgVncm91cBgGIAEoCRIVCg1yZXF1aXJlX2FnZW50GAcgASgIEikKD3JlcXVpcmVkX2V2ZW50cxgIIAMoDjIQLmFyLnYxLkV2ZW50VHlwZRIpCg9vcHRpb25hbF9ldmVudHMYCSADKA4yEC5hci52MS5FdmVudFR5cGUSEAoIZGlzYWJsZWQYCiABKAgiRAoSQWN0aW9uSW5mb3NNZXNzYWdlEi4KDGFjdGlvbl9pbmZvcxgBIAMoCzIYLmFyLnYxLkFjdGlvbkluZm9NZXNzYWdlQosBCgljb20uYXIudjFCD0FjdGlvbkluZm9Qcm90b1ABWi9naXRodWIuY29tL2NvYm90YXIvcHJvdG9jb2wvbWVzc2FnZXMvYXIvdjE7YXJ2MaICA0FYWKoCDk1lc3NhZ2VzLkFSLlYxygIFQXJcVjHiAhFBclxWMVxHUEJNZXRhZGF0YeoCBkFyOjpWMWIGcHJvdG8z", [file_ar_v1_action, file_ar_v1_events]);

/**
 * Describes the message ar.v1.ActionInfoMessage.
 * Use `create(ActionInfoMessageSchema)` to create a new message.
 */
export const ActionInfoMessageSchema = /*@__PURE__*/
  messageDesc(file_ar_v1_action_info, 0);

/**
 * Describes the message ar.v1.ActionInfosMessage.
 * Use `create(ActionInfosMessageSchema)` to create a new message.
 */
export const ActionInfosMessageSchema = /*@__PURE__*/
  messageDesc(file_ar_v1_action_info, 1);

