"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from finance_dev.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class DeleteKeysRequestTypedDict(TypedDict):
    keys: List[str]
    r"""Array of setting keys to delete"""


class DeleteKeysRequest(BaseModel):
    keys: List[str]
    r"""Array of setting keys to delete"""
