"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date
from finance_dev.types import BaseModel
from finance_dev.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetEarningsCalendarRequestTypedDict(TypedDict):
    from_: date
    r"""Start date in YYYY-MM-DD format"""
    to: date
    r"""End date in YYYY-MM-DD format"""
    symbol: NotRequired[str]
    r"""Optional stock symbol to filter results. If not provided, returns earnings for all symbols."""


class GetEarningsCalendarRequest(BaseModel):
    from_: Annotated[
        date,
        pydantic.Field(alias="from"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Start date in YYYY-MM-DD format"""

    to: Annotated[
        date, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""End date in YYYY-MM-DD format"""

    symbol: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Optional stock symbol to filter results. If not provided, returns earnings for all symbols."""
