"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from finance_dev.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UpdateClientStatusRequestTypedDict(TypedDict):
    client_id: str
    r"""OAuth2 client ID"""
    status: str
    r"""Client status: 'active', 'inactive', or 'suspended'"""


class UpdateClientStatusRequest(BaseModel):
    client_id: str
    r"""OAuth2 client ID"""

    status: str
    r"""Client status: 'active', 'inactive', or 'suspended'"""


class UpdateClientStatusResponseTypedDict(TypedDict):
    r"""Client status updated successfully"""

    client_id: NotRequired[str]
    r"""OAuth2 client ID"""
    message: NotRequired[str]
    r"""Status update message"""
    updated_at: NotRequired[datetime]
    r"""Status update timestamp"""


class UpdateClientStatusResponse(BaseModel):
    r"""Client status updated successfully"""

    client_id: Optional[str] = None
    r"""OAuth2 client ID"""

    message: Optional[str] = None
    r"""Status update message"""

    updated_at: Optional[datetime] = None
    r"""Status update timestamp"""
