
from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from ntnx_vmm_py_client.api.esxi_stats_api import EsxiStatsApi
from ntnx_vmm_py_client.api.esxi_vm_api import EsxiVmApi
from ntnx_vmm_py_client.api.image_placement_policies_api import ImagePlacementPoliciesApi
from ntnx_vmm_py_client.api.image_rate_limit_policies_api import ImageRateLimitPoliciesApi
from ntnx_vmm_py_client.api.images_api import ImagesApi
from ntnx_vmm_py_client.api.ovas_api import OvasApi
from ntnx_vmm_py_client.api.stats_api import StatsApi
from ntnx_vmm_py_client.api.template_placement_policies_api import TemplatePlacementPoliciesApi
from ntnx_vmm_py_client.api.templates_api import TemplatesApi
from ntnx_vmm_py_client.api.vm_api import VmApi
from ntnx_vmm_py_client.api.vm_anti_affinity_policies_api import VmAntiAffinityPoliciesApi
from ntnx_vmm_py_client.api.vm_guest_customization_profiles_api import VmGuestCustomizationProfilesApi
from ntnx_vmm_py_client.api.vm_host_affinity_policies_api import VmHostAffinityPoliciesApi
from ntnx_vmm_py_client.api.vm_recovery_points_api import VmRecoveryPointsApi
from ntnx_vmm_py_client.api.vm_startup_policies_api import VmStartupPoliciesApi
