# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetConversationResolutionResponse(UniversalBaseModel):
    total_conversations: int = pydantic.Field()
    """
    Total number of conversations in the period
    """

    resolved_conversations: int = pydantic.Field()
    """
    Number of resolved conversations
    """

    unresolved_conversations: int = pydantic.Field()
    """
    Number of unresolved conversations
    """

    resolution_rate: float = pydantic.Field()
    """
    Percentage of conversations resolved (0-100)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
