from _typeshed import Incomplete

class TimeoutException(Exception):
    message: Incomplete
    def __init__(self, message) -> None: ...

class Timeout:
    def __init__(self, timeout, message) -> None: ...
    def remaining(self): ...
    def timed_out(self): ...
    def check_time_out_for(self, activity) -> None: ...
