import threading
from _typeshed import Incomplete
from hil.core import Cantp as Cantp

class UdsServer(threading.Thread):
    tp: Incomplete
    live: int
    timeout: int
    ctx: Incomplete
    def __init__(self, tp: Cantp) -> None: ...
    def service_default_handle(self, req_bytes: bytearray) -> bytearray: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def run(self) -> None: ...
