# coding: utf-8

"""
    Kadoa API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Contact: support@kadoa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_v5_workspaces_workspace_id_details_get(self) -> None:
        """Test case for v5_workspaces_workspace_id_details_get

        Get workspace details (supports users, teams, and organizations)
        """
        pass

    def test_v5_workspaces_workspace_id_quotas_get(self) -> None:
        """Test case for v5_workspaces_workspace_id_quotas_get

        Get workspace quotas and usage (supports teams and organizations)
        """
        pass

    def test_v5_workspaces_workspace_id_usage_get(self) -> None:
        """Test case for v5_workspaces_workspace_id_usage_get

        Get workspace usage data (supports teams and organizations)
        """
        pass


if __name__ == '__main__':
    unittest.main()
