# coding: utf-8

"""
    Kadoa API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Contact: support@kadoa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.data_validation_config1_alerting import DataValidationConfig1Alerting
from openapi_client.models.validation_rule_counts import ValidationRuleCounts
from typing import Optional, Set
from typing_extensions import Self

class DataValidationConfig(BaseModel):
    """
    Configuration for data validation
    """ # noqa: E501
    enabled: StrictBool
    alerting: Optional[DataValidationConfig1Alerting] = None
    rule_counts: Optional[ValidationRuleCounts] = Field(default=None, alias="ruleCounts")
    __properties: ClassVar[List[str]] = ["enabled", "alerting", "ruleCounts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataValidationConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of alerting
        if self.alerting:
            _dict['alerting'] = self.alerting.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rule_counts
        if self.rule_counts:
            _dict['ruleCounts'] = self.rule_counts.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataValidationConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled"),
            "alerting": DataValidationConfig1Alerting.from_dict(obj["alerting"]) if obj.get("alerting") is not None else None,
            "ruleCounts": ValidationRuleCounts.from_dict(obj["ruleCounts"]) if obj.get("ruleCounts") is not None else None
        })
        return _obj


