from ._tensor import FLOAT_2_COMPLEX as FLOAT_2_COMPLEX, bmm as bmm, unary_operators_preprocess as unary_operators_preprocess
from .utils import device_map_torch as device_map_torch, dtype_map_torch as dtype_map_torch
from pyvqnet.backends_mock import TorchMock as TorchMock

def expval_pauli(self, q_machine, obs): ...
def ry_matrix(params): ...
def crz_matrix(params): ...
def marginal_prob(prob, num_wires, wires): ...
def probs(q_state, num_wires, wires): ...
