# coding: utf-8

"""
    Kadoa API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Contact: support@kadoa.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v4_adhoc_schema_id_post400_response import V4AdhocSchemaIdPost400Response

class TestV4AdhocSchemaIdPost400Response(unittest.TestCase):
    """V4AdhocSchemaIdPost400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V4AdhocSchemaIdPost400Response:
        """Test V4AdhocSchemaIdPost400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V4AdhocSchemaIdPost400Response`
        """
        model = V4AdhocSchemaIdPost400Response()
        if include_optional:
            return V4AdhocSchemaIdPost400Response(
                error = ''
            )
        else:
            return V4AdhocSchemaIdPost400Response(
        )
        """

    def testV4AdhocSchemaIdPost400Response(self):
        """Test V4AdhocSchemaIdPost400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
