# coding: utf-8

"""
    public-api

    Public-facing API for external access

    The version of the OpenAPI document: 8779317
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from knowledge_stack.models.thread_agent_token_response import ThreadAgentTokenResponse

class TestThreadAgentTokenResponse(unittest.TestCase):
    """ThreadAgentTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThreadAgentTokenResponse:
        """Test ThreadAgentTokenResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThreadAgentTokenResponse`
        """
        model = ThreadAgentTokenResponse()
        if include_optional:
            return ThreadAgentTokenResponse(
                agent_id = '',
                agent_name = '',
                agent_url = '',
                agent_thread_token = ''
            )
        else:
            return ThreadAgentTokenResponse(
                agent_id = '',
                agent_name = '',
                agent_url = '',
        )
        """

    def testThreadAgentTokenResponse(self):
        """Test ThreadAgentTokenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
