# coding: utf-8

"""
    public-api

    Public-facing API for external access

    The version of the OpenAPI document: 8779317
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from knowledge_stack.models.resp_document_version import RespDocumentVersion

class TestRespDocumentVersion(unittest.TestCase):
    """RespDocumentVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RespDocumentVersion:
        """Test RespDocumentVersion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RespDocumentVersion`
        """
        model = RespDocumentVersion()
        if include_optional:
            return RespDocumentVersion(
                id = '',
                document_id = '',
                processing_status = 'PENDING',
                document_version_metadata = knowledge_stack.models.document_version_metadata.DocumentVersionMetadata(
                    summary = '', 
                    toc = '', 
                    num_pages = 56, 
                    file_created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    file_updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                version_number = 56,
                document_hash = '',
                active_chunk_container_id = '',
                asset_download_url = ''
            )
        else:
            return RespDocumentVersion(
                id = '',
                document_id = '',
                processing_status = 'PENDING',
                version_number = 56,
                document_hash = '',
        )
        """

    def testRespDocumentVersion(self):
        """Test RespDocumentVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
