"""
AWS CloudFormation PCAConnectorSCEP Resources

⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️

This file is automatically generated from the AWS CloudFormation Resource Specification.
Any manual changes will be overwritten when regenerated.

Version Information:
  CloudFormation Spec: 2025.12.11
  Generator Version: 1.0.0
  Combined: spec-2025.12.11_gen-1.0.0
  Generated: 2025-12-17 21:57:48

To regenerate this file:
    uv run python -m cloudformation_dataclasses.codegen.generator --service PCAConnectorSCEP
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar, Optional, Union

from cloudformation_dataclasses.core.base import CloudFormationResource, PropertyType, Tag
from cloudformation_dataclasses.intrinsics.functions import GetAtt, Ref, Sub


@dataclass
class Challenge(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pcaco"""

    resource_type: ClassVar[str] = "AWS::PCAConnectorSCEP::Challenge"
    _property_mappings: ClassVar[dict[str, str]] = {
        "connector_arn": "ConnectorArn",
        "tags": "Tags",
    }

    connector_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    tags: Optional[dict[str, str]] = None

    @property
    def attr_challenge_arn(self) -> GetAtt:
        """Get the ChallengeArn attribute."""
        return self.get_att("ChallengeArn")




@dataclass
class IntuneConfiguration(PropertyType):
    _property_mappings: ClassVar[dict[str, str]] = {
        "azure_application_id": "AzureApplicationId",
        "domain": "Domain",
    }

    azure_application_id: Optional[Union[str, Ref, GetAtt, Sub]] = None
    domain: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class MobileDeviceManagement(PropertyType):
    _property_mappings: ClassVar[dict[str, str]] = {
        "intune": "Intune",
    }

    intune: Optional[IntuneConfiguration] = None


@dataclass
class OpenIdConfiguration(PropertyType):
    _property_mappings: ClassVar[dict[str, str]] = {
        "issuer": "Issuer",
        "audience": "Audience",
        "subject": "Subject",
    }

    issuer: Optional[Union[str, Ref, GetAtt, Sub]] = None
    audience: Optional[Union[str, Ref, GetAtt, Sub]] = None
    subject: Optional[Union[str, Ref, GetAtt, Sub]] = None


@dataclass
class Connector(CloudFormationResource):
    """http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-pcaco"""

    resource_type: ClassVar[str] = "AWS::PCAConnectorSCEP::Connector"
    _property_mappings: ClassVar[dict[str, str]] = {
        "certificate_authority_arn": "CertificateAuthorityArn",
        "mobile_device_management": "MobileDeviceManagement",
        "tags": "Tags",
    }

    certificate_authority_arn: Optional[Union[str, Ref, GetAtt, Sub]] = None
    mobile_device_management: Optional[MobileDeviceManagement] = None
    tags: Optional[dict[str, str]] = None

    @property
    def attr_connector_arn(self) -> GetAtt:
        """Get the ConnectorArn attribute."""
        return self.get_att("ConnectorArn")

    @property
    def attr_open_id_configuration__audience(self) -> GetAtt:
        """Get the OpenIdConfiguration.Audience attribute."""
        return self.get_att("OpenIdConfiguration.Audience")

    @property
    def attr_type(self) -> GetAtt:
        """Get the Type attribute."""
        return self.get_att("Type")

    @property
    def attr_open_id_configuration__issuer(self) -> GetAtt:
        """Get the OpenIdConfiguration.Issuer attribute."""
        return self.get_att("OpenIdConfiguration.Issuer")

    @property
    def attr_endpoint(self) -> GetAtt:
        """Get the Endpoint attribute."""
        return self.get_att("Endpoint")

    @property
    def attr_open_id_configuration(self) -> GetAtt:
        """Get the OpenIdConfiguration attribute."""
        return self.get_att("OpenIdConfiguration")

    @property
    def attr_open_id_configuration__subject(self) -> GetAtt:
        """Get the OpenIdConfiguration.Subject attribute."""
        return self.get_att("OpenIdConfiguration.Subject")



