import pydicom.uid
from pynetdicom import build_context
# noinspection PyProtectedMember
from pynetdicom.sop_class import _STORAGE_CLASSES  # type: ignore

TRANSFER_SYNTAX = [
    pydicom.uid.ExplicitVRLittleEndian,
    pydicom.uid.ExplicitVRBigEndian,
    pydicom.uid.JPEGBaseline8Bit,
    pydicom.uid.JPEGExtended12Bit,
    pydicom.uid.JPEGLosslessSV1,
    pydicom.uid.JPEG2000Lossless,
    pydicom.uid.JPEG2000
]

AllStoragePresentationContexts = [
    build_context(uid, TRANSFER_SYNTAX) for uid in sorted(_STORAGE_CLASSES.values())  # type: ignore
]

StoragePresentationContexts = AllStoragePresentationContexts[:128]

# Based on DCMTK dcuid.cc
SOP_CLASS_UID_TO_PREFIX = {
    pydicom.uid.AcquisitionContextSRStorage: 'SRa.',
    pydicom.uid.AdvancedBlendingPresentationStateStorage: 'PSa.',
    pydicom.uid.AmbulatoryECGWaveformStorage: 'ECA.',
    pydicom.uid.ArterialPulseWaveformStorage: 'WVa.',
    pydicom.uid.AutorefractionMeasurementsStorage: 'OPa.',
    pydicom.uid.BasicStructuredDisplayStorage: 'SD.',
    pydicom.uid.BasicTextSRStorage: 'SRt.',
    pydicom.uid.BasicVoiceAudioWaveformStorage: 'AUV.',
    pydicom.uid.BlendingSoftcopyPresentationStateStorage: 'PSb.',
    pydicom.uid.BodyPositionWaveformStorage: 'WVb.',
    pydicom.uid.BreastProjectionXRayImageStorageForPresentation: 'BX.',
    pydicom.uid.BreastProjectionXRayImageStorageForProcessing: 'BP.',
    pydicom.uid.BreastTomosynthesisImageStorage: 'BT.',
    pydicom.uid.CardiacElectrophysiologyWaveformStorage: 'WVc.',
    pydicom.uid.CArmPhotonElectronRadiationRecordStorage: 'RRc.',
    pydicom.uid.CArmPhotonElectronRadiationStorage: 'Rca.',
    pydicom.uid.ChestCADSRStorage: 'SRh.',
    pydicom.uid.ColonCADSRStorage: 'SRo.',
    pydicom.uid.ColorPaletteStorage: 'CP.',
    pydicom.uid.ColorSoftcopyPresentationStateStorage: 'PSc.',
    pydicom.uid.CompositingPlanarMPRVolumetricPresentationStateStorage: 'VPc.',
    pydicom.uid.Comprehensive3DSRStorage: 'SR3.',
    pydicom.uid.ComprehensiveSRStorage: 'SRc.',
    pydicom.uid.ComputedRadiographyImageStorage: 'CR.',
    pydicom.uid.ContentAssessmentResultsStorage: 'AS.',
    pydicom.uid.CornealTopographyMapStorage: 'CM.',
    pydicom.uid.CTDefinedProcedureProtocolStorage: 'PPcd.',
    pydicom.uid.CTImageStorage: 'CT.',
    pydicom.uid.CTPerformedProcedureProtocolStorage: 'PPcp.',
    pydicom.uid.DeformableSpatialRegistrationStorage: 'RGd.',
    pydicom.uid.DermoscopicPhotographyImageStorage: 'VLd.',
    pydicom.uid.DigitalIntraOralXRayImageStorageForPresentation: 'DXo.',
    pydicom.uid.DigitalIntraOralXRayImageStorageForProcessing: 'DPo.',
    pydicom.uid.DigitalMammographyXRayImageStorageForPresentation: 'DXm.',
    pydicom.uid.DigitalMammographyXRayImageStorageForProcessing: 'DPm.',
    pydicom.uid.DigitalXRayImageStorageForPresentation: 'DX.',
    pydicom.uid.DigitalXRayImageStorageForProcessing: 'DP.',
    pydicom.uid.ElectromyogramWaveformStorage: 'EMG.',
    pydicom.uid.ElectrooculogramWaveformStorage: 'EOG.',
    pydicom.uid.EncapsulatedCDAStorage: 'CDA.',
    pydicom.uid.EncapsulatedMTLStorage: 'MTL.',
    pydicom.uid.EncapsulatedOBJStorage: 'OBJ.',
    pydicom.uid.EncapsulatedPDFStorage: 'PDF.',
    pydicom.uid.EncapsulatedSTLStorage: 'STL.',
    pydicom.uid.EnhancedCTImageStorage: 'CTe.',
    pydicom.uid.EnhancedMRColorImageStorage: 'MRc.',
    pydicom.uid.EnhancedMRImageStorage: 'MRe.',
    pydicom.uid.EnhancedPETImageStorage: 'PIe.',
    pydicom.uid.EnhancedSRStorage: 'SRe.',
    pydicom.uid.EnhancedUSVolumeStorage: 'USe.',
    pydicom.uid.EnhancedXAImageStorage: 'XAe.',
    pydicom.uid.EnhancedXRayRadiationDoseSRStorage: 'SRde.',
    pydicom.uid.EnhancedXRFImageStorage: 'RFe.',
    pydicom.uid.ExtensibleSRStorage: 'SRx.',
    pydicom.uid.GeneralAudioWaveformStorage: 'AUG.',
    pydicom.uid.GeneralECGWaveformStorage: 'ECG.',
    pydicom.uid.GenericImplantTemplateStorage: 'IT.',
    pydicom.uid.GrayscalePlanarMPRVolumetricPresentationStateStorage: 'VPg.',
    pydicom.uid.GrayscaleSoftcopyPresentationStateStorage: 'PSg.',
    pydicom.uid.HangingProtocolStorage: 'HP.',
    pydicom.uid.HemodynamicWaveformStorage: 'WVh.',
    pydicom.uid.ImplantAssemblyTemplateStorage: 'ITa.',
    pydicom.uid.ImplantationPlanSRStorage: 'SRi.',
    pydicom.uid.ImplantTemplateGroupStorage: 'ITg.',
    pydicom.uid.IntraocularLensCalculationsStorage: 'OPc.',
    pydicom.uid.IntravascularOpticalCoherenceTomographyImageStorageForPresentation: 'OCt.',
    pydicom.uid.IntravascularOpticalCoherenceTomographyImageStorageForProcessing: 'OCp.',
    pydicom.uid.KeratometryMeasurementsStorage: 'OPk.',
    pydicom.uid.KeyObjectSelectionDocumentStorage: 'KO.',
    pydicom.uid.LegacyConvertedEnhancedCTImageStorage: 'CTl.',
    pydicom.uid.LegacyConvertedEnhancedMRImageStorage: 'MRl.',
    pydicom.uid.LegacyConvertedEnhancedPETImageStorage: 'PIl.',
    pydicom.uid.LensometryMeasurementsStorage: 'OPl.',
    pydicom.uid.MacularGridThicknessAndVolumeReportStorage: 'SRg.',
    pydicom.uid.MammographyCADSRStorage: 'SRm.',
    pydicom.uid.MicroscopyBulkSimpleAnnotationsStorage: 'MAs.',
    pydicom.uid.MRImageStorage: 'MR.',
    pydicom.uid.MRSpectroscopyStorage: 'MRs.',
    pydicom.uid.MultichannelRespiratoryWaveformStorage: 'WVm.',
    pydicom.uid.MultiFrameGrayscaleByteSecondaryCaptureImageStorage: 'SCb.',
    pydicom.uid.MultiFrameGrayscaleWordSecondaryCaptureImageStorage: 'SCw.',
    pydicom.uid.MultiFrameSingleBitSecondaryCaptureImageStorage: 'SCs.',
    pydicom.uid.MultiFrameTrueColorSecondaryCaptureImageStorage: 'SCc.',
    pydicom.uid.MultipleVolumeRenderingVolumetricPresentationStateStorage: 'VPm.',
    pydicom.uid.NuclearMedicineImageStorage: 'NM.',
    pydicom.uid.OphthalmicAxialMeasurementsStorage: 'OPx.',
    pydicom.uid.OphthalmicOpticalCoherenceTomographyBscanVolumeAnalysisStorage: 'OCb.',
    pydicom.uid.OphthalmicOpticalCoherenceTomographyEnFaceImageStorage: 'OCe.',
    pydicom.uid.OphthalmicPhotography16BitImageStorage: 'OPw.',
    pydicom.uid.OphthalmicPhotography8BitImageStorage: 'OPb.',
    pydicom.uid.OphthalmicThicknessMapStorage: 'OPm.',
    pydicom.uid.OphthalmicTomographyImageStorage: 'OPt.',
    pydicom.uid.OphthalmicVisualFieldStaticPerimetryMeasurementsStorage: 'OPp.',
    pydicom.uid.ParametricMapStorage: 'PM.',
    pydicom.uid.PatientRadiationDoseSRStorage: 'SRq.',
    pydicom.uid.PerformedImagingAgentAdministrationSRStorage: 'SRi.',
    pydicom.uid.PlannedImagingAgentAdministrationSRStorage: 'SRj.',
    pydicom.uid.PositronEmissionTomographyImageStorage: 'PI.',
    pydicom.uid.ProcedureLogStorage: 'SRp.',
    pydicom.uid.ProtocolApprovalStorage: 'PA.',
    pydicom.uid.PseudoColorSoftcopyPresentationStateStorage: 'PSp.',
    pydicom.uid.RadiopharmaceuticalRadiationDoseSRStorage: 'SRr.',
    pydicom.uid.RawDataStorage: 'RAW.',
    pydicom.uid.RealWorldValueMappingStorage: 'RWM.',
    pydicom.uid.RespiratoryWaveformStorage: 'WVr.',
    pydicom.uid.RoboticArmRadiationStorage: 'Rra.',
    pydicom.uid.RoboticRadiationRecordStorage: 'RRr.',
    pydicom.uid.RoutineScalpElectroencephalogramWaveformStorage: 'EEG.',
    pydicom.uid.RTBeamsDeliveryInstructionStorage: 'RTd.',
    pydicom.uid.RTBeamsTreatmentRecordStorage: 'RTb.',
    pydicom.uid.RTBrachyApplicationSetupDeliveryInstructionStorage: 'RTa.',
    pydicom.uid.RTBrachyTreatmentRecordStorage: 'RTr.',
    pydicom.uid.RTDoseStorage: 'RD.',
    pydicom.uid.RTImageStorage: 'RI.',
    pydicom.uid.RTIonBeamsTreatmentRecordStorage: 'RTi.',
    pydicom.uid.RTIonPlanStorage: 'RPi.',
    pydicom.uid.RTPlanStorage: 'RP.',
    pydicom.uid.RTPhysicianIntentStorage: 'RIp.',
    pydicom.uid.RTRadiationRecordSetStorage: 'RSr.',
    pydicom.uid.RTRadiationSalvageRecordStorage: 'RRs.',
    pydicom.uid.RTRadiationSetDeliveryInstructionStorage: 'RSd.',
    pydicom.uid.RTRadiationSetStorage: 'RSe.',
    pydicom.uid.RTSegmentAnnotationStorage: 'RAs.',
    pydicom.uid.RTStructureSetStorage: 'RS.',
    pydicom.uid.RTTreatmentPreparationStorage: 'RTp.',
    pydicom.uid.RTTreatmentSummaryRecordStorage: 'RTs.',
    pydicom.uid.SecondaryCaptureImageStorage: 'SC.',
    pydicom.uid.SegmentationStorage: 'SG.',
    pydicom.uid.SegmentedVolumeRenderingVolumetricPresentationStateStorage: 'VPs.',
    pydicom.uid.SimplifiedAdultEchoSRStorage: 'SRu.',
    pydicom.uid.SleepElectroencephalogramWaveformStorage: 'WVs.',
    pydicom.uid.SpatialFiducialsStorage: 'FID.',
    pydicom.uid.SpatialRegistrationStorage: 'RGs.',
    pydicom.uid.SpectaclePrescriptionReportStorage: 'SRs.',
    pydicom.uid.StereometricRelationshipStorage: 'OPr.',
    pydicom.uid.SubjectiveRefractionMeasurementsStorage: 'OPs.',
    pydicom.uid.SurfaceScanMeshStorage: 'SSm.',
    pydicom.uid.SurfaceScanPointCloudStorage: 'SSp.',
    pydicom.uid.SurfaceSegmentationStorage: 'SGs.',
    pydicom.uid.TomotherapeuticRadiationRecordStorage: 'RRt.',
    pydicom.uid.TomotherapeuticRadiationStorage: 'Rto.',
    pydicom.uid.TractographyResultsStorage: 'TR.',
    pydicom.uid.TwelveLeadECGWaveformStorage: 'TLE.',
    pydicom.uid.UltrasoundImageStorage: 'US.',
    pydicom.uid.UltrasoundMultiFrameImageStorage: 'USm.',
    pydicom.uid.VideoEndoscopicImageStorage: 'VVe.',
    pydicom.uid.VideoMicroscopicImageStorage: 'VVm.',
    pydicom.uid.VideoPhotographicImageStorage: 'VVp.',
    pydicom.uid.VisualAcuityMeasurementsStorage: 'OPv.',
    pydicom.uid.VLEndoscopicImageStorage: 'VLe.',
    pydicom.uid.VLMicroscopicImageStorage: 'VLm.',
    pydicom.uid.VLPhotographicImageStorage: 'VLp.',
    pydicom.uid.VLSlideCoordinatesMicroscopicImageStorage: 'VLs.',
    pydicom.uid.VLWholeSlideMicroscopyImageStorage: 'VLw.',
    pydicom.uid.VolumeRenderingVolumetricPresentationStateStorage: 'VPv.',
    pydicom.uid.WideFieldOphthalmicPhotographyStereographicProjectionImageStorage: 'OWs.',
    pydicom.uid.WideFieldOphthalmicPhotography3DCoordinatesImageStorage: 'OW3.',
    pydicom.uid.XADefinedProcedureProtocolStorage: 'PPxd.',
    pydicom.uid.XAPerformedProcedureProtocolStorage: 'PPxp.',
    pydicom.uid.XAXRFGrayscaleSoftcopyPresentationStateStorage: 'PSx.',
    pydicom.uid.XRay3DAngiographicImageStorage: 'XA3.',
    pydicom.uid.XRay3DCraniofacialImageStorage: 'XC3.',
    pydicom.uid.XRayAngiographicImageStorage: 'XA.',
    pydicom.uid.XRayRadiationDoseSRStorage: 'SRd.',
    pydicom.uid.XRayRadiofluoroscopicImageStorage: 'RF.',
}
