# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ReindexingJobRecord(UniversalBaseModel):
    """
    Reindexing job record model
    """

    domain: str
    status: str
    memory_mb: int
    retry_count: int
    task_arn: typing.Optional[str] = None
    sqs_message_id: typing.Optional[str] = None
    started_at: typing.Optional[dt.datetime] = None
    updated_at: dt.datetime
    completed_at: typing.Optional[dt.datetime] = None
    duration_ms: typing.Optional[int] = None
    num_inserted: typing.Optional[int] = None
    error: typing.Optional[str] = None
    reason: typing.Optional[str] = None
    task_arns: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
