"""Type stubs for nitro - RocketSim Python bindings"""

from typing import List, Optional, Callable, Tuple
from enum import IntEnum

__version__: str

# ========== Math Types ==========

class Vec:
    """3D vector"""

    x: float
    y: float
    z: float

    def __init__(self, x: float = 0, y: float = 0, z: float = 0) -> None: ...
    def is_zero(self) -> bool: ...
    def to_2d(self) -> Vec: ...
    def length_sq(self) -> float: ...
    def length(self) -> float: ...
    def length_sq_2d(self) -> float: ...
    def length_2d(self) -> float: ...
    def dot(self, other: Vec) -> float: ...
    def cross(self, other: Vec) -> Vec: ...
    def dist_sq(self, other: Vec) -> float: ...
    def dist(self, other: Vec) -> float: ...
    def dist_sq_2d(self, other: Vec) -> float: ...
    def dist_2d(self, other: Vec) -> float: ...
    def normalized(self) -> Vec: ...
    def __add__(self, other: Vec) -> Vec: ...
    def __sub__(self, other: Vec) -> Vec: ...
    def __mul__(self, other: Vec | float) -> Vec: ...
    def __truediv__(self, other: Vec | float) -> Vec: ...
    def __rmul__(self, other: float) -> Vec: ...
    def __rtruediv__(self, other: float) -> Vec: ...
    def __iadd__(self, other: Vec) -> Vec: ...
    def __isub__(self, other: Vec) -> Vec: ...
    def __imul__(self, other: Vec | float) -> Vec: ...
    def __itruediv__(self, other: Vec | float) -> Vec: ...
    def __neg__(self) -> Vec: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Vec) -> bool: ...
    def __gt__(self, other: Vec) -> bool: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __repr__(self) -> str: ...

class RotMat:
    """3x3 rotation matrix (column-major)"""

    forward: Vec
    right: Vec
    up: Vec

    def __init__(self, forward: Vec = ..., right: Vec = ..., up: Vec = ...) -> None: ...
    @staticmethod
    def get_identity() -> RotMat: ...
    @staticmethod
    def look_at(forward_dir: Vec, up_dir: Vec) -> RotMat: ...
    def dot(self, other: Vec | RotMat) -> Vec | RotMat: ...
    def transpose(self) -> RotMat: ...
    def __add__(self, other: RotMat) -> RotMat: ...
    def __sub__(self, other: RotMat) -> RotMat: ...
    def __mul__(self, val: float) -> RotMat: ...
    def __truediv__(self, val: float) -> RotMat: ...
    def __iadd__(self, other: RotMat) -> RotMat: ...
    def __isub__(self, other: RotMat) -> RotMat: ...
    def __imul__(self, val: float) -> RotMat: ...
    def __itruediv__(self, val: float) -> RotMat: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class Angle:
    """Euler angles in radians (yaw, pitch, roll)"""

    yaw: float
    pitch: float
    roll: float

    def __init__(self, yaw: float = 0, pitch: float = 0, roll: float = 0) -> None: ...
    @staticmethod
    def from_rot_mat(mat: RotMat) -> Angle: ...
    def to_rot_mat(self) -> RotMat: ...
    @staticmethod
    def from_vec(forward: Vec) -> Angle: ...
    def get_forward_vec(self) -> Vec: ...
    def normalize_fix(self) -> None: ...
    def get_delta_to(self, other: Angle) -> Angle: ...
    def __add__(self, other: Angle) -> Angle: ...
    def __sub__(self, other: Angle) -> Angle: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __repr__(self) -> str: ...

# ========== Game Types ==========

class GameMode(IntEnum):
    """Game mode types"""

    SOCCAR = ...
    HOOPS = ...
    HEATSEEKER = ...
    SNOWDAY = ...
    DROPSHOT = ...
    THE_VOID = ...

class Team(IntEnum):
    """Team colors"""

    BLUE = ...
    ORANGE = ...

class DemoMode(IntEnum):
    """Demolition mode"""

    NORMAL = ...
    ON_CONTACT = ...
    DISABLED = ...

class ArenaMemWeightMode(IntEnum):
    """Arena memory weight mode"""

    HEAVY = ...
    LIGHT = ...

class RocketSimStage(IntEnum):
    """RocketSim initialization stage"""

    UNINITIALIZED = ...
    INITIALIZING = ...
    INITIALIZED = ...

# ========== Physics State ==========

class PhysState:
    """Base physics state"""

    pos: Vec
    rot_mat: RotMat
    vel: Vec
    ang_vel: Vec

    def __init__(self) -> None: ...
    def get_inverted_y(self) -> PhysState: ...

# ========== Car ==========

class CarControls:
    """Car control inputs"""

    throttle: float
    steer: float
    pitch: float
    yaw: float
    roll: float
    jump: bool
    boost: bool
    handbrake: bool

    def __init__(self) -> None: ...
    def clamp_fix(self) -> None: ...

class BallHitInfo:
    """Information about ball hit"""

    is_valid: bool
    relative_pos_on_ball: Vec
    ball_pos: Vec
    extra_hit_vel: Vec
    tick_count_when_hit: int
    tick_count_when_extra_impulse_applied: int

    def __init__(self) -> None: ...

class CarState(PhysState):
    """Car physics state"""

    is_on_ground: bool
    wheels_with_contact: List[bool]  # Length 4
    has_jumped: bool
    has_double_jumped: bool
    has_flipped: bool
    flip_rel_torque: Vec
    jump_time: float
    flip_time: float
    is_flipping: bool
    is_jumping: bool
    air_time: float
    air_time_since_jump: float
    boost: float
    time_since_boosted: float
    is_boosting: bool
    boosting_time: float
    is_supersonic: bool
    supersonic_time: float
    handbrake_val: float
    is_auto_flipping: bool
    auto_flip_timer: float
    auto_flip_torque_scale: float
    is_demoed: bool
    demo_respawn_timer: float
    ball_hit_info: BallHitInfo
    last_controls: CarControls

    def __init__(self) -> None: ...
    def has_flip_or_jump(self) -> bool: ...
    def has_flip_reset(self) -> bool: ...
    def got_flip_reset(self) -> bool: ...

class WheelPairConfig:
    """Configuration for a pair of wheels"""

    wheel_radius: float
    suspension_rest_length: float
    connection_point_offset: Vec

    def __init__(self) -> None: ...

class CarConfig:
    """Car configuration"""

    hitbox_size: Vec
    hitbox_pos_offset: Vec
    front_wheels: WheelPairConfig
    back_wheels: WheelPairConfig
    three_wheels: bool
    dodge_deadzone: float

    def __init__(self) -> None: ...

# Preset car configs
CAR_CONFIG_OCTANE: CarConfig
CAR_CONFIG_DOMINUS: CarConfig
CAR_CONFIG_PLANK: CarConfig
CAR_CONFIG_BREAKOUT: CarConfig
CAR_CONFIG_HYBRID: CarConfig
CAR_CONFIG_MERC: CarConfig

class Car:
    """Car instance"""

    config: CarConfig
    team: Team
    id: int
    controls: CarControls
    state: CarState

    def get_state(self) -> CarState: ...
    def set_state(self, state: CarState) -> None: ...
    def respawn(
        self, game_mode: GameMode, seed: int = -1, boost_amount: float = 33.0
    ) -> None: ...
    def demolish(self) -> None: ...
    def get_forward_dir(self) -> Vec: ...
    def get_right_dir(self) -> Vec: ...
    def get_up_dir(self) -> Vec: ...

# ========== Ball ==========

class BallState(PhysState):
    """Ball physics state"""
    def __init__(self) -> None: ...

class Ball:
    """Ball instance"""

    state: BallState

    def get_state(self) -> BallState: ...
    def set_state(self, state: BallState) -> None: ...

# ========== Boost Pads ==========

class BoostPadConfig:
    """Boost pad configuration"""

    pos: Vec
    is_big: bool

    def __init__(self) -> None: ...

class BoostPadState:
    """Boost pad state"""

    is_active: bool
    cooldown: float

    def __init__(self) -> None: ...

class BoostPad:
    """Boost pad instance"""

    config: BoostPadConfig

    def get_state(self) -> BoostPadState: ...
    def set_state(self, state: BoostPadState) -> None: ...

# ========== Arena Configuration ==========

class MutatorConfig:
    """Physics mutator configuration"""

    gravity: Vec
    car_mass: float
    car_world_friction: float
    car_world_restitution: float
    ball_mass: float
    ball_max_speed: float
    ball_drag: float
    ball_world_friction: float
    ball_world_restitution: float
    jump_accel: float
    jump_immediate_force: float
    boost_accel_ground: float
    boost_accel_air: float
    boost_used_per_second: float
    respawn_delay: float
    bump_cooldown_time: float
    boost_pad_cooldown_big: float
    boost_pad_cooldown_small: float
    car_spawn_boost_amount: float
    ball_hit_extra_force_scale: float
    bump_force_scale: float
    ball_radius: float
    unlimited_flips: bool
    unlimited_double_jumps: bool
    demo_mode: DemoMode
    enable_team_demos: bool

    def __init__(self, game_mode: GameMode) -> None: ...

class ArenaConfig:
    """Arena configuration"""

    mem_weight_mode: ArenaMemWeightMode
    min_pos: Vec
    max_pos: Vec
    max_aabb_len: float
    no_ball_rot: bool
    use_custom_broadphase: bool
    max_objects: int

    def __init__(self) -> None: ...

# ========== Arena ==========

class Arena:
    """Main simulation container"""

    game_mode: GameMode
    tick_count: int
    tick_rate: float
    tick_time: float
    ball: Ball

    @staticmethod
    def create(
        game_mode: GameMode, arena_config: ArenaConfig = ..., tick_rate: float = 120.0
    ) -> Arena: ...
    def get_cars(self) -> List[Car]: ...
    def add_car(self, team: Team, config: CarConfig = ...) -> Car: ...
    def remove_car(self, id: int) -> bool: ...
    def get_car(self, id: int) -> Optional[Car]: ...
    def step(self, ticks_to_simulate: int = 1) -> None: ...
    def reset_to_random_kickoff(self, seed: int = -1) -> None: ...
    def is_ball_probably_going_in(
        self,
        max_time: float = 2.0,
        extra_margin: float = 0.0,
        goal_team_out: Optional[Team] = None,
    ) -> bool: ...
    def is_ball_scored(self) -> bool: ...
    def get_mutator_config(self) -> MutatorConfig: ...
    def set_mutator_config(self, config: MutatorConfig) -> None: ...
    def get_arena_config(self) -> ArenaConfig: ...
    def get_boost_pads(self) -> List[BoostPad]: ...
    def clone(self, copy_callbacks: bool = False) -> Arena: ...
    def set_goal_score_callback(
        self, callback: Callable[[Arena, Team], None]
    ) -> None: ...
    def set_car_bump_callback(
        self, callback: Callable[[Arena, Car, Car, bool], None]
    ) -> None: ...

# ========== Initialization ==========

def init(collision_meshes_folder: str, silent: bool = False) -> None:
    """Initialize RocketSim with collision mesh folder"""
    ...

def get_stage() -> RocketSimStage:
    """Get the current initialization stage"""
    ...

# ========== Ball Prediction ==========

class BallPredTracker:
    """Ball trajectory prediction tracker"""

    pred_data: List[BallState]
    num_pred_ticks: int

    def __init__(self, arena: Arena, num_pred_ticks: int) -> None: ...
    def update_from_arena(self, arena: Arena) -> None: ...
    def update_manual(
        self, cur_ball_state: BallState, ticks_since_last_update: int
    ) -> None: ...
    def force_update_all(self, initial_ball_state: BallState) -> None: ...
    def get_ball_state_for_time(self, pred_time: float) -> BallState: ...

# ========== Game Event Tracking ==========

class GameEventTrackerConfig:
    """Configuration for game event tracking"""

    shot_min_speed: float
    shot_touch_min_delay: float
    pred_score_extra_margin: float
    shot_event_cooldown: float
    shot_min_score_time: float
    goal_max_touch_time: float
    pass_max_touch_time: float

    def __init__(self) -> None: ...

class GameEventTracker:
    """Tracks shots, goals, and saves"""

    config: GameEventTrackerConfig
    auto_state_set_detection: bool

    def __init__(self) -> None: ...
    def update(self, arena: Arena) -> None: ...
    def reset_persistent_info(self) -> None: ...
    def set_shot_callback(
        self, callback: Callable[[Arena, Car, Optional[Car]], None]
    ) -> None: ...
    def set_goal_callback(
        self, callback: Callable[[Arena, Car, Optional[Car]], None]
    ) -> None: ...
    def set_save_callback(self, callback: Callable[[Arena, Car], None]) -> None: ...
