# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grr_response_proto/crowdstrike.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grr_response_proto/crowdstrike.proto',
  package='grr',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$grr_response_proto/crowdstrike.proto\x12\x03grr\"/\n\x1bGetCrowdstrikeAgentIdResult\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t'
)




_GETCROWDSTRIKEAGENTIDRESULT = _descriptor.Descriptor(
  name='GetCrowdstrikeAgentIdResult',
  full_name='grr.GetCrowdstrikeAgentIdResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='grr.GetCrowdstrikeAgentIdResult.agent_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['GetCrowdstrikeAgentIdResult'] = _GETCROWDSTRIKEAGENTIDRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetCrowdstrikeAgentIdResult = _reflection.GeneratedProtocolMessageType('GetCrowdstrikeAgentIdResult', (_message.Message,), {
  'DESCRIPTOR' : _GETCROWDSTRIKEAGENTIDRESULT,
  '__module__' : 'grr_response_proto.crowdstrike_pb2'
  # @@protoc_insertion_point(class_scope:grr.GetCrowdstrikeAgentIdResult)
  })
_sym_db.RegisterMessage(GetCrowdstrikeAgentIdResult)


# @@protoc_insertion_point(module_scope)
