"""Type stubs for the Rust native extension module."""

from collections.abc import Sequence

# -----------------------------------------------------------------------------
# Wire format types for parameter serialization (internal)
# -----------------------------------------------------------------------------

class WireCiphertext:
    """Serialized ciphertext for wire format (internal)."""

    @property
    def bit_width(self) -> int: ...
    @property
    def data(self) -> bytes: ...
    def __init__(self, data: bytes) -> None: ...
    def __eq__(self, other: object) -> bool: ...

class WireCiphertextArray:
    """Serialized ciphertext array for wire format (internal)."""

    @property
    def bit_width(self) -> int: ...
    @property
    def data(self) -> list[bytes]: ...
    def __init__(self, data: Sequence[bytes]) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class WireOutputCiphertextArray:
    """Output buffer declaration for wire format (internal)."""

    @property
    def bit_width(self) -> int: ...
    @property
    def size(self) -> int: ...
    def __init__(self, bit_width: int, size: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...

class WirePlaintext:
    """Plaintext value for wire format (internal)."""

    @property
    def bit_width(self) -> int: ...
    @property
    def value(self) -> int: ...
    def __init__(self, value: int, bit_width: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...

class WirePlaintextArray:
    """Plaintext array for wire format (internal)."""

    @property
    def bit_width(self) -> int: ...
    @property
    def values(self) -> list[int]: ...
    def __init__(self, values: Sequence[int], bit_width: int) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

WireParameter = (
    WireCiphertext
    | WireCiphertextArray
    | WireOutputCiphertextArray
    | WirePlaintext
    | WirePlaintextArray
)

class SecretKey:
    """Secret key for decryption operations."""

    @staticmethod
    def generate() -> SecretKey: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> SecretKey: ...
    def decrypt(self, ciphertext: Ciphertext, signed: bool) -> int: ...

class PublicKey:
    """Public key for encryption operations."""

    @staticmethod
    def from_secret_key(secret_key: SecretKey) -> PublicKey: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> PublicKey: ...
    def encrypt(self, value: int, bit_width: int, signed: bool) -> Ciphertext: ...

class ComputeKey:
    """Compute key for server-side FHE operations."""

    @staticmethod
    def from_secret_key(secret_key: SecretKey) -> ComputeKey: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> ComputeKey: ...

class KeySet:
    """A complete set of keys for FHE operations."""

    def __init__(
        self, secret_key: SecretKey, public_key: PublicKey, compute_key: ComputeKey
    ) -> None: ...
    @staticmethod
    def generate() -> KeySet: ...
    @property
    def secret_key(self) -> SecretKey: ...
    @property
    def public_key(self) -> PublicKey: ...
    @property
    def compute_key(self) -> ComputeKey: ...
    def encrypt(self, value: int, bit_width: int, signed: bool) -> Ciphertext: ...
    def decrypt(self, ciphertext: Ciphertext, signed: bool) -> int: ...

class Ciphertext:
    """An encrypted value."""

    @property
    def bit_width(self) -> int: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(data: bytes) -> Ciphertext: ...
    @staticmethod
    def encrypt(value: int, public_key: PublicKey, bit_width: int, signed: bool) -> Ciphertext: ...
    def decrypt(self, secret_key: SecretKey, signed: bool) -> int: ...

# Internal functions for parameter serialization. Not part of public API.
# Use Parameters.to_bytes() and Parameters.from_bytes() instead.
def serialize_parameters(params: Sequence[WireParameter]) -> bytes: ...
def deserialize_parameters(data: bytes) -> list[WireParameter]: ...
def deserialize_output(data: bytes) -> list[Ciphertext]: ...

# Version functions
def peek_parameters_version(data: bytes) -> int:
    """Peek the version number from parameter bytes without full deserialization."""
    ...

def peek_output_version(data: bytes) -> int:
    """Peek the version number from output bytes without full deserialization."""
    ...

def get_parameters_version() -> int:
    """Get the current parameters version."""
    ...

def get_output_version() -> int:
    """Get the current output version."""
    ...
