
import base64
DATA_B64 = "dmVyaWZ5X21zYV9tYXRjaF9wcm9tcHQgPSAiIiIKWW91IGFyZSBhIGJpbGluZ3VhbCBNYXJpdGltZSBBbmFseXN0LgpJIGhhdmUgYSByZXBvcnQgZXhjZXJwdCAoU291cmNlIEEgLSBWaWV0bmFtZXNlKSBhbmQgYSBNYXJpdGltZSBTYWZldHkgQW5ub3VuY2VtZW50IChTb3VyY2UgQiAtIFRyYW5zbGF0ZWQgZnJvbSBDaGluZXNlKS4KCioqVGFzazoqKiBEZXRlcm1pbmUgaWYgU291cmNlIEEgYW5kIFNvdXJjZSBCIHJlZmVyIHRvIHRoZSAqKlNBTUUgZXZlbnQqKiwgZGVzcGl0ZSB0cmFuc2xhdGlvbiBkaWZmZXJlbmNlcyBpbiBuYW1lcyBvciBzbGlnaHQgZGlzY3JlcGFuY2llcyBpbiBkZXRhaWxzLgoKKipTb3VyY2UgQSAoUmVwb3J0KToqKiAie3JlcG9ydF9jaHVua30iCioqU291cmNlIEIgKE1TQSBKU09OKToqKiAie21zYV9qc29uX3N0cmluZ30iCgoqKkFuYWx5c2lzIFJ1bGVzOioqCjEuICoqQ29vcmRpbmF0ZXM6KiogVHJ1c3QgbnVtYmVycyBvdmVyIHRleHQuIElmIGNvb3JkaW5hdGVzIG1hdGNoLCB0aGV5IGFyZSBsaWtlbHkgdGhlIHNhbWUuCjIuICoqVHJhbnNsYXRpb24gTm9pc2U6KioKICAgLSAiSGFpeWFuZyBTaGl5b3UiID09ICJI4bqjaSBExrDGoW5nIiA9PSAiSOG6o2kgRMawxqFuZyBUaOG6oWNoIER1IgogICAtICJOYW5zaGEiID09ICJUcsaw4budbmcgU2EiID09ICJOYW0gU2EiCiAgIC0gIlNhbnlhIiA9PSAiVGFtIMOBIgozLiAqKlRpbWU6KiogU3RhcnQvRW5kIHRpbWVzIHNob3VsZCBvdmVybGFwIG9yIGJlIHZlcnkgY2xvc2UuCgoqKk91dHB1dDoqKgpSZXR1cm4gSlNPTjoKe3sKICAiaXNfbWF0Y2giOiBib29sZWFuLCAvLyB0cnVlL2ZhbHNlCiAgImNvbmZpZGVuY2UiOiBpbnQsICAgLy8gMC0xMDAKICAicmVhc29uIjogIkV4cGxhaW4gd2h5LCBzcGVjaWZpY2FsbHkgbWVudGlvbmluZyBpZiB0cmFuc2xhdGlvbiBjYXVzZWQgZGlmZnMiCn19CiIiIg=="
def save(filename="code_moi_ve.py"):
    try:
        decoded = base64.b64decode(DATA_B64).decode("utf-8")
        with open(filename, "w", encoding="utf-8") as f:
            f.write(decoded)
        print(f"OK: Da luu code vao {filename}")
    except Exception as e:
        print(f"LOI: {e}")
