import xml.etree.ElementTree

def read_xml(path: str) -> xml.etree.ElementTree.Element | None: ...
def parse_junit(root: xml.etree.ElementTree.Element | None) -> tuple[int, int, int, int, int, float, list[dict[str, str]]]: ...
