from enum import StrEnum


class PresetType(StrEnum):
    """Enums for the different types of presets available in Coda."""

    JOBS = "jobs"
    WORKFLOWS = "workflows"
    LOUDNESS = "loudness"
    TIMECODE = "timecode"
    GROUPS = "groups"
    NAMING = "naming"
    DOLBY = "dolby"
    DTS = "dts"
    SUPER_SESSION = "super_session"
    IO_LOCATIONS = "io_locations"


class SourceType(StrEnum):
    """Enums for the different types of input sources for a job."""

    INTERLEAVED = "interleaved"
    MULTI_MONO = "multi_mono"
    ADM = "bwav_adm"
    IAB_MXF = "iab_mxf"


class VenueType(StrEnum):
    """Enums for the different venues supported."""

    NEARFIELD = "nearfield"
    THEATRICAL = "theatrical"
    ALL_FROM_ESSENCE = "all_from_essence"
    SAME_AS_INPUT = "same_as_input"


class InputFilter(StrEnum):
    """Enums for the input filters used in workflow process blocks."""

    ALL_STEMS = "all_stems"
    ALL_STEMS_EXCEPT_OPTIONALS = "all_stems_except_optionals"
    ALL_DX = "all_dx"
    ALL_MX = "all_mx"
    ALL_FX = "all_fx"
    MNE_STEMS = "m&e_stems"
    OPTIONALS_ONLY = "optionals_only"
    PRINTMASTER_ONLY = "printmaster_only"


class Language(StrEnum):
    """Enums for language codes."""

    NO_LINGUISTIC_CONTENT = "ZXX"
    QUALIFIED_FOR_ALL_LANGUAGES = "QAL"
    SEMI_TEXTLESS = "STX"
    ENGLISH = "ENG"
    AFRIKAANS = "AFK"
    ALBANIAN = "SQI"
    AMERICAN_SIGN_LANGUAGE = "ASE"
    ARABIC_MODERN_STANDARD = "MSA"
    ARABIC_EGYPTIAN = "ARE"
    ARABIC_UAE_LEBANON = "ARL"
    ARABIC_CLASSICAL_FORMAL = "QCA"
    ARABIC_SYRIAN = "ASY"
    ARAMAIC = "ARC"
    ARMENIAN = "HYE"
    AZERBAIJANI = "AZE"
    BELARUSIAN = "BEL"
    BOSNIAN = "BOS"
    BRITISH_SIGN_LANGUAGE = "BFI"
    BULGARIAN = "BUL"
    BURMESE = "BUR"
    CATALAN_VALENCIAN = "SCA"
    CHEROKEE = "CHR"
    CHINESE_CANTONESE = "CNT"
    CHINESE_MANDARIN_PRC = "PRC"
    CHINESE_MANDARIN_TAIWAN = "QMT"
    CHINESE_MIN_NAN = "TAI"
    CHINESE_SIMPLIFIED_CHARACTERS = "CMN"
    CHINESE_SIMPLIFIED_CHARACTERS_MALAYSIA = "ZM1"
    CHINESE_SIMPLIFIED_CHARACTERS_PRC = "CN1"
    CHINESE_SIMPLIFIED_CHARACTERS_SINGAPORE = "ZS1"
    CHINESE_TRADITIONAL_CHARACTERS = "CM1"
    CHINESE_TRADITIONAL_CHARACTERS_HONG_KONG = "YU1"
    CHINESE_TRADITIONAL_CHARACTERS_TAIWAN = "ZT1"
    CHINESE_WU = "WUU"
    CHOCTAW = "CHO"
    COMANCHE = "COM"
    CROATIAN = "CRO"
    CZECH = "CZE"
    DANISH = "DAN"
    DUTCH = "DUT"
    DUTCH_FLEMISH = "DFD"
    ENGLISH_AUSTRALIAN = "AUS"
    ENGLISH_BRITISH = "EUK"
    ENGLISH_FOR_INDONESIA = "ENI"
    ENGLISH_FOR_PHILIPPINES = "ENP"
    ESTONIAN = "EST"
    FARSI_PERSIAN = "PER"
    FINNISH = "FIN"
    FLEMISH = "FLM"
    FRENCH_CANADIAN_QUEBECOIS = "FRC"
    FRENCH_FRANCE = "FRP"
    GEORGIAN = "GEO"
    GERMAN = "GER"
    GERMAN_AUSTRIAN = "AST"
    GERMAN_SWISS_ALSATIAN = "SWI"
    GREEK_MODERN = "GRK"
    HAWAIIAN = "HAW"
    HEBREW = "HEB"
    HINDI = "HIN"
    HUNGARIAN = "HUN"
    ICELANDIC = "ICE"
    INDONESIAN_BAHASA = "INB"
    ITALIAN = "ITA"
    JAPANESE = "JPN"
    KANNADA = "KAN"
    KAZAKH = "KAZ"
    KOREAN = "KOR"
    LAKOTA = "LKT"
    LATIN = "LAT"
    LATVIAN = "LTV"
    LITHUANIAN = "LTH"
    LUXEMBOURGISH = "LTZ"
    MACEDONIAN = "MAS"
    MALAY_BAHASA = "MAB"
    MALAYALAM = "MYM"
    MAORI = "MAO"
    MOHAWK = "MOH"
    MONGOLIAN = "MON"
    NORTHERN_SAMI = "SME"
    NORWEGIAN = "NOR"
    OJIBWE = "OJI"
    PANJABI = "PAN"
    POLISH = "POL"
    PORTUGUESE_BRAZILIAN = "PTB"
    PORTUGUESE_EUROPEAN = "PTE"
    PUSHTO = "PUS"
    ROMANIAN_MOLDAVIAN = "ROM"
    RUSSIAN = "RUS"
    SERBIAN = "SER"
    SLAVIC = "SLA"
    SLOVAK = "SLK"
    SLOVENIAN = "SLV"
    SOMALI = "SOM"
    SPANISH_ARGENTINIAN = "SPA"
    SPANISH_CASTILIAN = "SPC"
    SPANISH_CHILEAN = "ECH"
    SPANISH_LATIN_AMERICAN = "LAS"
    SPANISH_MEXICAN = "SPM"
    SWEDISH = "SWE"
    TAGALOG = "TAG"
    TAIWANESE_MIN_NAN = "TAI"
    TAMIL = "TAM"
    TELUGU = "TEL"
    THAI = "THA"
    THAI_ISAN = "TTS"
    TURKISH = "TUR"
    UKRAINIAN = "UKR"
    URDU = "URD"
    VIETNAMESE = "VIE"
    UNDETERMINED = "UND"


class Format(StrEnum):
    """Enums for supported audio channel configurations."""

    ONE_ZERO = "1.0"
    TWO_ZERO = "2.0"
    THREE_ZERO = "3.0"
    LCRS = "LCRS"
    FIVE_ZERO = "5.0"
    FIVE_ZERO_TWO = "5.0.2"
    SEVEN_ZERO = "7.0"
    SEVEN_ONE = "7.1"
    FIVE_ONE = "5.1"
    FIVE_ONE_ONE = "5.1.1"
    FIVE_ONE_TWO = "5.1.2"
    FIVE_ZERO_FOUR = "5.0.4"
    SEVEN_ZERO_TWO = "7.0.2"
    FIVE_ONE_FOUR = "5.1.4"
    SEVEN_ONE_TWO = "7.1.2"
    SEVEN_ZERO_FOUR = "7.0.4"
    SEVEN_ONE_FOUR = "7.1.4"
    SEVEN_ONE_FIVE = "7.1.5"
    SEVEN_ZERO_SIX = "7.0.6"
    NINE_ZERO_FOUR = "9.0.4"
    SEVEN_ONE_SIX = "7.1.6"
    NINE_ONE_FOUR = "9.1.4"
    NINE_ZERO_SIX = "9.0.6"
    NINE_ONE_SIX = "9.1.6"
    IMAX5 = "imax5"
    IMAX6 = "imax6"
    IMAX12 = "imax12"
    ATMOS = "atmos"
    ALL_FROM_ESSENCE = "all_from_essence"


class StemType(StrEnum):
    """Enums for stem types."""

    PRINTMASTER = "printmaster"
    MNE = "mne"
    DME = "dme"
    WIDES = "wides"
    ALL_FROM_ESSENCE = "all_from_essence"


class FrameRate(StrEnum):
    """Enums for frame rates."""

    TWENTY_THREE = "23"
    TWENTY_FOUR = "24"
    TWENTY_FIVE = "25"
    TWENTY_NINE = "29"
    TWENTY_NINE_DROP_FRAME = "29DF"
    THIRTY = "30"
    ALL_FROM_ESSENCE = "all_from_essence"


class InputStemType(StrEnum):
    """Enums for input source stem types."""

    PRINTMASTER = "audio/pm"
    DX_COMP = "audio/dxcomp"
    FX_COMP = "audio/fxcomp"
    MX_COMP = "audio/mxcomp"
    DX = "audio/dx"
    MX = "audio/mx"
    FX = "audio/fx"
    BG = "audio/bg"
    FOL = "audio/fol"
    LG = "audio/lg"
    PFX = "audio/pfx"
    ADR = "audio/adr"
    SONG = "audio/sng"
    SCORE = "audio/scr"
    VOX = "audio/vox"
    FIX = "audio/fix"
    FFFX = "audio/fffx"
    MNE = "audio/mne"
    MNE_MX = "audio/mnemx"
    OPT_A = "audio/opta"
    OPT_B = "audio/optb"
    OPT_C = "audio/optc"
    OPT_D = "audio/optd"
    OPT_E = "audio/opte"
    OPT_F = "audio/optf"
    OPT_G = "audio/optg"
    AUDIO_DESCRIPTION = "audio/audiodescription"
    ARCH = "audio/arch"
    VO = "audio/vo"
    CRD = "audio/crd"
    NAR = "audio/nar"


class PackageType(StrEnum):
    """Enums for the different types of packages that can be created in a workflow."""

    ADM = "adm"
    DTS = "dts"
    IMAX_ENHANCED = "imax_enhanced"
    DOLBY = "dolby"
    DCP_MXF = "dcp_mxf"
    MULTI_MONO_REELS = "multi_mono_reels"
    SUPER_SESSION = "super_session"
    INTERLEAVED = "interleaved"
    MOV = "mov"
    MULTI_MONO = "multi_mono"
    # IAB_MXF = "iab_mxf"
