# nrobo/helpers/typing_logging.py
from typing import Any, Protocol


class DevLogger(Protocol):  # pragma: no cover
    # standard Logger API (only what you use)
    def debug(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def info(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def error(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
    def exception(self, msg: str, *args: Any, **kwargs: Any) -> None: ...

    # nRoBo extension
    def dev_debug(self, msg: str, *args: Any, **kwargs: Any) -> None: ...
