# coding: utf-8

"""
    Lakewatch public API

    Interact with the Lakewatch API.

    The version of the OpenAPI document: 0.1.30
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dasl_api.models.core_v1_rule_metric_summary_list import CoreV1RuleMetricSummaryList

class TestCoreV1RuleMetricSummaryList(unittest.TestCase):
    """CoreV1RuleMetricSummaryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoreV1RuleMetricSummaryList:
        """Test CoreV1RuleMetricSummaryList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoreV1RuleMetricSummaryList`
        """
        model = CoreV1RuleMetricSummaryList()
        if include_optional:
            return CoreV1RuleMetricSummaryList(
                api_version = '',
                items = [
                    null
                    ],
                kind = '',
                metadata = dasl_api.models.common/v1/list_meta.common.v1.ListMeta(
                    cursor = '', )
            )
        else:
            return CoreV1RuleMetricSummaryList(
                items = [
                    null
                    ],
        )
        """

    def testCoreV1RuleMetricSummaryList(self):
        """Test CoreV1RuleMetricSummaryList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
