# coding: utf-8

"""
    Lakewatch public API

    Interact with the Lakewatch API.

    The version of the OpenAPI document: 0.1.30
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dasl_api.models.core_v1_data_source_spec_custom import CoreV1DataSourceSpecCustom

class TestCoreV1DataSourceSpecCustom(unittest.TestCase):
    """CoreV1DataSourceSpecCustom unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoreV1DataSourceSpecCustom:
        """Test CoreV1DataSourceSpecCustom
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoreV1DataSourceSpecCustom`
        """
        model = CoreV1DataSourceSpecCustom()
        if include_optional:
            return CoreV1DataSourceSpecCustom(
                notebook = ''
            )
        else:
            return CoreV1DataSourceSpecCustom(
        )
        """

    def testCoreV1DataSourceSpecCustom(self):
        """Test CoreV1DataSourceSpecCustom"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
