# coding: utf-8

"""
    Lakewatch public API

    Interact with the Lakewatch API.

    The version of the OpenAPI document: 0.1.30
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dasl_api.models.content_v1_datasource_preset_silver_transform_inner import ContentV1DatasourcePresetSilverTransformInner

class TestContentV1DatasourcePresetSilverTransformInner(unittest.TestCase):
    """ContentV1DatasourcePresetSilverTransformInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentV1DatasourcePresetSilverTransformInner:
        """Test ContentV1DatasourcePresetSilverTransformInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentV1DatasourcePresetSilverTransformInner`
        """
        model = ContentV1DatasourcePresetSilverTransformInner()
        if include_optional:
            return ContentV1DatasourcePresetSilverTransformInner(
                name = '',
                filter = '',
                post_filter = '',
                fields = [
                    dasl_api.models.core/v1/data_source/field_spec.core.v1.DataSource.FieldSpec(
                        name = '', 
                        comment = '', 
                        assert = [
                            dasl_api.models.core_v1_data_source_field_spec_assert_inner.core_v1_DataSource_FieldSpec_assert_inner(
                                expr = '', 
                                message = '', )
                            ], 
                        from = '', 
                        alias = '', 
                        expr = '', 
                        literal = '', 
                        join = dasl_api.models.core_v1_data_source_field_spec_join.core_v1_DataSource_FieldSpec_join(
                            with_table = '', 
                            with_csv = dasl_api.models.core_v1_data_source_field_spec_join_with_csv.core_v1_DataSource_FieldSpec_join_withCSV(
                                path = '', ), 
                            lhs = '', 
                            rhs = '', 
                            select = '', ), )
                    ],
                utils = dasl_api.models.core/v1/data_source/field_utils.core.v1.DataSource.FieldUtils(
                    temporary_fields = [
                        dasl_api.models.core/v1/data_source/field_spec.core.v1.DataSource.FieldSpec(
                            name = '', 
                            comment = '', 
                            assert = [
                                dasl_api.models.core_v1_data_source_field_spec_assert_inner.core_v1_DataSource_FieldSpec_assert_inner(
                                    expr = '', 
                                    message = '', )
                                ], 
                            from = '', 
                            alias = '', 
                            expr = '', 
                            literal = '', 
                            join = dasl_api.models.core_v1_data_source_field_spec_join.core_v1_DataSource_FieldSpec_join(
                                with_table = '', 
                                with_csv = dasl_api.models.core_v1_data_source_field_spec_join_with_csv.core_v1_DataSource_FieldSpec_join_withCSV(
                                    path = '', ), 
                                lhs = '', 
                                rhs = '', 
                                select = '', ), )
                        ], 
                    unreferenced_columns = dasl_api.models.core_v1_data_source_field_utils_unreferenced_columns.core_v1_DataSource_FieldUtils_unreferencedColumns(
                        preserve = True, 
                        embed_column = '', 
                        embed_column_type = '', 
                        omit_columns = [
                            ''
                            ], 
                        duplicate_prefix = '', ), 
                    json_extract = [
                        dasl_api.models.core_v1_data_source_field_utils_json_extract_inner.core_v1_DataSource_FieldUtils_jsonExtract_inner(
                            source = '', 
                            omit_fields = [
                                ''
                                ], 
                            duplicate_prefix = '', 
                            embed_column = '', )
                        ], )
            )
        else:
            return ContentV1DatasourcePresetSilverTransformInner(
        )
        """

    def testContentV1DatasourcePresetSilverTransformInner(self):
        """Test ContentV1DatasourcePresetSilverTransformInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
