#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2506-50-gb9f491e6"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2506
#define NETGEN_VERSION_TWEAK 50
#define NETGEN_VERSION_HASH "gb9f491e6"
#endif // NETGEN_VERSION_HPP_INCLUDED
