from ..logging import log_error as log_error, log_info as log_info
from ..subprocess_utils import SubprocessExecutor as SubprocessExecutor
from .exceptions import WorkspaceDetectionError as WorkspaceDetectionError
from pathlib import Path

def get_venv_path(root: Path, executor: SubprocessExecutor) -> Path | None: ...
def get_active_venv_path_str(root: Path) -> str: ...
def get_active_venv_path(root: Path) -> str: ...
