from .function01 import DownloadER
from .function02 import Extractors
from .function08 import Instagram
from .function03 import FormatoR
from .function04 import Filename
from .function07 import Quality
from .function09 import Finders
from .function10 import Manage
from .function15 import Utubes
from .function05 import BKeys
from .function05 import UKeys
