from _typeshed import Incomplete

class QKmeansCircuits:
    num_qubits: Incomplete
    machine: Incomplete
    qubits: Incomplete
    cbits: Incomplete
    def __init__(self, num_qubits: int = 3) -> None: ...
    def get_theta(self, d): ...
    def build_circuit(self, x, y): ...
    def run(self, x, y): ...
    def __del__(self) -> None: ...
