class IncorrectConfigError(Exception): ...

class InsufficientPermissionsError(PermissionError): ...

class InvalidUsernameError(ValueError): ...

class InvalidInputError(ValueError): ...

class NotFoundError(ValueError): ...

class ProcessUnavailableError(NotFoundError): ...

class ContainerNotFoundError(NotFoundError): ...

class DuplicateError(ValueError): ...