// Automatically generated frame parser
// Generated by 0.0.1 at Fri Dec  5 01:14:49 2025.

import {
    FrameParserConfig, createFrameParserClass, GenericParserState,
} from './frame_base';

// =============================================================================
// BasicExtendedLength Frame Format Configuration
// =============================================================================

/** Configuration for BasicExtendedLength frame format */
export const BasicExtendedLengthConfig: FrameParserConfig = {
    name: 'BasicExtendedLength',
    startBytes: [0x90, 0x73],
    headerSize: 5,
    footerSize: 2,
    hasLength: true,
    lengthBytes: 2,
    hasCrc: true,
};

/**
 * BasicExtendedLength - Frame format parser and encoder
 * 
 * Format: [START_BYTE1=0x90] [START_BYTE2=0x73] [MSG_ID] [LEN16] [MSG...] [CRC1] [CRC2]
 *
 * This class is generated using createFrameParserClass() for code reuse.
 */
export const BasicExtendedLength = createFrameParserClass(BasicExtendedLengthConfig);

/** Parser state type alias for backward compatibility */
export type BasicExtendedLengthParserState = GenericParserState;
export { GenericParserState as BasicExtendedLengthParserState_Enum };
