from ...exceptions import CommandError as CommandError
from ...utils.logging import log_error as log_error, log_info as log_info
from ...utils.subprocess import run_command as run_command
from ...utils.workspace_detector import WorkspaceDetectionError as WorkspaceDetectionError, WorkspaceDetector as WorkspaceDetector
from ..format.python_formatter import generate_type_stubs as generate_type_stubs

def is_rust_enabled() -> bool: ...
def build_project_full() -> None: ...
def build_windows() -> None: ...
def build_unix() -> None: ...
def build_project() -> None: ...
