### COLUMN NAMES ###
# Provided in this file are dicts to standardize column names as necessary #

def col_map():
    return {
        'schedule':{
            'season':'season',
            'id':'game_id',
            'game_title':'game_title',
            'game_date':'game_date',
            'gameType':'season_type',
            'neutralSite':'neutral_site',
            'startTimeUTC':'start_time_utc',
            'start_time_est':'start_time_est',
            'easternUTCOffset':'eastern_utc',
            'venueUTCOffset':'venue_utc',
            'venueTimezone':'venue_timezone',
            'gameState':'game_state',
            'gameScheduleState':'game_schedule_state',
            'tvBroadcasts':'tv_broadcasts',
            'threeMinRecap':'three_min_recap',
            'threeMinRecapFr':'three_min_recap_fr',
            'condensedGame':'condensed_game',
            'condensedGameFr':'condensed_game_fr',
            'gameCenterLink':'gamecenter_link',
            'venue.default':'venue',
            'awayTeam.id':'away_team_id',
            'homeTeam.id':'home_team_id',
            'awayTeam.abbrev':'away_team_abbr',
            'homeTeam.abbrev':'home_team_abbr',
            'awayTeam.logo':'away_team_logo',
            'homeTeam.logo':'home_team_logo',
            'awayTeam.awaySplitSquad':'away_team_split_squad',
            'homeTeam.homeSplitSquad':'home_team_split_squad',
            'awayTeam.score':'away_score',
            'homeTeam.score':'home_score',
            'periodDescriptor.number':'period',
            'periodDescriptor.maxRegulationPeriods':'period_max_regulation',
            'periodDescriptor.periodType':'period_type',
            'gameOutcome.lastPeriodType':'period_type_last',
            'gameOutcome.otPeriods':'ot_periods',
            'seriesUrl':'series_url',
            'seriesStatus.round':'series_round',
            'seriesStatus.seriesAbbrev':'series_abbr',
            'seriesStatus.seriesTitle':'series_name',
            'seriesStatus.seriesLetter':'series_letter',
            'seriesStatus.neededToWin':'series_games_needed_to_win',
            'seriesStatus.gameNumberOfSeries':'series_game_num',
            'seriesStatus.topSeedTeamAbbrev':'top_seed_team_abbr',
            'seriesStatus.bottomSeedTeamAbbrev':'bottom_seed_team_abbr',
            'seriesStatus.topSeedWins':'top_seed_wins',
            'seriesStatus.bottomSeedWins':'bottom_seed_wins',
            'clock.timeRemaining':'period_time_remaining',
            'clock.secondsRemaining':'period_seconds_remaining',
            'clock.running':'period_clock_running',
            'clock.inIntermission':'game_in_intermission'
        },
        'season_info':{
            'id':'season',
            'formattedSeasonId':'season_name',
            'seasonOrdinal':'season_ordinal',
            'startDate':'start_date',
            'endDate':'end_date',
            'numberOfGames':'games_num',
            'totalRegularSeasonGames':'regular_season_total_games_num',
            'totalPlayoffGames':'playoffs_total_games_num',
            'regularSeasonStartDate':'regular_season_start_date',
            'regularSeasonEndDate':'regular_season_end_date',
            'standingsStart':'standings_start_date',
            'standingsEnd':'standings_end_date',
            'allStarGameInUse':'all_star_game',
            'conferencesInUse':'conferences',
            'divisionsInUse':'divisions',
            'wildcardInUse':'wildcard',
            'entryDraftInUse':'entry_draft',
            'nhlStanleyCupOwner':'nhl_stanley_cup_owner',
            'olympicsParticipation':'olympic_participation',
            'tiesInUse':'ties',
            'pointForOTLossInUse':'ot_loss_point',
            'regulationWinsInUse':'reg_wins',
            'rowInUse':'row',
            'supplementalDraftInUse':'supplemental_draft'
        },
        'standings':{
            "clinchIndicator": "clinch_indicator",
            "conferenceAbbrev": "conference_abbr",
            "conferenceHomeSequence": "conference_home_sequence",
            "conferenceL10Sequence": "conference_l10_sequence",
            "conferenceName": "conference_name",
            "conferenceRoadSequence": "conference_road_sequence",
            "conferenceSequence": "conference_sequence",
            "date": "date",
            "divisionAbbrev": "division_abbr",
            "divisionHomeSequence": "division_home_sequence",
            "divisionL10Sequence": "division_l10_sequence",
            "divisionName": "division_name",
            "divisionRoadSequence": "division_road_sequence",
            "divisionSequence": "division_sequence",
            "gameTypeId": "game_type_id",
            "gamesPlayed": "GP",
            "goalDifferential": "GD",
            "goalDifferentialPctg": "GD%",
            "goalAgainst": "GA",
            "goalFor": "GF",
            "goalsForPctg": "GF%",
            "homeGamesPlayed": "HGP",
            "homeGoalDifferential": "HGD",
            "homeGoalsAgainst": "HGA",
            "homeGoalsFor": "HGF",
            "homeLosses": "HL",
            "homeOtLosses": "HOL",
            "homePoints": "HPTS",
            "homeRegulationPlusOtWins": "HROW",
            "homeRegulationWins": "HRW",
            "homeTies": "HT",
            "homeWins": "HW",
            "l10GamesPlayed": "l10_GP",
            "l10GoalDifferential": "l10_GD",
            "l10GoalsAgainst": "l10_GA",
            "l10GoalsFor": "l10_GF",
            "l10Losses": "l10_L",
            "l10OtLosses": "l10_OTL",
            "l10Points": "l10_PTS",
            "l10RegulationPlusOtWins": "l10_ROW",
            "l10RegulationWins": "l10_RW",
            "l10Ties": "l10_T",
            "l10Wins": "l10_W",
            "leagueHomeSequence": "league_home_sequence",
            "leagueL10Sequence": "league_l10_sequence",
            "leagueRoadSequence": "league_road_sequence",
            "leagueSequence": "league_sequence",
            "losses": "L",
            "otLosses": "OTL",
            "pointPctg": "PTS%",
            "points": "PTS",
            "regulationPlusOtWinPctg": "ROW%",
            "regulationPlusOtWins": "ROW",
            "regulationWinPctg": "RW%",
            "regulationWins": "RW",
            "roadGamesPlayed": "AGP",
            "roadGoalDifferential": "AGD",
            "roadGoalsAgainst": "AGA",
            "roadGoalsFor": "AGF",
            "roadLosses": "AL",
            "roadOtLosses": "AOTL",
            "roadPoints": "APTS",
            "roadRegulationPlusOtWins": "AROW",
            "roadRegulationWins": "ARW",
            "roadTies": "AT",
            "roadWins": "AW",
            "seasonId": "season",
            "shootoutLosses": "SOL",
            "shootoutWins": "SOW",
            "streakCode": "streak_code",
            "streakCount": "streak_count",
            "teamLogo": "team_logo",
            "ties": "T",
            "waiversSequence": "waivers_sequence",
            "wildcardSequence": "wildcard_sequence",
            "winPctg": "W%",
            "wins": "W",
            "placeName.default": "place_name",
            "teamName.default": "team_name",
            "teamCommonName.default": "team_common_name",
            "teamAbbrev.default": "team_abbr",
            "seriesUrl": "series_url",
            "seriesTitle": "series_title",
            "seriesAbbrev": "series_abbrev",
            "seriesLetter": "series_letter",
            "playoffRound": "playoff_round",
            "topSeedRank": "top_seed_rank",
            "topSeedRankAbbrev": "top_seed_rank_abbr",
            "topSeedWins": "top_seed_wins",
            "bottomSeedRank": "bottom_seed_rank",
            "bottomSeedRankAbbrev": "bottom_seed_rank_abbr",
            "bottomSeedWins": "bottom_seed_wins",
            "winningTeamId": "winning_team_id",
            "losingTeamId": "losing_team_id",
            "topSeedTeam.id": "top_seed_team_id",
            "topSeedTeam.abbrev": "top_seed_team_abbr",
            "topSeedTeam.name.default": "top_seed_team_name",
            "topSeedTeam.commonName.default": "top_seed_team_common_name",
            "topSeedTeam.placeNameWithPreposition.default": "top_seed_team_place_name",
            "topSeedTeam.logo": "top_seed_team_logo",
            "topSeedTeam.darkLogo": "top_seed_team_dark_logo",
            "bottomSeedTeam.id": "bottom_seed_team_id",
            "bottomSeedTeam.abbrev": "bottom_seed_team_abbr",
            "bottomSeedTeam.name.default": "bottom_seed_team_name",
            "bottomSeedTeam.commonName.default": "bottom_seed_team_common_name",
            "bottomSeedTeam.placeNameWithPreposition.default": "bottom_seed_team_place_name",
            "bottomSeedTeam.logo": "bottom_seed_team_logo",
            "bottomSeedTeam.darkLogo": "bottom_seed_team_dark_logo",
            "seriesLogo": "series_logo",
        },
        'roster':{
            "id": "player_id",
            "team_abbr": "team_abbr",
            "season": "season",
            "headshot": "headshot",
            "sweaterNumber": "sweater_number",
            "positionCode": "position",
            "heading_position": "heading_position",
            "shootsCatches": "handedness",
            "heightInInches": "height_in",
            "weightInPounds": "weight_lbs",
            "heightInCentimeters": "height_cm",
            "weightInKilograms": "weight_kg",
            "birthDate": "birth_date",
            "birthCountry": "birth_country",
            "player_name":"player_name",
            "firstName.default": "player_first_name",
            "lastName.default": "player_last_name",
            "birthCity.default": "birth_city",
            "birthStateProvince.default": "birth_state_province"
            },
        'prospects':{
            "id": "player_id",
            "headshot": "headshot",
            "sweaterNumber": "sweater_number",
            "positionCode": "position",
            "shootsCatches": "handedness",
            "heightInInches": "height_in",
            "weightInPounds": "weight_lbs",
            "heightInCentimeters": "height_cm",
            "weightInKilograms": "weight_kg",
            "birthDate": "birth_date",
            "birthCountry": "birth_country",
            "player_name":"player_name",
            "firstName.default": "player_first_name",
            "lastName.default": "player_last_name",
            "birthCity.default": "birth_city",
            "birthStateProvince.default": "birth_state_province",
        },
        'player_info':{
            'playerId': 'player_id',
            'player_name': 'player_name',
            'isActive': 'is_active',
            'currentTeamId': 'current_team_id',
            'currentTeamAbbrev': 'current_team_abbr',
            'badges': 'badges',
            'teamLogo': 'team_logo',
            'sweaterNumber': 'sweater_number',
            'position': 'position',
            'headshot': 'headshot',
            'heroImage': 'hero_image',
            'heightInInches': 'height_in',
            'heightInCentimeters': 'height_cm',
            'weightInPounds': 'weight_lbs',
            'weightInKilograms': 'weight_kg',
            'birthDate': 'birth_date',
            'birthCountry': 'birth_country',
            'shootsCatches': 'handedness',
            'playerSlug': 'player_slug',
            'inTop100AllTime': 'in_top_100_all_time',
            'inHHOF': 'in_hhof',
            'shopLink': 'shop_link',
            'twitterLink': 'twitter_link',
            'watchLink': 'watch_link',
            'last5Games': 'last_5_games',
            'seasonTotals': 'season_totals',
            'awards': 'awards',
            'currentTeamRoster': 'current_team_roster',
            'fullTeamName.default': 'full_team_name',
            'teamCommonName.default': 'team_common_name',
            'teamPlaceNameWithPreposition.default': 'team_place_name_with_preposition',
            'firstName.default': 'player_first_name',
            'lastName.default': 'player_last_name',
            'birthCity.default': 'birth_city',
            'birthStateProvince.default': 'birth_state_province',
            'draftDetails.year': 'draft_year',
            'draftDetails.teamAbbrev': 'draft_team_abbr',
            'draftDetails.round': 'draft_round',
            'draftDetails.pickInRound': 'draft_pick_in_round',
            'draftDetails.overallPick': 'draft_overall_pick',
        },
        'team_info':{
            "id":"team_id",
            "franchiseId":"franchise_id",
            "fullName":"team_name",
            "leagueId":"league_id",
            "triCode":"team_abbr",
            "logo_light":"logo_light",
            "logo_dark":"logo_dark",
            "country3Code":"country_abbr",
            "countryCode":"country_abbr_2",
            "countryName":"country_name",
            "hasPlayerStats":"has_player_stats",
            "imageUrl":"country_flag_large",
            "isActive":"is_active",
            "nationalityName":"nationality",
            "olympicUrl":"olympic_url",
            "thumbnailUrl":"thumbnail_url"
        },
        'draft_rankings':{
            "id": "player_id",
            "player_name":"player_name",
            "firstName": "player_first_name",
            "lastName": "player_last_name",
            "headshot": "headshot",
            "sweaterNumber": "sweater_number",
            "positionCode": "position",
            "shootsCatches": "handedness",
            "heightInInches": "height_in",
            "weightInPounds": "weight_lbs",
            "heightInCentimeters": "height_cm",
            "weightInKilograms": "weight_kg",
            "birthDate": "birth_date",
            "birthCity": "birth_city",
            "birthCountry": "birth_country",
            "birthStateProvince": "birth_state_province",
            "lastAmateurClub": "last_amateur_club",
            "lastAmateurLeague": "last_amateur_league",
            "midtermRank":"midterm_rank",
            "finalRank":"final_rank"
        },
        'edge':{
            "player.id": "player_id",
            "player.team_abbrev": "team_abbr",
            "season":"season",
            "player.headshot": "headshot",
            "player.sweaterNumber": "sweater_number",
            "player.positionCode": "position",
            "player.heading_position": "heading_position",
            "player.shootsCatches": "handedness",
            "player.heightInInches": "height_in",
            "player.weightInPounds": "weight_lbs",
            "player.heightInCentimeters": "height_cm",
            "player.weightInKilograms": "weight_kg",
            "player.birthDate": "birth_date",
            "player.birthCountry": "birth_country",
            "player_name":"player_name",
            "player.firstName.default": "player_first_name",
            "player.lastName.default": "player_last_name",
            "player.birthCity.default": "birth_city",
            "player.birthStateProvince.default": "birth_state_province",
            'team.id': 'team_id',
            'team.commonName.default': 'team_common_name',
            'team.placeNameWithPreposition.default': 'team_place_name',
            'team.abbrev': 'team_abbr',
            'team.teamLogo.dark': 'team_logo',
            'team.conference': 'conference_name',
            'team.division': 'division_name',
            'shotLocationSummary': 'shot_location_summary',
            'shotLocationDetails': 'shot_location_details',
            'shotAttemptsOver90.value': 'shot_attempts_over_90',
            'shotAttemptsOver90.rank': 'shot_attempts_over_90_rank',
            'topShotSpeed.imperial': 'top_shot_speed',
            'topShotSpeed.rank': 'top_shot_speed_rank',
            'topShotSpeed.leagueAvg.imperial': 'league_avg_top_shot_speed',
            'burstsOver22.value': 'bursts_over_22',
            'burstsOver22.rank': 'bursts_over_22_rank',
            'burstsOver20.value': 'bursts_over_20',
            'burstsOver20.rank': 'bursts_over_20_rank',
            'burstsOver20.leagueAvg.value': 'league_avg_bursts_over_20',
            'speedMax.imperial': 'max_speed',
            'speedMax.rank': 'max_speed_rank',
            'speedMax.leagueAvg.imperial': 'league_avg_max_speed',
            'total.imperial': 'total_distance_skated',
            'total.rank': 'total_distance_skated_rank',
            'total.leagueAvg.imperial': 'league_avg_total_distance_skated',
            'offensiveZonePctg': 'offensive_zone_percentage',
            'offensiveZoneRank': 'offensive_zone_rank',
            'offensiveZoneLeagueAvg': 'league_avg_offensive_zone',
            'neutralZonePctg': 'neutral_zone_percentage',
            'neutralZoneRank': 'neutral_zone_rank',
            'neutralZoneLeagueAvg': 'league_avg_neutral_zone',
            'defensiveZonePctg': 'defensive_zone_percentage',
            'defensiveZoneRank': 'defensive_zone_rank',
            'defensiveZoneLeagueAvg': 'league_avg_defensive_zone',
            'shotSpeed.shotAttemptsOver90.value': 'shot_attempts_over_90',
            'shotSpeed.shotAttemptsOver90.rank': 'shot_attempts_over_90_rank',
            'shotSpeed.topShotSpeed.imperial': 'top_shot_speed',
            'shotSpeed.topShotSpeed.rank': 'top_shot_speed_rank',
            'shotSpeed.topShotSpeed.leagueAvg.imperial': 'league_avg_top_shot_speed',
            'skatingSpeed.burstsOver22.value': 'bursts_over_22',
            'skatingSpeed.burstsOver22.rank': 'bursts_over_22_rank',
            'skatingSpeed.burstsOver20.value': 'bursts_over_20',
            'skatingSpeed.burstsOver20.rank': 'bursts_over_20_rank',
            'skatingSpeed.burstsOver20.leagueAvg.value': 'league_avg_bursts_over_20',
            'skatingSpeed.speedMax.imperial': 'max_speed',
            'skatingSpeed.speedMax.rank': 'max_speed_rank',
            'skatingSpeed.speedMax.leagueAvg.imperial': 'league_avg_max_speed',
            'distanceSkated.total.imperial': 'total_distance_skated',
            'distanceSkated.total.rank': 'total_distance_skated_rank',
            'distanceSkated.total.leagueAvg.imperial': 'league_avg_total_distance_skated',
            'zoneTimeDetails.offensiveZonePctg': 'offensive_zone_percentage',
            'zoneTimeDetails.offensiveZoneRank': 'offensive_zone_rank',
            'zoneTimeDetails.offensiveZoneLeagueAvg': 'league_avg_offensive_zone',
            'zoneTimeDetails.neutralZonePctg': 'neutral_zone_percentage',
            'zoneTimeDetails.neutralZoneRank': 'neutral_zone_rank',
            'zoneTimeDetails.neutralZoneLeagueAvg': 'league_avg_neutral_zone',
            'zoneTimeDetails.defensiveZonePctg': 'defensive_zone_percentage',
            'zoneTimeDetails.defensiveZoneRank': 'defensive_zone_rank',
            'zoneTimeDetails.defensiveZoneLeagueAvg': 'league_avg_defensive_zone',
        },
        'stats':{
            "Player":"player_name",
            "Goalie":"player_name",
            "Season":"season",
            "Team":"team_abbr",
            "ID":"player_id",
            "Game":"game_id",
            "WSBA":"wsba_id",
            "Headshot":"headshot",
            "Position":"position",
            "Handedness":"handedness",
            "Height (in)":"height_in",
            "Weight (lbs)":"weight_lbs",
            "Birthday":"birthday",
            "Age":"age",
            "Nationality":"nationality",
            "GP":"games_played",
            "TOI":"time_on_ice",
            "GF":"goals_for",
            "SF":"shots_for",
            "FF":"fenwick_for",
            "xGF":"expected_goals_for",
            "xGF/FF":"expected_goals_per_fenwick_for",
            "GF/xGF":"goals_for_per_expected_goals_for",
            "ShF%":"shooting_percentage_for",
            "FshF%":"fenwick_shot_percentage_for",
            "GA":"goals_against",
            "SA":"shots_against",
            "FA":"fenwick_against",
            "xGA":"expected_goals_against",
            "xGA/FA":"expected_goals_per_fenwick_against",
            "GA/xGA":"goals_against_per_expected_goals_against",
            "ShA%":"shooting_percentage_against",
            "FshA%":"fenwick_shot_percentage_against",
            "CF":"corsi_for",
            "CA":"corsi_against",
            "CF%":"corsi_for_percentage",
            "FF%":"fenwick_for_percentage",
            "xGF%":"expected_goals_for_percentage",
            "GF%":"goals_for_percentage",
            "HF":"hits_for",
            "HA":"hits_against",
            "HF%":"hits_for_percentage",
            "Penl":"penalties",
            "Penl2":"minor_penalties",
            "Penl5":"major_penalties",
            "PIM":"penalty_minutes",
            "Draw":"penalties_drawn",
            "PENL%":"penalties_drawn_percentage",
            "Give":"giveaways",
            "Take":"takeaways",
            "PM%":"puck_management_percentage",
            "Block":"blocked_shots",
            "RushF":"rush_attempts_for",
            "RushA":"rush_attempts_against",
            "RushFxG":"rush_expected_goals_for",
            "RushAxG":"rush_expected_goals_against",
            "RushFG":"rush_goals_for",
            "RushAG":"rush_goals_against",
            "Rush":"rush_attempts",
            "Rush xG":"rush_expected_goals",
            "Rush G":"rush_goals",
            "GSAx":"goals_saved_above_expected",
            "Gi":"goals",
            "A1":"primary_assists",
            "A2":"secondary_assists",
            "P1":"primary_points",
            "P":"points",
            "Si":"shots",
            "Shi%":"shooting_percentage",
            "Fi":"fenwick",
            "xGi":"expected_goals",
            "xGi/Fi":"expected_goals_per_fenwick",
            "Gi/xGi":"goals_per_expected_goals",
            "Fshi%":"fenwick_shot_percentage",
            "OZF":"offensive_zone_faceoffs",
            "NZF":"neutral_zone_faceoffs",
            "DZF":"defensive_zone_faceoffs",
            "OZF%":"offensive_zone_faceoffs_percentage",
            "NZF%":"neutral_zone_faceoffs_percentage",
            "DZF%":"defensive_zone_faceoffs_percentage",
            "GC%":"goals_contribution_percentage",
            "AC%":"assists_contribution_percentage",
            "GI%":"individual_goals_percentage",
            "FC%":"fenwick_contribution_percentage",
            "xGC%":"expected_goals_contribution_percentage",
            "F":"faceoffs_taken",
            "FW":"faceoff_wins",
            "FL":"faceoff_losses",
            "F%":"faceoff_percentage",
            "OOFF-SR":"on_ice_offense_shot_rate_percentile",
            "OOFF-SQ":"on_ice_offense_shot_quality_percentile",
            "OOFF-FN":"on_ice_offense_finishing_percentile",
            "OOFF-SRI":"on_ice_offense_shot_rate_impact",
            "OOFF-SQI":"on_ice_offense_shot_quality_impact",
            "OOFF-FNI":"on_ice_offense_finishing_impact",
            "OOFF-SRI-T":"on_ice_offense_shot_rate_impact_total",
            "OOFF-SQI-T":"on_ice_offense_shot_quality_impact_total",
            "OOFF-FNI-T":"on_ice_offense_finishing_impact_total",
            "ODEF-SR":"on_ice_defense_shot_rate_percentile",
            "ODEF-SQ":"on_ice_defense_shot_quality_percentile",
            "ODEF-FN":"on_ice_defense_finishing_percentile",
            "ODEF-SRI":"on_ice_defense_shot_rate_impact",
            "ODEF-SQI":"on_ice_defense_shot_quality_impact",
            "ODEF-FNI":"on_ice_defense_finishing_impact",
            "ODEF-SRI-T":"on_ice_defense_shot_rate_impact_total",
            "ODEF-SQI-T":"on_ice_defense_shot_quality_impact_total",
            "ODEF-FNI-T":"on_ice_defense_finishing_impact_total",
            "EGF":"extraneous_goals_for",
            "ExGF":"extraneous_expected_goals_for",
            "EGA":"extraneous_goals_against",
            "ExGA":"extraneous_expected_goals_against",
            "EGF-P":"extraneous_goals_for_percentile",
            "ExGF-P":"extraneous_expected_goals_for_percentile",
            "EGA-P":"extraneous_goals_against_percentile",
            "ExGA-P":"extraneous_expected_goals_against_percentile",
            "EGF-T":"extraneous_goals_for_total",
            "ExGF-T":"extraneous_expected_goals_for_total",
            "EGA-T":"extraneous_goals_against_total",
            "ExGA-T":"extraneous_expected_goals_against_total",
            "Team-Adjusted-EGI":"team_adjusted_extraneous_expected_goals_impact",
            "GISAx":"goals_saved_above_expected",
            "NetGI":"net_goal_impact",
            "NetxGI":"net_expected_goals_impact",
            "Team-Adjusted-EGI-P":"team_adjusted_extraneous_expected_goals_impact_percentile",
            "GISAx-P":"goals_saved_above_expected_percentile",
            "NetGI-P":"net_goal_impact_percentile",
            "NetxGI-P":"net_expected_goals_impact_percentile",
            "Team-Adjusted-EGI-T":"team_adjusted_extraneous_expected_goals_impact_total",
            "GISAx-T":"goals_saved_above_expected_total",
            "NetGI-T":"net_goal_impact_total",
            "NetxGI-T":"net_expected_goals_impact_total",
            "RushF/60":"rush_attempts_for_per_sixty",
            "RushA/60":"rush_attempts_against_per_sixty",
            "RushesFF":"rush_attempts_for_percentile",
            "RushesFA":"rush_attempts_against_percentile",
            "RushFxG/60":"rush_expected_goals_for_per_sixty",
            "RushAxG/60":"rush_expected_goals_against_per_sixty",
            "RushesxGF":"rush_expected_goals_for_percentile",
            "RushesxGA":"rush_expected_goals_against_percentile",
            "RushFG/60":"rush_goals_for_per_sixty",
            "RushAG/60":"rush_goals_against_per_sixty",
            "RushesGF":"rush_goals_for_percentile",
            "RushesGA":"rush_goals_against_percentile",
            "EGi":"extraneous_individual_expected_goals",
            "ExGi":"extraneous_individual_expected_goals_excluding_finishing",
            "EGi-P":"extraneous_individual_expected_goals_percentile",
            "ExGi-P":"extraneous_individual_expected_goals_excluding_finishing_percentile",
            "EGi-T":"extraneous_individual_expected_goals_total",
            "ExGi-T":"extraneous_individual_expected_goals_excluding_finishing_total",
            "LiEG":"line_extraneous_expected_goals",
            "LiExG":"line_extraneous_expected_goals_excluding_finishing",
            "LiGIn":"line_individual_goal_involvement",
            "LixGIn":"line_individual_expected_goals_involvement",
            "ALiGIn":"adjusted_line_individual_goal_involvement",
            "CompGI":"composite_goal_impact",
            "LiRelGI":"line_relative_goal_impact",
            "LiEG-P":"line_extraneous_expected_goals_percentile",
            "LiExG-P":"line_extraneous_expected_goals_excluding_finishing_percentile",
            "LiGIn-P":"line_individual_goal_involvement_percentile",
            "LixGIn-P":"line_individual_expected_goals_involvement_percentile",
            "ALiGIn-P":"adjusted_line_individual_goal_involvement_percentile",
            "CompGI-P":"composite_goal_impact_percentile",
            "LiRelGI-P":"line_relative_goal_impact_percentile",
            "LiEG-T":"line_extraneous_expected_goals_total",
            "LiExG-T":"line_extraneous_expected_goals_excluding_finishing_total",
            "LiGIn-T":"line_individual_goal_involvement_total",
            "LixGIn-T":"line_individual_expected_goals_involvement_total",
            "ALiGIn-T":"adjusted_line_individual_goal_involvement_total",
            "CompGI-T":"composite_goal_impact_total",
            "LiRelGI-T":"line_relative_goal_impact_total",
            "NetGI-T":"net_goal_impact_total",
            "NetxGI-T":"net_expected_goals_impact_total",
            "Fi/60":"fenwick_per_sixty",
            "xGi/60":"expected_goals_per_sixty",
            "Gi/60":"goals_per_sixty",
            "A1/60":"primary_assists_per_sixty",
            "A2/60":"secondary_assists_per_sixty",
            "P1/60":"primary_points_per_sixty",
            "P/60":"points_per_sixty",
            "Si/60":"shots_per_sixty",
            "OZF/60":"offensive_zone_faceoffs_per_sixty",
            "NZF/60":"neutral_zone_faceoffs_per_sixty",
            "DZF/60":"defensive_zone_faceoffs_per_sixty",
            "FF/60":"fenwick_for_per_sixty",
            "FA/60":"fenwick_against_per_sixty",
            "xGF/60":"expected_goals_for_per_sixty",
            "xGA/60":"expected_goals_against_per_sixty",
            "GF/60":"goals_for_per_sixty",
            "GA/60":"goals_against_per_sixty",
            "SF/60":"shots_for_per_sixty",
            "SA/60":"shots_against_per_sixty",
            "CF/60":"corsi_for_per_sixty",
            "CA/60":"corsi_against_per_sixty",
            "HF/60":"hits_for_per_sixty",
            "HA/60":"hits_against_per_sixty",
            "Give/60":"giveaways_per_sixty",
            "Take/60":"takeaways_per_sixty",
            "Penl/60":"penalties_per_sixty",
            "Penl2/60":"minor_penalties_per_sixty",
            "Penl5/60":"major_penalties_per_sixty",
            "Draw/60":"penalties_drawn_per_sixty",
            "PIM/60":"penalty_minutes_per_sixty",
            "Block/60":"blocked_shots_per_sixty",
            "GSAx/60":"goals_saved_above_expected_per_sixty",
            "WristFi":"wrist_fenwick",
            "WristxGi":"wrist_expected_goals",
            "WristGi":"wrist_goals",
            "DeflectedFi":"deflected_fenwick",
            "DeflectedxGi":"deflected_expected_goals",
            "DeflectedGi":"deflected_goals",
            "Tip-inFi":"tip_in_fenwick",
            "Tip-inxGi":"tip_in_expected_goals",
            "Tip-inGi":"tip_in_goals",
            "SlapFi":"slap_fenwick",
            "SlapxGi":"slap_expected_goals",
            "SlapGi":"slap_goals",
            "BackhandFi":"backhand_fenwick",
            "BackhandxGi":"backhand_expected_goals",
            "BackhandGi":"backhand_goals",
            "SnapFi":"snap_fenwick",
            "SnapxGi":"snap_expected_goals",
            "SnapGi":"snap_goals",
            "Wrap-aroundFi":"wrap_around_fenwick",
            "Wrap-aroundxGi":"wrap_around_expected_goals",
            "Wrap-aroundGi":"wrap_around_goals",
            "PokeFi":"poke_fenwick",
            "PokexGi":"poke_expected_goals",
            "PokeGi":"poke_goals",
            "BatFi":"bat_fenwick",
            "BatxGi":"bat_expected_goals",
            "BatGi":"bat_goals",
            "CradleFi":"cradle_fenwick",
            "CradlexGi":"cradle_expected_goals",
            "CradleGi":"cradle_goals",
            "Between-legsFi":"between_legs_fenwick",
            "Between-legsxGi":"between_legs_expected_goals",
            "Between-legsGi":"between_legs_goals",
            "GS":"game_score",
            "T-GD":"team_goal_differential",
            "EV_xGC%":"even_strength_expected_goals_contribution_percentage",
            "EV_xGF":"even_strength_expected_goals_for",
            "EV_xGA":"even_strength_expected_goals_against",
            "PP_xGC%":"power_play_expected_goals_contribution_percentage",
            "PP_xGF":"power_play_expected_goals_for",
            "PP_xGA":"power_play_expected_goals_against",
            "SH_xGC%":"short_handed_expected_goals_contribution_percentage",
            "SH_xGF":"short_handed_expected_goals_for",
            "SH_xGA":"short_handed_expected_goals_against",
            "P Score": "points_score",
            "PENL% Score": "penalties_drawn_percentage_score",
            "PM% Score": "puck_management_percentage_score",
            "F% Score": "faceoff_percentage_score",
            "EV_xGC% Score": "even_strength_expected_goals_contribution_percentage_score",
            "EV_xGF Score": "even_strength_expected_goals_for_score",
            "EV_xGA Score": "even_strength_expected_goals_against_score",
            "PP_xGC% Score": "power_play_expected_goals_contribution_percentage_score",
            "PP_xGF Score": "power_play_expected_goals_for_score",
            "PP_xGA Score": "power_play_expected_goals_against_score",
            "SH_xGC% Score": "short_handed_expected_goals_contribution_percentage_score",
            "SH_xGF Score": "short_handed_expected_goals_for_score",
            "SH_xGA Score": "short_handed_expected_goals_against_score",
            "xGF% Score": "expected_goals_for_percentage_score",
            "GA/xGA Score": "goals_against_per_expected_goals_against_score",
            "EV Score": "even_strength_score",
            "PP Score": "power_play_score",
            "SH Score": "short_handed_score",
            "Production Score": "production_score",
            "Play-Driving Score": "play_driving_score",
            "Offensive Score": "offensive_score",
            "Defensive Score": "defensive_score",
            "Workload Score": "workload_score",
            "Goaltending Score": "goaltending_score",
            "Misc Score": "misc_score",
            "Penalties Score": "penalties_score",
            "Puck Management Score": "puck_management_score",
            "Faceoffs Score": "faceoffs_score"
        }
    }