class ErrorCode:
    ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND"
    NO_PROVIDERS = "NO_PROVIDERS"
    ALL_PROVIDERS_FAILED = "ALL_PROVIDERS_FAILED"
    PROVIDER_MISCONFIGURED = "PROVIDER_MISCONFIGURED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    INVALID_MESSAGE = "INVALID_MESSAGE"
