"""
ActionEngine interfaces for AsyncNode and NodeMap.
"""
from __future__ import annotations
import actionengine._C.chunk_store
import actionengine._C.data
import collections.abc
import typing
__all__: list[str] = ['AsyncNode', 'NodeMap']
class AsyncNode:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: AsyncNode) -> None:
        ...
    @typing.overload
    def __init__(self, id: str = '', node_map: NodeMap = None, chunk_store: actionengine._C.chunk_store.ChunkStore = None) -> None:
        ...
    @typing.overload
    def __init__(self, id: str = '', node_map: NodeMap = None, chunk_store_factory: collections.abc.Callable[[str], actionengine._C.chunk_store.ChunkStoreVirtualBase] = None) -> None:
        ...
    def bind_stream(self, stream: ...) -> None:
        ...
    def get_id(self) -> str:
        ...
    def make_reader(self, options: actionengine._C.chunk_store.ChunkStoreReaderOptions = ...) -> ...:
        ...
    def next_chunk(self, timeout: typing.SupportsFloat = -1.0) -> actionengine._C.data.Chunk | None:
        ...
    def next_fragment(self, timeout: typing.SupportsFloat = -1.0) -> actionengine._C.data.NodeFragment | None:
        ...
    def put_chunk(self, chunk: actionengine._C.data.Chunk = ..., seq: typing.SupportsInt = -1, final: bool = False) -> None:
        ...
    def put_fragment(self, fragment: actionengine._C.data.NodeFragment = ..., seq: typing.SupportsInt = -1) -> None:
        ...
    @typing.overload
    def set_reader_options(self, ordered: bool = False, remove_chunks: bool = False, n_chunks_to_buffer: typing.SupportsInt = -1, timeout: typing.SupportsFloat = -1.0, start_seq_or_offset: typing.SupportsInt = 0) -> AsyncNode:
        ...
    @typing.overload
    def set_reader_options(self, options: actionengine._C.chunk_store.ChunkStoreReaderOptions = ...) -> AsyncNode:
        ...
class NodeMap:
    @typing.overload
    def __init__(self, arg0: NodeMap) -> None:
        ...
    @typing.overload
    def __init__(self, chunk_store_factory: collections.abc.Callable[[str], actionengine._C.chunk_store.ChunkStoreVirtualBase] = None) -> None:
        ...
    def contains(self, arg0: str) -> bool:
        ...
    def extract(self, arg0: str) -> ... | None:
        ...
    def get(self, arg0: str) -> ...:
        ...
