"""
@Author = 'Mike Stanley'

============ Change Log ============
2025-Dec-18 = Created.

============ License ============
The MIT License (MIT)

Copyright (c) 2025 Michael Stanley

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
from wmul_rivendell_tcp_client.song import Song


def test_no_padUpdates():
    test_string = "test_string"
    result = Song._remove_extra_updates(rivendell_json=test_string)
    assert result == test_string


def test_one_padUpdate():
    test_string =   '{\n    "padUpdate": {\n        "dateTime": "2025-12-18T11:08:46-05:00",\n        "hostName": "ipsum_dolor",\n        "log": {\n            "name": "sit-amet"\n        },\n        "machine": 1,\n        "mode": "Automatic",\n        "next": {\n            "agency": "",\n            "album": "",\n            "artist": "consectetur adipiscing",\n            "cartNumber": 119268,\n            "cartType": "Audio",\n            "client": "Pretium tellus",\n            "composer": "",\n            "conductor": "",\n            "cutNumber": 1,\n            "description": "duis convallis tempus leo eu aenean",\n            "eventType": "Audio",\n            "externalAnncType": "",\n            "externalData": "",\n            "externalEventId": "",\n            "groupName": "Iaculis",\n            "isci": "",\n            "isrc": "",\n            "label": "",\n            "length": 238213,\n            "lineId": 307,\n            "lineNumber": 306,\n            "outcue": "",\n            "publisher": "",\n            "recordingMbId": "",\n            "releaseMbId": "",\n            "songId": "",\n            "startDateTime": "2025-12-18T11:11:44-05:00",\n            "title": "massa nisl malesuada lacinia",\n            "userDefined": "2024",\n            "year": null\n        },\n        "now": {\n            "agency": "",\n            "album": "",\n            "artist": "integer nunc posuere",\n            "cartNumber": 103869,\n            "cartType": "Audio",\n            "client": "",\n            "composer": "Conubia nostra inceptos",\n            "conductor": "",\n            "cutNumber": 1,\n            "description": "himenaeos orci varius natoque",\n            "eventType": "Audio",\n            "externalAnncType": "",\n            "externalData": "",\n            "externalEventId": "",\n            "groupName": "penatibus",\n            "isci": "",\n            "isrc": "",\n            "label": "",\n            "length": 178000,\n            "lineId": 306,\n            "lineNumber": 305,\n            "outcue": "",\n            "publisher": "",\n            "recordingMbId": "",\n            "releaseMbId": "",\n            "songId": "",\n            "startDateTime": "2025-12-18T11:08:46-05:00",\n            "title": "Nulla molestie mattis scelerisque",\n            "userDefined": "",\n            "year": 2020\n        },\n        "onairFlag": false,\n        "service": {\n            "description": "maximus ",\n            "programCode": ""\n        },\n        "shortHostName": "eget fermentum odio"\n    }\n}'
    result = Song._remove_extra_updates(rivendell_json=test_string)
    assert result == test_string

def test_two_padUpdates():
    first_string =  '{\n    "padUpdate": {\n        "dateTime": "2025-12-18T11:15:39-05:00",\n        "hostName": "ipsum_dolor",\n        "log": {\n            "name": "sit-amet"\n        },\n        "machine": 1,\n        "mode": "Automatic",\n        "next": {\n            "agency": "",\n            "album": "",\n            "artist": "consectetur adipiscing",\n            "cartNumber": 118598,\n            "cartType": "Audio",\n            "client": "Pretium tellus",\n            "composer": "",\n            "conductor": "",\n            "cutNumber": 1,\n            "description": "duis convallis tempus leo eu aenean",\n            "eventType": "Audio",\n            "externalAnncType": "",\n            "externalData": "",\n            "externalEventId": "",\n            "groupName": "Iaculis",\n            "isci": "",\n            "isrc": "",\n            "label": "",\n            "length": 213454,\n            "lineId": 309,\n            "lineNumber": 308,\n            "outcue": "",\n            "publisher": "",\n            "recordingMbId": "",\n            "releaseMbId": "",\n            "songId": "",\n            "startDateTime": null,\n            "title": "massa nisl malesuada lacinia",\n            "userDefined": "2023",\n            "year": null\n        },\n        "now": null,\n        "onairFlag": false,\n        "service": {\n            "description": "maximus",\n            "programCode": ""\n        },\n        "shortHostName": "eget fermentum odio"\n    }\n}'
    second_string = '{\n    "padUpdate": {\n        "dateTime": "2025-12-18T11:15:39-05:00",\n        "hostName": "ipsum_dolor",\n        "log": {\n            "name": "sit-amet"\n        },\n        "machine": 1,\n        "mode": "Automatic",\n        "next": {\n            "agency": "",\n            "album": "",\n            "artist": "Blandit quis",\n            "cartNumber": 119587,\n            "cartType": "Audio",\n            "client": "suspendisse aliquet",\n            "composer": "",\n            "conductor": "",\n            "cutNumber": 1,\n            "description": "nisi sodales consequat magna",\n            "eventType": "Audio",\n            "externalAnncType": "",\n            "externalData": "",\n            "externalEventId": "",\n            "groupName": "Iaculis",\n            "isci": "",\n            "isrc": "",\n            "label": "",\n            "length": 211332,\n            "lineId": 310,\n            "lineNumber": 309,\n            "outcue": "",\n            "publisher": "",\n            "recordingMbId": "",\n            "releaseMbId": "",\n            "songId": "",\n            "startDateTime": "2025-12-18T11:19:12-05:00",\n            "title": "Ligula congue sollicitudin",\n            "userDefined": "",\n            "year": null\n        },\n        "now": {\n            "agency": "",\n            "album": "",\n            "artist": "erat viverra ac tincidunt",\n            "cartNumber": 118598,\n            "cartType": "Audio",\n            "client": "Velit aliquam",\n            "composer": "",\n            "conductor": "",\n            "cutNumber": 1,\n            "description": "imperdiet mollis nullam",\n            "eventType": "Audio",\n            "externalAnncType": "",\n            "externalData": "",\n            "externalEventId": "",\n            "groupName": "volutpat",\n            "isci": "",\n            "isrc": "",\n            "label": "",\n            "length": 213454,\n            "lineId": 309,\n            "lineNumber": 308,\n            "outcue": "",\n            "publisher": "",\n            "recordingMbId": "",\n            "releaseMbId": "",\n            "songId": "",\n            "startDateTime": "2025-12-18T11:15:39-05:00",\n            "title": "porttitor ullamcorper",\n            "userDefined": "2023",\n            "year": null\n        },\n        "onairFlag": false,\n        "service": {\n            "description": "Dui felis venenatis",\n            "programCode": ""\n        },\n        "shortHostName": "ultrices proin libero"\n    }\n}'
    test_string = first_string + second_string
    
    result = Song._remove_extra_updates(rivendell_json=test_string)

    assert result == second_string


def test_three_padUpdates():
    first_string =  '{\n    "padUpdate": {\n        "dateTime": "2025-12-18T11:15:39-05:00",\n        "hostName": "ipsum_dolor",\n        "log": {\n            "name": "sit-amet"\n        },\n        "machine": 1,\n        "mode": "Automatic",\n        "next": {\n            "agency": "",\n            "album": "",\n            "artist": "consectetur adipiscing",\n            "cartNumber": 118598,\n            "cartType": "Audio",\n            "client": "Pretium tellus",\n            "composer": "",\n            "conductor": "",\n            "cutNumber": 1,\n            "description": "duis convallis tempus leo eu aenean",\n            "eventType": "Audio",\n            "externalAnncType": "",\n            "externalData": "",\n            "externalEventId": "",\n            "groupName": "Iaculis",\n            "isci": "",\n            "isrc": "",\n            "label": "",\n            "length": 213454,\n            "lineId": 309,\n            "lineNumber": 308,\n            "outcue": "",\n            "publisher": "",\n            "recordingMbId": "",\n            "releaseMbId": "",\n            "songId": "",\n            "startDateTime": null,\n            "title": "massa nisl malesuada lacinia",\n            "userDefined": "2023",\n            "year": null\n        },\n        "now": null,\n        "onairFlag": false,\n        "service": {\n            "description": "maximus",\n            "programCode": ""\n        },\n        "shortHostName": "eget fermentum odio"\n    }\n}'
    second_string = '{\n    "padUpdate": {\n        "dateTime": "2025-12-18T11:15:39-05:00",\n        "hostName": "ipsum_dolor",\n        "log": {\n            "name": "sit-amet"\n        },\n        "machine": 1,\n        "mode": "Automatic",\n        "next": {\n            "agency": "",\n            "album": "",\n            "artist": "Blandit quis",\n            "cartNumber": 119587,\n            "cartType": "Audio",\n            "client": "suspendisse aliquet",\n            "composer": "",\n            "conductor": "",\n            "cutNumber": 1,\n            "description": "nisi sodales consequat magna",\n            "eventType": "Audio",\n            "externalAnncType": "",\n            "externalData": "",\n            "externalEventId": "",\n            "groupName": "Iaculis",\n            "isci": "",\n            "isrc": "",\n            "label": "",\n            "length": 211332,\n            "lineId": 310,\n            "lineNumber": 309,\n            "outcue": "",\n            "publisher": "",\n            "recordingMbId": "",\n            "releaseMbId": "",\n            "songId": "",\n            "startDateTime": "2025-12-18T11:19:12-05:00",\n            "title": "Ligula congue sollicitudin",\n            "userDefined": "",\n            "year": null\n        },\n        "now": {\n            "agency": "",\n            "album": "",\n            "artist": "erat viverra ac tincidunt",\n            "cartNumber": 118598,\n            "cartType": "Audio",\n            "client": "Velit aliquam",\n            "composer": "",\n            "conductor": "",\n            "cutNumber": 1,\n            "description": "imperdiet mollis nullam",\n            "eventType": "Audio",\n            "externalAnncType": "",\n            "externalData": "",\n            "externalEventId": "",\n            "groupName": "volutpat",\n            "isci": "",\n            "isrc": "",\n            "label": "",\n            "length": 213454,\n            "lineId": 309,\n            "lineNumber": 308,\n            "outcue": "",\n            "publisher": "",\n            "recordingMbId": "",\n            "releaseMbId": "",\n            "songId": "",\n            "startDateTime": "2025-12-18T11:15:39-05:00",\n            "title": "porttitor ullamcorper",\n            "userDefined": "2023",\n            "year": null\n        },\n        "onairFlag": false,\n        "service": {\n            "description": "Dui felis venenatis",\n            "programCode": ""\n        },\n        "shortHostName": "ultrices proin libero"\n    }\n}'
    third_string =  '{\n    "padUpdate": {\n        "dateTime": "2025-12-18T11:19:12-05:00",\n        "hostName": "ipsum_dolor",\n        "log": {\n            "name": "sit-amet"\n        },\n        "machine": 1,\n        "mode": "Automatic",\n        "next": {\n            "agency": "",\n            "album": "",\n            "artist": "feugiat tristique",\n            "cartNumber": 3799,\n            "cartType": "Audio",\n            "client": "Cubilia curae hac",\n            "composer": "",\n            "conductor": "",\n            "cutNumber": 7,\n            "description": "habitasse platea dictumst",\n            "eventType": "Audio",\n            "externalAnncType": "",\n            "externalData": "",\n            "externalEventId": "",\n            "groupName": "lorem",\n            "isci": "",\n            "isrc": "",\n            "label": "",\n            "length": 33500,\n            "lineId": 312,\n            "lineNumber": 310,\n            "outcue": "",\n            "publisher": "",\n            "recordingMbId": "",\n            "releaseMbId": "",\n            "songId": "",\n            "startDateTime": "2025-12-18T11:22:43-05:00",\n            "title": "Sem placerat in id",\n            "userDefined": "2024",\n            "year": null\n        },\n        "now": {\n            "agency": "",\n            "album": "",\n            "artist": "cursus mi pretium",\n            "cartNumber": 119587,\n            "cartType": "Audio",\n            "client": "Fringilla lacus",\n            "composer": "",\n            "conductor": "",\n            "cutNumber": 1,\n            "description": "nec metus bibendum",\n            "eventType": "Audio",\n            "externalAnncType": "",\n            "externalData": "",\n            "externalEventId": "",\n            "groupName": "egestas",\n            "isci": "",\n            "isrc": "",\n            "label": "",\n            "length": 211332,\n            "lineId": 310,\n            "lineNumber": 309,\n            "outcue": "",\n            "publisher": "",\n            "recordingMbId": "",\n            "releaseMbId": "",\n            "songId": "",\n            "startDateTime": "2025-12-18T11:19:12-05:00",\n            "title": "iaculis massa",\n            "userDefined": "",\n            "year": null\n        },\n        "onairFlag": false,\n        "service": {\n            "description": "Taciti sociosqu",\n            "programCode": ""\n        },\n        "shortHostName": "ad litora torquent"\n    }\n}'
    test_string = first_string + second_string + third_string
    
    result = Song._remove_extra_updates(rivendell_json=test_string)

    assert result == third_string
