from __future__ import annotations

from typing import Literal

def parse(html: str, /) -> DOM: ...

class DOM:
    def get_element_by_id(self, id_: str, /) -> Element | None: ...
    def get_elements_by_class_name(self, class_name: str, /) -> list[Element]: ...
    def children(self) -> list[Element]: ...
    def query_selector(self, selector: str, /) -> list[Element]: ...
    def outer_html(self) -> str: ...
    def version(self) -> str | None: ...
    def __repr__(self) -> str: ...

class Element:
    def inner_text(self) -> str: ...
    def inner_html(self) -> str: ...
    def outer_html(self) -> str: ...
    def name(self) -> str | None: ...
    def get_attribute(self, name: str, /) -> str | None: ...
    def attributes(self) -> dict[str, str | None]: ...
    def id(self) -> str | None: ...
    def class_name(self) -> str | None: ...
    def class_list(self) -> list[str]: ...
    def has_class(self, name: str, /) -> bool: ...
    def children(self) -> list[Element]: ...
    def node_type(self) -> Literal["element", "text", "comment"]: ...
    def query_selector(self, selector: str, /) -> list[Element]: ...
    def __repr__(self) -> str: ...
