import argparse
from ...commands import Command
from ...utils.logging import log_error as log_error
from ..buildcommands.build_utils import is_rust_enabled as is_rust_enabled

class PublishCommand(Command):
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def help(self) -> str: ...
    def add_arguments(self, parser: argparse.ArgumentParser) -> None: ...
    def execute(self, *args, **kwargs) -> None: ...
