from scapy.contrib.automotive.doip import *
from scapy.contrib.automotive.uds import *
import threading
from _typeshed import Incomplete

def ishex(s): ...

class DoipServer(threading.Thread):
    live: int
    daemon: bool
    src: Incomplete
    tester: Incomplete
    ip: Incomplete
    port: Incomplete
    def __init__(self, src, tester: int = ..., ip: str = ..., port: int = ...) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def running(self) -> bool: ...
    def service_default_handle(self, req_bytes: bytearray) -> bytearray: ...
    def run(self) -> None: ...
