from scapy.contrib.automotive.doip import *
from _typeshed import Incomplete

logger: Incomplete

class DoipClient:
    ip: Incomplete
    port: Incomplete
    src: Incomplete
    tgt: Incomplete
    func: Incomplete
    tcp: Incomplete
    cmd: Incomplete
    functional: bool
    def __init__(self, src, tgt, func, ip, port: int = ...) -> None: ...
    def __del__(self): ...
    def close(self): ...
    def warp_cmd(self, cmd: str, functional: bool = ...): ...
    def send_request(self, cmd: Packet, functional: bool = ..., timeout: int = ...): ...
    def poll_response(self, timeout: int = ...) -> bytes: ...
    def send_vehicle_identification_request(self) -> Packet: ...
