from pyvqnet import tensor as tensor

def is_model_parallel_parameter(p) -> bool: ...
def align_dense_tensors(tensor_list, alignment): ...
def all_gather_into_tensor_dp_groups(groups_flat, partitioned_param_groups, dp_process_group): ...
def all_gather_dp_groups(groups_flat, partitioned_param_groups, dp_process_group, start_alignment_factor, allgather_bucket_size): ...
