from abc import ABC, abstractmethod
from typing import Any, TYPE_CHECKING, Protocol


if TYPE_CHECKING:
    from ..core import Terminal, NonTerminal, Sequence, Choice, Symbol, Epsilon
    from ..grammar import Grammar


class Compiler[T](Protocol):
    """
    Protocol for all compilers (GBNF, JsonSchema, Lark).
    """

    def visit_terminal(self, node: "Terminal") -> T: ...
    def visit_sequence(self, node: "Sequence") -> T: ...
    def visit_choice(self, node: "Choice") -> T: ...
    def visit_non_terminal(self, node: "NonTerminal") -> T: ...
    def visit_epsilon(self, node: "Epsilon") -> T: ...
    def visit_rule(self, head: "NonTerminal", body: "Symbol") -> T: ...
    def compile(self, grammar: "Grammar") -> T: ...
