class VersionComparator:
    @staticmethod
    def is_version_increment_valid(old_version: str | None, new_version: str | None) -> bool: ...
    @staticmethod
    def get_greater_version(version1: str | None, version2: str | None) -> str | None: ...
    @staticmethod
    def increment_version_from_base(base_version: str) -> str: ...
