from ...utils.version import VersionService as VersionService
from _typeshed import Incomplete

class VersionManager:
    version_service: Incomplete
    def __init__(self) -> None: ...
    def get_current_version(self) -> str: ...
    def check_version_with_pypi(self, repository: str, current_version: str) -> None: ...
    def increment_version(self, dry_run: bool = False) -> None: ...
