# coding: utf-8

"""
    Gomtm API

    The Gomtm API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class SbSystemInfo(BaseModel):
    """
    System information relevant to Tor operation
    """ # noqa: E501
    os: StrictStr = Field(description="Operating system name")
    architecture: StrictStr = Field(description="System architecture (amd64, arm64, etc.)")
    has_root_privileges: StrictBool = Field(description="Whether the process has root/admin privileges", alias="hasRootPrivileges")
    kernel_version: Optional[StrictStr] = Field(default=None, description="Kernel version", alias="kernelVersion")
    available_memory: Optional[StrictInt] = Field(default=None, description="Available system memory in bytes", alias="availableMemory")
    total_memory: Optional[StrictInt] = Field(default=None, description="Total system memory in bytes", alias="totalMemory")
    load_average: Optional[List[Union[StrictFloat, StrictInt]]] = Field(default=None, description="System load average (1, 5, 15 minutes)", alias="loadAverage")
    is_codespaces: Optional[StrictBool] = Field(default=None, description="Whether running in GitHub Codespaces", alias="isCodespaces")
    is_container: Optional[StrictBool] = Field(default=None, description="Whether running in a container", alias="isContainer")
    __properties: ClassVar[List[str]] = ["os", "architecture", "hasRootPrivileges", "kernelVersion", "availableMemory", "totalMemory", "loadAverage", "isCodespaces", "isContainer"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SbSystemInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SbSystemInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in SbSystemInfo) in the input: " + _key)

        _obj = cls.model_validate({
            "os": obj.get("os"),
            "architecture": obj.get("architecture"),
            "hasRootPrivileges": obj.get("hasRootPrivileges"),
            "kernelVersion": obj.get("kernelVersion"),
            "availableMemory": obj.get("availableMemory"),
            "totalMemory": obj.get("totalMemory"),
            "loadAverage": obj.get("loadAverage"),
            "isCodespaces": obj.get("isCodespaces"),
            "isContainer": obj.get("isContainer")
        })
        return _obj


