/* Generated by Cython 3.2.2 */

#ifndef __PYX_HAVE_API__dpctl___sycl_context
#define __PYX_HAVE_API__dpctl___sycl_context
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"
#include "_sycl_context.h"

static PyTypeObject *__pyx_ptype_5dpctl_13_sycl_context__SyclContext = 0;
#define Py_SyclContextType (*__pyx_ptype_5dpctl_13_sycl_context__SyclContext)
static PyTypeObject *__pyx_ptype_5dpctl_13_sycl_context_SyclContext = 0;
#define PySyclContextType (*__pyx_ptype_5dpctl_13_sycl_context_SyclContext)

static DPCTLSyclContextRef (*__pyx_api_f_5dpctl_13_sycl_context_SyclContext_GetContextRef)(struct PySyclContextObject *) = 0;
#define SyclContext_GetContextRef __pyx_api_f_5dpctl_13_sycl_context_SyclContext_GetContextRef
static struct PySyclContextObject *(*__pyx_api_f_5dpctl_13_sycl_context_SyclContext_Make)(DPCTLSyclContextRef) = 0;
#define SyclContext_Make __pyx_api_f_5dpctl_13_sycl_context_SyclContext_Make
static int __Pyx_ImportFunction_3_2_2(PyObject *module, const char *funcname, void (**f)(void), const char *sig);

#ifndef __PYX_HAVE_RT_ImportFromPxd_3_2_2
#define __PYX_HAVE_RT_ImportFromPxd_3_2_2
static int __Pyx_ImportFromPxd_3_2_2(PyObject *module, const char *name, void **p, const char *sig, const char *what) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    d = PyObject_GetAttrString(module, "__pyx_capi__");
    if (!d)
        goto bad;
#if (defined(Py_LIMITED_API) && Py_LIMITED_API >= 0x030d0000) || (!defined(Py_LIMITED_API) && PY_VERSION_HEX >= 0x030d0000)
    PyDict_GetItemStringRef(d, name, &cobj);
#else
    cobj = PyDict_GetItemString(d, name);
    Py_XINCREF(cobj);
#endif
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C %.8s %.200s",
                PyModule_GetName(module), what, name);
        goto bad;
    }
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C %.8s %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             what, PyModule_GetName(module), name, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    *p = PyCapsule_GetPointer(cobj, sig);
    if (!(*p))
        goto bad;
    Py_DECREF(d);
    Py_DECREF(cobj);
    return 0;
bad:
    Py_XDECREF(d);
    Py_XDECREF(cobj);
    return -1;
}
#endif

#ifndef __PYX_HAVE_RT_ImportFunction_3_2_2
#define __PYX_HAVE_RT_ImportFunction_3_2_2
static int __Pyx_ImportFunction_3_2_2(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    int result = __Pyx_ImportFromPxd_3_2_2(module, funcname, &tmp.p, sig, "function");
    if (result == 0) {
        *f = tmp.fp;
    }
    return result;
}
#endif

#ifndef __PYX_HAVE_RT_ImportType_proto_3_2_2
#define __PYX_HAVE_RT_ImportType_proto_3_2_2
#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#include <stdalign.h>
#endif
#if (defined (__STDC_VERSION__) && __STDC_VERSION__ >= 201112L) || __cplusplus >= 201103L
#define __PYX_GET_STRUCT_ALIGNMENT_3_2_2(s) alignof(s)
#else
#define __PYX_GET_STRUCT_ALIGNMENT_3_2_2(s) sizeof(void*)
#endif
enum __Pyx_ImportType_CheckSize_3_2_2 {
   __Pyx_ImportType_CheckSize_Error_3_2_2 = 0,
   __Pyx_ImportType_CheckSize_Warn_3_2_2 = 1,
   __Pyx_ImportType_CheckSize_Ignore_3_2_2 = 2
};
static PyTypeObject *__Pyx_ImportType_3_2_2(PyObject* module, const char *module_name, const char *class_name, size_t size, size_t alignment, enum __Pyx_ImportType_CheckSize_3_2_2 check_size);
#endif

#ifndef __PYX_HAVE_RT_ImportType_3_2_2
#define __PYX_HAVE_RT_ImportType_3_2_2
static PyTypeObject *__Pyx_ImportType_3_2_2(PyObject *module, const char *module_name, const char *class_name,
    size_t size, size_t alignment, enum __Pyx_ImportType_CheckSize_3_2_2 check_size)
{
    PyObject *result = 0;
    Py_ssize_t basicsize;
    Py_ssize_t itemsize;
#if defined(Py_LIMITED_API) || (defined(CYTHON_COMPILING_IN_LIMITED_API) && CYTHON_COMPILING_IN_LIMITED_API)
    PyObject *py_basicsize;
    PyObject *py_itemsize;
#endif
    result = PyObject_GetAttrString(module, class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError,
            "%.200s.%.200s is not a type object",
            module_name, class_name);
        goto bad;
    }
#if !( defined(Py_LIMITED_API) || (defined(CYTHON_COMPILING_IN_LIMITED_API) && CYTHON_COMPILING_IN_LIMITED_API) )
    basicsize = ((PyTypeObject *)result)->tp_basicsize;
    itemsize = ((PyTypeObject *)result)->tp_itemsize;
#else
    if (size == 0) {
        return (PyTypeObject *)result;
    }
    py_basicsize = PyObject_GetAttrString(result, "__basicsize__");
    if (!py_basicsize)
        goto bad;
    basicsize = PyLong_AsSsize_t(py_basicsize);
    Py_DECREF(py_basicsize);
    py_basicsize = 0;
    if (basicsize == (Py_ssize_t)-1 && PyErr_Occurred())
        goto bad;
    py_itemsize = PyObject_GetAttrString(result, "__itemsize__");
    if (!py_itemsize)
        goto bad;
    itemsize = PyLong_AsSsize_t(py_itemsize);
    Py_DECREF(py_itemsize);
    py_itemsize = 0;
    if (itemsize == (Py_ssize_t)-1 && PyErr_Occurred())
        goto bad;
#endif
    if (itemsize) {
        if (size % alignment) {
            alignment = size % alignment;
        }
        if (itemsize < (Py_ssize_t)alignment)
            itemsize = (Py_ssize_t)alignment;
    }
    if ((size_t)(basicsize + itemsize) < size) {
        PyErr_Format(PyExc_ValueError,
            "%.200s.%.200s size changed, may indicate binary incompatibility. "
            "Expected %zd from C header, got %zd from PyObject",
            module_name, class_name, size, basicsize+itemsize);
        goto bad;
    }
    if (check_size == __Pyx_ImportType_CheckSize_Error_3_2_2 &&
            ((size_t)basicsize > size || (size_t)(basicsize + itemsize) < size)) {
        PyErr_Format(PyExc_ValueError,
            "%.200s.%.200s size changed, may indicate binary incompatibility. "
            "Expected %zd from C header, got %zd-%zd from PyObject",
            module_name, class_name, size, basicsize, basicsize+itemsize);
        goto bad;
    }
    else if (check_size == __Pyx_ImportType_CheckSize_Warn_3_2_2 && (size_t)basicsize > size) {
        if (PyErr_WarnFormat(NULL, 0,
                "%.200s.%.200s size changed, may indicate binary incompatibility. "
                "Expected %zd from C header, got %zd from PyObject",
                module_name, class_name, size, basicsize) < 0) {
            goto bad;
        }
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(result);
    return NULL;
}
#endif


static int import_dpctl___sycl_context(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("dpctl._sycl_context");
  if (!module) goto bad;
  if (__Pyx_ImportFunction_3_2_2(module, "SyclContext_GetContextRef", (void (**)(void))&__pyx_api_f_5dpctl_13_sycl_context_SyclContext_GetContextRef, "DPCTLSyclContextRef (struct PySyclContextObject *)") < 0) goto bad;
  if (__Pyx_ImportFunction_3_2_2(module, "SyclContext_Make", (void (**)(void))&__pyx_api_f_5dpctl_13_sycl_context_SyclContext_Make, "struct PySyclContextObject *(DPCTLSyclContextRef)") < 0) goto bad;
  __pyx_ptype_5dpctl_13_sycl_context__SyclContext = __Pyx_ImportType_3_2_2(module, "dpctl._sycl_context", "_SyclContext",
  #if defined(PYPY_VERSION_NUM) && PYPY_VERSION_NUM < 0x050B0000
  sizeof(struct Py_SyclContextObject), __PYX_GET_STRUCT_ALIGNMENT_3_2_2(struct Py_SyclContextObject),
  #elif CYTHON_COMPILING_IN_LIMITED_API
  sizeof(struct Py_SyclContextObject), __PYX_GET_STRUCT_ALIGNMENT_3_2_2(struct Py_SyclContextObject),
  #else
  sizeof(struct Py_SyclContextObject), __PYX_GET_STRUCT_ALIGNMENT_3_2_2(struct Py_SyclContextObject),
  #endif
  __Pyx_ImportType_CheckSize_Warn_3_2_2); if (!__pyx_ptype_5dpctl_13_sycl_context__SyclContext) goto bad;
  __pyx_ptype_5dpctl_13_sycl_context_SyclContext = __Pyx_ImportType_3_2_2(module, "dpctl._sycl_context", "SyclContext",
  #if defined(PYPY_VERSION_NUM) && PYPY_VERSION_NUM < 0x050B0000
  sizeof(struct PySyclContextObject), __PYX_GET_STRUCT_ALIGNMENT_3_2_2(struct PySyclContextObject),
  #elif CYTHON_COMPILING_IN_LIMITED_API
  sizeof(struct PySyclContextObject), __PYX_GET_STRUCT_ALIGNMENT_3_2_2(struct PySyclContextObject),
  #else
  sizeof(struct PySyclContextObject), __PYX_GET_STRUCT_ALIGNMENT_3_2_2(struct PySyclContextObject),
  #endif
  __Pyx_ImportType_CheckSize_Warn_3_2_2); if (!__pyx_ptype_5dpctl_13_sycl_context_SyclContext) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__dpctl___sycl_context */
