"""
Court data for Polish eKW numbers.
"""

# Court data: CODE, NAME, FULL_NAME
COURTS = {
    "BB1B": {"name": "BIELSKO-BIAŁA", "full_name": "w Bielsku-Białej"},
    "BB1C": {"name": "CIESZYN", "full_name": "w Cieszynie"},
    "BB1Z": {"name": "ŻYWIEC", "full_name": "w Żywcu"},
    "BI1B": {"name": "BIAŁYSTOK", "full_name": "w Białymstoku"},
    "BI1P": {"name": "BIELSK PODLASKI", "full_name": "w Bielsku Podlaskim"},
    "BI1S": {"name": "SOKÓŁKA", "full_name": "w Sokółce"},
    "BI2P": {
        "name": "HAJNÓWKA",
        "full_name": "w Bielsku Podlaskim - wydział zamiejscowy z siedzibą w Hajnówce",
    },
    "BI3P": {
        "name": "SIEMIATYCZE",
        "full_name": "w Bielsku Podlaskim - wydział zamiejscowy z siedzibą w Siemiatyczach",
    },
    "BY1B": {"name": "BYDGOSZCZ", "full_name": "w Bydgoszczy"},
    "BY1I": {"name": "INOWROCŁAW", "full_name": "w Inowrocławiu"},
    "BY1M": {"name": "MOGILNO", "full_name": "w Mogilnie"},
    "BY1N": {"name": "NAKŁO NAD NOTECIĄ", "full_name": "w Nakle nad Notecią"},
    "BY1S": {"name": "ŚWIECIE", "full_name": "w Świeciu"},
    "BY1T": {"name": "TUCHOLA", "full_name": "w Tucholi"},
    "BY1U": {"name": "SZUBIN", "full_name": "w Szubinie"},
    "BY1Z": {"name": "ŻNIN", "full_name": "w Żninie"},
    "BY2T": {
        "name": "SĘPÓLNO KRAJEŃSKIE",
        "full_name": "w Tucholi - wydział zamiejscowy z siedzibą w Sępólnie Krajeńskim",
    },
    "CIKW": {"name": "WARSZAWA", "full_name": "w Warszawie"},
    "CZ1C": {"name": "CZĘSTOCHOWA", "full_name": "w Częstochowie"},
    "CZ1L": {"name": "LUBLINIEC", "full_name": "w Lublińcu"},
    "CZ1M": {"name": "MYSZKÓW", "full_name": "w Myszkowie"},
    "CZ1Z": {"name": "ZAWIERCIE", "full_name": "w Zawierciu"},
    "CZ2C": {
        "name": "KŁOBUCK",
        "full_name": "w Częstochowie - wydział zamiejscowy z siedzibą w Kłobucku",
    },
    "DIRS": {"name": "ŻŻ DIRS", "full_name": "ŻŻ DIRS"},
    "EL1B": {"name": "BRANIEWO", "full_name": "w Braniewie"},
    "EL1D": {"name": "DZIAŁDOWO", "full_name": "w Działdowie"},
    "EL1E": {"name": "ELBLĄG", "full_name": "w Elblągu"},
    "EL1I": {"name": "IŁAWA", "full_name": "w Iławie"},
    "EL1N": {"name": "NOWE MIASTO LUBAWSKIE", "full_name": "w Nowym Mieście Lubawskim"},
    "EL1O": {"name": "OSTRÓDA", "full_name": "w Ostródzie"},
    "EL2O": {
        "name": "MORĄG",
        "full_name": "w Ostródzie - wydział zamiejscowy z siedzibą w Morągu",
    },
    "GD1A": {"name": "STAROGARD GDAŃSKI", "full_name": "w Starogardzie Gdańskim"},
    "GD1E": {"name": "KOŚCIERZYNA", "full_name": "w Kościerzynie"},
    "GD1G": {"name": "GDAŃSK", "full_name": "Gdańsk-Północ w Gdańsku"},
    "GD1I": {"name": "KWIDZYN", "full_name": "w Kwidzynie"},
    "GD1M": {"name": "MALBORK", "full_name": "w Malborku"},
    "GD1R": {"name": "KARTUZY", "full_name": "w Kartuzach"},
    "GD1S": {"name": "SOPOT", "full_name": "w Sopocie"},
    "GD1T": {"name": "TCZEW", "full_name": "w Tczewie"},
    "GD1W": {"name": "WEJHEROWO", "full_name": "w Wejherowie"},
    "GD1Y": {"name": "GDYNIA", "full_name": "w Gdyni"},
    "GD2I": {"name": "SZTUM", "full_name": "w Sztumie"},
    "GD2M": {
        "name": "NOWY DWÓR GDAŃSKI",
        "full_name": "w Malborku - wydział zamiejscowy z siedzibą w Nowym Dworze Gdańskim",
    },
    "GD2W": {
        "name": "PUCK",
        "full_name": "w Wejherowie - wydział zamiejscowy z siedzibą w Pucku",
    },
    "GL1G": {"name": "GLIWICE", "full_name": "w Gliwicach"},
    "GL1J": {"name": "JASTRZĘBIE-ZDRÓJ", "full_name": "w Jastrzębiu-Zdroju"},
    "GL1R": {"name": "RACIBÓRZ", "full_name": "w Raciborzu"},
    "GL1S": {"name": "RUDA ŚLĄSKA", "full_name": "w Rudzie Śląskiej"},
    "GL1T": {"name": "TARNOWSKIE GÓRY", "full_name": "w Tarnowskich Górach"},
    "GL1W": {"name": "WODZISŁAW ŚLĄSKI", "full_name": "w Wodzisławiu Śląskim"},
    "GL1X": {"name": "ŻORY", "full_name": "w Żorach"},
    "GL1Y": {"name": "RYBNIK", "full_name": "w Rybniku"},
    "GL1Z": {"name": "ZABRZE", "full_name": "w Zabrzu"},
    "GW1G": {"name": "GORZÓW WIELKOPOLSKI", "full_name": "w Gorzowie Wielkopolskim"},
    "GW1K": {"name": "STRZELCE KRAJEŃSKIE", "full_name": "w Strzelcach Krajeńskich"},
    "GW1M": {"name": "MIĘDZYRZECZ", "full_name": "w Międzyrzeczu"},
    "GW1S": {"name": "SŁUBICE", "full_name": "w Słubicach"},
    "GW1U": {"name": "SULĘCIN", "full_name": "w Sulęcinie"},
    "JG1B": {"name": "BOLESŁAWIEC", "full_name": "w Bolesławcu"},
    "JG1J": {"name": "JELENIA GÓRA", "full_name": "w Jeleniej Górze"},
    "JG1K": {"name": "KAMIENNA GÓRA", "full_name": "w Kamiennej Górze"},
    "JG1L": {"name": "LUBAŃ", "full_name": "w Lubaniu"},
    "JG1S": {"name": "LWÓWEK ŚLĄSKI", "full_name": "w Lwówku Śląskim"},
    "JG1Z": {"name": "ZGORZELEC", "full_name": "w Zgorzelcu"},
    "KA1B": {"name": "BĘDZIN", "full_name": "w Będzinie"},
    "KA1C": {"name": "CHORZÓW", "full_name": "w Chorzowie"},
    "KA1D": {"name": "DĄBROWA GÓRNICZA", "full_name": "w Dąbrowie Górniczej"},
    "KA1I": {"name": "SIEMIANOWICE ŚLĄSKIE", "full_name": "w Siemianowicach Śląskich"},
    "KA1J": {"name": "JAWORZNO", "full_name": "w Jaworznie"},
    "KA1K": {"name": "KATOWICE", "full_name": "Katowice-Wschód w Katowicach"},
    "KA1L": {"name": "MYSŁOWICE", "full_name": "w Mysłowicach"},
    "KA1M": {"name": "MIKOŁÓW", "full_name": "w Mikołowie"},
    "KA1P": {"name": "PSZCZYNA", "full_name": "w Pszczynie"},
    "KA1S": {"name": "SOSNOWIEC", "full_name": "w Sosnowcu"},
    "KA1T": {"name": "TYCHY", "full_name": "w Tychach"},
    "KA1Y": {"name": "BYTOM", "full_name": "w Bytomiu"},
    "KI1A": {"name": "STASZÓW", "full_name": "w Staszowie"},
    "KI1B": {"name": "BUSKO ZDRÓJ", "full_name": "w Busku-Zdroju"},
    "KI1H": {"name": "STARACHOWICE", "full_name": "w Starachowicach"},
    "KI1I": {
        "name": "KAZIMIERZA WIELKA",
        "full_name": "w Busku-Zdroju - wydział zamiejscowy z siedzibą w Kazimierzy Wielkiej",
    },
    "KI1J": {"name": "JĘDRZEJÓW", "full_name": "w Jędrzejowie"},
    "KI1K": {"name": "KOŃSKIE", "full_name": "w Końskich"},
    "KI1L": {"name": "KIELCE", "full_name": "w Kielcach"},
    "KI1O": {
        "name": "OSTROWIEC ŚWIĘTOKRZYSKI",
        "full_name": "w Ostrowcu Świętokrzyskim",
    },
    "KI1P": {"name": "PIŃCZÓW", "full_name": "w Pińczowie"},
    "KI1R": {"name": "SKARŻYSKO-KAMIENNA", "full_name": "w Skarżysku-Kamiennej"},
    "KI1S": {"name": "SANDOMIERZ", "full_name": "w Sandomierzu"},
    "KI1T": {"name": "OPATÓW", "full_name": "w Opatowie"},
    "KI1W": {"name": "WŁOSZCZOWA", "full_name": "we Włoszczowie"},
    "KN1K": {"name": "KOŁO", "full_name": "w Kole"},
    "KN1N": {"name": "KONIN", "full_name": "w Koninie"},
    "KN1S": {"name": "SŁUPCA", "full_name": "w Słupcy"},
    "KN1T": {"name": "TUREK", "full_name": "w Turku"},
    "KO1B": {"name": "BIAŁOGARD", "full_name": "w Białogardzie"},
    "KO1D": {"name": "DRAWSKO POMORSKIE", "full_name": "w Drawsku Pomorskim"},
    "KO1E": {"name": "SŁAWNO", "full_name": "w Sławnie"},
    "KO1I": {"name": "SZCZECINEK", "full_name": "w Szczecinku"},
    "KO1K": {"name": "KOSZALIN", "full_name": "w Koszalinie"},
    "KO1L": {"name": "KOŁOBRZEG", "full_name": "w Kołobrzegu"},
    "KO1W": {"name": "WAŁCZ", "full_name": "w Wałczu"},
    "KO2B": {
        "name": "ŚWIDWIN",
        "full_name": "w Białogardzie - wydział zamiejscowy z siedzibą w Świdwinie",
    },
    "KR1B": {"name": "SUCHA BESKIDZKA", "full_name": "w Suchej Beskidzkiej"},
    "KR1C": {"name": "CHRZANÓW", "full_name": "w Chrzanowie"},
    "KR1E": {"name": "OŚWIĘCIM", "full_name": "w Oświęcimiu"},
    "KR1H": {
        "name": "PROSZOWICE",
        "full_name": "dla Krakowa-Nowej Huty w Krakowie - wydział zamiejscowy z siedzibą w Proszowicach",
    },
    "KR1I": {"name": "WIELICZKA", "full_name": "w Wieliczce"},
    "KR1K": {
        "name": "CZERNICHÓW",
        "full_name": "dla Krakowa-Krowodrzy w Krakowie - wydział zamiejscowy z siedzibą w Czernichowie",
    },
    "KR1M": {"name": "MIECHÓW", "full_name": "w Miechowie"},
    "KR1O": {"name": "OLKUSZ", "full_name": "w Olkuszu"},
    "KR1P": {"name": "KRAKÓW", "full_name": "dla Krakowa-Podgórza w Krakowie"},
    "KR1S": {
        "name": "SŁOMNIKI",
        "full_name": "w Miechowie - wydział zamiejscowy z siedzibą w Słomnikach",
    },
    "KR1W": {"name": "WADOWICE", "full_name": "w Wadowicach"},
    "KR1Y": {"name": "MYŚLENICE", "full_name": "w Myślenicach"},
    "KR2E": {
        "name": "KĘTY",
        "full_name": "w Oświęcimiu - wydział zamiejscowy z siedzibą w Kętach",
    },
    "KR2I": {
        "name": "NIEPOŁOMICE",
        "full_name": "w Wieliczce - wydział zamiejscowy z siedzibą w Niepołomicach",
    },
    "KR2K": {
        "name": "KRZESZOWICE",
        "full_name": "dla Krakowa-Krowodrzy w Krakowie - wydział zamiejscowy z siedzibą w Krzeszowicach",
    },
    "KR2P": {
        "name": "SKAŁA",
        "full_name": "dla Krakowa-Podgórza w Krakowie - wydział zamiejscowy z siedzibą w Skale",
    },
    "KR2Y": {
        "name": "DOBCZYCE",
        "full_name": "w Myślenicach - wydział zamiejscowy z siedzibą w Dobczycach",
    },
    "KR3I": {
        "name": "SKAWINA",
        "full_name": "w Wieliczce - wydział zamiejscowy z siedzibą w Skawinie",
    },
    "KS1B": {"name": "BRZOZÓW", "full_name": "w Brzozowie"},
    "KS1E": {"name": "LESKO", "full_name": "w Lesku"},
    "KS1J": {"name": "JASŁO", "full_name": "w Jaśle"},
    "KS1K": {"name": "KROSNO", "full_name": "w Krośnie"},
    "KS1S": {"name": "SANOK", "full_name": "w Sanoku"},
    "KS2E": {
        "name": "USTRZYKI DOLNE",
        "full_name": "w Lesku - wydział zamiejscowy z siedzibą w Ustrzykach Dolnych",
    },
    "KZ1A": {"name": "KALISZ", "full_name": "w Kaliszu"},
    "KZ1E": {"name": "KĘPNO", "full_name": "w Kępnie"},
    "KZ1J": {"name": "JAROCIN", "full_name": "w Jarocinie"},
    "KZ1O": {"name": "OSTRZESZÓW", "full_name": "w Ostrzeszowie"},
    "KZ1P": {"name": "PLESZEW", "full_name": "w Pleszewie"},
    "KZ1R": {"name": "KROTOSZYN", "full_name": "w Krotoszynie"},
    "KZ1W": {"name": "OSTRÓW WIELKOPOLSKI", "full_name": "w Ostrowie Wielkopolskim"},
    "LD1B": {"name": "BRZEZINY", "full_name": "w Brzezinach"},
    "LD1G": {"name": "ZGIERZ", "full_name": "w Zgierzu"},
    "LD1H": {"name": "SKIERNIEWICE", "full_name": "w Skierniewicach"},
    "LD1K": {"name": "KUTNO", "full_name": "w Kutnie"},
    "LD1M": {"name": "ŁÓDŹ", "full_name": "dla Łodzi-Śródmieścia w Łodzi"},
    "LD1O": {"name": "ŁOWICZ", "full_name": "w Łowiczu"},
    "LD1P": {"name": "PABIANICE", "full_name": "w Pabianicach"},
    "LD1R": {"name": "RAWA MAZOWIECKA", "full_name": "w Rawie Mazowieckiej"},
    "LD1Y": {"name": "ŁĘCZYCA", "full_name": "w Łęczycy"},
    "LE1G": {"name": "GŁOGÓW", "full_name": "w Głogowie"},
    "LE1J": {"name": "JAWOR", "full_name": "w Jaworze"},
    "LE1L": {"name": "LEGNICA", "full_name": "w Legnicy"},
    "LE1U": {"name": "LUBIN", "full_name": "w Lubinie"},
    "LE1Z": {"name": "ZŁOTORYJA", "full_name": "w Złotoryi"},
    "LM1G": {"name": "GRAJEWO", "full_name": "w Grajewie"},
    "LM1L": {"name": "ŁOMŻA", "full_name": "w Łomży"},
    "LM1W": {"name": "WYSOKIE MAZOWIECKIE", "full_name": "w Wysokiem Mazowieckiem"},
    "LM1Z": {"name": "ZAMBRÓW", "full_name": "w Zambrowie"},
    "LU1A": {"name": "LUBARTÓW", "full_name": "w Lubartowie"},
    "LU1B": {"name": "BIAŁA PODLASKA", "full_name": "w Białej Podlaskiej"},
    "LU1C": {"name": "CHEŁM", "full_name": "w Chełmie"},
    "LU1I": {"name": "LUBLIN", "full_name": "Lublin-Zachód w Lublinie"},
    "LU1K": {"name": "KRAŚNIK", "full_name": "w Kraśniku"},
    "LU1O": {"name": "OPOLE LUBELSKIE", "full_name": "w Opolu Lubelskim"},
    "LU1P": {"name": "PUŁAWY", "full_name": "w Puławach"},
    "LU1R": {"name": "RADZYŃ PODLASKI", "full_name": "w Radzyniu Podlaskim"},
    "LU1S": {
        "name": "ŚWIDNIK",
        "full_name": "Lublin-Wschód w Lublinie z siedzibą w Świdniku",
    },
    "LU1U": {"name": "ŁUKÓW", "full_name": "w Łukowie"},
    "LU1W": {"name": "WŁODAWA", "full_name": "we Włodawie"},
    "LU1Y": {"name": "RYKI", "full_name": "w Rykach"},
    "NS1G": {"name": "GORLICE", "full_name": "w Gorlicach"},
    "NS1L": {"name": "LIMANOWA", "full_name": "w Limanowej"},
    "NS1M": {
        "name": "MUSZYNA",
        "full_name": "w Nowym Sączu - wydział zamiejscowy z siedzibą w Muszynie",
    },
    "NS1S": {"name": "NOWY SĄCZ", "full_name": "w Nowym Sączu"},
    "NS1T": {"name": "NOWY TARG", "full_name": "w Nowym Targu"},
    "NS1Z": {"name": "ZAKOPANE", "full_name": "w Zakopanem"},
    "NS2L": {
        "name": "MSZANA DOLNA",
        "full_name": "w Limanowej - wydział zamiejscowy z siedzibą w Mszanie Dolnej",
    },
    "OL1B": {"name": "BISKUPIEC", "full_name": "w Biskupcu"},
    "OL1C": {"name": "OLECKO", "full_name": "w Olecku"},
    "OL1E": {"name": "EŁK", "full_name": "w Ełku"},
    "OL1G": {"name": "GIŻYCKO", "full_name": "w Giżycku"},
    "OL1K": {"name": "KĘTRZYN", "full_name": "w Kętrzynie"},
    "OL1L": {"name": "LIDZBARK WARMIŃSKI", "full_name": "w Lidzbarku Wamińskim "},
    "OL1M": {"name": "MRĄGOWO", "full_name": "w Mrągowie"},
    "OL1N": {"name": "NIDZICA", "full_name": "w Nidzicy"},
    "OL1O": {"name": "OLSZTYN", "full_name": "w Olsztynie"},
    "OL1P": {"name": "PISZ", "full_name": "w Piszu"},
    "OL1S": {"name": "SZCZYTNO", "full_name": "w Szczytnie"},
    "OL1Y": {"name": "BARTOSZYCE", "full_name": "w Bartoszycach"},
    "OL2G": {
        "name": "WĘGORZEWO",
        "full_name": "w Giżycku - wydział zamiejscowy z siedzibą w Węgorzewie",
    },
    "OP1B": {"name": "BRZEG", "full_name": "w Brzegu"},
    "OP1G": {"name": "GŁUBCZYCE", "full_name": "w Głubczycach"},
    "OP1K": {"name": "KĘDZIERZYN-KOŹLE", "full_name": "w Kędzierzynie-Koźlu"},
    "OP1L": {"name": "OLESNO", "full_name": "w Oleśnie"},
    "OP1N": {"name": "NYSA", "full_name": "w Nysie"},
    "OP1O": {"name": "OPOLE", "full_name": "w Opolu"},
    "OP1P": {"name": "PRUDNIK", "full_name": "w Prudniku"},
    "OP1S": {"name": "STRZELCE OPOLSKIE", "full_name": "w Strzelcach Opolskich"},
    "OP1U": {"name": "KLUCZBORK", "full_name": "w Kluczborku"},
    "OS1M": {"name": "OSTRÓW MAZOWIECKA", "full_name": "w Ostrowi Mazowieckiej"},
    "OS1O": {"name": "OSTROŁĘKA", "full_name": "w Ostrołęce"},
    "OS1P": {"name": "PRZASNYSZ", "full_name": "w Przasnyszu"},
    "OS1U": {"name": "PUŁTUSK", "full_name": "w Pułtusku"},
    "OS1W": {"name": "WYSZKÓW", "full_name": "w Wyszkowie"},
    "PL1C": {"name": "CIECHANÓW", "full_name": "w Ciechanowie"},
    "PL1E": {"name": "SIERPC", "full_name": "w Sierpcu"},
    "PL1G": {"name": "GOSTYNIN", "full_name": "w Gostyninie"},
    "PL1L": {"name": "PŁOŃSK", "full_name": "w Płońsku"},
    "PL1M": {"name": "MŁAWA", "full_name": "w Mławie"},
    "PL1O": {"name": "SOCHACZEW", "full_name": "w Sochaczewie"},
    "PL1P": {"name": "PŁOCK", "full_name": "w Płocku"},
    "PL1Z": {"name": "ŻYRARDÓW", "full_name": "w Żyrardowie"},
    "PL2M": {
        "name": "ŻUROMIN",
        "full_name": "w Mławie - wydział zamiejscowy z siedzibą w Żurominie",
    },
    "PO1A": {"name": "SZAMOTUŁY", "full_name": "w Szamotułach"},
    "PO1B": {"name": "WĄGROWIEC", "full_name": "w Wągrowcu"},
    "PO1D": {"name": "ŚRODA WLKP.", "full_name": "w Środzie Wielkopolskiej"},
    "PO1E": {"name": "WOLSZTYN", "full_name": "w Wolsztynie"},
    "PO1F": {"name": "WRZEŚNIA", "full_name": "we Wrześni"},
    "PO1G": {"name": "GNIEZNO", "full_name": "w Gnieźnie"},
    "PO1H": {"name": "CHODZIEŻ", "full_name": "w Chodzieży"},
    "PO1I": {"name": "PIŁA", "full_name": "w Pile"},
    "PO1K": {"name": "KOŚCIAN", "full_name": "w Kościanie"},
    "PO1L": {"name": "LESZNO", "full_name": "w Lesznie"},
    "PO1M": {"name": "ŚREM", "full_name": "w Śremie"},
    "PO1N": {"name": "NOWY TOMYŚL", "full_name": "w Nowym Tomyślu"},
    "PO1O": {"name": "OBORNIKI", "full_name": "w Obornikach"},
    "PO1P": {
        "name": "POZNAŃ (V)",
        "full_name": "Poznań-Stare Miasto w Poznaniu - dla części miasta Poznania w granicach ustalonych tradycyjnie dla dzielnic: Grunwald, Jeżyce i Stare Miasto oraz gmin: Czerwonak, Dopiewo, Murowana Goślina, Suchy Las i Tarnowo Podgórne",
    },
    "PO1R": {"name": "RAWICZ", "full_name": "w Rawiczu"},
    "PO1S": {"name": "GRODZISK WLKP.", "full_name": "w Grodzisku Wielkopolskim"},
    "PO1T": {"name": "TRZCIANKA", "full_name": "w Trzciance"},
    "PO1Y": {"name": "GOSTYŃ", "full_name": "w Gostyniu"},
    "PO1Z": {"name": "ZŁOTÓW", "full_name": "w Złotowie"},
    "PO2A": {
        "name": "MIĘDZYCHÓD",
        "full_name": "w Szamotułach - wydział zamiejscowy z siedzibą w Międzychodzie",
    },
    "PO2H": {
        "name": "WYRZYSK",
        "full_name": "w Chodzieży - wydział zamiejscowy z siedzibą w Wyrzysku",
    },
    "PO2P": {
        "name": "POZNAŃ (VI)",
        "full_name": "Poznań-Stare Miasto w Poznaniu - dla części miasta Poznania w granicach ustalonych tradycyjnie dla dzielnic: Nowe Miasto i Wilda, miast Luboń i Puszczykowo oraz gmin Komorniki i Swarzędz",
    },
    "PO2T": {
        "name": "CZARNKÓW",
        "full_name": "w Trzciance - wydział zamiejscowy z siedzibą w Czarnkowie",
    },
    "PR1J": {"name": "JAROSŁAW", "full_name": "w Jarosławiu"},
    "PR1L": {"name": "LUBACZÓW", "full_name": "w Lubaczowie"},
    "PR1P": {"name": "PRZEMYŚL", "full_name": "w Przemyślu"},
    "PR1R": {"name": "PRZEWORSK", "full_name": "w Przeworsku"},
    "PR2R": {
        "name": "SIENIAWA",
        "full_name": "w Przeworsku - wydział zamiejscowy z siedzibą w Sieniawie",
    },
    "PT1B": {"name": "BEŁCHATÓW", "full_name": "w Bełchatowie"},
    "PT1O": {"name": "OPOCZNO", "full_name": "w Opocznie"},
    "PT1P": {"name": "PIOTRKÓW TRYBUNALSKI", "full_name": "w Piotrkowie Trybunalskim"},
    "PT1R": {"name": "RADOMSKO", "full_name": "w Radomsku"},
    "PT1T": {"name": "TOMASZÓW MAZOWIECKI", "full_name": "w Tomaszowie Mazowieckim"},
    "RA1G": {"name": "GRÓJEC", "full_name": "w Grójcu"},
    "RA1K": {"name": "KOZIENICE", "full_name": "w Kozienicach"},
    "RA1L": {"name": "LIPSKO", "full_name": "w Lipsku"},
    "RA1P": {"name": "PRZYSUCHA", "full_name": "w Przysusze"},
    "RA1R": {"name": "RADOM", "full_name": "w Radomiu"},
    "RA1S": {"name": "SZYDŁOWIEC", "full_name": "w Szydłowcu"},
    "RA1Z": {"name": "ZWOLEŃ", "full_name": "w Zwoleniu"},
    "RA2G": {
        "name": "BIAŁOBRZEGI",
        "full_name": "w Grójcu - wydział zamiejscowy z siedzibą w Białobrzegach",
    },
    "RA2Z": {"name": "PIONKI", "full_name": "w Pionki"},
    "RZ1A": {"name": "ŁAŃCUT", "full_name": "w Łańcucie"},
    "RZ1D": {"name": "DĘBICA", "full_name": "w Dębicy"},
    "RZ1E": {"name": "LEŻAJSK", "full_name": "w Leżajsku"},
    "RZ1R": {"name": "ROPCZYCE", "full_name": "w Ropczycach"},
    "RZ1S": {"name": "STRZYŻÓW", "full_name": "w Strzyżowie"},
    "RZ1Z": {"name": "RZESZÓW", "full_name": "w Rzeszowie"},
    "RZ2Z": {
        "name": "TYCZYN",
        "full_name": "w Rzeszowie - wydział zamiejscowy z siedzibą w Tyczynie",
    },
    "SI1G": {"name": "GARWOLIN", "full_name": "w Garwolinie"},
    "SI1M": {"name": "MIŃSK MAZOWIECKI", "full_name": "w Mińsku Mazowieckim"},
    "SI1P": {"name": "SOKOŁÓW PODLASKI", "full_name": "w Sokołowie Podlaskim"},
    "SI1S": {"name": "SIEDLCE", "full_name": "w Siedlcach"},
    "SI1W": {"name": "WĘGRÓW", "full_name": "w Węgrowie"},
    "SI2S": {
        "name": "ŁOSICE",
        "full_name": "w Siedlcach - wydział zamiejscowy z siedzibą w Łosicach",
    },
    "SL1B": {"name": "BYTÓW", "full_name": "w Bytowie"},
    "SL1C": {"name": "CHOJNICE", "full_name": "w Chojnicach"},
    "SL1L": {"name": "LĘBORK", "full_name": "w Lęborku"},
    "SL1M": {"name": "MIASTKO", "full_name": "w Miastku"},
    "SL1S": {"name": "SŁUPSK", "full_name": "w Słupsku"},
    "SL1Z": {"name": "CZŁUCHÓW", "full_name": "w Człuchowie"},
    "SO1C": {"name": "CZELADŹ", "full_name": "CZELADŹ"},
    "SR1L": {"name": "ŁASK", "full_name": "w Łasku"},
    "SR1S": {"name": "SIERADZ", "full_name": "w Sieradzu"},
    "SR1W": {"name": "WIELUŃ", "full_name": "w Wieluniu"},
    "SR1Z": {"name": "ZDUŃSKA WOLA", "full_name": "w Zduńskiej Woli"},
    "SR2L": {
        "name": "PODDĘBICE",
        "full_name": "w Łasku - wydział zamiejscowy z siedzibą w Poddębicach",
    },
    "SR2W": {
        "name": "PAJĘCZNO",
        "full_name": "w Wieluniu - wydział zamiejscowy z siedzibą w Pajęcznie",
    },
    "SU1A": {"name": "AUGUSTÓW", "full_name": "w Augustowie"},
    "SU1N": {
        "name": "SEJNY",
        "full_name": "w Augustowie - wydział zamiejscowy z siedzibą w Sejnach",
    },
    "SU1S": {"name": "SUWAŁKI", "full_name": "w Suwałkach"},
    "SW1D": {"name": "DZIERŻONIÓW", "full_name": "w Dzierżoniowie"},
    "SW1K": {"name": "KŁODZKO", "full_name": "w Kłodzku"},
    "SW1S": {"name": "ŚWIDNICA", "full_name": "w Świdnicy"},
    "SW1W": {"name": "WAŁBRZYCH", "full_name": "w Wałbrzychu"},
    "SW1Z": {"name": "ZĄBKOWICE ŚLĄSKIE", "full_name": "w Ząbkowicach Śląskich"},
    "SW2K": {
        "name": "NOWA RUDA",
        "full_name": "w Kłodzku - wydział zamiejscowy z siedzibą w Nowej Rudzie",
    },
    "SZ1C": {"name": "CHOSZCZNO", "full_name": "w Choszcznie"},
    "SZ1G": {"name": "GRYFICE", "full_name": "w Gryficach"},
    "SZ1K": {"name": "KAMIEŃ POMORSKI", "full_name": "w Kamieniu Pomorskim"},
    "SZ1L": {"name": "ŁOBEZ", "full_name": "w Łobzie"},
    "SZ1M": {"name": "MYŚLIBÓRZ", "full_name": "w Myśliborzu"},
    "SZ1O": {"name": "GOLENIÓW", "full_name": "w Goleniowie"},
    "SZ1S": {
        "name": "SZCZECIN",
        "full_name": "Szczecin-Prawobrzeże i Zachód w Szczecinie",
    },
    "SZ1T": {"name": "STARGARD", "full_name": "w Stargardzie"},
    "SZ1W": {"name": "ŚWINOUJŚCIE", "full_name": "w Świnoujściu"},
    "SZ1Y": {"name": "GRYFINO", "full_name": "w Gryfinie"},
    "SZ2S": {
        "name": "POLICE",
        "full_name": "Szczecin-Prawobrzeże i Zachód w Szczecinie - wydział zamiejscowy z siedzibą w Policach",
    },
    "SZ2T": {
        "name": "PYRZYCE",
        "full_name": "w Stargardzie - wydział zamiejscowy z siedzibą w Pyrzycach",
    },
    "TB1K": {"name": "KOLBUSZOWA", "full_name": "w Kolbuszowej"},
    "TB1M": {"name": "MIELEC", "full_name": "w Mielcu"},
    "TB1N": {"name": "NISKO", "full_name": "w Nisku"},
    "TB1S": {"name": "STALOWA WOLA", "full_name": "w Stalowej Woli"},
    "TB1T": {"name": "TARNOBRZEG", "full_name": "w Tarnobrzegu"},
    "TO1B": {"name": "BRODNICA", "full_name": "w Brodnicy"},
    "TO1C": {"name": "CHEŁMNO", "full_name": "w Chełmnie"},
    "TO1G": {"name": "GOLUB-DOBRZYŃ", "full_name": "w Golubiu-Dobrzyniu"},
    "TO1T": {"name": "TORUŃ", "full_name": "w Toruniu"},
    "TO1U": {"name": "GRUDZIĄDZ", "full_name": "w Grudziądzu"},
    "TO1W": {"name": "WĄBRZEŹNO", "full_name": "w Wąbrzeźnie"},
    "TR1B": {"name": "BRZESKO", "full_name": "w Brzesku"},
    "TR1D": {"name": "DĄBROWA TARNOWSKA", "full_name": "w Dąbrowie Tarnowskiej"},
    "TR1O": {"name": "BOCHNIA", "full_name": "w Bochni"},
    "TR1T": {"name": "TARNÓW", "full_name": "w Tarnowie"},
    "TR2T": {
        "name": "TUCHÓW",
        "full_name": "w Tarnowie - wydział zamiejscowy z siedzibą w Tuchowie",
    },
    "WA1G": {"name": "GRODZISK MAZOWIECKI", "full_name": "w Grodzisku Mazowieckim"},
    "WA1I": {"name": "PIASECZNO", "full_name": "w Piasecznie"},
    "WA1L": {"name": "LEGIONOWO", "full_name": "w Legionowie"},
    "WA1M": {
        "name": "WARSZAWA (VI)",
        "full_name": "dla Warszawy-Mokotowa w Warszawie - dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Bemowo, Bielany, Ochota i Żoliborz oraz gminy Izabelin",
    },
    "WA1N": {"name": "NOWY DWÓR MAZOWIECKI", "full_name": "w Nowym Dworze Mazowieckim"},
    "WA1O": {"name": "OTWOCK", "full_name": "w Otwocku"},
    "WA1P": {"name": "PRUSZKÓW", "full_name": "w Pruszkowie"},
    "WA1W": {"name": "WOŁOMIN", "full_name": "w Wołominie"},
    "WA2M": {
        "name": "WARSZAWA (VII)",
        "full_name": "dla Warszawy-Mokotowa w Warszawie - dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic Mokotów i Wilanów",
    },
    "WA3M": {
        "name": "WARSZAWA (IX)",
        "full_name": "dla Warszawy-Mokotowa w Warszawie - dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Białołęka, Praga-Północ, Targówek",
    },
    "WA4M": {
        "name": "WARSZAWA (X)",
        "full_name": "dla Warszawy-Mokotowa w Warszawie - dla części miasta stołecznego Warszawy w Warszawie w granicach ustalonych dla dzielnic Śródmieście i Wola oraz gminy Łomianki",
    },
    "WA5M": {
        "name": "WARSZAWA (XIII)",
        "full_name": "dla Warszawy-Mokotowa w Warszawie - dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Ursus, Ursynów i Włochy",
    },
    "WA6M": {
        "name": "WARSZAWA (XV)",
        "full_name": "dla Warszawy-Mokotowa w Warszawie - dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Praga-Południe, Rembertów, Wawer i Wesoła",
    },
    "WL1A": {"name": "ALEKSANDRÓW KUJAWSKI", "full_name": "w Aleksandrowie Kujawskim"},
    "WL1L": {"name": "LIPNO", "full_name": "w Lipnie"},
    "WL1R": {"name": "RADZIEJÓW", "full_name": "w Radziejowie"},
    "WL1W": {"name": "WŁOCŁAWEK", "full_name": "we Włocławku"},
    "WL1Y": {"name": "RYPIN", "full_name": "w Rypinie"},
    "WR1E": {"name": "OLEŚNICA", "full_name": "w Oleśnicy"},
    "WR1K": {"name": "WROCŁAW", "full_name": "dla Wrocławia-Krzyków we Wrocławiu"},
    "WR1L": {"name": "WOŁÓW", "full_name": "w Wołowie"},
    "WR1M": {"name": "MILICZ", "full_name": "w Miliczu"},
    "WR1O": {"name": "OŁAWA", "full_name": "w Oławie"},
    "WR1S": {"name": "ŚRODA ŚLĄSKA", "full_name": "w Środzie Śląskiej"},
    "WR1T": {"name": "STRZELIN", "full_name": "w Strzelinie"},
    "WR1W": {"name": "TRZEBNICA", "full_name": "w Trzebnicy"},
    "ZA1B": {"name": "BIŁGORAJ", "full_name": "w Biłgoraju"},
    "ZA1H": {"name": "HRUBIESZÓW", "full_name": "w Hrubieszowie"},
    "ZA1J": {"name": "JANÓW LUBELSKI", "full_name": "w Janowie Lubelskim"},
    "ZA1K": {"name": "KRASNYSTAW", "full_name": "w Krasnymstawie"},
    "ZA1T": {"name": "TOMASZÓW LUBELSKI", "full_name": "w Tomaszowie Lubelskim"},
    "ZA1Z": {"name": "ZAMOŚĆ", "full_name": "w Zamościu"},
    "ZG1E": {"name": "ZIELONA GÓRA", "full_name": "w Zielonej Górze"},
    "ZG1G": {"name": "ŻAGAŃ", "full_name": "w Żaganiu"},
    "ZG1K": {"name": "KROSNO ODRZAŃSKIE", "full_name": "w Krośnie Odrzańskim"},
    "ZG1N": {"name": "NOWA SÓL", "full_name": "w Nowej Soli"},
    "ZG1R": {"name": "ŻARY", "full_name": "w Żarach"},
    "ZG1S": {"name": "ŚWIEBODZIN", "full_name": "w Świebodzinie"},
    "ZG1W": {"name": "WSCHOWA", "full_name": "we Wschowie"},
    "ZG2K": {
        "name": "GUBIN",
        "full_name": "w Krośnie Odrzańskim - wydział zamiejscowy z siedzibą w Gubinie",
    },
    "ZG2S": {
        "name": "SULECHÓW",
        "full_name": "w Świebodzinie - wydział zamiejscowy z siedzibą w Sulechowie",
    },
}
